### ISSUE TITLE
Failed to compile OpenSYCL with LLVM 17

### ISSUE THREAD

**Issue by AlbertXingZhang** [AdaptiveCpp/AdaptiveCpp#1000]
**Bug summary**
The following error prevents compiling OpenSYCL with LLVM which is built from its latest git main branch.
```
[1/57] Building CXX object src/compiler/CMakeFiles/opensycl-clang.dir/GlobalsPruningPass.cpp.obj
FAILED: src/compiler/CMakeFiles/opensycl-clang.dir/GlobalsPruningPass.cpp.obj 
D:\a\1\s\llvm\build\install\bin\clang++.exe -DENABLE_OPAQUE_POINTERS="1 -D_GLIBCXX_ASSERTIONS -D_LIBCPP_ENABLE_ASSERTIONS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" -DHIPSYCL_COMPILER_COMPONENT -DHIPSYCL_DEBUG_LEVEL=2 -Dopensycl_clang_EXPORTS -ID:/a/1/s/OpenSYCL/src/compiler/../../include -ID:/a/1/s/llvm/llvm/include -ID:/a/1/s/llvm/build/include -ID:/a/1/s/OpenSYCL/src/compiler -ID:/a/1/s/OpenSYCL/build/include -ID:/a/1/s/llvm/build/install/include -ID:/a/1/s/llvm/clang/include -ID:/a/1/s/llvm/build/tools/clang/include -ID:/a/1/s/llvm/build/install/include/sycl -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -std=c++17 -fno-exceptions -MD -MT src/compiler/CMakeFiles/opensycl-clang.dir/GlobalsPruningPass.cpp.obj -MF src\compiler\CMakeFiles\opensycl-clang.dir\GlobalsPruningPass.cpp.obj.d -o src/compiler/CMakeFiles/opensycl-clang.dir/GlobalsPruningPass.cpp.obj -c D:/a/1/s/OpenSYCL/src/compiler/GlobalsPruningPass.cpp
In file included from D:/a/1/s/OpenSYCL/src/compiler/GlobalsPruningPass.cpp:1:
D:/a/1/s/OpenSYCL/src/compiler/../../include\hipSYCL/compiler/GlobalsPruningPass.hpp:39:10: fatal error: 'llvm/Transforms/IPO/PassManagerBuilder.h' file not found
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**To Reproduce**
1. Build LLVM from its latest git main branch.
2. Use the built LLVM to compile OpenSYCL.

**Expected behavior**
OpenSYCL could be compiled properly as before.

**Additional context**
I think it might be caused by this commit: https://github.com/llvm/llvm-project/commit/d623b2f95fd559901f008a0588dddd0949a8db01. It seems PassManagerBuilder was removed from LLVM recently. I'm wondering if there is a way to solve this issue. Thanks.

**Comment by fodinabor** [comment]
Hi @AlbertXingZhang,
wow, congrats, you opened the 1000s issue/pr! 🥳

I fixed most of the LLVM 17 compatibility issues in #1003 but the SSCP (generic/JIT) compilation flow does not yet work with it.
As always, remember we mainly target stable LLVM versions, so no promises on when SSCP will be fixed with LLVM 17.

**Comment by aaronmondal** [comment]
Potentially related: https://github.com/OpenSYCL/OpenSYCL/issues/766. I remember having similar issues.

Edit: Ahh nevermind, this is just a missing header 😅

**Comment by illuhad** [comment]
I think this should be resolved by now.
