### ISSUE TITLE
getting an error while building opensycl

### ISSUE THREAD

**Issue by garadeaniket** [AdaptiveCpp/AdaptiveCpp#1010]
I was installing opensycl using llvm version 15.0.7 on x86 and after make install command , it shows the error below mentioned.
Please help to rectify the same.

make install
[  2%] Built target opensycl-common
[ 31%] Built target opensycl-clang
[ 32%] Linking CXX shared library libllvm-to-backend.so
/bin/ld: cannot find -lLLVM
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/compiler/llvm-to-backend/libllvm-to-backend.so] Error 1
make[1]: *** [src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/all] Error 2
make: *** [all] Error 2

**Comment by illuhad** [comment]
Hi,

If you are building with the SSCP compiler enabled (this is the case by default) you need an LLVM that provides dynamic libraries, i.e. an `libLLVM.so` or `libLLVM-<version>.so`. Do you have such a file?

If not, you can either:
* If you have built LLVM from source, build it in the way described here: https://github.com/OpenSYCL/OpenSYCL/blob/develop/doc/install-llvm.md#only-if-you-wish-to-compile-llvm-from-source-not-recommended
* If you have installed LLVM from binary packages, check if there might be additional packages available that provide the required library.
* Or disable the SSCP compiler using `-DWITH_SSCP_COMPILER=OFF`, if you do not intend to use it.

**Comment by garadeaniket** [comment]
I was installing opensycl using llvm version 15.0.7 on x86 and after make install command , it shows the error below mentioned.My previous error has been resolved but now getting new error.
Please help to rectify the same. 

 Building CXX object src/runtime/CMakeFiles/rt-backend-cuda.dir/cuda/cuda_allocator.cpp.o
/aniket/prakash/garade/OpenSYCL/src/runtime/cuda/cuda_allocator.cpp:143:15: error: no member named 'type' in 'cudaPointerAttributes'
  if (attribs.type == cudaMemoryTypeUnregistered) {
      ~~~~~~~ ^
/aniket/prakash/garade/OpenSYCL/src/runtime/cuda/cuda_allocator.cpp:143:23: error: use of undeclared identifier 'cudaMemoryTypeUnregistered'; did you mean 'cudaMemoryTypeDevice'?
  if (attribs.type == cudaMemoryTypeUnregistered) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                      cudaMemoryTypeDevice
/usr/local/cuda/include/driver_types.h:833:5: note: 'cudaMemoryTypeDevice' declared here
    cudaMemoryTypeDevice = 2  /**< Device memory */
    ^
/aniket/prakash/garade/OpenSYCL/src/runtime/cuda/cuda_allocator.cpp:153:35: error: no member named 'type' in 'cudaPointerAttributes'
  out.is_optimized_host = attribs.type == cudaMemoryTypeHost;
                          ~~~~~~~ ^
/aniket/prakash/garade/OpenSYCL/src/runtime/cuda/cuda_allocator.cpp:154:24: error: no member named 'type' in 'cudaPointerAttributes'
  out.is_usm = attribs.type == cudaMemoryTypeManaged;
               ~~~~~~~ ^
/aniket/prakash/garade/OpenSYCL/src/runtime/cuda/cuda_allocator.cpp:154:32: error: use of undeclared identifier 'cudaMemoryTypeManaged'; did you mean 'cudaMemoryTypeDevice'?
  out.is_usm = attribs.type == cudaMemoryTypeManaged;
                               ^~~~~~~~~~~~~~~~~~~~~
                               cudaMemoryTypeDevice
/usr/local/cuda/include/driver_types.h:833:5: note: 'cudaMemoryTypeDevice' declared here
    cudaMemoryTypeDevice = 2  /**< Device memory */
    ^
5 errors generated.
make[2]: *** [src/runtime/CMakeFiles/rt-backend-cuda.dir/cuda/cuda_allocator.cpp.o] Error 1
make[1]: *** [src/runtime/CMakeFiles/rt-backend-cuda.dir/all] Error 2
make: *** [all] Error 2

**Comment by illuhad** [comment]
Which CUDA version are you using? You might have to update your CUDA SDK.

**Comment by garadeaniket** [comment]
we dont have cuda , ROCm. we have to install it only on x86 architecture and we are also  skipping cuda dependencies during cmake during installation and  still we are getting this error. Please guide for installation on x86 without cuda , ROCm.

**Comment by illuhad** [comment]
Please provide the commands you use to configure and compile the project. The error is triggered in the CUDA backend, so the CUDA backend was enabled. cmake must have found some CUDA installation (or remnants of one?) on your system.

**Comment by garadeaniket** [comment]
cmake -DCMAKE_INSTALL_PREFIX=/path/to/OpenSYCL/build -DCLANG_EXECUTABLE_PATH=/path/to/bin/clang++ -DCLANG_INCLUDE_PATH=/path/to/include/clang/ -DCMAKE_CXX_COMPILER=/path/to/bin/clang++ -DBOOST_ROOT=/path/to/build 

This was the command used and cmake does find a CUDA installation but while building CUDA dependencies were ignored

**Comment by nilsfriess** [comment]
If I understand correctly, you _don't_ want to build for CUDA, right? You can try passing `-DWITH_CUDA_BACKEND=OFF`

**Comment by illuhad** [comment]
Given the lack of feedback I assume that this issue was resolved with the argument in the last comment. If not, please reopen the issue.
