### ISSUE TITLE
opensycl on arm

### ISSUE THREAD

**Issue by garadeaniket** [AdaptiveCpp/AdaptiveCpp#1044]

**Comment by fodinabor** [comment]
Yes. At least the CPU side has been successfully tested on Fujitsu's A64FX, Marvell ThunderX2, Apple M1.

**Comment by garadeaniket** [comment]
can you please guide how we can install on arm aarch64 , since i am new in this, what commands can use ?

**Comment by fodinabor** [comment]
Installing Open SYCL on Arm follows the normal procedures. (Cross-compilation from x86 is *not* tested)
Please take a look at the following documentation as a starting point: https://github.com/OpenSYCL/OpenSYCL/blob/develop/doc/installing.md

If you're stuck somewhere specific feel free to report back.
(Also with more information on what system you're targeting, what OS you have, ...)

**Comment by garadeaniket** [comment]
ok will follow the doc tq
