### ISSUE TITLE
The function createExitWithID is defined inconsistently in src/compiler/cbs/SubCfgFormation.cpp

### ISSUE THREAD

**Issue by yurivict** [AdaptiveCpp/AdaptiveCpp#1060]
Declaration and definition have different types [here](https://github.com/OpenSYCL/OpenSYCL/blob/develop/src/compiler/cbs/SubCfgFormation.cpp#L377).

**Comment by illuhad** [comment]
Thanks for reporting. Seems in one `size_t` is used and in the other `unsigned long` which I suppose is not the same on some platforms.
