### ISSUE TITLE
Generic SSCP seems interfering CPU OpenMP debugging ?

### ISSUE THREAD

**Issue by fxzjshm** [AdaptiveCpp/AdaptiveCpp#1064]
**Bug summary**
If SSCP & OpenMP backend is used together, when debugging kernel on CPU, local variables cannot be read.

**To Reproduce**
Code like this (modified from Xilinx's answer_42 example, named e.g. `answer_42_host_debug.cpp`):
```c++
#include <iostream>
#include <sycl/sycl.hpp>

int main() {
  sycl::buffer<int> answer{1};
  sycl::queue q;

  using real = float;
  real x = 1;

  q.submit([&](sycl::handler &cgh) {
     sycl::accessor acc{answer, cgh, sycl::write_only};
     cgh.parallel_for(sycl::range<1>(1), [=](sycl::id<1> id) {
       real y = x + 1;
       real z = y + 1;
       real a = z + 1;
       real b = a + 1;
       real c = b + 1;
       real d = c + 1;
       real e = d + 1;
       real f = e + 1;
       real g = f + 1;
       acc[0] = (g == g) ? 42 : 0;
     });
   }).wait();

  sycl::host_accessor ans{answer, sycl::read_only};
  std::cout << "The universal answer to the question is " << ans[0]
            << std::endl;
}
```

Compiled with
```bash
/opt/hipSYCL/bin/syclcc --hipsycl-targets="generic;omp.accelerated" -g answer_42_host_debug.cpp -O0 -o answer_42_host_debug -lstdc++
```
(Also tried `omp.library-only`, same result)

Debugged using gdb `GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1`.
Set breakpoint on each line of the kernel, then when each line is hit, only variable from last line can be read, others are all "optimized out".

![Screenshot_20230610_122122](https://github.com/OpenSYCL/OpenSYCL/assets/11426482/89a6520a-ee36-4053-950c-27a32ff1db95)

It sometimes gives incorrect values on some larger kernel, but I cannot reproduce it on smaller examples...

**Expected behavior**
If compiled without "generic", all values can be seen.

**Describe your setup**
* hipSYCL on commit `12fdcae` and `27542ab` (last 2 commits), with ROCm & SSCP enabled.
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang 16.0.5 from apt.llvm.org
   * host compiler: gcc / g++ 11.3.0 or clang 16.0.5
   * CUDA version: N/A
   * ROCm version and how ROCm was installed: ROCm 5.5.0 from repo.radeon.com
* How you have compiled your application and which arguments you have passed to `syclcc`. In particular, which backends and hardware you have compiled for.

```bash
/opt/hipSYCL/bin/syclcc --hipsycl-targets="generic;omp.accelerated" -g answer_42_host_debug.cpp -O0 -o answer_42_host_debug -lstdc++
```
and same without `generic`

**Optional additional diagnostic information**
The following information can potentially help us:
* For compilation/toolchain or setup-related issues: Setting the environment variable `HIPSYCL_DRYRUN=1` during compilation will cause `syclcc` to print the commands it would execute instead of actually executing. This can help verify the sanity of your setup.

<details>
With `generic`:

```bash
/usr/lib/llvm-16/bin/clang++ -isystem /opt/hipSYCL/bin/../include/ -D__OPENSYCL__ -D__HIPSYCL__ -std=c++17 -D__HIPSYCL_ENABLE_LLVM_SSCP_TARGET__ -Xclang -disable-O0-optnone -mllvm -hipsycl-sscp -fplugin=/opt/hipSYCL/bin/../lib/libopensycl-clang.so -fpass-plugin=/opt/hipSYCL/bin/../lib/libopensycl-clang.so -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -D__HIPSYCL_USE_ACCELERATED_CPU__ -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE -g answer_42_host_debug.cpp -O0 -o answer_42_host_debug -lstdc++ -L/opt/hipSYCL/bin/../lib/ -lhipSYCL-rt -Wl,-rpath=/opt/hipSYCL/bin/../lib/ -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
```

Without `generic`:

```bash
/usr/lib/llvm-16/bin/clang++ -isystem /opt/hipSYCL/bin/../include/ -D__OPENSYCL__ -D__HIPSYCL__ -std=c++17 -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -fplugin=/opt/hipSYCL/bin/../lib/libopensycl-clang.so -fpass-plugin=/opt/hipSYCL/bin/../lib/libopensycl-clang.so -D__HIPSYCL_USE_ACCELERATED_CPU__ -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE -g answer_42_host_debug.cpp -O0 -o answer_42_host_debug -lstdc++ -L/opt/hipSYCL/bin/../lib/ -lhipSYCL-rt -Wl,-rpath=/opt/hipSYCL/bin/../lib/ -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
```

</details>

* `syclcc --hipsycl-version` prints information about the hipSYCL configuration that may be interesting for setup-related issues.

<details>

```
syclcc [Open SYCL compilation driver], Copyright (C) 2018-2023 Aksel Alpay and the Open SYCL project
  Open SYCL version: 0.9.4
  Installation root: /opt/hipSYCL
  Plugin LLVM version: 16, can accelerate CPU: True
  Available runtime backends:
     librt-backend-hip.so
     librt-backend-ze.so
     librt-backend-omp.so


Full configuration [can be overriden using environment variables or command line arguments]:
    version-major: 0
    version-minor: 9
    version-patch: 4
    plugin-llvm-version-major: 16
    plugin-with-cpu-acceleration: true
    default-clang: /usr/lib/llvm-16/bin/clang++
    default-nvcxx: (unconfigured)
    default-platform: rocm
    default-cuda-path: (unconfigured)
    default-gpu-arch: (unconfigured)
    default-cpu-cxx: /usr/bin/clang++-16
    default-rocm-path: /opt/rocm-5.5.0
    default-use-bootstrap-mode: false
    default-is-dryrun: false
    default-use-accelerated-cpu: true
    default-clang-include-path: /usr/lib/llvm-16/lib/clang/16/include/..
    default-sequential-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
    default-sequential-cxx-flags: -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-omp-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
    default-omp-cxx-flags: -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm-5.5.0/lib -L/opt/rocm-5.5.0/hip/lib -lamdhip64
    default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike -isystem /usr/lib/llvm-16/lib/clang/16/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
    default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
    default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike
    default-is-explicit-multipass: false
    default-save-temps: false
```

</details>

* For issues related to the runtime, setting the environment variable `HIPSYCL_DEBUG_LEVEL=3` will cause it to print *a lot* of diagnostic information that might be helpful. Attach the output of your program with `HIPSYCL_DEBUG_LEVEL=3` if you think it might be helpful for your issue.
* Recent hipSYCL versions include a tool called `opensycl-info`, which will print information about available backends and devices. This may be interesting for issues related to e.g. device visibility.

**Additional context**

**Comment by illuhad** [comment]
Interesting. `generic` does not change the kernel instantiation for the OpenMP backend. However, it does need to run dead code elimination passes to implement the single-pass code separation between host and device code. Because this affects functional correctness, this needs to be done even with -O0. In particular, what it also does is constant propagation. This is to enable host constants affect code across the host-device boundary, and to be able to reliably implement branching based on IR constants such as
```
if(__hipsycl_sscp_is_device) {
// device code
} else {
// host code
}
```
where the exact if-statement might also be a more complex statement based on some IR constant.
My guess is that in your example, it has found out that it can optimize kernel generation by folding the host x into device code and merging those instructions.

**Comment by fxzjshm** [comment]
Oh thanks for the explanation, so this is within expectation, right? Have to temporarily disable `generic` to debug...

**Comment by illuhad** [comment]
I think some minor interference can be expected, especially for such trivial cases as in your example. Whether there are additional issues I don't know.
Is there any change if you use `omp.library-only;generic` instead of `omp.accelerated`?

**Comment by fxzjshm** [comment]
In my cases seems no change.

**Comment by illuhad** [comment]
I see. In that case it's most likely a consequence of the dead code elimination and constant propagation that is necessary as part of the single-pass SSCP device code extraction as explained. I don't know how to easily solve this, as this is fundamentally necessary for SSCP.

**Comment by fxzjshm** [comment]
Also noticed some variables on "host" are affected if a kernel is called.
Before calling kerne (this function contains a kernel):
![Screenshot_20230610_234833](https://github.com/OpenSYCL/OpenSYCL/assets/11426482/aecd59cc-6417-4f1c-877c-5d40308a3278)

When breakpoint in kernel is hit, switch back to host thread to check values on "host" side:
![Screenshot_20230610_234908](https://github.com/OpenSYCL/OpenSYCL/assets/11426482/6dcf4c02-38ce-4788-91a1-37c818b8693c)

`f_c` and `f_min` are sky frequencies of a radio telescope in MHz unit, so the changed values are strange. Result of the code is correct, so maybe gdb interpreted wrong memory regions, maybe also something caused by optimizations.
Cannot reproduce this in smaller code though...

As it's necessary for SSCP, I think just leave it as it is then;
in case anyone hits this, try removing `generic` to debug kernel on CPU.

**Comment by illuhad** [comment]
If breakpoints in kernels on host are involved, I could imagine that the compiler transformations of the `omp.accelerated` backend also play a role, even though I really don't know how SSCP might influence this if kernel is exclusively invoked on host. Maybe @fodinabor has an idea?

**Comment by fxzjshm** [comment]
Well, this is also triggered in `omp.library-only`... The screenshots above is captured using `omp.library-only`

**Comment by fxzjshm** [comment]
I managed to construct a reproduce code for breakpoints on host, the key point is that the function calling kernel (`f()`) is not affected, but the function calling `f()` is,
```c++
#include <iostream>
#include <sycl/sycl.hpp>

using real = float;

inline auto f(sycl::buffer<int>& answer, sycl::queue& q, real c) {
  q.submit([&](sycl::handler& cgh) {
     sycl::accessor acc{answer, cgh, sycl::write_only};
     cgh.parallel_for(sycl::range<1>(1), [=](sycl::id<1> id) {
       real d = c + 1;
       real e = d + 1;
       real f = e + 1;
       real g = f + 1;
       acc[0] = (g == g) ? 42 : 0;
     });
   }).wait();
}

inline auto g(sycl::buffer<int>& answer, sycl::queue& q, real z) {
  real a = z + 1;
  real b = a + 1;
  real c = b + 1;
  return f(answer, q, c);
}

int main() {
  sycl::buffer<int> answer{1};
  sycl::queue q;

  real x = 1;
  real y = x + 1;
  real z = y + 1;
  g(answer, q, z);

  sycl::host_accessor ans{answer, sycl::read_only};
  std::cout << "The universal answer to the question is " << ans[0]
            << std::endl;
}
```

![Screenshot_20230611_003047](https://github.com/OpenSYCL/OpenSYCL/assets/11426482/7b74525e-8673-467a-b458-5cb8d3bd658a)
