### ISSUE TITLE
 fatal error: 'CL/sycl.hpp' file not found #include <CL/sycl.hpp>  

### ISSUE THREAD

**Issue by Hongbin-Bao** [AdaptiveCpp/AdaptiveCpp#1079]
When I try to build a SYCL project with clion on my macbook
that is the code:
‘’‘
#include <iostream>
#include <CL/sycl.hpp>
int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
‘’‘

that is the cmake.txt
'’‘
cmake_minimum_required(VERSION 3.25)
project(untitled9)
set(CMAKE_CXX_STANDARD 17)
include_directories(/usr/local/include/SYCL)
add_executable(untitled9 main.cpp)
'’‘’
There is sycl.hpp in the /usr/local/include/SYCL directory
'‘’‘(base)MacBook-Pro ~ % ls /usr/local/include/CL
sycl.hpp'’‘

but when i run the code i get the error:
'‘’
====================[ Build | untitled9 | Debug ]===============================
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /Users/Desktop/code/c/untitled9/cmake-build-debug --target untitled9 -j 8
[1/2] Building CXX object CMakeFiles/untitled9.dir/main.cpp.o
FAILED: CMakeFiles/untitled9.dir/main.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/usr/local/include/SYCL -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.5 -fcolor-diagnostics -std=gnu++17 -MD -MT CMakeFiles/untitled9.dir/main.cpp.o -MF CMakeFiles/untitled9.dir/main.cpp.o.d -o CMakeFiles/untitled9.dir/main.cpp.o -c /Users/Desktop/code/c/untitled9/main.cpp
/Users/Desktop/code/c/untitled9/main.cpp:2:10: fatal error: 'CL/sycl.hpp' file not found
#include <CL/sycl.hpp>
         ^~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.'’‘

**Comment by illuhad** [comment]
Probably you've already found the issue, but in case someone else has the same issue and sees this: You are not using `syclcc`, the hipSYCL compiler driver, which needs to be used even if you are using a library-only compilation flow. It sets include paths, ensures programs links correctly and configures SYCL headers correctly for the targeted backends.

See here on how to correctly set up a cmake project: https://github.com/OpenSYCL/OpenSYCL/blob/develop/doc/using-hipsycl.md#using-the-cmake-integration
