### ISSUE TITLE
Matrix vector multiplication performances 1D vs 2D 

### ISSUE THREAD

**Issue by deicidia** [AdaptiveCpp/AdaptiveCpp#1082]
hi, 

I'm trying to code an optimized matrix-vector product using Open SYCL, and my initial code looks like this:
```
h.parallel_for(nd_range(range<1>(nb_ligne * nb_thread_ligne),range<1>(nb_thread_ligne)), [=](auto item) {
    size_t global_id = item.get_global_id(0);
    size_t local_id = item.get_local_id();
    
    double sum = 0;

    int ligne = global_id / nb_thread_ligne;

    for(size_t j = local_id; j < nb_elem_ligne; j += nb_thread_ligne)
    {
        sum += acc_M[ligne * nb_elem_ligne + j] * acc_V[j]; 
    }
    local_sum[local_id] = sum;

    item.barrier(access::fence_space::local_space);

    if(local_id == 0)
    {
        double group_sum = 0;
	for(size_t i = 0; i < nb_thread_ligne; i++)
	{
	    group_sum += local_sum[i];
	}
	acc_R[item.get_group(0)] = group_sum;
    }
});	
```
I wanted to reuse the vector and, instead of assigning one work group per line of the matrix, I tried to assign one subgroup. The code is as follows: 
```
cgh.parallel_for(nd_range(range<2>(nb_ligne, dim_x), range<2>(dim_y, dim_x)),[=](nd_item<2> it) {

    auto X = it.get_global_id(1);  
    auto Y = it.get_global_id(0);

    auto x = it.get_local_id(1);
    auto y = it.get_local_id(0);

    double sum = 0; 

    for(size_t i = x; i < nb_col; i+=dim_x)
    {
        sum += acc_M[i + Y*nb_col] * acc_V[i]; 
    }
    
    local_sum[x + y*dim_x] = sum;

    it.barrier(access::fence_space::local_space);

    if(x == 0)
    {
        double group_sum = 0;
	for(size_t i = 0; i < dim_x; i++)
        {
	    group_sum += local_sum[i + y*dim_x];
	}
	acc_R[Y] = group_sum;
    }
});
```
The issue is that I'm experiencing worse performance even when I fix it to (256x1), which should be equivalent to the other version. Do you have any idea if the problem lies with the concept, the implementation, or the 2D kernel ? 

(My code runs on an NVIDIA A100)

**Comment by illuhad** [comment]
Is this code ported from CUDA? I see some unusual index swapping (i.e. x refers to dimension 1) which makes it more difficult to understand the memory access pattern. I assume this is to account for different assumptions in CUDA and SYCL (In CUDA, x, is the vectorizing dimension, while in SYCL it is the highest index), if the code originated from CUDA.

I don't understand yet how those codes are equivalent. The output memory access pattern is different. In the 1D version, each group writes to the index of the group id, while in the 2D version, the output is stored at the global id of the work item with local id 0, causing a strided memory access pattern.

**Comment by deicidia** [comment]
No, it's not ported code.

As I conceived it, the first one assigns one workgroup per line of the matrix with 256 work items (when working with an NVIDIA GPU, it should assign 8 subgroups performing coalesced memory access).

In the second one, I tried to assign 32 work items (1 subgroup) per line and 32 lines per workgroup, resulting in a total of 1024 work items. Each subgroup performing coalesced memory access.

However, when I assign (256x1) instead of (32x32), which in my mind should be equivalent, the performance does not match. I apologize for any misunderstanding, and thank you for the quick answer.

**Comment by deicidia** [comment]
I tried using the demo code for scoped parallelism in the hope of translating the code above, but I encountered numerous errors. When I attempted a simpler example like:

```
#include <sycl/sycl.hpp>
#include <vector>

int main(){

	sycl::queue q{};

	sycl::range<1> num_work_groups = 4;
	sycl::range<1> logical_group_size = 1;
	
	
	std::vector<int> m(16, 1);
	std::vector<int> v(4, 1);
	std::vector<int> r(4, 0); 
	
	sycl::buffer<int> M(m.data(), sycl::range<1>{m.size()});
	sycl::buffer<int> V(v.data(), sycl::range<1>{v.size()});
	{		
	sycl::buffer<int> R(r.data(), sycl::range<1>{r.size()});
	q.submit([&](sycl::handler& cgh)
	{
		sycl::stream out(1024, 256, cgh);
		
		sycl::accessor acc_m(M, cgh); 
		sycl::accessor acc_v(V, cgh);
		sycl::accessor acc_r(R, cgh);

		cgh.parallel(num_work_groups, logical_group_size, [=](auto grp)
		{
				
			sycl::distribute_items(grp, [=](auto local_id)
			{
                 		auto gid = local_id.get_global_id(0);
                  		auto lid = local_id.get_innermost_local_id(0);
				
				for(auto i = 0; i < 4; i++){
					acc_r[gid] += acc_m[gid+i] * acc_v[i];
				}
			});
			//sycl::group_barrier(grp);
		});
	}).wait();
	}

	for(auto nb : r) std::cout << nb << " ";
	std::cout << "\n"; 
}
```

It's `sycl::group_barrier(grp);` that block the compilation with the associated error : 

```
~/opt/OpenSYCL/bin/syclcc -O3 ~/TEST/scoped_parallelism.cpp  --opensycl-targets="cuda-nvcxx"

/tmp/nvc++VThBjngrAdj0W.o: In function `_ZN7hipsycl4glue12omp_dispatch21iterate_range_omp_forILi1EZZNS1_15parallel_regionINS_4sycl6detail12nested_rangeINS5_12static_rangeILin1ELin1ELin1EEENS6_INS7_ILi16ELi1ELi1EEENS5_18unity_nested_rangeEEEEEZZ4mainENKUlRNS4_7handlerEE_clESE_EUlT_E_Li1EJEEEvT0_NS4_5rangeIXT1_EEESK_mDpT2_ENKUlDpRSG_E_clIJEEEDaSO_EUlNS4_2idILi1EEEE_EEvNSJ_IXT_EEESI_': /opt/OpenSYCL/bin/../include/hipSYCL/glue/omp/omp_kernel_launcher.hpp:410: undefined reference to `__builtin_is_device_code'
```
Any idea why ? Thanks for your time !

**Comment by illuhad** [comment]
> /tmp/nvc++VThBjngrAdj0W.o: In function `_ZN7hipsycl4glue12omp_dispatch21iterate_range_omp_forILi1EZZNS1_15parallel_regionINS_4sycl6detail12nested_rangeINS5_12static_rangeILin1ELin1ELin1EEENS6_INS7_ILi16ELi1ELi1EEENS5_18unity_nested_rangeEEEEEZZ4mainENKUlRNS4_7handlerEE_clESE_EUlT_E_Li1EJEEEvT0_NS4_5rangeIXT1_EEESK_mDpT2_ENKUlDpRSG_E_clIJEEEDaSO_EUlNS4_2idILi1EEEE_EEvNSJ_IXT_EEESI_': /opt/OpenSYCL/bin/../include/hipSYCL/glue/omp/omp_kernel_launcher.hpp:410: undefined reference to `__builtin_is_device_code'

nvc++ bug. `__builtin_is_device_code` is an internal nvc++ builtin. We have nothing to do with that. nvc++ is sometimes challenged by complex C++ constructs like multiple nested lambdas as they commonly occur in scoped parallelism.
That said, it's unlikely that scoped parallelism help you with your performance behavior, as on GPUs, it just maps back to regular `nd_range`-style kernels.

EDIT: If you have used `cuda-nvcxx` so far, I'd recommend trying regular `cuda` (or `generic`) targets, which go through clang, to verify if those exhibit the same performance behavior.

**Comment by deicidia** [comment]
Thank you very much for the help, I'll try to use it.
