### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by breyerml** [AdaptiveCpp/AdaptiveCpp#1092]
**Bug summary**
A `sycl::nd_item::barrier` is necessary, where it shouldn't be.

**To Reproduce**
A "small" triangular GEMM kernel:
```c++
#include "sycl/sycl.hpp"

using real_type = double;

class device_kernel_gemm {
  static constexpr unsigned long long FEATURE_BLOCK_SIZE = 16;
  static constexpr unsigned long long THREAD_BLOCK_SIZE = 32;

  public:
    device_kernel_gemm(::sycl::handler &cgh, const unsigned long long m, const unsigned long long n, const unsigned long long k, const real_type alpha, const real_type *A, const real_type *B, const real_type beta, real_type *C) :
        A_cache_{ ::sycl::range<2>{ FEATURE_BLOCK_SIZE, THREAD_BLOCK_SIZE }, cgh }, B_cache_{ ::sycl::range<2>{ FEATURE_BLOCK_SIZE, THREAD_BLOCK_SIZE }, cgh },
        m_{ m }, n_{ n }, k_{ k }, alpha_{ alpha }, A_{ A }, B_{ B }, beta_{ beta }, C_{ C } {}

    void operator()(::sycl::nd_item<2> nd_idx) const {
        // compute: C = alpha * A * B + beta * C with A in m x k, B in n x k, and C in n x m, alpha, beta as scalar
        const unsigned long long i = nd_idx.get_global_id(0);
        const unsigned long long i_cached_idx = nd_idx.get_group(0) * nd_idx.get_local_range(0) + nd_idx.get_local_id(1);
        const unsigned long long j = nd_idx.get_global_id(1);

        real_type temp{ 0.0 };

        for (unsigned long long dim = 0; dim < k_; dim += FEATURE_BLOCK_SIZE) {
            // zero out shared memory
            if (nd_idx.get_local_id(0) < FEATURE_BLOCK_SIZE) {
                A_cache_[nd_idx.get_local_id(0)][nd_idx.get_local_id(1)] = real_type{ 0.0 };
                B_cache_[nd_idx.get_local_id(0)][nd_idx.get_local_id(1)] = real_type{ 0.0 };
            }
            nd_idx.barrier();  // shouldn't be necessary

            // load data into shared memory
            if (nd_idx.get_local_id(0) < FEATURE_BLOCK_SIZE && dim + nd_idx.get_local_id(0) < k_) {
                if (dim + nd_idx.get_local_id(0) < i_cached_idx) {
                    if (i_cached_idx < k_) {
                        A_cache_[nd_idx.get_local_id(0)][nd_idx.get_local_id(1)] = A_[(dim + nd_idx.get_local_id(0)) * k_ + i_cached_idx - (dim + nd_idx.get_local_id(0)) * (dim + nd_idx.get_local_id(0) + 1) / 2];
                    }
                } else {
                    A_cache_[nd_idx.get_local_id(0)][nd_idx.get_local_id(1)] = A_[i_cached_idx * k_ + dim + nd_idx.get_local_id(0) - i_cached_idx * (i_cached_idx + 1) / 2];
                }
                if (j < n_) {
                    B_cache_[nd_idx.get_local_id(0)][nd_idx.get_local_id(1)] = B_[(dim + nd_idx.get_local_id(0)) * n_ + j];
                }
            }
            nd_idx.barrier();

            // calculation
            for (unsigned long long block_dim = 0; block_dim < FEATURE_BLOCK_SIZE; ++block_dim) {
                temp += A_cache_[block_dim][nd_idx.get_local_id(0)] * B_cache_[block_dim][nd_idx.get_local_id(1)];
            }
            nd_idx.barrier();
        }

        if (i < m_ && j < n_) {
            C_[i * n_ + j] = alpha_ * temp + beta_ * C_[i * n_ + j];
        }
    }

  private:
    /// Local memory used for internal memory access optimizations.
    ::sycl::local_accessor<real_type, 2> A_cache_;
    /// Local memory used for internal memory access optimizations.
    ::sycl::local_accessor<real_type, 2> B_cache_;

    const unsigned long long m_;
    const unsigned long long n_;
    const unsigned long long k_;
    const real_type alpha_;
    const real_type *A_;
    const real_type *B_;
    const real_type beta_;
    real_type *C_;
};


int main() {
  constexpr unsigned long long N = 32768;
  constexpr unsigned long long M = 64;

  sycl::queue q{};

  real_type *A = sycl::malloc_shared<real_type>(N * (N + 1) / 2, q);
  for (unsigned long long i = 0; i < N * (N + 1) / 2; ++i) {
    A[i] = 1.0;
  }
  real_type *B = sycl::malloc_shared<real_type>(M * N, q);
  for (unsigned long long i = 0; i < M * N; ++i) {
    B[i] = 1.0;
  }
  real_type *C = sycl::malloc_shared<real_type>(M * N, q);

  const sycl::range<2> block{ 32, 32 };
  const sycl::range<2> grid{ static_cast<std::size_t>(std::ceil(static_cast<double>(N) / static_cast<double>(block[0]))) * block[0],
                             static_cast<std::size_t>(std::ceil(static_cast<double>(M) / static_cast<double>(block[1]))) * block[1] };
  const sycl::nd_range<2> execution_range{ grid, block };

  q.submit([&](::sycl::handler &cgh) {
    cgh.parallel_for(execution_range, device_kernel_gemm{ cgh, N, M, N, real_type{ 1.0 }, A, B, real_type{ 0.0 }, C });
  }).wait();

  std::cout << std::boolalpha << std::all_of(C, C + M * N, [](const real_type val) { return val == N; }) << std::endl;
  std::cout << *C << std::endl;

  return 0;
}
```
Compiled with `syclcc -O3 -std=c++17 --opensycl-targets="cuda:sm_86" main.cpp` on an NVIDIA RTX 3080.
If the barrier after zeroing out the local/shared memory is present, the output of the program is: 
```
true
32768
```
If the barrier es removed, the output is:
```
false
0
```

**Expected behavior**
The code should work even without the barrier after zeroing the local/shared memory. Since after zeroing the memory its guaranteed that a thread T_{i, j} only writes to a memory location it has been previously zeroed out, there shouldn't be any race conditions.
(The same code without a barrier works under DPC++, similar code works under OpenCL, CUDA, and HIP.)

**Describe your setup**
The hipSYCL commit caee556 has been compiled with
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../caee5569 -DWITH_CUDA_BACKEND=ON -DWITH_ACCELERATED_CPU=ON -DWITH_SSCP_COMPILER=ON -DCMAKE_CXX_COMPILER=clang++ ../source
```
where `clang++` is the DPC++ compiler:
```
clang version 17.0.0 (https://github.com/intel/llvm.git 15f5ac37bb52cde9133f8e8b69e33b5fe8e68c65)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /data/scratch/breyerml/Programs/dpcpp/20230708/build/bin
```
compiled with CUDA support. The used CUDA version is 12.0.1.

**Optional additional diagnostic information**
- `HIPSYCL_DRYRUN`: [HIPSYCL_DRYRUN.txt](https://github.com/OpenSYCL/OpenSYCL/files/12147580/HIPSYCL_DRYRUN.txt)
- `HIPSYCL_VERSION`: [HIPSYCL_VERSION.txt](https://github.com/OpenSYCL/OpenSYCL/files/12147587/HIPSYCL_VERSION.txt)
- `HIPSYCL_DEBUG_LEVEL`: [HIPSYCL_DEBUG_LEVEL.txt](https://github.com/OpenSYCL/OpenSYCL/files/12147607/HIPSYCL_DEBUG_LEVEL.txt)
- `OPENSYCL_INFO`: [OPENSYCL_INFO.txt](https://github.com/OpenSYCL/OpenSYCL/files/12147614/OPENSYCL_INFO.txt)

**Comment by illuhad** [comment]
> The code should work even without the barrier after zeroing the local/shared memory. Since after zeroing the memory its guaranteed that a thread T_{i, j} only writes to a memory location it has been previously zeroed out, there shouldn't be any race conditions.

Well clearly this assumption is incorrect :-) We don't do any magic to the execution model or barriers. With `--hipsycl-targets=cuda`, a barrier literally just calls `__syncthreads()`. If it does not work, most likely it is because either the hardware does not behave the way you expect it to, or the LLVM backend reorders instructions in a way you don't expect. We don't touch either.

So far I cannot reproduce here. Check if a subgroup barrier is sufficient (maybe some warp divergence occurs somewhere?), or try a stock LLVM release. Those vendor LLVMs sometimes mess things up because vendors mainly test with their particular compilation flow, and might break other things. Officially we only support released versions of vanilla LLVM, so no development versions either (which might be unstable too).

EDIT: Also try with cuda-memcheck or similar to check for UB memory accesses.

**Comment by breyerml** [comment]
It looks like it is indeed a bug in DPC++. Compiling hipSYCL with a clang 16.0.2 build via spack and everything works as expected.
Thank you nevertheless, we would have never thought that it may be a DPC++ problem, because it works fine with DPC++ itself.
