### ISSUE TITLE
LLVMSpirvTranslator configure step fails LLVMSPIRVLib already exists

### ISSUE THREAD

**Issue by reguly** [AdaptiveCpp/AdaptiveCpp#1101]
**Bug summary**
When trying to compile with SPIRV support, the LLVMSpirvTranslator step fails with the following CMake error:
[ 78%] Performing configure step for 'LLVMSpirvTranslator'
CMake Error at /home/u101201/llvm-nightly-2023-08-04/build/install/lib/cmake/llvm/AddLLVM.cmake:590 (add_library):
  add_library cannot create target "LLVMSPIRVLib" because an imported target
  with the same name already exists.
Call Stack (most recent call first):
  /home/u101201/llvm-nightly-2023-08-04/build/install/lib/cmake/llvm/AddLLVM.cmake:850 (llvm_add_library)
  lib/SPIRV/CMakeLists.txt:41 (add_llvm_library)

CMake Error at /home/u101201/llvm-nightly-2023-08-04/build/install/lib/cmake/llvm/AddLLVM.cmake:714 (target_link_libraries):
  Cannot specify link libraries for target "LLVMSPIRVLib" which is not built
  by this project.
Call Stack (most recent call first):
  /home/u101201/llvm-nightly-2023-08-04/build/install/lib/cmake/llvm/AddLLVM.cmake:850 (llvm_add_library)
  lib/SPIRV/CMakeLists.txt:41 (add_llvm_library)

**To Reproduce**
Using llvm-nightly-2023-08-04, compiled with --shared-libs
then opensycl config goes through fine:
cmake .. -DWITH_LEVEL_ZERO_BACKEND=ON
make fails with the above

**Expected behavior**
compilation should work

**Describe your setup**
OpenSYCL 485ea8089cfc051d1d5ed916f4cf3fd6800c6335
llvm-nightly-2023-08-04

**Comment by illuhad** [comment]
Firstly, please note that unreleased/nightly LLVM development versions are not officially supported. These LLVM versions are moving targets, and are generally not stable. They may or may not work. We only test against LLVM releases.

For unreleased development versions, you may have to additionally set `-DLLVMSPIRV_BRANCH=main`. Otherwise it will try to find the appropriate llvm-spirv translator branch for the LLVM version, which may not exist if it is an unreleased LLVM.

If that does not help, there might be some upstream compatibility issue between llvm-spirv translator and LLVM. It looks like that LLVM version already ships some SPIR-V components which might conflict (?) with llvm-spirv translator.

**Comment by reguly** [comment]
Thanks for the quick answer. As I understand, I need to build with the intel/llvm fork. Can you suggest a version/tag/commit that is known to work? 
If I set `-DLLVMSPIRV_BRANCH=main`, then it gives the following error.

CMake Error at CMakeLists.txt:82 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "18.0.0".

  The following configuration files were considered but not accepted:

    /home/u101201/llvm-nightly-2023-08-04/build/install/lib/cmake/llvm/LLVMConfig.cmake, version: 17.0.0git

**Comment by illuhad** [comment]
> Thanks for the quick answer. As I understand, I need to build with the intel/llvm fork. 

No, this is incorrect. The production SPIR-V support goes through our generic single-pass compiler (`--hipsycl-targets=generic`), which is fully independent. It should work with any LLVM release >= 14.

Earlier experiments (`--hipsycl-targets=spirv`) did use some components from intel/llvm, but those never were reliable and will be removed in the future.

> The following configuration files were considered but not accepted:

Sounds like that package still advertises itself as 17, while llvm-spirv is already on 18. Or something is broken with the LLVM cmake infrastructure.

**Comment by reguly** [comment]
It does indeed work with the latest LLVM release, 16.0.6
