### ISSUE TITLE
How to compile for integrated AMD GPUs?

### ISSUE THREAD

**Issue by ManuelCostanzo** [AdaptiveCpp/AdaptiveCpp#1105]
Hey! How are you?

Thanks again for this project.

I have an AMD Ryzen 3 5300U notebook with Radeon Graphics (iGPU). I could run with openMP on the CPU without any issues, but I'm wondering if it's possible to run on the iGPU? What flag would I need to specify?

I already have LLVM with ROCM and openSYCL.

Thank you very much!

**Comment by illuhad** [comment]
Targeting APUs works the same as for any AMD GPU. You can either use `syclcc --hipsycl-targets=generic` if you want to use the generic SSCP compiler, or `--hipsycl-targets=hip:gfxXYZ` if you want to use the older SMCP compiler. `gfxXYZ` is the GPU architecture where X, Y, Z need to be replaced. You can find the GPU architecture for your device in the output of `opensycl-info`.
The generic SSCP compiler JIT-compiles at runtime to whatever device it finds on the system (including Intel, NVIDIA and AMD GPUs), so it does not need to know the target in advance.

Note that AMD APUs are not officially supported in ROCm by AMD, although they may work well in practice. I regularly run SYCL code on my AMD 4750U APU. Your mileage may vary.

**Comment by ManuelCostanzo** [comment]
Hi @illuhad, thank you very much! Do you think these flags are ok for llvm? 

```
CC=cc
CXX=c++
BUILD_TYPE=Release
TARGETS_TO_BUILD="AMDGPU;NVPTX;X86"
NUMTHREADS=`nproc`

CMAKE_OPTIONS="-DLLVM_ENABLE_PROJECTS=clang;compiler-rt;lld;openmp \
-DOPENMP_ENABLE_LIBOMPTARGET=OFF \
-DCMAKE_C_COMPILER=$CC \
-DCMAKE_CXX_COMPILER=$CXX \
-DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DCMAKE_INSTALL_PREFIX=$LLVM_INSTALL_PREFIX \
-DLLVM_ENABLE_RUNTIMES=all \
-DLLVM_ENABLE_ASSERTIONS=OFF \
-DLLVM_TARGETS_TO_BUILD=$TARGETS_TO_BUILD \
-DCLANG_ANALYZER_ENABLE_Z3_SOLVER=0 \
-DLLVM_INCLUDE_BENCHMARKS=0 \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON \
-DCMAKE_INSTALL_RPATH=$LLVM_INSTALL_PREFIX/lib \
-DLLVM_ENABLE_OCAMLDOC=OFF \
-DLLVM_LINK_LLVM_DYLIB=ON \
-DLLVM_ENABLE_BINDINGS=ON \
-DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=OFF \
-DLLVM_BUILD_LLVM_DYLIB=ON \
-DWITH_ROCM_BACKEND=ON \
-DWITH_LEVEL_ZERO_BACKEND=ON \
-DLLVM_ENABLE_DUMP=OFF" \
```

And then for OpenSYCL, I just use:

```
cmake \
-DWITH_ACCELERATED_CPU=ON \
-DWITH_SSCP_COMPILER=ON \
-DWITH_CPU_BACKEND=ON \
-DWITH_CUDA_BACKEND=ON \
-DWITH_ROCM_BACKEND=ON \
-DLLVM_DIR=$OPENSYCL_LLVM_DIR \
-DROCM_PATH=/opt/rocm \
-DCMAKE_INSTALL_PREFIX=$OPENSYCL_INSTALL_PREFIX \
..
```
Then, using ```opensycl-info``` I will be able to see both my Intel and AMD computer the CPU and APU, right?

**Comment by illuhad** [comment]
> -DWITH_ROCM_BACKEND=ON \
-DWITH_LEVEL_ZERO_BACKEND=ON \
-DLLVM_ENABLE_DUMP=OFF" \

These flags are for Open SYCL, not LLVM

> And then for OpenSYCL, I just use:

You are missing `-DWITH_LEVEL_ZERO_BACKEND=ON`, if you want Intel GPU support.

> Then, using opensycl-info I will be able to see both my Intel and AMD computer the CPU and APU, right?

You will all the supported devices attached to the system, including your CPU as well as GPUs from Intel, NVIDIA and AMD.

**Comment by illuhad** [comment]
This seems to be resolved.
