### ISSUE TITLE
handler::fill() - offset of ranged accessor is applied twice

### ISSUE THREAD

**Issue by stukowski** [AdaptiveCpp/AdaptiveCpp#1110]
**Bug summary**

There seems to be a critical bug in the implementation of `handler::fill()` if it used with a ranged accessor. The accessor's offset is applied twice.

**To Reproduce**

```c++
std::vector<int> data(8, 0);
{
    using namespace cl::sycl;
    queue q;
    buffer<int> buf(data.data(), data.size());
    q.submit([&](handler& cgh) {
        auto access = buf.get_access<access::mode::write>(cgh, range(1), id(2));
        cgh.fill(access, 1);
    });
}
for(auto val : data)
    std::cout << val << " ";
std::cout << std::endl;
```

The code snippet initializes a buffer of length 8 with zeros. It then submits a `fill` operation using a ranged accessor (`range`=1, `offset`=2) to set the 3rd array element to 1. The expected output is 
```
0 0 1 0 0 0 0 0 
``` 
but the observed output is 
```
0 0 0 0 1 0 0 0 
``` 

Tested on macOS with OpenMP backend (HEAD of branch develop, git commit 485ea8089cfc05). 

Bug is likely located in [line 508 of handler.hpp](https://github.com/OpenSYCL/OpenSYCL/blob/aec54afe7735bc41e03283eb6c9697e653ac6586/include/hipSYCL/sycl/handler.hpp#L508). The use of `get_offset(dest)` leads to the range offset being applied twice. Instead, `sycl::id<dim>{}` should be used to fix this issue, I think.

**Comment by illuhad** [comment]
Thanks for reporting, this probably happened when transitioning to SYCL 2020 accessor semantics. In earlier versions of SYCL (SYCL 1.2.1 specification), accessors were not supposed to add their offset when using `operator[]`. Instead, you were supposed to rely on providing an offset to `parallel_for`. This was changed in the SYCL 2020 specification, when `parallel_for` offsets were deprecated, and accessors were changed to now add their offset in `operator[]`.

It seems when we made the change to SYCL 2020 accessor semantics, we missed changing it here.

@nilsfriess Can you look into fixing this, and verify that the other member functions of `handler` are fine?

**Comment by nilsfriess** [comment]
Yes, I'll take a look
