### ISSUE TITLE
Problem with std::stoi when compiling OpenSYCL on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1129]
Please excuse me if I ask something stupid, I am new on compiling cross-platform projects on Windows.

I am trying to build OpenSYCL on Windows 11, using instructions from wiki.

I've built Clang, boost, and now am trying to compile OpenSYCL using Clang I built.

This is the cmake command:

`cmake .. -G Ninja -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe -DBOOST_ROOT=C:/Libraries/boost_1_83 -DLLVM_DIR=c:/llvm/lib/cmake/llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=c:/OpenSYCL`

cmake finishes fine, but ninja, while building, says this:

```
[42/105] Building CXX object src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/LLVMToBackend.cpp.obj
FAILED: src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/LLVMToBackend.cpp.obj
C:\llvm\bin\clang++.exe -DHIPSYCL_COMPILER_COMPONENT -DHIPSYCL_DEBUG_LEVEL=2 -DHIPSYCL_WITH_SSCP_COMPILER -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dllvm_to_backend_EXPORTS -IC:/Users/Daniil/source/OpenSYCL/src/compiler/llvm-to-backend/../../../include -IC:/llvm/include -IC:/Users/Daniil/source/OpenSYCL/src/compiler/llvm-to-backend -IC:/Users/Daniil/source/OpenSYCL/Build/include -O2 -DNDEBUG -g -Xclang -gcodeview -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -std=c++17 -MD -MT src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/LLVMToBackend.cpp.obj -MF src\compiler\llvm-to-backend\CMakeFiles\llvm-to-backend.dir\LLVMToBackend.cpp.obj.d -o src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/LLVMToBackend.cpp.obj -c C:/Users/Daniil/source/OpenSYCL/src/compiler/llvm-to-backend/LLVMToBackend.cpp
In file included from C:/Users/Daniil/source/OpenSYCL/src/compiler/llvm-to-backend/LLVMToBackend.cpp:28:
C:/Users/Daniil/source/OpenSYCL/src/compiler/llvm-to-backend/../../../include\hipSYCL/common/debug.hpp:73:29: error: no member named 'stoi' in namespace 'std'
        _debug_level = std::stoi(std::string{env});
                       ~~~~~^
1 error generated.
```

I assume this error is because standard c++ library in Windows is a bit different to that is used in Linux? How I can fix the problem then? Build libc++?

**Comment by illuhad** [comment]
Can you try adding `#include <string>` to the beginning of `include/hipSYCL/common/debug.hpp`?
If that doesn't help, I'm not sure what else to do - `std::stoi` has been part of the C++ standard since C++11. Maybe @fodinabor or @nilsfriess have more ideas.

EDIT: It seems that error is triggered when building our SSCP compiler, which is not yet fully supported on Windows anyway, so `cmake -DWITH_SSCP_COMPILER=OFF` might be a workaround too.

**Comment by blinkfrog** [comment]
> Can you try adding `#include <string>` to the beginning of `include/hipSYCL/common/debug.hpp`? If that doesn't help, I'm not sure what else to do - `std::stoi` has been part of the C++ standard since C++11. Maybe @fodinabor or @nilsfriess have more ideas.
> EDIT: It seems that error is triggered when building our SSCP compiler, which is not yet fully supported on Windows anyway, so `cmake -DWITH_SSCP_COMPILER=OFF` might be a workaround too.

Thank you very much, adding `#include <string>` helped. I haven't tried the solution with -DWITH_SSCP_COMPILER=OFF, will try it shortly too.

Compiling continued, but there were another problems, some I resolved, such as absence of `patch` and `true` programs, which I found in `git` and solved by adding "Git/usr/bin" to PATH variable, and some are notm such as inability to link `llvm.lib`, which is  actually absent in my built LLVM 16, as well as in prebuilt LLVM 11 from wiki. I'll try to use `cmake -DWITH_SSCP_COMPILER=OFF` and, if I get this problem again, I'll create another discussion.

**Comment by blinkfrog** [comment]
> Can you try adding `#include <string>` to the beginning of `include/hipSYCL/common/debug.hpp`? If that doesn't help, I'm not sure what else to do - `std::stoi` has been part of the C++ standard since C++11. Maybe @fodinabor or @nilsfriess have more ideas.
> EDIT: It seems that error is triggered when building our SSCP compiler, which is not yet fully supported on Windows anyway, so `cmake -DWITH_SSCP_COMPILER=OFF` might be a workaround too.

Thank you very much, adding `#include <string>` helped. I haven't tried the solution with -DWITH_SSCP_COMPILER=OFF, will try it shortly too.

Compiling continued, but there were another problems, some I resolved, such as absence of `patch` and `true` programs, which I found in `git` and solved by adding "Git/usr/bin" to PATH variable (may be worth adding to wiki article), and some are not, such as inability to link `llvm.lib`, which is  actually absent in my built LLVM 16, as well as in prebuilt LLVM 11 from wiki. I'll try to use `cmake -DWITH_SSCP_COMPILER=OFF` and, if I get this problem again, I'll open another isue.
