### ISSUE TITLE
`No llvm.lib` error during building OpenSYCL on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1130]
I am trying to compile OpenSYCL on Windows. I compiled LLVM 16 and boost.

This is cmake command line I use:
`cmake .. -G Ninja -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe -DBOOST_ROOT=C:/Libraries/boost_1_83 -DLLVM_DIR=c:/llvm/lib/cmake/llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=c:/OpenSYCL -DWITH_SSCP_COMPILER=OFF`

I get this error while building:

```
[50/105] Linking CXX shared library src\compiler\llvm-to-backend\llvm-to-backend.dll
FAILED: src/compiler/llvm-to-backend/llvm-to-backend.dll src/compiler/llvm-to-backend/llvm-to-backend.lib
cmd.exe /C "cd . && C:\llvm\bin\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O2 -DNDEBUG -g -Xclang -gcodeview -D_DLL -D_MT -Xclang --dependent-lib=msvcrt   -shared -o src\compiler\llvm-to-backend\llvm-to-backend.dll  -Xlinker /MANIFEST:EMBED -Xlinker /implib:src\compiler\llvm-to-backend\llvm-to-backend.lib -Xlinker /pdb:src\compiler\llvm-to-backend\llvm-to-backend.pdb -Xlinker /version:0.0 src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/LLVMToBackend.cpp.obj src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/AddressSpaceInferencePass.cpp.obj src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/__/sscp/KernelOutliningPass.cpp.obj  -lLLVM.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
lld-link: error: could not open 'LLVM.lib': no such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Indeed, I cannot find the "llvm.lib" file in LLVM I built. Instead, I can only see the "llvm-c.lib" file. However, I verified that neither the official Windows binaries of LLVM 16 nor the prebuilt LLVM 11 from the wiki include this file.

How can I fix this problem?

**Comment by nilsfriess** [comment]
In CI we are using a prebuilt LLVM 16 that you can download here: https://www.dropbox.com/s/o8eth32n9ajzw0l/llvm-15-windows-prebuilt.7z

Can you try if it works using this? I haven’t checked if it has the missing llvm.lib but it works in CI (or rather it worked until a few weeks ago), so maybe something went wrong when you built LLVM.

**Comment by blinkfrog** [comment]
> In CI we are using a prebuilt LLVM 16 that you can download here: https://www.dropbox.com/s/o8eth32n9ajzw0l/llvm-15-windows-prebuilt.7z
> 
> Can you try if it works using this? I haven’t checked if it has the missing llvm.lib but it works in CI (or rather it worked until a few weeks ago), so maybe something went wrong when you built LLVM.

Thank you very much. I've tried this LLVM, but without success, unfortunately. This is Clang 15, BTW, not 16, and probably this is what leads to errors.
 
Cmake outputs this error:

```
- Using clang include directory: C:/llvm/lib/clang/15.0.0/include/..
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - not found
-- Looking for C++ include experimental/filesystem
-- Looking for C++ include experimental/filesystem - not found
CMake Error at cmake/FindFilesystem.cmake:286 (message):
  Cannot run simple program using std::filesystem
Call Stack (most recent call first):
  src/common/CMakeLists.txt:17 (find_package)
```

Also this probably is related to the error message I get when trying to rebuild boost using this Clang.

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals_core.h:847:1: error: static assertion failed: Error in C++ Standard Library usage.
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 16.0.0 or newer.");
```

Also, all these are the errors that I got earlier when tried to build OpenSYCL using prebuilt versions of Clang and boost from that Windows-wiki page.

**Comment by fodinabor** [comment]
Hmm.. it shouldn't build `llvm-to-backend` when specifying `-DWITH_SSCP_COMPILER=OFF` (which is the default on windows, afaict).
Can you try wrapping the following in a `if(WITH_SSCP_COMPILER)`: https://github.com/OpenSYCL/OpenSYCL/blob/842aae19b503503a7c97f5056a075b16cc570d83/src/compiler/CMakeLists.txt#L111C34-L111C34 ?

**Comment by blinkfrog** [comment]
> Can you try wrapping the following in a `if(WITH_SSCP_COMPILER)`:

Thank you for your suggestion. Excuse me if I misunderstood you. Do you mean wrapping this block:

```
set(SSCP_COMPILER 
    sscp/KernelOutliningPass.cpp
    sscp/IRConstantReplacer.cpp
    sscp/TargetSeparationPass.cpp
    sscp/HostKernelNameExtractionPass.cpp
    sscp/AggregateArgumentExpansionPass.cpp
    sscp/StdBuiltinRemapperPass.cpp)
  add_definitions(-DHIPSYCL_WITH_SSCP_COMPILER)
```

 into that `if` condition?

If so, then it already is wrapped into it, at least in the source I have.

**Comment by fodinabor** [comment]
I meant the very last line: 
`add_subdirectory(llvm-to-backend)`
So 
```
if(WITH_SSCP_COMPILER)
add_subdirectory(llvm-to-backend)
endif()
```

**Comment by blinkfrog** [comment]
> I meant the very last line:

Thank you. I've just tried this - almost no effect, same error, although strangely at another place - 67/105.
Just in case I've tried to output debug messages to see if there is actual effect of `WITH_SSCP_COMPILER` variable - and it is. That `if` condition works properly.

**Comment by fodinabor** [comment]
maybe you need to reconfigure (clean the build directory and run cmake again), because if it does have an effect, it should not try to build `llvm-to-backend` anymore (or I'm missing another place...).
Or is the issue now with another linking step (i.e. not the number but the name of the file created is interesting).

**Comment by blinkfrog** [comment]
Thank you. I clean build directory every time I relaunch build.

This is the error message:

```
[67/105] Linking CXX shared library src\compiler\llvm-to-backend\llvm-to-backend.dll
FAILED: src/compiler/llvm-to-backend/llvm-to-backend.dll src/compiler/llvm-to-backend/llvm-to-backend.lib 
cmd.exe /C "cd . && C:\llvm\bin\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O2 -DNDEBUG -g -Xclang -gcodeview -D_DLL -D_MT -Xclang --dependent-lib=msvcrt   -shared -o src\compiler\llvm-to-backend\llvm-to-backend.dll  -Xlinker /MANIFEST:EMBED -Xlinker /implib:src\compiler\llvm-to-backend\llvm-to-backend.lib -Xlinker /pdb:src\compiler\llvm-to-backend\llvm-to-backend.pdb -Xlinker /version:0.0 src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/LLVMToBackend.cpp.obj src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/AddressSpaceInferencePass.cpp.obj src/compiler/llvm-to-backend/CMakeFiles/llvm-to-backend.dir/__/sscp/KernelOutliningPass.cpp.obj  -lLLVM.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
lld-link: error: could not open 'LLVM.lib': no such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

It is identical to that I posted earlier, I used diff checker to be sure.

**Comment by illuhad** [comment]
Can you try adding `-DWITH_OPENCL_BACKEND=OFF`? Maybe it finds OpenCL somewhere on your system, and tries to enable it, which then would pull in the SSCP compiler as dependency.

**Comment by blinkfrog** [comment]
> -DWITH_OPENCL_BACKEND=OFF

Thank you, this worked, effectively greatly decreasing the amount of building steps to 49.
However, I get another error in the last step. I've created another issue, so it will be easier to find for other users, experiencing the same problems:

https://github.com/OpenSYCL/OpenSYCL/issues/1131#issue-1892002383
