### ISSUE TITLE
No executable syclcc after building OpenSycl on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1134]
I still am trying to build OpenSYCL on Windows 11. :)

Source is the most recent from github. (I also tried to build 0.9.4 release, and results are different: https://github.com/OpenSYCL/OpenSYCL/issues/1135)

I use these commands to build and install OpenSYCL:
`cmake .. -G Ninja -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe -DBOOST_ROOT=C:/Libraries/boost_1_83 -DLLVM_DIR=c:/llvm/lib/cmake/llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=c:/OpenSYCL -DWITH_SSCP_COMPILER=OFF -DWITH_OPENCL_BACKEND=OFF`
`ninja`
`ninja install`

However, after installing, there is no syclcc.exe in the /bin folder. There are such files as `opensycl-info.exe`, `opensycl-hcf-tool.exe`, and they work.
Also there are two files in this folder:
`syclcc` and `syclcc-clang` without `.exe` extension, and they are actually python files.

**Comment by illuhad** [comment]
This is expected, `syclcc` is a python script. On Linux you can just run it as `syclcc` (which will then invoke python), no idea about Windows.

**Comment by fodinabor** [comment]
On windows you need to prepend the invocation with `python3` (which requires that python is in your `%PATH%`)

**Comment by blinkfrog** [comment]
> This is expected, `syclcc` is a python script. On Linux you can just run it as `syclcc` (which will then invoke python), no idea about Windows.
> On windows you need to prepend the invocation with `python3` (which requires that python is in your `%PATH%`)

Thank you very much, adding `python` works!
