### ISSUE TITLE
`No available targets are compatible with triple "nvptx64-nvidia-cuda"` error on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1139]
I am trying to compile a simple SYCL-app with OpenSYCL.

This is the command line I use: 
`python c:/opensycl/bin/syclcc simple-sycl-app.cpp -o simple-sycl-app.exe --hipsycl-targets="cuda:sm_86"`

And I get this error:
`error: unable to create target: 'No available targets are compatible with triple "nvptx64-nvidia-cuda"'
1 error generated when compiling for sm_86.`

May be I compiled Clang or OpenSYCL incorrectly?

After googling I found a somewhat similar problem, and it was solved by compiling llvm with `-DLLVM_TARGETS_TO_BUILD="X86;NVPTX"`. Or this isn't needed? (In wiki article it isn't mentioned)

**Comment by fodinabor** [comment]
When wanting to target Nvidia GPUs, one indeed has to build LLVM with the NVPTX back end.
Be warned though, I haven't been able to make Open SYCL's GPU path succeed at runtime with newer Clang versions (I am certain it worked with 11, maaaybe 13).. I am happy to be proven wrong :)

**Comment by nilsfriess** [comment]
I'm not really a Windows expert but recently I stumble across this document by NVIDIA

**Comment by nilsfriess** [comment]
I'm not really a Windows expert but recently I stumbled across [this guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) by NVIDIA. Would this generally be an option for Windows users trying to target NVIDIA hardware? Maybe this way we could avoid some difficulties, in particular it would not be necessary to build your own LLVM. But again, I'm not a Windows user so I'm not sure if there is some obvious downside to this.

**Comment by fodinabor** [comment]
Didnt test, but WSL2 is supposed to be GPU "friendly" by now, so yeah, might be interesting to test hipSYCL there!

**Comment by blinkfrog** [comment]
Thanks! Rebuilding Clang (16, BTW) with NVPTX backend worked.

**Comment by blinkfrog** [comment]
Closing the issue as solved.
