### ISSUE TITLE
dag_direct_scheduler message on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1140]
I finally managed to compile my test app on Windows with using cuda backend.

While compiling there were errors that "M_PI" identifier not found in builtins.hpp, and adding `#define _USE_MATH_DEFINES` before including cmath didn't help, so I simply defined M_PI manually.

However, the app still doesn't work. It doesn't output anything expected. Only this warning:

```[hipSYCL Warning] dag_direct_scheduler: Detected a requirement that is neither of discard access mode (SYCL 1.2.1) nor no_init property (SYCL 2020) that accesses uninitialized data. Consider changing to discard/no_init. Optimizing potential data transfers away.```

**Comment by blinkfrog** [comment]
No, I've tried official OpenSYCL example, and it works. It seems the code that I used (which I used to test DPC++) isn't compatible with  OpenSYCL.

**Comment by illuhad** [comment]
Out of curiosity, what is the code you have used to test?

**Comment by blinkfrog** [comment]
This is the code I tried (one of DPC++ examples):
```
#include <sycl/sycl.hpp>

int main() {
  // Creating buffer of 4 elements to be used inside the kernel code
  sycl::buffer<size_t, 1> Buffer(4);

  // Creating SYCL queue
  sycl::queue Queue;

  // Size of index space for kernel
  sycl::range<1> NumOfWorkItems{Buffer.size()};

  // Submitting command group(work) to queue
  Queue.submit([&](sycl::handler &cgh) {
    // Getting write only access to the buffer on a device.
    sycl::accessor Accessor{Buffer, cgh, sycl::write_only};
    // Executing kernel
    cgh.parallel_for<class FillBuffer>(
        NumOfWorkItems, [=](sycl::id<1> WIid) {
          // Fill buffer with indexes.
          Accessor[WIid] = WIid.get(0);
        });
  });

  // Getting read only access to the buffer on the host.
  // Implicit barrier waiting for queue to complete the work.
  sycl::host_accessor HostAccessor{Buffer, sycl::read_only};

  // Check the results
  bool MismatchFound = false;
  for (size_t I = 0; I < Buffer.size(); ++I) {
    if (HostAccessor[I] != I) {
      std::cout << "The result is incorrect for element: " << I
                << " , expected: " << I << " , got: " << HostAccessor[I]
                << std::endl;
      MismatchFound = true;
    }
  }

  if (!MismatchFound) {
    std::cout << "The results are correct!" << std::endl;
  }

  return MismatchFound;
}
```

**Comment by blinkfrog** [comment]
As for the crash, I think it is the try-catch: in my other test I noticed that the app crashes when it comes to `catch` block (without performing the code in this block). After removing, app works without crash.
Edit: no, in this particular code there is no try/catch. Still it crashes.
(BTW, this another test (a simple non-linear blur) performs 10% faster than CUDA app! Amazing!)
