### ISSUE TITLE
Static-Linked Library for HPC use without sudo install

### ISSUE THREAD

**Issue by Kiguli** [AdaptiveCpp/AdaptiveCpp#1148]
**Describe the motivation for the feature request**

Hi, I am a PhD student trying to use SYCL to parallelise some code I am running, the problem I am solving has an exponential number of computations so I am using the universities HPC. 

**Describe the solution you'd like**

Previously, a tool I used setup some of the parts as a static-linked library in order to avoid having to use sudo to install parts of the tool, simply it could be compiled with a makefile and then used. Is this possible with adaptivecpp?

**If applicable, describe alternatives you've considered**

I could install and run things as normal on a PC machine, but this has challenges due to the exponential scaling of the problem.

**Comment by fodinabor** [comment]
You can install AdaptiveCpp locally by adding `-DCMAKE_INSTALL_PREFIX=<local/path>`, no sudo required. Likely your HPC facility has a shared (writable) filesystem, where you can store this.

Static linking is not possible.
