### ISSUE TITLE
Compiling any SYCL program fails Due to Missing Boost Fiber Library (Windows)

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1175]
Hello,

I've succesfully built LLVM, boost and AdaptiveCPP on Windows, but still encountering an issue with the linking stage, specifically with the Boost Fiber library.

Environment Details:
OS: Windows 11
CMake Version: 3.27.4
Compiler: Clang 16.0.6 (https://github.com/llvm/llvm-project 7cbf1a2591520c2491aa35339f227775f4d3adf6)
Boost Version: 1.83

Boost 1.83 is built with `b2 toolset=clang-win --build-type=complete stage install --prefix=c:/libraries/boost_1_83`.

AdaptiveCPP is built with
`cmake .. -G Ninja -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe -DBOOST_ROOT=C:/Libraries/boost_1_83 -DLLVM_DIR=c:/llvm/lib/cmake/llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=c:/AdaptiveCPP -DWITH_SSCP_COMPILER=OFF -DWITH_OPENCL_BACKEND=OFF`

Command to compile a program:
`python c:/adaptivecpp/bin/acpp Blur1.cpp -o Blur1.exe  -O3 --acpp-targets="cuda:sm_86"`

Expected Behavior:
The compiling should succeed, linking against the Boost Fiber library without issue.

Actual Behavior:
The linker fails with an error stating that libboost_fiber-clangw16-s-x64-1_83.lib is missing. However, the closest existing file is libboost_fiber-clangw16-mt-s-x64-1_83.lib.

Additional Information:
The CMakeCache.txt indicates that find_package(Boost COMPONENTS context fiber) is locating the Boost libraries correctly. The relevant variables are set as follows:

```
Boost_FIBER_LIBRARY_DEBUG:STRING=C:/Libraries/boost_1_83/lib/libboost_fiber-clangw16-mt-gd-x64-1_83.lib
Boost_FIBER_LIBRARY_RELEASE:STRING=C:/Libraries/boost_1_83/lib/libboost_fiber-clangw16-mt-x64-1_83.lib
Boost_INCLUDE_DIR:PATH=C:/Libraries/boost_1_83/include/boost-1_83
```

Workaround: copying and renaming `libboost_fiber-clangw16-mt-s-x64-1_83.lib` (and also corresponding files for `context`, `atomic` and `filesystem`) to `libboost_fiber-clangw16-s-x64-1_83.lib` works for simple programs using basic parallel kernels, but if a program uses nd-range kernel, then a lot of linking errors with boost libraries occur.

Would appreciate any guidance or fixes for this issue. Thank you.

**Comment by fodinabor** [comment]
It does seem your boost is only built with static libraries for some reason.. The default should be shared..
You might wanna add `link=shared` to the `b2` invocation...?

Maybe to verify first, Do you have corresponding DLLs?

**Comment by blinkfrog** [comment]
> It does seem your boost is only built with static libraries for some reason.. The default should be shared.. You might wanna add `link=shared` to the `b2` invocation...?
> Maybe to verify first, Do you have corresponding DLLs?

Thank you for suggesting. There are .dlls, but only for libraries having Windows naming convention, for example, `boost_atomic-clangw16-mt-gd-x64-1_83.dll`. For Linux naming convention there are only lib files, for example `libboost_atomic-clangw16-mt-x64-1_83.lib`.

I've just tried to rebuild boost with `link=shared`, which successfully generated dlls with linux naming convention, but in this case AdaptiveCPP doesn't compile at all: 
```
CMake Error at CMakeLists.txt:38 (message):
  Please provide the path to the root directory of the boost installation
  using the -DBOOST_ROOT option
```

Or should I compile AdaptiveCPP using lib-files of boost, and then compile SYCL programs with dll variants of boost?

**Comment by blinkfrog** [comment]
Update. I discovered that the problem with missing `libboost_fiber-clangw16-s-x64-1_83.lib` (which can be workarounded by renaming `libboost_fiber-clangw16-mt-s-x64-1_83.lib` to that filename) occurs only when compiling a cpp file using acpp python script like this: `python acpp  program.cpp -o program.exe --acpp-targets="cuda:sm_86"`. There is no this error when compiling SYCL-programs using cmake projects.

When compiling with -E flag, there are the next entries in the output:
```
# 478 "C:/Libraries/boost_1_83/include/boost-1_83\\boost/config/auto_link.hpp" 3
#pragma comment(lib, "lib" "boost_fiber" "-" "clangw" "16" "-s" "-x64" "-" "1_83" ".lib")
```

```
# 478 "C:/Libraries/boost_1_83/include/boost-1_83\\boost/config/auto_link.hpp" 3
#pragma comment(lib, "lib" "boost_context" "-" "clangw" "16" "-s" "-x64" "-" "1_83" ".lib")
```

So at least it is a bit clear where these filenames are coming from.

**Comment by fodinabor** [comment]
Ah that's interesting. So it seems there's some macro difference..
Can you build the cmake project and the acpp only comand once with the environment var `HIPSYCL_DRYRUN=1` set and post/compare the command lines?

**Comment by blinkfrog** [comment]
Sure! This is when compiling using `acpp` command:

```
c:\Temp\sycltest>python c:/adaptivecpp/bin/acpp Blur.cpp -o blur.exe -O3 --acpp-targets="cuda:sm_86"
C:/llvm/bin\clang.exe -isystem C:\AdaptiveCpp\bin\..\include\AdaptiveCpp -D__OPENSYCL__ -D__HIPSYCL__ -D__ADAPTIVECPP__ -D__ACPP__ -std=c++17 -x cuda --cuda-path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2 -D__HIPSYCL_ENABLE_CUDA_TARGET__ -fplugin=C:\AdaptiveCpp\bin\..\bin\acpp-clang.dll -D__HIPSYCL_CLANG__ -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem C:\AdaptiveCpp\bin\../include/AdaptiveCpp/hipSYCL/std/hiplike --cuda-gpu-arch=sm_86 -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -IC:/Libraries/boost_1_83/include/boost-1_83 -D_ENABLE_EXTENDED_ALIGNED_STORAGE Blur.cpp -o blur.exe -O3 -LC:\AdaptiveCpp\bin\..\lib/ -lacpp-rt -LC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2\lib\x64 -lcudart -LC:/Libraries/boost_1_83/lib -llibboost_context-clangw16-mt-x64-1_83.lib -llibboost_fiber-clangw16-mt-x64-1_83.lib -llibomp
```

And this is when building cmake project:
```
C:\Temp\sycltest\SyclCmakeProject\build>ninja
[1/2] Building CXX object CMakeFiles/Blur.dir/blur.cpp.obj
C:/llvm/bin\clang.exe -isystem C:\AdaptiveCpp\bin\..\include\AdaptiveCpp -D__OPENSYCL__ -D__HIPSYCL__ -D__ADAPTIVECPP__ -D__ACPP__ -std=c++17 -x cuda --cuda-path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2 -D__HIPSYCL_ENABLE_CUDA_TARGET__ -fplugin=C:\AdaptiveCpp\bin\..\bin\acpp-clang.dll -D__HIPSYCL_CLANG__ -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem C:\AdaptiveCpp\bin\../include/AdaptiveCpp/hipSYCL/std/hiplike --cuda-gpu-arch=sm_86 -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -IC:/Libraries/boost_1_83/include/boost-1_83 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -IC:/Temp/sycltest/SyclCmakeProject/build -IC:/Temp/sycltest/SyclCmakeProject -isystem C:/AdaptiveCpp/include -isystem C:/AdaptiveCpp/include/AdaptiveCpp -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -MD -MT CMakeFiles/Blur.dir/blur.cpp.obj -MF CMakeFiles\Blur.dir\blur.cpp.obj.d -o CMakeFiles/Blur.dir/blur.cpp.obj -c C:/Temp/sycltest/SyclCmakeProject/blur.cpp
[2/2] Linking CXX executable Blur.exe
C:/llvm/bin\clang.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -Xlinker /subsystem:console CMakeFiles/Blur.dir/blur.cpp.obj -o Blur.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:Blur.lib -Xlinker /pdb:Blur.pdb -Xlinker /version:0.0 C:/AdaptiveCpp/lib/acpp-rt.lib -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames -LC:\AdaptiveCpp\bin\..\lib/ -lacpp-rt -LC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2\lib\x64 -lcudart -LC:/Libraries/boost_1_83/lib -llibboost_context-clangw16-mt-x64-1_83.lib -llibboost_fiber-clangw16-mt-x64-1_83.lib -llibomp
```

**Comment by fodinabor** [comment]
Managing all compilation flags manually is kinda hard :)

`-DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt` (especially the `_DLL` part) is probably the relevant bit here.

**Comment by blinkfrog** [comment]
So, when compiling from the command line using `acpp` script, there is no `-D_MT` flag. I just have tried to add it to the `acpp` command, and it compiled without asking for these boost libraries!
(The only thing is that when I compile this file with acpp and newer AdaptiveCpp with that library finding hotfix, resulting .exe still silently crashes, while when I compile with older (or with newer within cmake project) it runs without problems)

**Comment by blinkfrog** [comment]
I can close the issue as solved, as adding `-D_MT` to the compile command solves it. But may be is it possible to add setting of `_MT` macro to `acpp` script in future versions of AdaptiveCpp, so it would be not needed to define it manually?

**Comment by blinkfrog** [comment]
I am closing the issue as adding `-D_MT` to compile line solves the compilation issue when compiling from command line. Still, it would be great if `acpp` script could do this automatically.

**Comment by fodinabor** [comment]
My problem with that is, that we're not hardcoding the boost lib to use.. so, in theory, one can e.g. set `-DBoost_USE_MULTITHREADED=Off` and CMake will (try to) use the non `mt` boost libraries... I think we'd be happy to consider a patch that deals with this in a "stable" way... but it feels like there might be a number of intricacies here of when building the AdaptiveCpp library with one config breaks when using it with another config... so I guess, yes, it'd be good if `acpp` "builds the downstream application, as AdaptiveCpp was built", but I won't be able to investigate what all the config options are that we'd need to consider, so happy to receive a PR here :)

(I could imagine that your exe crashing when building with acpp only, comes from a mismatch in the used standard library config -> the CMake-built AdaptiveCpp using the multithreaded one, while your `acpp`-built version does not.)

**Comment by blinkfrog** [comment]
I understand now and agreed. There are indeed so many intricacies everywhere - even in boost building, when on your Windows machine it works with `--with-fiber --with-context` only, while on my machine cmake results in "Could NOT find Boost: missing: fiber" error when configuring AdaptiveCpp unless I add `--with-filesystem --with-atomic` to b2 command, so even if some non-robust fix would work on my machine, there is still no warranty that it would work on another.

Actually, this isn't a big deal, as anyway any serious AdaptiveCpp project implies use of cmake, I don't know any other way to use it with Visual Studio, and all works just fine with cmake.

(Just in case if this information can be useful: I've successfully compiled LLVM 17.0.4 and AdaptiveCpp for this version - and it works on Windows too. There was no any difference in building process comparing to LLVM 16)
