### ISSUE TITLE
Link with AdaptiveCpp

### ISSUE THREAD

**Issue by bsobol** [AdaptiveCpp/AdaptiveCpp#1179]
Regarding #1069. so what's now a proper way to link with acpp and propagate include dirs to cmake targets which hawe a library using acpp as a dependency?

**Comment by illuhad** [comment]
Do the suggestions in this comment address your issue? https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1069#issuecomment-1592243068

**Comment by bsobol** [comment]
> Do the suggestions in this comment address your issue? [#1069 (comment)](https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1069#issuecomment-1592243068)

Yes, except that `target_link_libraries(... ... AdaptiveCpp::acpp-rt)` doesn't seem to propagate include dirs. At least it stopped doing that when I updated acpp yesterday. Previously I used dev branch from mid July, still with hipSYCL naming, and it worked fine.

**Comment by illuhad** [comment]
Are you using `find_package(hipSYCL)` or `find_package(AdaptiveCpp)`? In the latter case, can you check whether it works with `find_package(hipSYCL)`? (Note that then cmake arguments must be provided as `-DHIPSYCL_*`, as the `-DACPP_*` naming is not supported then).

**Comment by bsobol** [comment]
I've found the cause: in `adaptivecpp-targets.cmake` there is
```
set_target_properties(AdaptiveCpp::acpp-rt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```
instead of `INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/AdaptiveCpp"`

Same for `acpp-common` and in all three namespaces.

Unfortunately, I don't know how to fix this in the `install(EXPORT ...` in the root `CMakeLists.txt`.

**Comment by bsobol** [comment]
If I understand correctly, it was introduced in #1170, and does not affect compilation of the main library with `add_sycl_to_target` because of the change in the python script.

That also explains why CLion stopped recognising sycl headers also in the main library (initially I thought it was a CLions' fault as I use a beta channel).
