### ISSUE TITLE
adaptivecpp fails to compile using llvm-17

### ISSUE THREAD

**Issue by Kevin-Delnoije** [AdaptiveCpp/AdaptiveCpp#1190]
**Bug summary**
adaptivecpp fails to compile using llvm-17 

```bash
[ 36%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/SPIRVLowerMemmove.cpp.o
/home/kevin/Code/thirdparty/AdaptiveCpp/build/_deps/llvmspirvtranslator-src/lib/SPIRV/SPIRVLowerMemmove.cpp: In member function ‘bool SPIRV::SPIRVLowerMemmoveBase::expandMemMoveIntrinsicUses(llvm::Function&)’:
/home/kevin/Code/thirdparty/AdaptiveCpp/build/_deps/llvmspirvtranslator-src/lib/SPIRV/SPIRVLowerMemmove.cpp:105:26: error: too many arguments to function ‘void llvm::expandMemMoveAsLoop(llvm::MemMoveInst*)’
  105 |       expandMemMoveAsLoop(Inst,
      |       ~~~~~~~~~~~~~~~~~~~^~~~~~
  106 |                           TargetTransformInfo(F.getParent()->getDataLayout()));
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/kevin/Code/thirdparty/AdaptiveCpp/build/_deps/llvmspirvtranslator-src/lib/SPIRV/SPIRVLowerMemmove.cpp:46:
/usr/lib/llvm-17/include/llvm/Transforms/Utils/LowerMemIntrinsics.h:54:6: note: declared here
   54 | void expandMemMoveAsLoop(MemMoveInst *MemMove);
      |      ^~~~~~~~~~~~~~~~~~~
gmake[5]: *** [lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/build.make:272: lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/SPIRVLowerMemmove.cpp.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:246: lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/all] Error 2
gmake[3]: *** [Makefile:136: all] Error 2
make[2]: *** [src/compiler/llvm-to-backend/CMakeFiles/llvm-spirv-translator.dir/build.make:70: src/compiler/llvm-to-backend/CMakeFiles/llvm-spirv-translator] Error 2
make[1]: *** [CMakeFiles/Makefile2:644: src/compiler/llvm-to-backend/CMakeFiles/llvm-spirv-translator.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

llvm-17 seems to have changed the function signature as can be seen in the git history [here](https://github.com/llvm/llvm-project/blame/cc3d2533cc2e4ea06981b86ede5087fbf801e789/llvm/include/llvm/Transforms/Utils/LowerMemIntrinsics.h#L55)

**To Reproduce**
Installed llvm/clang with ubuntu apt packages  (apt.llvm.org)
system is ubuntu 22.04 lts with gcc 11.4 compiler and intel 10th gen cpu.

```bash
 cmake -DWITH_LEVEL_ZERO_BACKEND=ON -S . -B build
 make install
```

**Comment by illuhad** [comment]
The offending line is in the Khronos llvm-spirv translator. LLVM-SPIRV translator gets built as a dependency.

Can you verify that the git repository in `/home/kevin/Code/thirdparty/AdaptiveCpp/build/_deps/llvmspirvtranslator-src` was checked out on branch `llvm_release_170`? If so, it is a bug in the LLVM-SPIRV translator and not in AdaptiveCpp.

**Comment by Kevin-Delnoije** [comment]
yes, that seems to be the problem

```bash
git status
HEAD detached at origin/llvm_release_160
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   lib/SPIRV/SPIRVInternal.h

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	lib/SPIRV/SPIRVInternal.h.rej

no changes added to commit (use "git add" and/or "git commit -a")
```

although i compiled with llvm16 afterwards and now reconfigured with llvm17 again, so maybe this was not the state of the error.
ill try changing branch to 17

**Comment by illuhad** [comment]
It should automatically switch to the correct branch during cmake configuration, but perhaps something got stuck.

**Comment by Kevin-Delnoije** [comment]
on clean build llvmspirvtranslator-src was on branch 17  and got the same error, when compiling with llvm16 clean build this error doesn't happen.

This is my llvm-17 version of ubuntu just in case it is useful.
```
llvm-17 is already the newest version (1:17~++20230609042347+3004e9f86b4a-1~exp1~20230609042505.987).
```

I will use llvm16 for now

**Comment by illuhad** [comment]
> on clean build llvmspirvtranslator-src was on branch 17 and got the same error, when compiling with llvm16 clean build this error doesn't happen.

That sounds like there's a bug in upstream llvm-spirv translator around LLVM 17 support.

**Comment by fodinabor** [comment]
I mean the CI is happy..?
https://github.com/AdaptiveCpp/AdaptiveCpp/actions/runs/6567331949/job/17839828112

**Comment by illuhad** [comment]
Yes, I noticed that too...@Kevin-Delnoije, can you perhaps compare the commands you use to build AdaptiveCpp with what CI does? See https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/.github/workflows/linux.yml

**Comment by Kevin-Delnoije** [comment]
it is fixed now, the problem was that llvm17 install was a nightly version before the official release (so effectively llvm16) and it didn't get updated using sudo apt update, therefore had to install it fresh from apt.llvm .
Thanks for the CI reference it was easier to follow than the install documentation.

```bash
sudo apt install libboost-all-dev
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 
sudo apt install -y libclang-17-dev clang-tools-17 libomp-17-dev llvm-17-dev lld-17
git clone https://github.com/AdaptiveCpp/AdaptiveCpp.git
cd AdaptiveCpp/
cmake -S . -B build
sudo make -j$(nproc) install
```
