### ISSUE TITLE
Can't compile for AMD gfx90c

### ISSUE THREAD

**Issue by ManuelCostanzo** [AdaptiveCpp/AdaptiveCpp#1236]
Hey!

I have a Ryzen 3 5300U with an AMD Radeon Graphics gfx90c. I'm not able to execute my programs. I tried with

```
acpp --acpp-targets=generic
acpp --acpp-targets=hip:gfx90c
```
but nothing works.

Also I tried overriding with HSA_OVERRIDE_GFX_VERSION=9.0.0, but neither.

This is the acpp-info output related with the GPU:

```
** Devices for backend HIP **
Device 0:
 General device information:
  Name: 
  Backend: HIP
  Vendor: AMD
  Arch: gfx90c:xnack-
  Driver version: 50731921
  Is CPU: 0
  Is GPU: 1
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 0
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 0
  sub_group_independent_forward_progress: 1
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 0
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 0
  usm_system_allocations: 0
  execution_timestamps: 1
  sscp_kernels: 1
 Device properties:
  max_compute_units: 6
  max_global_size0: 2199023254528
  max_global_size1: 67108864
  max_global_size2: 67108864
  max_group_size: 1024
  max_num_sub_groups: 16
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
```

I'm using ROCM 5.7 and I have installed the following packages: rocm-dev hip-base hip-dev hip-runtime-amd

I'm using the last ACPP version and I enabled rocm:

```
-DWITH_ROCM_BACKEND
-DROCM_PATH=/opt/rocm
```

The compilation works fine. But then, for the generic mode I get this error:

```
[AdaptiveCpp Error] from /tmp/AdaptiveCPP-installer/include/hipSYCL/glue/llvm-sscp/jit.hpp:251 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed

[AdaptiveCpp Error] from /tmp/AdaptiveCPP-installer/include/hipSYCL/runtime/kernel_cache.hpp:427 @ get_or_construct_code_object_impl(): kernel_cache: code object creation has failed
[AdaptiveCpp Error] from /tmp/AdaptiveCPP-installer/src/runtime/hip/hip_queue.cpp:688 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
Vector add failed on device.
============== hipSYCL error report ============== 
hipSYCL has caught the following undhandled asynchronous errors: 

   
from /tmp/AdaptiveCPP-installer/include/hipSYCL/glue/llvm-sscp/jit.hpp:251 @ compile(): jit::compile: Encountered errors:
0: LLVMToAmdgpu: hiprtcLinkComplete() failed

   
from /tmp/AdaptiveCPP-installer/include/hipSYCL/runtime/kernel_cache.hpp:427 @ get_or_construct_code_object_impl(): kernel_cache: code object creation has failed
from /tmp/AdaptiveCPP-installer/src/runtime/hip/hip_queue.cpp:688 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
The application will now be terminated.
terminate called without an active exception
Aborted (core dumped)
```
has this happened to any of you? Thanks

**Comment by illuhad** [comment]
I have `gfx90c` my Ryzen 4750U as well, so I know that this GPU should work. However I have not tried with ROCm 5.7, but 5.4.

> Also I tried overriding with HSA_OVERRIDE_GFX_VERSION=9.0.0,

I've never had to  set this environment variable to get things working.


What is the error you see with `--acpp-targets=hip:gfx90c`?
For `--acpp-targets=generic`, the LLVM version that AdaptiveCpp was built against needs to be <= ROCm LLVM version (see e.g. `/opt/rocm/llvm/bin/clang++ --version`).

**Comment by ManuelCostanzo** [comment]
@illuhad ROCM 5.4 worked perfectly!  The only thing I saw is that acpp (or rocm idk who is responsible) cant detect the GPU name (gfx960c), but then is working so its just something visual. Thank you again!

**Comment by illuhad** [comment]
AdaptiveCpp just asks HIP for the device name. I've seen ROCm returning empty device names before, including for some "officially supported" data center GPUs. So this is nothing new, and probably just a ROCm bug that is mildly inconvenient, but does not have an impact on functionality. If everything works apart from that, I wouldn't be concerned about it :)

**Comment by ManuelCostanzo** [comment]
For sure! When I checked that it worked, I no longer cared to see the name haha.
Best!
