### ISSUE TITLE
Is Dynamic memory management supportted in the future releases?

### ISSUE THREAD

**Issue by JinlongLi2001** [AdaptiveCpp/AdaptiveCpp#1241]
Like <cudamalloc> used in Kernel function and device function as follow :
Is it possible as a new addiational feature in SYCL ? Or offer an alternative method ? 
#include<cuda_runtime.h>
#include"device_launch_parameters.h"
#include<stdio.h>

__global__ void malloc_test(double **a)
{
    int i = threadIdx.x + blockDim.x * blockIdx.x;
    int j = threadIdx.y + blockDim.y * blockIdx.y;
    if(i==10&&j==10)
    {
        int N = 10000;
        cudaMalloc((void**)a, sizeof(double)*N); //分配的地址记录在(*a)
        for(int i=0;i<N;i++)
        {
            (*a)[i] = i;
        } 
    }
    __syncthreads();
    if(i==11&&j==11)
    {
        printf("%f\n",(*a)[500]);
    }

}

int main()
{
    double **a;
    cudaMalloc((void**)&a, sizeof(double *)); //为a分配显存空间
    dim3 blockdim(3,3);
    dim3 griddim(6,6);
    malloc_test<<<griddim, blockdim>>>(a);
    cudaDeviceSynchronize();
    return 0;
}

**Comment by illuhad** [comment]
There are multiple layers to this question. As you say, this functionality is not currently part of the SYCL specification. Additionally,
* I am not aware that this is being discussed as a priority in inside the SYCL working group. This might be related to the second point:
* Even in CUDA, this functionality has limitations and is typically not efficient. Heap allocations require a shared data structure across all threads, which means that using it imposes a massive synchronization cost inside your kernel. The way it works in CUDA to my knowledge is that the runtime just preallocates some memory for in-kernel allocations, and then `cudaMalloc` just distributes this memory to its callers (with some additional bookkeeping to keep track of free memory). If you really need this functionality, you should be able to easily implement it yourself. But again, this pattern is always going to be inefficient.
* In the `--acpp-targets=cuda` compilation flow, we support interoperability with native CUDA source code. So you could just call `cudaMalloc()` inside your kernel if you are primarily interested in NVIDIA. Obviously this isn't going to work on GPUs from other vendors then. See here for details: https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/hip-source-interop.md


Ultimately, you are going to see much more improvements in your program if you can reformulate your algorithm to not require in-kernel allocations. My guess is that such algorithmic improvements will probably be a more beneficial investment of your time.
