### ISSUE TITLE
Building AdaptiveCpp with omp.accelerated compilation flow on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1244]
Hello. I am trying to build AdaptiveCpp with `omp.accelerated` compilation flow on Windows.

This is the configuring command I use:

`cmake .. -G Ninja -DCMAKE_C_COMPILER=c:/llvm/bin/clang.exe -DCMAKE_CXX_COMPILER=c:/llvm/bin/clang++.exe -DBOOST_ROOT=c:/libraries/boost_1_83_clangw17 -DLLVM_DIR=c:/llvm/lib/cmake/llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=c:/AdaptiveCpp/ -DWITH_SSCP_COMPILER=OFF -DWITH_OPENCL_BACKEND=OFF -DWITH_LEVEL_ZERO_BACKEND=OFF -DWITH_ACCELERATED_CPU=ON`

First, there was a minor error:

```
[12/77] Building CXX object src/compiler/CMakeFiles/acpp-clang.dir/cbs/IRUtils.cpp.obj
FAILED: src/compiler/CMakeFiles/acpp-clang.dir/cbs/IRUtils.cpp.obj
c:\llvm\bin\clang++.exe -DHIPSYCL_COMPILER_COMPONENT -DHIPSYCL_DEBUG_LEVEL=2 -DHIPSYCL_WITH_ACCELERATED_CPU -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dacpp_clang_EXPORTS -ID:/source/AdaptiveCppHotFix/AdaptiveCpp/src/compiler/../../include -IC:/llvm/include -ID:/source/AdaptiveCppHotFix/AdaptiveCpp/src/compiler -ID:/source/AdaptiveCppHotFix/AdaptiveCpp/build/include -O2 -DNDEBUG -g -Xclang -gcodeview -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -std=c++17 -fno-exceptions -MD -MT src/compiler/CMakeFiles/acpp-clang.dir/cbs/IRUtils.cpp.obj -MF src\compiler\CMakeFiles\acpp-clang.dir\cbs\IRUtils.cpp.obj.d -o src/compiler/CMakeFiles/acpp-clang.dir/cbs/IRUtils.cpp.obj -c D:/source/AdaptiveCppHotFix/AdaptiveCpp/src/compiler/cbs/IRUtils.cpp
In file included from D:/source/AdaptiveCppHotFix/AdaptiveCpp/src/compiler/cbs/IRUtils.cpp:29:
In file included from D:/source/AdaptiveCppHotFix/AdaptiveCpp/src/compiler/../../include\hipSYCL/compiler/cbs/IRUtils.hpp:31:
D:/source/AdaptiveCppHotFix/AdaptiveCpp/src/compiler/../../include\hipSYCL/common/debug.hpp:73:29: error: no member named 'stoi' in namespace 'std'
   73 |         _debug_level = std::stoi(std::string{e});
      |                        ~~~~~^
1 error generated.
```

which I solved by adding `#include <string>` to `debug.hpp`.

After this, build process went well until the last step, where I got a lot of linking errors. I am providing the full message of the first message, and then only the first line of others, as they are similar to the first.

```
[77/77] Linking CXX shared library src\compiler\acpp-clang.dll
FAILED: src/compiler/acpp-clang.dll src/compiler/acpp-clang.lib
cmd.exe /C "cmd.exe /C ""C:\Program Files\CMake\bin\cmake.exe" -E __create_def D:\source\AdaptiveCppHotFix\AdaptiveCpp\build\src\compiler\CMakeFiles\acpp-clang.dir\.\exports.def D:\source\AdaptiveCppHotFix\AdaptiveCpp\build\src\compiler\CMakeFiles\acpp-clang.dir\.\exports.def.objs --nm=C:\llvm\bin\llvm-nm.exe && cd D:\source\AdaptiveCppHotFix\AdaptiveCpp\build" && c:\llvm\bin\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O2 -DNDEBUG -g -Xclang -gcodeview -D_DLL -D_MT -Xclang --dependent-lib=msvcrt  -Xlinker /DEF:src\compiler\CMakeFiles\acpp-clang.dir\.\exports.def -shared -o src\compiler\acpp-clang.dll  -Xlinker /MANIFEST:EMBED -Xlinker /implib:src\compiler\acpp-clang.lib -Xlinker /pdb:src\compiler\acpp-clang.pdb -Xlinker /version:0.0 src/compiler/CMakeFiles/acpp-clang.dir/AdaptiveCppClangPlugin.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/GlobalsPruningPass.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/LoopSplitterInlining.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/SplitterAnnotationAnalysis.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/IRUtils.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/KernelFlattening.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/LoopsParallelMarker.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/PHIsToAllocas.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/RemoveBarrierCalls.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/CanonicalizeBarriers.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/SimplifyKernel.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/LoopSimplify.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/PipelineBuilder.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/SubCfgFormation.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/UniformityAnalysis.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/VectorShape.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/VectorizationInfo.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/AllocaSSA.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/VectorShapeTransformer.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/Region.cpp.obj src/compiler/CMakeFiles/acpp-clang.dir/cbs/SyncDependenceAnalysis.cpp.obj -LC:/llvm/lib -lclang.lib  C:/llvm/lib/LLVMSupport.lib  -lpsapi.lib  -lshell32.lib  -lole32.lib  -luuid.lib  -ladvapi32.lib  -ldelayimp.lib  -delayload:shell32.dll  -delayload:ole32.dll  C:/llvm/lib/LLVMDemangle.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
lld-link: error: undefined symbol: private: static struct llvm::AnalysisKey llvm::OuterAnalysisManagerProxy<class llvm::AnalysisManager<class llvm::Module>, class llvm::Function>::Key
>>> referenced by D:\source\AdaptiveCppHotFix\AdaptiveCpp\src\compiler\cbs\LoopSplitterInlining.cpp:176
>>>               src/compiler/CMakeFiles/acpp-clang.dir/cbs/LoopSplitterInlining.cpp.obj:(public: class llvm::PreservedAnalyses __cdecl hipsycl::compiler::LoopSplitterInliningPass::run(class llvm::Function &, class llvm::AnalysisManager<class llvm::Function> &))
>>> referenced by D:\source\AdaptiveCppHotFix\AdaptiveCpp\src\compiler\cbs\KernelFlattening.cpp:98
>>>               src/compiler/CMakeFiles/acpp-clang.dir/cbs/KernelFlattening.cpp.obj:(public: class llvm::PreservedAnalyses __cdecl hipsycl::compiler::KernelFlatteningPass::run(class llvm::Function &, class llvm::AnalysisManager<class llvm::Function> &))
>>> referenced by D:\source\AdaptiveCppHotFix\AdaptiveCpp\src\compiler\cbs\LoopsParallelMarker.cpp:165
>>>               src/compiler/CMakeFiles/acpp-clang.dir/cbs/LoopsParallelMarker.cpp.obj:(public: class llvm::PreservedAnalyses __cdecl hipsycl::compiler::LoopsParallelMarkerPass::run(class llvm::Function &, class llvm::AnalysisManager<class llvm::Function> &))
>>> referenced 5 more times

lld-link: error: undefined symbol: private: static struct llvm::AnalysisSetKey llvm::PreservedAnalyses::AllAnalysesKey
lld-link: error: undefined symbol: public: void __cdecl llvm::LoopInfoBase<class llvm::BasicBlock, class llvm::Loop>::releaseMemory(void)
lld-link: error: undefined symbol: public: static char llvm::LoopInfoWrapperPass::ID
lld-link: error: undefined symbol: public: static char llvm::DominatorTreeWrapperPass::ID
lld-link: error: undefined symbol: public: static char llvm::TargetTransformInfoWrapperPass::ID
lld-link: error: undefined symbol: private: static struct llvm::AnalysisKey llvm::LoopAnalysis::Key
lld-link: error: undefined symbol: private: static struct llvm::AnalysisKey llvm::TargetIRAnalysis::Key
lld-link: error: undefined symbol: public: static char llvm::PostDominatorTreeWrapperPass::ID
lld-link: error: undefined symbol: private: static struct llvm::AnalysisKey llvm::DominatorTreeAnalysis::Key
lld-link: error: undefined symbol: public: static char llvm::AssumptionCacheTracker::ID
lld-link: error: undefined symbol: private: static struct llvm::AnalysisKey llvm::AssumptionAnalysis::Key
lld-link: error: undefined symbol: private: static struct llvm::AnalysisSetKey llvm::CFGAnalyses::SetKey
lld-link: error: undefined symbol: public: static char llvm::ScalarEvolutionWrapperPass::ID
lld-link: error: undefined symbol: public: static class llvm::OptimizationLevel const llvm::OptimizationLevel::O0
lld-link: error: undefined symbol: public: static class llvm::OptimizationLevel const llvm::OptimizationLevel::O3
lld-link: error: undefined symbol: public: class llvm::PreservedAnalyses __cdecl llvm::PassManager<class llvm::Function, class 
lld-link: error: undefined symbol: private: static struct llvm::AnalysisKey llvm::PostDominatorTreeAnalysis::Key
lld-link: error: undefined symbol: public: bool __cdecl llvm::LoopBase<class llvm::BasicBlock, class llvm::Loop>::isLoopExiting(class 
```

I am using Clang 17.0.4, which was configured using the next command:

`cmake ../llvm -G Ninja -DCMAKE_INSTALL_PREFIX=c:/llvm/ -DLLVM_ENABLE_PROJECTS="clang;lld" -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_RUNTIMES="compiler-rt;openmp"`

(In this version I have tried to rebuild openmp and not copy libomp libraries from binary distribution just in case if this causes this problem, but this didn't help)

If I build AdaptiveCpp without `omp.accelerated`, there is no any problems.

**Comment by nilsfriess** [comment]
It seems that the `LLVM_LIBS` variable used [here](https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/src/compiler/CMakeLists.txt#L105) does not contain all the necessary LLVM libraries on Windows (I remember that I had a similar problem at some point, and adding  `LLVMContext` [here](https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/src/compiler/CMakeLists.txt#L111) fixed it).

Probably we should make this a bit more robust by doing it as described in the [LLVM docs ](https://llvm.org/docs/CMake.html#embedding-llvm-in-your-project), i.e., use `llvm_map_components_to_libnames` to get all the necessary libraries.

In the meantime you could use the `llvm-config` tool (which might be called `llvm-config-XY` where XY is the LLVM version you have, e.g., 17) and just add  the libraries listed by `llvm-config --libs all` [here](https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/src/compiler/CMakeLists.txt#L111) (without the `-l`).

**Comment by fodinabor** [comment]
Yeah.. You can basically forget using any of the more advanced compiler flows on windows relying on the plugin architecture.. LLVM just cannot export all necessary symbols in a reliable way.
The only way to support this on windows, that I see feasible, is to build the passes into a custom clang (we have to build custom llvm on windows anyways) which isn't that painful, but will need some build system support and adaptation to the pass registration.

RV is one project I know of that supports the plugin flow as well as being built into the llvm tools: https://github.com/cdl-saarland/rv#buildling-librv

**Comment by blinkfrog** [comment]
Thank you very much Nils (@nilsfriess), adding libraries to `target_link_libraries` worked! No more these linking errors!
It looks like I finally got `omp.accelerated` compile flow.

I set ACCP_TARGETS to `omp.accelerated`, and the test file was built without that `acpp fatal error: Trying to use accelerated CPU variant, but plugin was built without support for it`, so I think it works (device name still is the same `hipSYCL OpenMP host device`, but it probably should not differ from usual `omp.library-only` flow).

Performance of my test files is the same, I think this is what Aksel Alpay (@illuhad) told about - that there is no any difference in usual basic parallel kernels, only in nd_range-kernels when barriers are used.

I can close the problem as solved, still, it would be good if ACPP source was updated so there would be no need for manual source edits: adding `#include <string>` to `debug.hpp`, and adding LLVM libraries to target_link_libraries in `/src/compiler/CMakeLists.txt`

@fodinabor, It looks like I still can use these advanced compiler flows on Windows. :)

**Comment by blinkfrog** [comment]
I've noticed that after `find_package(LLVM CONFIG)` `LLVM_LIBS` isn't set - it is empty. However, `LLVM_AVAILABLE_LIBS` is set to a correct set of llvm libraries.

May be this workaround could be added to AdaptiveCpp's main `CMakeLists.txt`:

```
if(NOT LLVM_LIBS AND LLVM_AVAILABLE_LIBS)
    set(LLVM_LIBS ${LLVM_AVAILABLE_LIBS})
endif()
```
?

I can submit a pull request if needed.

I've tried this, and the problem is gone and no manual adding the full list of libraries to https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/src/compiler/CMakeLists.txt#L105 is needed.

**Comment by illuhad** [comment]
Thanks for letting us know! I think we've discussed `LLVM_LIBS` being empty internally at some point (not sure in what context - perhaps @nilsfriess was involved?). I'm not sure if `LLVM_AVAILABLE_LIBS` is semantically the same as it might refer to all libraries, not just the needed ones. I'd like to see a PR, at the least in order to let this workaround run through CI to see if it causes problems somewhere :)

**Comment by blinkfrog** [comment]
Thank you @illuhad, I've submited two PRs, https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1250 and https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1251. I've tested, and ensured that with both these changes AdaptiveCpp is built with `omp.accelerated` compilation flow on Windows out-of-the-box, without any additional changes.
