### ISSUE TITLE
cmake linking on 64-bit systems looks for libOpenCL.so in 32-bit directory

### ISSUE THREAD

**Issue by RalphSteinhagen** [AdaptiveCpp/AdaptiveCpp#1249]
**Bug summary**
On a OpenSuse TumbleWeed, I am getting the following linking error:

```text
[ 85%] Built target rt-backend-cuda
[ 86%] Linking CXX shared library librt-backend-ocl.so
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib/libOpenCL.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [src/runtime/CMakeFiles/rt-backend-ocl.dir/build.make:198: src/runtime/librt-backend-ocl.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:833: src/runtime/CMakeFiles/rt-backend-ocl.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

It seems that the cmake script looks and links against the 32-bit version rather than the 64-bit version located in `/usr/lib64'.
Would be nice if the default order is switched. 

Thanks for the library and keep up the good work! :+1:

**Comment by illuhad** [comment]
We just invoke `find_package(OpenCL)`  - perhaps we could add a workaround, but I'm not sure it's worth the effort as this seems to be a bug in the upstream OpenCL cmake integration (https://cmake.org/cmake/help/latest/module/FindOpenCL.html) and probably can be easily avoid using `-DOpenCL_DIR` and similar?

**Comment by RalphSteinhagen** [comment]
@illuhad thanks for the pointers w.r.t. the cmake find implementation for OpenCL. 

A local workaround of overriding the indicated variable did the trick w.r.t. compiling. Next, I got stuck with the `libacpp-XXX.so` being installed in `lib`  rather than `lib64`. More workarounds ... maybe I am doing something wrong. What am I missing ... ? :thinking: 

In [here](https://github.com/AdaptiveCpp/AdaptiveCpp/blob/306c36b104189a0b016d628781042f6e04543d0a/install/scripts/README.md?plain=1#L10-L14) I read:
```text
Currently, we support
* Ubuntu 18.04
* Ubuntu 20.04
* CentOS 7
* Arch Linux
```

These are rather ~~old~~experienced distributions. Does this mean that with my openSUSE Tumbleweed I am out of luck for the time being ...?

**Comment by illuhad** [comment]
> These are rather oldexperienced distributions. Does this mean that with my openSUSE Tumbleweed I am out of luck for the time being ...?

We definitely also support newer versions such as Ubuntu 22.04 (which is the primary OS in CI). The scripts directory were you've found that documentation is deprecated.

Regarding the `lib` issue, I believe the directory is currently hardcoded (and we should generalize it). That said, unless you want to create a package, you should be able to just install AdaptiveCpp into its own directory such as `/opt/AdaptiveCpp` or locally in your home using `-DCMAKE_INSTALL_PREFIX=...` . This approach is better tested, and currently better supported as it does not require taking all those differences between distributions into account.

**Comment by RalphSteinhagen** [comment]
fixed with latest commits on `develop` (or before). Thanks for the help and all involved. :+1:
