### ISSUE TITLE
find no HIP devices while excuate acpp-info on Ubuntu22.04 with rocm-5.7.1 and AMD Readon 7900xtx device 

### ISSUE THREAD

**Issue by JinlongLi2001** [AdaptiveCpp/AdaptiveCpp#1285]
**Bug summary**
      find no HIP devices while excuate acpp-info on Ubuntu22.04(desktop version latest version: 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux) with rocm-5.7.1 and AMD Readon 7900xtx devices, there are six 7900xtx devices in this server

           $ rocm-smi
      ========================= ROCm System Management Interface =========================
      =================================== Concise Info ===================================
      GPU  Temp (DieEdge)  AvgPwr  SCLK  MCLK   Fan  Perf  PwrCap  VRAM%  GPU%  
      0    36.0c           22.0W   0Mhz  96Mhz  0%   auto  327.0W    0%   0%    
      1    36.0c           19.0W   0Mhz  96Mhz  0%   auto  327.0W    0%   0%    
      2    33.0c           21.0W   0Mhz  96Mhz  0%   auto  327.0W    0%   0%    
      3    33.0c           22.0W   0Mhz  96Mhz  0%   auto  327.0W    0%   0%    
      4    34.0c           22.0W   0Mhz  96Mhz  0%   auto  327.0W    0%   0%    
      5    34.0c           18.0W   0Mhz  96Mhz  0%   auto  327.0W    0%   0%    
      ====================================================================================
      =============================== End of ROCm SMI Log ================================

**To Reproduce**
      $ acpp-info
**Expected behavior**
      Out OMP devices and HIP devices 
**Describe your setup**
* how you have installed AdaptiveCpp, and which version/branch/git commit
      export CC=/opt/rocm/llvm/clang
      export CXX=/opt/rocm/llvm/clang++
      export BOOST_ROOT=/public/boost
      cmake -DCMAKE_INSTALL_PREFIX=/home/ljl/OpenSYCL -DROCM_PATH=/opt/rocm  -DWITH_ROCM_BACKEND=ON -DWITH_CUDA_BACKEND=OFF -DHIPSYCL_NO_DEVICE_MANGLER=ON -DWITH_ACCELERATED_CPU=OFF -DWITH_SSCP_COMPILER=OFF .. && mak -j install
* Describe the dependencies that AdaptiveCpp sits on top of in your setup: 
   * ROCm version and how ROCm was installed (if applicable)
    amdgpu-install --usecase=rocm
**Optional additional diagnostic information**
    ldd ./lib/hipSYCL/librt-backend-hip.so
output:
	linux-vdso.so.1 (0x00007ffc715de000)
	libacpp-rt.so => /public/OpenSYCL/lib/libacpp-rt.so (0x00007f44448ab000)
	libamdhip64.so.5 => /opt/rocm/lib/libamdhip64.so.5 (0x00007f4442e00000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4442a00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4442d19000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4444889000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4442600000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4444934000)
	libacpp-common.so => /public/OpenSYCL/lib/libacpp-common.so (0x00007f4444881000)
	libamd_comgr.so.2 => /opt/rocm/lib/libamd_comgr.so.2 (0x00007f4439c00000)
	libhsa-runtime64.so.1 => /opt/rocm/lib/libhsa-runtime64.so.1 (0x00007f4439800000)
	libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f4444874000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4442cfd000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f4442ccb000)
	libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007f4442cad000)
	libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f444485c000)
	libdrm_amdgpu.so.1 => /lib/x86_64-linux-gnu/libdrm_amdgpu.so.1 (0x00007f4442ca1000)
* For compilation/toolchain or setup-related issues: Setting the environment variable `HIPSYCL_DRYRUN=1` during compilation will cause `syclcc` to print the commands it would execute instead of actually executing. This can help verify the sanity of your setup.
* `syclcc --hipsycl-version` prints information about the AdaptiveCpp configuration that may be interesting for setup-related issues.
    acpp [AdaptiveCpp compilation driver], Copyright (C) 2018-2023 Aksel Alpay and the AdaptiveCpp project
    AdaptiveCpp version: 23.10.0+git.1fd4f9fb.20231114.branch.develop.dirty
    Installation root: /public/OpenSYCL
    Plugin LLVM version: 17, can accelerate CPU: False
    Available runtime backends:
       librt-backend-omp.so
       librt-backend-hip.so
  
  
  Full configuration [can be overriden using environment variables or command line arguments]:
      version-major: 23
      version-minor: 10
      version-patch: 0
      version-suffix: +git.1fd4f9fb.20231114.branch.develop.dirty
      plugin-llvm-version-major: 17
      plugin-with-cpu-acceleration: false
      default-clang: /opt/rocm/llvm/bin/clang++
      default-nvcxx: (unconfigured)
      default-platform: rocm
      default-cuda-path: (unconfigured)
      default-gpu-arch: (unconfigured)
      default-cpu-cxx: /opt/rocm/llvm/bin/clang++
      default-rocm-path: /opt/rocm
      default-use-bootstrap-mode: false
      default-is-dryrun: false
      default-use-accelerated-cpu: false
      default-clang-include-path: /opt/rocm/llvm/lib/clang/17.0.0/include/..
      default-sequential-link-line: -L/public/boost/lib -lboost_context -lboost_fiber -Wl,-rpath=/public/boost/lib
      default-sequential-cxx-flags: -I/public/boost/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
      default-omp-link-line: -L/public/boost/lib -lboost_context -lboost_fiber -Wl,-rpath=/public/boost/lib -fopenmp
      default-omp-cxx-flags: -I/public/boost/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
      default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
      default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike -isystem /opt/rocm/llvm/lib/clang/17.0.0/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
      default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
      default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike
      default-is-explicit-multipass: false
      default-save-temps: false
* For issues related to the runtime, setting the environment variable `ACPP_DEBUG_LEVEL=3` will cause it to print *a lot* of diagnostic information that might be helpful. Attach the output of your program with `ACPP_DEBUG_LEVEL=3` if you think it might be helpful for your issue.
           $ export ACPP_DEBUG_LEVEL=3
            $ acpp-info 
            [AdaptiveCpp Info] backend_loader: Searching path for backend libs: '"/public/OpenSYCL/lib/hipSYCL"'
            [AdaptiveCpp Info] backend_loader: Successfully opened plugin: "/public/OpenSYCL/lib/hipSYCL/librt-backend-omp.so" for backend 'omp'
            [AdaptiveCpp Info] backend_loader: Successfully opened plugin: "/public/OpenSYCL/lib/hipSYCL/librt-backend-hip.so" for backend 'hip'
            [AdaptiveCpp Info] Registering backend: 'omp'...
            [AdaptiveCpp Info] multi_queue_executor: Spawned for backend OpenMP with configuration: 
            [AdaptiveCpp Info]   device 0: 
            [AdaptiveCpp Info]     memcpy lane: 0
            [AdaptiveCpp Info]     kernel lane: 1
            [AdaptiveCpp Info] Registering backend: 'hip'...
            [AdaptiveCpp Info] multi_queue_executor: Spawned for backend HIP with configuration: 
            [AdaptiveCpp Info] Discovered devices from backend 'OpenMP': 
            [AdaptiveCpp Info]   device 0: 
            [AdaptiveCpp Info]     vendor: the hipSYCL project
            [AdaptiveCpp Info]     name: hipSYCL OpenMP host device
            [AdaptiveCpp Info] Discovered devices from backend 'HIP': 
            [AdaptiveCpp Info]   <no devices>
            [AdaptiveCpp Info] dag_manager: DAG manager is alive!
            [AdaptiveCpp Info] runtime: ******* rt launch initiated ********
            =================Backend information===================
            Loaded backend 0: OpenMP
              Found device: hipSYCL OpenMP host device
            Loaded backend 1: HIP
              (no devices found)
          =================Device information===================
          ***************** Devices for backend OpenMP *****************
          Device 0:
           General device information:
            Name: hipSYCL OpenMP host device
            Backend: OpenMP
            Vendor: the hipSYCL project
            Arch: <native-cpu>
            Driver version: 1.2
            Is CPU: 1
            Is GPU: 0
           Default executor information:
            Is in-order queue: 0
            Is out-of-order queue: 1
            Is task graph: 0
           Device support queries:
            images: 0
            error_correction: 0
            host_unified_memory: 1
            little_endian: 1
            global_mem_cache: 1
            global_mem_cache_read_only: 0
            global_mem_cache_read_write: 1
            emulated_local_memory: 1
            sub_group_independent_forward_progress: 0
            usm_device_allocations: 1
            usm_host_allocations: 1
            usm_atomic_host_allocations: 1
            usm_shared_allocations: 1
            usm_atomic_shared_allocations: 1
            usm_system_allocations: 1
            execution_timestamps: 1
            sscp_kernels: 0
           Device properties:
            max_compute_units: 32
            max_global_size0: 18446744073709551615
            max_global_size1: 18446744073709551615
            max_global_size2: 18446744073709551615
            max_group_size: 1024
            max_num_sub_groups: 18446744073709551615
            preferred_vector_width_char: 4
            preferred_vector_width_double: 1
            preferred_vector_width_float: 1
            preferred_vector_width_half: 2
            preferred_vector_width_int: 1
            preferred_vector_width_long: 1
            preferred_vector_width_short: 2
            native_vector_width_char: 4
            native_vector_width_double: 1
            native_vector_width_float: 1
            native_vector_width_half: 2
            native_vector_width_int: 1
            native_vector_width_long: 1
            native_vector_width_short: 2
            max_clock_speed: 0
            max_malloc_size: 18446744073709551615
            address_bits: 64
            max_read_image_args: 0
            max_write_image_args: 0
            image2d_max_width: 0
            image2d_max_height: 0
            image3d_max_width: 0
            image3d_max_height: 0
            image3d_max_depth: 0
            image_max_buffer_size: 0
            image_max_array_size: 0
            max_samplers: 0
            max_parameter_size: 18446744073709551615
            mem_base_addr_align: 8
            global_mem_cache_line_size: 64
            global_mem_cache_size: 1
            global_mem_size: 18446744073709551615
            max_constant_buffer_size: 18446744073709551615
            max_constant_args: 18446744073709551615
            local_mem_size: 18446744073709551615
            printf_buffer_size: 18446744073709551615
            partition_max_sub_devices: 0
            vendor_id: 18446744073709551615
            sub_group_sizes: 1 
          ***************** Devices for backend HIP *****************
            (no devices)
          [AdaptiveCpp Info] runtime: ******* rt shutdown ********
          [AdaptiveCpp Info] dag_manager: Waiting for async worker...
          [AdaptiveCpp Info] dag_manager: Submitting asynchronous flush...
          [AdaptiveCpp Info] dag_manager: Nothing to do
          [AdaptiveCpp Info] dag_manager: waiting for async worker...
          [AdaptiveCpp Info] dag_manager: Shutdown.

**Additional context**

**Comment by JinlongLi2001** [comment]
Is rocm-5.7.1 with llvm-17.0 not supportted now ?

**Comment by bsobol** [comment]
What a timing.. I've just encountered the same problem, but in slightly different conditions. 

What's different in my case:
* My environment is in an apptainer container (based on official rocm container with ubuntu 22.04 and rocm 5.4.2)
* I use LLVM 16
* Device not found is MI100 (listed correctly by `rocm-smi`)

**Comment by illuhad** [comment]
Hi @jiuxiaocloud - please validate that a regular HIP program works. In your case, the backend was loaded correctly but loads no devices. This means that most likely `hipGetDeviceCount()` returned 0. In that case, there is an issue at the HIP or driver level.

There is no inherent reason why LLVM 17 or ROCm 5.7.1 won't work. But please note that we only provide limited support for building AdaptiveCpp against the LLVM shipped with ROCm, as ROCm LLVM is known to be unstable for anything but HIP compilation, and is a moving target that typically sits in between LLVM versions and thus difficult to support. We discourage such configurations in our documentation.
In your case, the issue is most likely a runtime and not a compiler issue, so this won't matter.

@gogo2 Please validate whether a) the HIP backend plugin was loaded successfully (you'll see a warning if it could not be loaded) and if so, b) check whether a regular HIP program can see the devices.

**Comment by bsobol** [comment]
Nevermind, in my case, it was a permissions issue on the cluster.

**Comment by illuhad** [comment]
Right, for ROCm to work you need to be in the render and/or video group. @jiuxiaocloud - please also check that :)

**Comment by JinlongLi2001** [comment]
Thanks a lot. It's handled by add ROCm permission for my Ubuntu account following below instructions:
[sudo usermod -a -G render,video $LOGNAME]{https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/prerequisites.html}
