### ISSUE TITLE
getting error in cmake

### ISSUE THREAD

**Issue by garadeaniket** [AdaptiveCpp/AdaptiveCpp#1286]
During cmake , I am getting the below error. Please help to rectify 

CMake Error at cmake/FindFilesystem.cmake:286 (message):
  Cannot run simple program using std::filesystem
Call Stack (most recent call first):
  src/common/CMakeLists.txt:17 (find_package)

**Comment by nilsfriess** [comment]
Can you tell us more about your environment? How are you calling CMake, which compiler are you using etc.?

**Comment by garadeaniket** [comment]
cmake -DCMAKE_INSTALL_PREFIX=/path/to/build -DCMAKE_C_COMPILER=/path/to/bin/gcc -DCMAKE_CXX_COMPILER=/path/to/bin/g++ -DCLANG_EXECUTABLE_PATH=path/to/bin/clang++ -DCLANG_INCLUDE_PATH=/path/to/include/clang/ -DCMAKE_CXX_COMPILER=/path/to/bin/clang++ -DBOOST_ROOT=/path/to/build/ -DWITH_CUDA_BACKEND=ON
-DCUDA_TOOLKIT_ROOT_DIR=/path/to/cuda -DACPP_VERSION_SUFFIX="-"

gcc version 12.2.0
clang version  15.0.7

**Comment by nilsfriess** [comment]
You are passing two different compilers for `CMAKE_CXX_COMPILER`, not sure if this causes the problem, but I guess that's not what you want.

Can you try 
```
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install -DCMAKE_CXX_COMPILER=clang++ -DBOOST_ROOT=/path/to/boost -DWITH_CUDA_BACKEND=ON -DCUDA_TOOLKIT_ROOT_DIR=/path/to/cuda -DACPP_VERSION_SUFFIX="-"
```
Make sure to clean you build directory before that.

Note that `CMAKE_INSTALL_PREFIX` should be the path where you want the project to be installed. And `BOOST_ROOT` should point to the path where boost is installed (if you're on Ubuntu or similar and installed boost via `apt-get` then you probably don't need to specify this manually).

**Comment by garadeaniket** [comment]
I tried with the above command u mentioned but getting the same error and also nothing has been generated in build folder .The error seems more of missing package (Findfilesystem).Any idea about this?

**Comment by nilsfriess** [comment]
Could you please post the full CMake command you're using again and the complete output you're getting. And could you give us some details about your build environment, in particular your OS?  

We are testing with clang15 in CI and I also just tried to build AdaptiveCpp with gcc 12, which also worked.
