### ISSUE TITLE
[AMDGPU] Execution freezes on AMD MI100 with XNACK enabled

### ISSUE THREAD

**Issue by Luigi-Crisci** [AdaptiveCpp/AdaptiveCpp#1302]
**Bug summary**
When running a SYCL program using shared allocations on the device the execution freezes when waiting for the kernel to finish. Without XNACK the code runs fine.
The same code runs fine with DPC++, also with XNACK enabled.
If using `prefetch`, the program runs fine.

**To Reproduce**
Sample
```c++
#include <sycl/sycl.hpp>
#include <iostream>
int main(){
    sycl::queue q{sycl::gpu_selector_v};
    constexpr size_t N = 1024;
    float *data = (float*) sycl::malloc_shared(N, q);
    std::cout << "Past allocation\n";
    q.parallel_for(N, [=](auto i) { data[i] = i; }).wait();
    std::cout << "Past parallel_for\n";
}
```
It freezes on the parallel for.

**Describe your setup**
- AdaptiveCpp eeebfd47fc09afdb4c46cd72c17f3cca3048fb0f
- Clang 16.06
- ROCm 5.5.0

**Comment by illuhad** [comment]
XNACK as a whole is a bugfest, and known to be unstable already in pure HIP. This also includes driver issues and potential kernel hangs. And by kernel I mean both compute kernel and OS kernel.

It's quite possible that you just got lucky in DPC++ (or unlucky in AdaptiveCpp).

The environment variable `AMD_SERIALIZE_COPY=3` has been known to occasionally help, but not always.

I am going to close this unless there's evidence that AdaptiveCpp really does something wrong. You might also want to try different compilation flows. `hip` target and `generic` target will handle this slightly differently, with `hip` target by default generating code that works in both XNACK and non-XNACK environments, while `generic` will take the actual configuration of the GPU at runtime into account. I.e. it might generate XNACK-exclusive code if XNACK is enabled.
