### ISSUE TITLE
SPIR-V/OpenCL & sycl::reduce_over_group

### ISSUE THREAD

**Issue by OuadiElfarouki** [AdaptiveCpp/AdaptiveCpp#1309]
I've been trying AdaptiveCpp's generic compilation flow for spir-v/opencl targets _(intel CPU/GPU)_ on a SYCL program with a kernel invoking `sycl::reduce_over_group`.  Un-commenting the line at https://github.com/AdaptiveCpp/AdaptiveCpp/blob/v23.10.0/src/runtime/ocl/ocl_queue.cpp#L453 lifts  the `RequiresExtension` error related to the  `SPV_EXT_shader_atomic_float_add` not being enabled by default, but results in the following being unresolved :

`float hipsycl::sycl::detail::sscp_builtins::__hipsycl_reduce_over_group<float, hipsycl::sycl::plus<float> >(hipsycl::sycl::sub_group, float, hipsycl::sycl::plus<float>)`

So I was wondering if this is an expected behavior of the `__hipsycl_reduce_over_group` for SPIR-V/OpenCL flow or if I'm missing something?

**Comment by illuhad** [comment]
Yeah, the group algorithms library is not yet implemented with `generic` target :( Apologies.

**Comment by OuadiElfarouki** [comment]
Noted thanks a lot for confirming that!
