### ISSUE TITLE
Profiling issues with generic SPIRV/OpenCL flow

### ISSUE THREAD

**Issue by OuadiElfarouki** [AdaptiveCpp/AdaptiveCpp#1317]
I've been trying to profile some code with different flows, it seems to work file with the cuda generic flow for instance but I'm getting this error when targeting intel CPU/GPU through generic-spirv + OpenCL pass : 
```
terminate called after throwing an instance of 'hipsycl::sycl::exception'
  what():  Operation not profiled: No execution start timestamp available
```
`cl::sycl::property::queue::enable_profiling()` is set properly and the error is thrown right after the call to `event.get_profiling_info<event_profiling::command_start>()`. 
Is this expected due to an eventual partial support of profiling through spirv/opencl with AdaptiveCpp or is it supposed to work fine ?

**Comment by normallytangent** [comment]
Could you please share a short reproducer?

**Comment by illuhad** [comment]
Hi, queue profiling is not yet implemented for OpenCL or Level Zero backends. This has nothing to do with the `generic` target, just with the runtime backends.

**Comment by OuadiElfarouki** [comment]
Noted thanks for the answer Aksel. I'll close this one.
