### ISSUE TITLE
LLVMToAmdgpu: hiprtcLinkComplete() failed,  hip_queue: Code object construction failed

### ISSUE THREAD

**Issue by Deepak78956** [AdaptiveCpp/AdaptiveCpp#1405]
**Bug summary**
I am running a BFS program with some load balancing, this program is running fine when running with HIP (hipcc) and CUDA (nvcc), but when running using acpp --acpp-platform=rocm, it is throwing below errors:

> [AdaptiveCpp Error] from /home/deepak/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:259 @ compile(): jit::compile: Encountered errors:
> 0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.
> 
> [AdaptiveCpp Error] from /home/deepak/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:695 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
> 
> ============== hipSYCL error report ============== 
> hipSYCL has caught the following undhandled asynchronous errors: 
> 
>    0. from /home/deepak/AdaptiveCpp/include/hipSYCL/glue/llvm-sscp/jit.hpp:259 @ compile(): jit::compile: Encountered errors:
> 0: LLVMToAmdgpu: hiprtcLinkComplete() failed. Setting the environment variables AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1 might reveal more information.
> 
>    1. from /home/deepak/AdaptiveCpp/src/runtime/hip/hip_queue.cpp:695 @ submit_sscp_kernel_from_code_object(): hip_queue: Code object construction failed
> The application will now be terminated.
> terminate called without an active exception

**To Reproduce**
Download [these](https://github.com/Deepak78956/MTP-Files/tree/main/HIP_hipSYCL_implementation/LB_BFS) codes and use "make run_sycl"

**Expected behavior**
Expected output: Correct ans, Time taken = x 
x here could be any double value.

**Describe your setup**
llvm-14.0 clang-14.0 (installed using ubuntu package manager)
Running on AMD instinct MI210

dkms status:

> amdgpu/6.3.6-1718217.22.04, 6.5.0-17-generic, x86_64: installed
> amdgpu/6.3.6-1718217.22.04, 6.5.0-25-generic, x86_64: installed
> nvidia/545.23.08, 6.5.0-17-generic, x86_64: installed
> nvidia/545.23.08, 6.5.0-25-generic, x86_64: installed

applications are compiler using:

> acpp -O3 sycl_nnz_splitting_BFS.cpp --acpp-platform=rocm make_csr.cpp -o $(SYCL_OUTPUT)

**Optional additional diagnostic information**
**acpp-info**
[acpp-info.txt](https://github.com/AdaptiveCpp/AdaptiveCpp/files/14596970/acpp-info.txt)

**acpp-version**
[acpp-version.txt](https://github.com/AdaptiveCpp/AdaptiveCpp/files/14596980/acpp-version.txt)

**Comment by nilsfriess** [comment]
Not sure if this causes the issue here, but `--acpp-platform` is deprecated, please use `--acpp-targets=hip:gfx908` instead (replace gfx908 with your architecture), or just omit `--acpp-platform` and `--acpp-targets` completely, which will use the generic compiler which will compile faster and often produce faster code.

**Comment by illuhad** [comment]
Please post the output when you set the environment variables `AMD_COMGR_SAVE_TEMPS=1 AMD_COMGR_REDIRECT_LOGS=stdout AMD_COMGR_EMIT_VERBOSE_LOGS=1` as the error message asks you to :)

And as @nilsfriess said, don't use `--acpp-platform`. It's deprecated and you don't need it :)

**Comment by Deepak78956** [comment]
Thank you for your feedback. Following the implementation of the suggested flags, an error was encountered. Within the output, amidst various details, there was one particular line that notably contributed to resolving the error:

> error: <unknown>:0:0: in function _Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZ9init_distPiiRNS0_4sycl5queueEiE3$_0Li1EEEEvRKT_ void (i32, i32, ptr addrspace(1)): unsupported call to variadic function printf
> 
> 1 error generated.
>         ReturnStatus: AMD_COMGR_STATUS_ERROR

This error was coming because of **printf("source is %d\n", s)**  in the below kernel:

```cpp
void init_dist(int *dist, int num_vertices, sycl::queue &q, int s){
    unsigned nBlocks_for_vertices = ceil((float)num_vertices / B_SIZE);
    auto range = sycl::nd_range<1>(sycl::range<1>(nBlocks_for_vertices * B_SIZE), sycl::range<1>(B_SIZE));

    q.parallel_for(range, [=](sycl::nd_item<1> item){
        unsigned id = item.get_global_id(0);
        if (id < num_vertices) {
            if (id == s) {
                printf("source is %d\n", s);
                dist[id] = 0;
            }
            else {
                dist[id] = inf;
            }
        }
    }).wait();
}
```

But I'm confused why this error happened because when I ran this code with DPC++, it worked fine without any problems.

**Comment by illuhad** [comment]
> But I'm confused why this error happened because when I ran this code with DPC++, it worked fine without any problems.

The SYCL specification does not allow `printf` in kernel code. Implementations may choose to support it as an extension, but it is not guaranteed. AdaptiveCpp's generic JIT compiler does not implement `printf`.

**Comment by Deepak78956** [comment]
Thanks for the clarification, I was debugging the code only using the printfs till now. Is there any other way to print from kernel?

**Comment by illuhad** [comment]
The canonical way to print from kernels in SYCL is using the `sycl::stream` class. However, the generic compiler currently only can print `const char*` strings - for ints or floats we need to implement a device-side library for string formatting and conversion, which is a bit of work and not there yet.

Alternatively, for the purpose of debugging and testing you can always compile your code for `omp` target. This compilation flow will run the kernel on the host CPU, and you can use `printf` there and even use your regular host `gdb` to debug the application as any other host application.

**Comment by illuhad** [comment]
Closing due to lack of feedback and ithe original issue was addressed.
