### ISSUE TITLE
Typo in filename sycl/libkernel/sscp/builtins/interger.hpp

### ISSUE THREAD

**Issue by illuhad** [AdaptiveCpp/AdaptiveCpp#1406]
It seems a typo has entered the filename `interger.hpp` and nobody has noticed thanks to great modern IDE support ;)
We should rename that file to `integer.hpp` and change the places where it is referenced accordingly.

**Comment by Abdulrahman295** [comment]
Hello. Can I work on this issue?

**Comment by illuhad** [comment]
Sure, I have just assigned you :) Thanks!
