### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by Helena2007** [AdaptiveCpp/AdaptiveCpp#1413]
While trying to run the example bruteforce_nbody using CMake integration with AdaptiveCpp. When trying to run make install got the error.
/..../AdaptiveCpp/bin/../include/AdaptiveCpp/CL/../hipSYCL/sycl/../common/reinterpret_pointer_cast.hpp:51:12: error: no member named 'reinterpret_pointer_cast' in namespace 'std'
using std::reinterpret_pointer_cast;
      ~~~~~^
1 error generated when compiling for sm_86.
I am using Ubuntu 22.04.

**Comment by illuhad** [comment]
`reinterpret_pointer_cast` was introduced in C++17. If you don't have it, your C++ standard library is likely too old. You may have to install a `libstdc++-<version>-dev` package that is newer than what you currently have.
Also see this section of the documentation:
https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/install-llvm.md#missing-packages

**Comment by illuhad** [comment]
Closing because the issue was presumably solved.
