### ISSUE TITLE
sycl::info::platform::version lacks "0"

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#1426]
**Bug summary**

`platform.get_info<sycl::info::platform::version>()` (and `hipsycl::sycl::detail::version_string`) report version `AdaptiveCpp 24.2.0+abcd` instead of `AdaptiveCpp 24.02.0+abcd`.

**To Reproduce**

```console
$ acpp --acpp-version | grep 'AdaptiveCpp version'
  AdaptiveCpp version: 24.02.0+git.0359cac9.20240401.branch.develop.dirty

$ cat test.cpp 
#include <iostream>
#include <sycl/sycl.hpp>

int main()
{
    std::cout << hipsycl::sycl::detail::version_string() << std::endl;
    sycl::platform p;
    std::cout << p.get_info<sycl::info::platform::version>() << std::endl;
}

$ acpp -O2 test.cpp && ./a.out
AdaptiveCpp 24.2.0+git.0359cac9.20240401.branch.develop.dirty
AdaptiveCpp 24.2.0+git.0359cac9.20240401.branch.develop.dirty
```

**Expected behavior**

`AdaptiveCpp 24.02.0+git.0359cac9.20240401.branch.develop.dirty` is returned in both cases.

**Describe your setup**
* ACpp 0359cac9e08d44c48c586ef3ec88e95ac64a4d44
* Describe the dependencies that AdaptiveCpp sits on top of in your setup: 
   * Clang 17.0.6

**Additional context**

Nothing major or critical, just slightly annoying to have a discrepancy in reported versions.

**Comment by illuhad** [comment]
This is probably because the `ACPP_VERISON_*` macros are ints, which makes sense for the purpose of programmatically comparing version numbers. We'd have to enforce leading zeros in the version string formatting here: https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/include/hipSYCL/sycl/version.hpp

**Comment by al42and** [comment]
Yes, looks like that. And BTW, the year in `acpp --acpp-version | grep Copyright` is out-of-date too.

Shall this get a "good first issue" label? I don't think there's any rush in solving it before the late June? :)
