### ISSUE TITLE
clang: error

### ISSUE THREAD

**Issue by Helena2007** [AdaptiveCpp/AdaptiveCpp#1428]
While trying to run the example bruteforce_nbody using CMake integration with AdaptiveCpp. When trying to run make install got the error.
/usr/bin/ld: /.../.../AdaptiveCpp/lib/libacpp-rt.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by illuhad** [comment]
This indicates that the libstdc++ that you have available is perhaps not the same you had when building AdaptiveCpp. If you are on a cluster, check that you have the right modules loaded.

**Comment by illuhad** [comment]
Closing due to lack of feedback and issue presumably resolved.
