### ISSUE TITLE
`bad_function_call` when using `sycl::specialized`

### ISSUE THREAD

**Issue by Luigi-Crisci** [AdaptiveCpp/AdaptiveCpp#1429]
Note: I'm not sure if this is a bug or a known limitation, but I will anyway post it as it could be interesting.

The following code snipped causes a CUDA error 700 and `std::bad_function_call` when running on an nvidia device:
```c++
struct S{

    sycl::specialized<int> coeff_spec;

    S () : coeff_spec{std::rand()} {}

    void run(){
        sycl::queue q{sycl::gpu_selector_v};
        int* i = sycl::malloc_shared<int>(1, q);

        q.submit([&](sycl::handler& h){            
            h.parallel_for(sycl::range<1>(1), [=](sycl::item<1> item_id){
                int coeff = coeff_spec;
                *i = coeff;
            });
    }).wait_and_throw();

    std::cout << *i << std::endl;
    sycl::free(i,q);
    }
};

int main(){
    S s;
    s.run();
}
```

The output:
```bash
[AdaptiveCpp Error] from /software-local/sources/AdaptiveCpp/src/runtime/cuda/cuda_event.cpp:63 @ wait(): cuda_node_event: cudaEventSynchronize() failed (error code = CUDA:700)
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
[1]    4022712 IOT instruction (core dumped)  ./a.out
```

This can be fixed by making the `sycl::specialized` variable local to the `run` function instead of a member of `S`, so I suppose it's some kind of scope problem(?).  
Is this a known limitation of this approach?

## Environment
AdaptiveCpp 0359cac
HW: Nvidia V100S

**Comment by illuhad** [comment]
I think this is a general C++ problem, not an AdaptiveCpp issue or even a `specialized` issue:
If you capture member variables by value (`[=]`), what actually happens is that it captures the `this` pointer and accesses the variables through `this`. This creates an illegal memory access on device. The same thing would happen if you didn't store a `specialized` in the class, but some other type. It's a C++ issue.

Possible workarounds:
- Make the variable `static`
- Copy it to local scope, as you've tried
- Make a copy of the member variable in your capture clause: `[my_coeff_spec = coeff_spec](...){ /* use my_coeff_spec */}`

**Comment by Luigi-Crisci** [comment]
Thanks, I supposed it was more related to C++ rather than AdaptiveCpp.
