### ISSUE TITLE
[CUDA] Kernel with shared memory does not always run

### ISSUE THREAD

**Issue by AuroraPerego** [AdaptiveCpp/AdaptiveCpp#1434]
**Bug summary**
When using local accessors for the shared memory sometimes the kernel is not executed on an NVIDIA GPU, but no error is raised.
`cuda-gdb` instead catches an error (`warning: Cuda API error detected: cudaLaunchKernel returned (0x1)`).
Tested with NVIDIA T4, L4 and V100.

**To Reproduce**
```cpp
#include <sycl/sycl.hpp>

template <uint32_t N> struct ClusParamsT {
  uint32_t minRow[N];
  uint32_t maxRow[N];
  uint32_t minCol[N];
  uint32_t maxCol[N];

};

int main(int argc, char **argv) try {
  static const std::vector<sycl::device> devices =
      sycl::device::get_devices(sycl::info::device_type::all);

  std::cerr << "Found " << devices.size() << " SYCL devices:" << std::endl;
  for (auto const &device : devices)
    std::cerr << "  - " << device.get_info<sycl::info::device::name>() << " ["
              << device.get_info<sycl::info::device::driver_version>() << "]"
              << std::endl;
  std::cerr << std::endl;
  if (argc < 2) {
    std::cout << "Provide the device number N: ./test N" << std::endl;
    return 1;
  }
  auto q = sycl::queue{devices[atoi(argv[1])]};
  std::cout << "Running on "
            << q.get_device().get_info<sycl::info::device::name>() << std::endl;

  q.submit([&](sycl::handler &cgh) {
     cgh.parallel_for(sycl::nd_range<1>(1, 1), [=](sycl::nd_item<1> item) {
       printf("Running kernel\n");
     });
   }).wait();

  using clusParams = ClusParamsT<128>;
  q.submit([&](sycl::handler &cgh) {
     sycl::accessor<clusParams, 1, sycl::access_mode::read_write,
                    sycl::access::target::local> clusParams_acc(32, cgh); // with this accessor the kernel will not run
     // sycl::accessor<clusParams, 1, sycl::access_mode::read_write,
     //             sycl::access::target::local> clusParams_acc(1, cgh); // with this accessor the kernel runs
     cgh.parallel_for(sycl::nd_range<1>(32, 32), [=](sycl::nd_item<1> item) {
       printf("Running kernel with accessor\n");
       auto c = clusParams_acc.get_pointer();
       c[0].minRow[item.get_local_id(0)] = 0;
       sycl::group_barrier(item.get_group());
     });
   }).wait();

  return 0;
} catch (sycl::exception const& exc) {
  std::cerr << exc.what() << "Exception caught at file:" << __FILE__ << ", line:" << __LINE__ << std::endl;
  std::exit(1);
}
```
compile and run:
```
acpp --gcc-toolchain=/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/gcc/11.4.1-30ebdc301ebd200f2ae0e3d880258e65 -std=c++17 --acpp-targets="generic;cuda:sm_70" -O2  -o accessors accessors.cpp
./accessors N # N is the number of the device in the list of devices
```
Using `sycl::accessor<clusParams, 1, sycl::access_mode::read_write, sycl::access::target::local> clusParams_acc(32, cgh);` the kernel does not run and only `Running kernel` is printed.
Using `sycl::accessor<clusParams, 1, sycl::access_mode::read_write, sycl::access::target::local> clusParams_acc(1, cgh);` the kernel runs and also `Running kernel with accessor` is printed.

**Expected behavior**
The kernel should always run.

**Describe your setup**
* AdaptiveCpp cloned from github: `develop@57773099 + PR 1031` and built with:
   ```
  cmake \
    -DCMAKE_INSTALL_PREFIX=$PWD \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
    -DWITH_CUDA_BACKEND=ON \
    -DROCM_PATH=/opt/rocm \
    -DWITH_ROCM_BACKEND=ON \
    -DWITH_LEVEL_ZERO_BACKEND=ON \
    -DOpenCL_LIBRARY=/opt/intel/oneapi/compiler/2024.0/lib/libOpenCL.so \
    -DWITH_OPENCL_BACKEND=ON \
    -DLLVM_DIR=/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/llvm/16.0.3-d5387186335b0dd85e1c294a1fd64dd0/lib64/cmake/llvm \
    ..
    ```
* ```
  clang version 16.0.3
  Target: x86_64-redhat-linux-gnu
  Thread model: posix
  InstalledDir: /cvmfs/cms.cern.ch/el9_amd64_gcc11/external/llvm/16.0.3-d5387186335b0dd85e1c294a1fd64dd0/bin
  Found CUDA installation: /usr/local/cuda-12.2, version
  Found HIP installation: /opt/rocm, version 6.0.32831
  ```
* `gcc (GCC) 11.4.1 20230601`
* ```
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2023 NVIDIA Corporation
  Built on Tue_Aug_15_22:02:13_PDT_2023
  Cuda compilation tools, release 12.2, V12.2.140
  Build cuda_12.2.r12.2/compiler.33191640_0 
  ```

**Comment by illuhad** [comment]
This is not a problem in AdaptiveCpp. You are requesting amounts of local memory that exceed the hardware limits.

> Expected behavior
> The kernel should always run.

Your assumption that the kernel should always run is incorrect. The amount of local memory that the hardware supports is limited. If too much local memory is requested, the hardware will be unable to launch the kernel.

Also, due to limitations in CUDA/clang, in `--acpp-targets=cuda` mode unfortunately  we cannot catch errors related to kernel submission (such as too much local memory requested). 
In `--acpp-targets=generic` and `--acpp-targets=cuda.explicit-multipass` modes, it will report that it could not launch the kernels instead of silently failing.

Note that if you use `--acpp-targets="generic;cuda:sm_70"` it will run on CUDA throught the `--acpp-targets=cuda` SMCP compiler, not the generic JIT compiler. Unless you really want SMCP and know what you are doing, I recommend just using `--acpp-targets=generic` (i.e. drop the `cuda`). This should also give you better performance.
