### ISSUE TITLE
Improve SSCP std builtins remapping for -ffast-math

### ISSUE THREAD

**Issue by breyerml** [AdaptiveCpp/AdaptiveCpp#1435]
**Bug summary**
If fast-math is enabled, the JIT compilation (on an NVIDIA GPU) fails when using `std::pow` inside `std::for_each` with:
```
fatal error: error in backend: Undefined external symbol "__powidf2"
[AdaptiveCpp Error] from adaptivecpp/source/include/hipSYCL/glue/llvm-sscp/jit.hpp:265 @ compile(): jit::compile: Encountered errors:
0: LLVMToPtx: clang invocation failed with exit code 70
```
The same also happens with `std::exp`:
```
fatal error: error in backend: Undefined external symbol "exp"
[AdaptiveCpp Error] adaptivecpp/source/include/hipSYCL/glue/llvm-sscp/jit.hpp:265 @ compile(): jit::compile: Encountered errors:
0: LLVMToPtx: clang invocation failed with exit code 70
```

**To Reproduce**
Compile a code snippet using C++ standard parallelism on an NVIDIA GPU with AdaptiveCpp v24.02.0

**Expected behavior**
JIT compilation should not fail.

**Comment by illuhad** [comment]
We should also look into supporting the functions here: https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html which is where the mentioned `__powidf2` is listed.

Not sure though why these are specifically emitted with fast-math, seems as this is more related to emulating functions without hardware support.
