### ISSUE TITLE
Typo in error report

### ISSUE THREAD

**Issue by keldu** [AdaptiveCpp/AdaptiveCpp#1463]
**Bug summary**

Just stumbled upon a minor typo. I almost feel silly reporting this. And I kinda don't want to appear in AdaptiveCpp as an author with just this typo fix.
Also I didn't find this in any other issue. Only searched in commit `d57b9f5879c620cf5b13a3842337715f9e8015e6` (currently develop) for the typo and found it here.  

> include/hipSYCL/glue/error.hpp:52:        << "hipSYCL has caught the following undhandled asynchronous errors: "

**To Reproduce**
Nothing to reproduce

**Expected behavior**

Printing `unhandled` instead of `undhandled`. One `d` over the expected amount of `d`'s. Namely two.

**Comment by illuhad** [comment]
Thanks! You know, we are so generous, we currently have a "buy 1 letter, get 1 free" offer ;) Should be fixed in #1464

>  And I kinda don't want to appear in AdaptiveCpp as an author with just this typo fix.

Feel free to submit more involved PRs ;)
