### ISSUE TITLE
Compatibility issue with latest Microsoft C++ Library on Windows

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1469]
Hello. Thank you again for amazing SYCL implementation!

Recently I was using VS 17.8.3 with MSVC 14.38.33130. AdaptiveCpp was compiled using LLVM v17.0.4, and all worked just fine.
However, I decided to update VS to the latest 17.10.1 with MSVC 14.40.33807. After this AdaptiveCpp stopped to compile programs, targeted OpenMP.

Specifically, I got a lot of error messages like this:

```
 In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\chrono:25:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\format(3204,54): error GBC023BAB: capturing a structured binding is not yet supported in OpenMP
   3204 |         return _STD _Widen_and_copy<_CharT>(_Buffer, _End, _STD move(_Out));
```

I suppose the problem is in updated C++ library?

The thing I tried to do the first was recompiling LLVM, boost and AdaptiveCpp with this new MS C++ library, but this didn't help.

After some search I found this bugreport: https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg69040.html
Then I tried the godbolt code by the link on that page, and discovered that there is no such error when using LLVM 19 trunk.

Then I tried to build LLVM 19.0.0git, boost, and AdaptiveCpp, but got a lot of errors. I suppose AdaptiveCpp is not guaranteed to be built with pre-release versions of LLVM?

So, the only solution which worked was reverting VS to 17.8.3. On this version, I also tried to build LLVM 18.1.6 and AdaptiveCpp, and can confirm that this combination works on Windows.

However, I am wondering if there is a way to make AdaptiveCpp to work with the latest MS C++ library?

Thanks.

**Comment by nilsfriess** [comment]
I'm afraid there's not a lot we can do here (as you've already observed). It seems that MSVC started to use structured bindings somewhere which are not yet supported in Clang OpenMP. The reason that the small godbolt example works with clang 19 seems to be [this PR](
https://github.com/llvm/llvm-project/pull/80216), so it's actually still not implemented, but clang now only shows the diagnostic if you're actually using the structured binding inside a `#pragma omp parallel` or similar.

So this will probably work as soon as AdaptiveCpp can be compiled with LLVM 19 (which we don't test yet since we generally only test with released LLVM versions).

**Comment by blinkfrog** [comment]
> So this will probably work as soon as AdaptiveCpp can be compiled with LLVM 19 (which we don't test yet since we generally only test with released LLVM versions).

Thank you very much. I won't close this issue yet then and will close it after I confirm that this issue is solved (likely after AdaptiveCpp can be compiled with LLVM 19).

**Comment by blinkfrog** [comment]
So, now that we have a stable LLVM 19, I tried to build it and AdaptiveCpp. It worked, although AdaptiveCpp wasn't able to find HIP (I'll look into this problem later), and, strangely, `acpp-clang.dll` was installed to `lib` subdirectory instead of `bin`.

Still, code doesn't compile. Now I don't get those structured bindings-related errors (but, probably, compiler simply stops earlier), but get other errors like this:

```
GC266E94E	non-const lvalue reference to type '__builtin_va_list' cannot bind to a value of unrelated type 'va_list' (aka 'char *')	D:\source\repos\G2\G2.cpp\G.SYCL\out\build\x64-Release\G.SYCL	C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wstdio.h	486		
```

This is a bit frustrating, because this means that I still can't use updated Visual Studio/MSVC and must stick with 7-months old version.

Does somebody have success with the latest MSVC and Clang/AdaptiveCpp?

P. S. I've noticed this exciting PR: https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1609, and I certainly will test it, but I afraid that it won't solve the problem of compatibility of Clang/AdaptiveCpp with updated VS.

**Comment by fodinabor** [comment]
Meh.. seems like MS-STL and LLVM just don't care enough... :/
btw. there's this fun issue about things MS-STL is already working around: https://github.com/microsoft/STL/issues/4413
But as far as I can tell LLVM still isn't part of MS-STL's CI either.. so no wonder..

And yes, #1609 will most likely not change much about these kinds of issues.. 🤔 
A few clang CUDA specific issues can be worked around thanks to the `generic` workflow though...
Btw. I didn't test this with HIP, as I don't have that set up at all..

> acpp-clang.dll was installed to lib subdirectory instead of bin.

I wonder if this change was the source for this? https://github.com/AdaptiveCpp/AdaptiveCpp/commit/9c07a78445794e7b38f3da15fdbafebb7387368b

**Comment by blinkfrog** [comment]
I've tried to compile simpler test code, and it compiles just fine. This is great news, meaning that new Clang still can work with updated VS. Probably, it is something in my bigger project that triggers this problem. I just need to find a way to localize it. Anyway, even if I find it, it would be better to report to llvm-project. AdaptiveCpp per se is fine, and this is great.

So, I am closing this issue now.
