### ISSUE TITLE
Runtime issues with Atomics using 'generic' compilation flow. 

### ISSUE THREAD

**Issue by HariAbram** [AdaptiveCpp/AdaptiveCpp#1500]
I compiled a SYCL code with the `atomic_ref` method. It compiled without a issue, but I am getting the following runtime error. Is my workflow flow broken? or are the atomics yet to be implemented in SSCP compilation? 

```
[AdaptiveCpp Error] from /home/hari.abram/Intel_Xeon_9468/AdaptiveCpp-24.02.0-ocl/src/runtime/ocl/ocl_queue.cpp:513 @ submit_sscp_kernel_from_code_object(): ocl_queue: Code object construction failed
RequiresExtension: Feature requires the following SPIR-V extension:
 SPV_EXT_shader_atomic_float_add
[AdaptiveCpp Error] from /home/hari.abram/Intel_Xeon_9468/AdaptiveCpp-24.02.0-ocl/include/hipSYCL/glue/llvm-sscp/jit.hpp:265 @ compile(): jit::compile: Encountered errors:
0: LLVMToSpirv: llvm-spirv invocation failed with exit code 19
```

**Comment by illuhad** [comment]
No, atomics are fully implemented in the generic JIT compiler. However, the atomic support provided by the core OpenCL and SPIR-V specification is limited. For native atomics on float types, the SPIR-V extension that is mentioned in the error message is required.

Intel OpenCL supports this extension; so recently #1488 was merged, which automatically enables those (and similar) extensions when targeting the Intel OpenCL runtimes for CPU and GPU. So if you update AdaptiveCpp, it should just work.

**Comment by HariAbram** [comment]
Yes, the merge #1488 worked for me. Thanks for the help.
