### ISSUE TITLE
Inconsistent order of evaluation in `sycl::float2` constructor across different devices

### ISSUE THREAD

**Issue by blinkfrog** [AdaptiveCpp/AdaptiveCpp#1511]
**Bug summary**

There appears to be an inconsistency in the order of evaluation when using `sycl::float2` constructor with function calls as arguments across different compute devices (CPU and GPU). When initializing `sycl::float2` directly with consecutive calls to a generator function, the order of `x` and `y` components gets reversed on CPU device (tested with both "omp.library-only" and "omp.accelerated" targets) compared to GPU (tested with "cuda:sm_86" target).

**To Reproduce**

Reproducer:

```
#include <sycl/sycl.hpp>
#include <iostream>

class float_generator
{
private:
    float state = 0.0f;
public:
    float_generator() {}
    float next()
	{
        float result = state;
        state += 1.0f;
        return result;
    }
};

int main() {
    sycl::queue q(sycl::cpu_selector_v);

    sycl::buffer<sycl::float2, 1> position_buffer(sycl::range<1>(1));

    q.submit([&](sycl::handler& cgh)
    {
        sycl::accessor position(position_buffer, cgh, sycl::write_only);
        cgh.single_task([=]
        {
            float_generator gen;
            position[0] = sycl::float2(gen.next(), gen.next());
            //float x = gen.next();
            //float y = gen.next();
            //position[0] = sycl::float2(x, y);
        });
    });
    {
        sycl::host_accessor position(position_buffer, sycl::read_only);
        std::cout << "Position X: " << position[0].x() << ", Position Y: " << position[0].y() << std::endl;
    }

    return 0;
}
```

**Expected behavior**

The output should consistently be:
```
Position X: 0, Position Y: 1
```
on all devices, indicating that the first call to gen.next() initializes x and the second call initializes y.

**Actual behavior**

On GPU device (`cuda:sm_86` target):
```
Position X: 0, Position Y: 1
```
On CPU device (omp.library-only and omp.accelerated targets):
```
Position X: 1, Position Y: 0
```

**Describe your setup**

clang version 17.0.4 

AdaptiveCpp commit 57773099de9f6a27fe544b94dd2fb2bc5db460fc (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 3d794731 05963c5f
Author: Aksel Alpay <aksel.alpay@uni-heidelberg.de>
Date:   Fri Mar 15 01:39:19 2024 +0100

OS: Windows 11

**Additional context**

When I use a workaround (currently commented out lines of code) by storing the results of gen.next() into temporary variables before constructing sycl::float2, the outputs are consistent across all devices.

**Comment by illuhad** [comment]
I cannot reproduce this:

```
$ ACPP_VISIBILITY_MASK="omp" ./test
[AdaptiveCpp Warning] dag_direct_scheduler: Detected a requirement that is neither of discard access mode (SYCL 1.2.1) nor no_init property (SYCL 2020) that accesses uninitialized data. Consider changing to discard/no_init. Optimizing potential data transfers away.
Position X: 0, Position Y: 1
$ ACPP_VISIBILITY_MASK="omp;cuda" ./test
[AdaptiveCpp Warning] dag_direct_scheduler: Detected a requirement that is neither of discard access mode (SYCL 1.2.1) nor no_init property (SYCL 2020) that accesses uninitialized data. Consider changing to discard/no_init. Optimizing potential data transfers away.
Position X: 0, Position Y: 1
```

compiled with `--acpp-targets="omp;cuda:sm_86"`. Is this on Windows? There is no branching between CPU or GPU targets that could explain this, so my best guess is that LLVM miscompiles your code. Can you try a different LLVM version, either older or newer?

**Comment by illuhad** [comment]
Looking closer at your code, the result depends on the order in which the function parameters are evaluated. In C++ this is in general undefined: https://en.cppreference.com/w/cpp/language/eval_order

So the result is just not well-defined.

**Comment by blinkfrog** [comment]
Thank you very much, this is a good explanation.
