### ISSUE TITLE
Regression around reductions on instant-submission

### ISSUE THREAD

**Issue by fknorr** [AdaptiveCpp/AdaptiveCpp#1525]
e8717464 / #1507 introduces a regression around reductions on in-order queues when instant submission is active.

Found via bisecting AdaptiveCpp, it reliably causes Celerity test suite to fail. Creating a minimal reproducer turned out to be somewhat difficult, the following sometimes reproduces the error, but not very reliably. On my machine it appears to only trigger on the first run (CUDA device image cache miss?), so after one run the parameter to `combine()` has to be changed to make it trigger repeatedly.

Reproducer:
```c++
sycl::queue q(sycl::gpu_selector_v, sycl::property::queue::in_order{});
const auto buf = sycl::malloc_device<int>(1, q);
q.parallel_for(sycl::range(32), sycl::reduction(buf, sycl::plus<int>{},
	sycl::property::reduction::initialize_to_identity{}), [](auto, auto& r) { r.combine(1); });
auto e = q.parallel_for(sycl::range(32), [](auto){});
e.wait();
sycl::free(buf, q);
```
Build with
```
-DHIPSYCL_ALLOW_INSTANT_SUBMISSION=1 -DHIPSYCL_TARGETS=cuda:sm_75
```

Output:
```
[AdaptiveCpp Error] from /software-local/fabian/code/hipSYCL/src/runtime/cuda/cuda_event.cpp:46 @ wait(): cuda_node_event: cudaEventSynchronize() failed (error code = CUDA:700)
[AdaptiveCpp Error] from /software-local/fabian/code/hipSYCL/src/runtime/cuda/cuda_queue.cpp:201 @ ~cuda_queue(): cuda_queue: Couldn't destroy stream (error code = CUDA:700)
[AdaptiveCpp Error] from /software-local/fabian/code/hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:41 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:700)
[AdaptiveCpp Error] from /software-local/fabian/code/hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:41 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:700)
```

Acpp was built with:
```
-DWITH_CUDA_BACKEND=YES -DWITH_OPENCL_BACKEND=NO -DWITH_SSCP_COMPILER=NO
```

System: 4x RTX 2070, Linux 5.15 x86_64, CUDA 12.5, Clang 17

**Comment by illuhad** [comment]
I think this is because reductions actually cannot currently run via instant submission mode. So the real culprit is likely the interaction between non-instant and instant submitted tasks.

> CUDA device image cache miss?

There is no device image cache for `--acpp-targets=cuda`, it's AOT compilation. If you use it you're running in slow mode ;) It's probably just a timing issue due to drivers already loaded etc.
