### ISSUE TITLE
acpp compilation issue 

### ISSUE THREAD

**Issue by aideveloperme** [AdaptiveCpp/AdaptiveCpp#1547]
**Bug summary**
An error while compiling the sycl code using adaptivecpp compiler that optional file not found. i built clang along with gcc-12.2 version. 
this is centOS 7, and gcc 4.8, but i have compiled and built clang, cmake, python3.10, and adaptivecpp with gcc-12.2 version i have not used gcc 4.8.

acpp sycl_matrixmul.cpp -g -O3 --acpp-targets="cuda:sm_60"  -I/home/gcc/include/:/home/adaptivecpp/build/include/AdaptiveCpp/ -L/home/gcc/lib64/:/home/adaptivecpp/build/lib/hisSYCL/
clang++: warning: CUDA version is newer than the latest supported version 12.3 [-Wunknown-cuda-version]
In file included from sycl_matrixmul.cpp:1:
In file included from /home/adaptivecpp/build/bin/../include/AdaptiveCpp/CL/sycl.hpp:14:
In file included from /home/adaptivecpp/build/bin/../include/AdaptiveCpp/CL/../hipSYCL/sycl/sycl.hpp:30:
In file included from /home/adaptivecpp/build/bin/../include/AdaptiveCpp/hipSYCL/glue/persistent_runtime.hpp:15:
In file included from /home/adaptivecpp/build/bin/../include/AdaptiveCpp/hipSYCL/runtime/application.hpp:18:
/home/adaptivecpp/build/bin/../include/AdaptiveCpp/hipSYCL/runtime/settings.hpp:17:10: fatal error: 'optional' file not found
   17 | #include <optional>
      |          ^~~~~~~~~~
1 error generated when compiling for sm_70.

clang -v /dev/null
clang version 18.1.8
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/llvm/clang/llvm-omp-build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /home/cuda-12.5, version
 "/usr/bin/ld" --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -pie -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a                                                                  .out /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/Scrt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../..                                                                  /../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbeginS.o -L/home/llvm/clang/llvm-omp-build/li                                                                  b/clang/18/lib/x86_64-unknown-linux-gnu -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linu                                                                  x/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib /dev/null -lgcc --as-needed -lgcc_                                                                  s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtendS.o /us                                                                  r/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/dev/null: file not recognized: File truncated
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Expected behavior**
sycl Compilation using acpp,on CPU and NVIDIA GPU 

**Describe your setup**
CUDA-VERSION -12.5 
clang  version -18 
cmake- 3.31
gcc -12.2 
python-3.10
acpp dir- https://github.com/AdaptiveCpp/AdaptiveCpp/archive/refs/heads/develop.zip

**Comment by al42and** [comment]
Can you try adding `--gcc-toolchain=/home/user1/gcc12/` to your `acpp` call?

While you have built ACpp itself with GCC12, when you call `acpp` it runs the Clang compiler internally, which defaults to the system-installed GCC standard library. The flag I'm suggesting should point it to the newer standard library.

**Comment by aideveloperme** [comment]
acpp sample.cpp -g -O3 --acpp-targets="cuda:sm_70"  --gcc-toolchain=/home/user1/gcc12/
clang++: warning: CUDA version is newer than the latest supported version 12.3 [-Wunknown-cuda-version]
/home/usr1/boost/lib/libboost_fiber.so: undefined reference to `std::ios_base_library_init()@GLIBCXX_3.4.32'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
I tried with –cuda-path 
 acpp sample.cpp -g -O3 --acpp-targets="cuda:sm_70"  --gcc-toolchain=/home/user1/gcc12/ --cuda-path=/home/user1cuda-12.5
clang++: error: cannot find libdevice for sm_70; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
clang++: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
clang++: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes


i think i have to make sure that boost library  built along with gcc12 , and the rebuilt acpp with boost library again ?

**Comment by al42and** [comment]
> i think i have to make sure that boost library built along with gcc12 , and the rebuilt acpp with boost library again ?

Yes, I'd try that.

>  clang++: error: cannot find libdevice for sm_70; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice

I think you're missing `/` in your `--cuda-path`, should be `--cuda-path=/home/user1/cuda-12.5`.

**Comment by nilsfriess** [comment]
> acpp sample.cpp -g -O3 --acpp-targets="cuda:sm_70" --gcc-toolchain=/home/user1/gcc12/ --cuda-path=/home/user1cuda-12.5

There is a `/` missing in your CUDA path.

And regarding the other error: can you first try if compiling and linking a simple program works with plain clang?

Edit: @al42and beat me to it

**Comment by illuhad** [comment]
This kind of issue is described in detail in the documentation. Note that `--gcc-toolchain` can be very picky and may silently ignore values passed to it if the path is not the right one. Use clang config files to make the flag permanent.

Documentation: https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/install-llvm.md#gcc-toolchainc-standard-library-is-in-a-non-standard-location

In any case, this is not an AdaptiveCpp issue.

> acpp sample.cpp -g -O3 --acpp-targets="cuda:sm_70"

I strongly recommend using `--acpp-target=generic` (which is usually the default setting anyway, so you can omit the `--acpp-targets` flag entirely). `--acpp-targets=generic` uses our generic JIT compiler which compiles faster and typically produces faster binaries than the `--acpp-targets=cuda`. `--acpp-targets=cuda` should only be used for very specific use cases as described in the documentation:

https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/performance.md#use-the-right-compilation-flow-generic-is-typically-fastest

**Comment by aideveloperme** [comment]
error is resolved  by  install boost library along with gcc12 , and the rebuilt acpp. 
Thank you for the support
