### ISSUE TITLE
KnownGroupSizeOptPass.cpp:48:28: error: invalid use of incomplete type 'class llvm::Module with llvm 19

### ISSUE THREAD

**Issue by Thomas-Ulrich** [AdaptiveCpp/AdaptiveCpp#1576]
**Bug summary**
adaptive cpp 24.06 does not compile with llvm19
**To Reproduce**
See issue at:
https://github.com/spack/spack/issues/46681

**Comment by fodinabor** [comment]
https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1550
Support for LLVM 19 was merged in August, i.e. after 24.06 (and therefore also 24.02) was released. You'd have to use develop. Not sure if spack supports that?

**Comment by Thomas-Ulrich** [comment]
yes you can specify hipsycl@develop, thank you!
