### ISSUE TITLE
clang-tidy issue since #1599 merge

### ISSUE THREAD

**Issue by tdavidcl** [AdaptiveCpp/AdaptiveCpp#1605]
Hi, 
clang-tidy raise some error since the merge of #1599

In a Ubuntu 20 docker image (even though the actual version is irrelevant i think to this case)
```bash
docker run --rm -it --entrypoint bash ghcr.io/shamrock-code/ci-ubuntu20:main
```

clang tidy on a cpp file having just a single include to sycl/sycl.hpp create the following error : 
```
root@885939f463c4:/home/docker# clang-tidy-17 main.cpp  -- -Iacpp/include/AdaptiveCpp
1 warning and 1 error generated.
Error while processing /home/docker/main.cpp.
acpp/include/AdaptiveCpp/hipSYCL/algorithms/util/memory_streaming.hpp:64:27: error: expected namespace name [clang-diagnostic-error]
   64 |     namespace jit = sycl::AdaptiveCpp_jit;
      |                     ~~~~~~^
Suppressed 1 warnings (1 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
```

The following commands create a clang-tidy error :
```bash
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 17
sudo apt install -y libclang-17-dev clang-tools-17 libomp-17-dev clang-tidy-17

git clone https://github.com/AdaptiveCpp/AdaptiveCpp.git
cmake -G Ninja -S AdaptiveCpp -B AdaptiveCpp/build -DCMAKE_INSTALL_PREFIX=acpp
cd AdaptiveCpp/build
ninja && ninja install
cd ../..

printf "#include<sycl/sycl.hpp>\nint main(){}" > main.cpp
clang-tidy-17 main.cpp  -- -Iacpp/include/AdaptiveCpp
```

Additionally the error can be traced to that specific commit : 
`c07b5023c8c9b7937a29b3b2b2ac754297ed4f18`

**Comment by illuhad** [comment]
> clang-tidy-17 main.cpp  -- -Iacpp/include/AdaptiveCpp

This probably does not result in the same include order that `acpp` uses.  `acpp` e.g. uses `-isystem` which can result in a different include order. The problematic file `memory_streaming.hpp` also would never be included without `--acpp-stdpar`.
Can you check which include statements `acpp main.cpp --acpp-dryrun` prints, and then try aligning clang tidy with that?

Obviously, if there were an issue with that namespace not being available at the point of use, our stdpar tests wouldn't compile (which they do).

EDIT: Independently, the error might also be fixed on the AdaptiveCpp side by adding `#include "hipSYCL/sycl/jit.hpp"` to `memory_streaming.hpp`.

**Comment by tdavidcl** [comment]
Yeah was testing with an additional include to hipSYCL/sycl/jit.hpp and it fixes the issue. But indeed copying flags from acpp dryrun also remove the error:
```
root@885939f463c4:/home/docker# acpp/bin/acpp main.cpp --acpp-dryrun
acpp warning: No optimization flag was given, optimizations are disabled by default. Performance may be degraded. Compile with e.g. -O2/-O3 to enable optimizations.
/usr/lib/llvm-17/bin/clang++ -isystem /home/docker/acpp/bin/../include/AdaptiveCpp -D__OPENSYCL__ -D__HIPSYCL__ -D__ADAPTIVECPP__ -D__ACPP__ -std=c++17 -D__ACPP_ENABLE_LLVM_SSCP_TARGET__ -Xclang -disable-O0-optnone -mllvm -acpp-sscp -fplugin=/home/docker/acpp/bin/../lib/libacpp-clang.so -fpass-plugin=/home/docker/acpp/bin/../lib/libacpp-clang.so main.cpp -L/home/docker/acpp/bin/../lib/ -lacpp-rt -Wl,-rpath=/home/docker/acpp/bin/../lib/
root@885939f463c4:/home/docker# clang-tidy-17 main.cpp  -- -isystem /home/docker/acpp/bin/../include/AdaptiveCpp -D__OPENSYCL__ -D__HIPSYCL__ -D__ADAPTIVECPP__ -D__ACPP__ -std=c++17 -D__ACPP_ENABLE_LLVM_SSCP_TARGET__
<no ouput and no errors>
```

**Comment by illuhad** [comment]
Ok, then let's be throrough, I'll fix the AdaptiveCpp header and you can fix your clang-tidy invocation to reflect what `acpp` does :P

**Comment by tdavidcl** [comment]
Yeah, also it would be neat if there is a way to export include & define flags from acpp for tools such as clang-tidy or others

**Comment by illuhad** [comment]
Hm, yeah, I can see that such a feature could be useful. What would you need in addition to what is already possible with `acpp --acpp-dryrun dummy.cpp` ?

**Comment by tdavidcl** [comment]
well i was thinking of removing argument such as `-acpp-sscp`, `-fplugin`, ... and only keep Include and defines.
For clang-tidy those might me ok (altought i get some warnings) but i don't know for clangd ...

**Comment by tdavidcl** [comment]
For now i'm trying to rebuild a `compile_commands.json` from the results of `--acpp-dryrun`, clang-tidy works without errors, however it complains about the `-fplugin` and `-fpass-plugin` flags. 
Just by removing those two clang-tidy works like a charm, so i would propose the addition of a `--acpp-dry-run-no-plugin` flag that does the same as `--acpp-dryrun` but remove the `-fplugin` and `-fpass-plugin` flags from the output.

See #1607
