### ISSUE TITLE
Question Regarding the Speedup Ratio of stdpar on GPU vs. CPU

### ISSUE THREAD

**Issue by Ehu1** [AdaptiveCpp/AdaptiveCpp#1637]
I've noticed that nvc++ claims their stdpar implementation in LULESH can achieve a speedup of 6 to 7 times when running on a GPU. However, on my device, whether using nvc++ or acpp, the performance of the stdpar implementation in LULESH is roughly the same when running on a CPU versus a GPU. While I understand that performance can vary depending on the hardware, obtaining such significantly different results is surprising.

Given that I know you have conducted tests on the stdpar implementation in LULESH, I would like to inquire about the approximate speedup ratio you observed between CPU and GPU execution times when using acpp. I previously read your papers, but they seem to provide only comparative analyses without the specific answers I'm looking for.

<img width="728" alt="image" src="https://github.com/user-attachments/assets/f98c3a42-3840-4dd5-9031-b5e6f78d79f2">

**Comment by illuhad** [comment]
The left image in figure 3 of my paper answers your question: https://dl.acm.org/doi/pdf/10.1145/3648115.3648117
AdaptiveCpp achieves a speedup for LULESH of around up to 15x compared to CPU on A100, outperforming nvc++.

However, this is highly dependent on the host performace, interconnect (offloading latency and data transfer time) and GPU. If you have a weaker GPU, it is quite possible that you end up with similar performance than host - or even below it. I observed this on an old notebook GPU.

It also depends on the quality of host PSTL. The normal libstdc++ is not particularly efficient, especially when running on systems with multiple NUMA nodes.

The problem size for LULESH also matters a lot. If the problem size is too small, it's not worth offloading.

**Comment by Ehu1** [comment]
Got it, I have understood the situation. And I sincerely thank you for responding to my questions multiple times; your assistance has been of great help to me.

**Comment by illuhad** [comment]
No problem! :)
