### ISSUE TITLE
safer patterns in install scripts - part 1

### ISSUE THREAD

**Issue by jeffhammond** [AdaptiveCpp/AdaptiveCpp#333]
I am of the view that `rm -rf`-ing something in a user's home directory is not an appropriate thing to do without explicit confirmation.

A better pattern would be to check for the existence of the directory and only use it if it does not already exist.

https://github.com/illuhad/hipSYCL/blob/develop/install/scripts/install-llvm.sh
```sh
set -e
BUILD_DIR=$HOME/git/llvm-vanilla
rm -rf $BUILD_DIR

echo "Cloning LLVM $HIPSYCL_PKG_LLVM_REPO_BRANCH"
git clone -b $HIPSYCL_PKG_LLVM_REPO_BRANCH https://github.com/llvm/llvm-project $BUILD_DIR
```

**Comment by jeffhammond** [comment]
The script should also look to see what is in the directory `llvm-vanilla` and not remove it if it's already populated.  I just spend 10 minutes cloning the repo only to see an error in the CMake phase, and the script is starting over from scratch instead of starting where it left off.

**Comment by illuhad** [comment]
Thanks @jeffhammond, that makes sense. @sbalint98 Can you have a look?
