### ISSUE TITLE
safer patterns in install scripts - part 2

### ISSUE THREAD

**Issue by jeffhammond** [AdaptiveCpp/AdaptiveCpp#334]
hipSYCL install scripts use `BUILD_DIR` and `INSTALL_PREFIX`, which default to `/opt/hipsycl`.  On machines where that directory isn't writeable, I'd like to be able to define a global environment variable where stuff should go, but I don't want to give these particular variables global scope because other code might use them.

It would be ideal if all hipSYCL environment variables like this were named `HIPSYCL_*`.

**Comment by illuhad** [comment]
Agreed. @sbalint98 can you please also look into this?

**Comment by sbalint98** [comment]
sure I will have a look

**Comment by jeffhammond** [comment]
I haven't reverse engineered the problem yet but the scripts are now targeting `/usr/local` despite my best efforts to the contrary.

**Comment by sbalint98** [comment]
Ah well, sorry, I will look into it
