### ISSUE TITLE
CUDA: Alignment mismatch between emulated and native vector types causes hard to debug errors

### ISSUE THREAD

**Issue by psalz** [AdaptiveCpp/AdaptiveCpp#346]
It seems that CUDA's `::float2` has an alignment of 8, while hipSYCL's `emulated_vector`, which is used on the host, has an alignment of 4. Obviously that's not good, and causes some very weird looking and hard to debug problems - see below. I'll mostly just dump the repro case here as I think it's quite self-explanatory:

```cpp
#include <CL/sycl.hpp>

namespace sycl = cl::sycl;

namespace foosycl {

struct emulated_float2 { float x; float y; };

// Fix:
// struct alignas(8) emulated_float2 { float x; float y; };
//
// #ifdef SYCL_DEVICE_ONLY
// static_assert(alignof(emulated_float2) == alignof(::float2));
// #endif

struct float2 {
  HIPSYCL_UNIVERSAL_TARGET
  float2(const float& x, const float& y) { data.x = x; data.y = y; }
  HIPSYCL_UNIVERSAL_TARGET float& x() { return data.x; }
  HIPSYCL_UNIVERSAL_TARGET float x() const { return data.x; }
  HIPSYCL_UNIVERSAL_TARGET float& y() { return data.y; }
  HIPSYCL_UNIVERSAL_TARGET float y() const { return data.y; }

#ifdef SYCL_DEVICE_ONLY
  ::float2 data;
#else
  emulated_float2 data;
#endif
};

}

int main(int argc, char* argv[]) {
    sycl::queue queue;

    //using float2_t = sycl::float2;
    using float2_t = foosycl::float2;

    float2_t vec = {42.f, 1337.f};

    printf("vec on host: %f,%f\n", vec.x(), vec.y());

    queue.submit([&](sycl::handler& cgh) {
        cgh.single_task<class buggy>([=, a = 9.f]() {
            printf("a in buggy kernel: %f\n", a);
            printf("vec in buggy kernel: %f,%f\n", vec.x(), vec.y());
        });
    });

    queue.submit([&](sycl::handler& cgh) {
        cgh.single_task<class worky>([=]() {
            printf("vec in worky kernel: %f,%f\n", vec.x(), vec.y());

            printf("sizeof(::float2) = %lu\n", sizeof(::float2));
            printf("sizeof(emulated_float2) = %lu\n", sizeof(foosycl::emulated_float2));
            printf("alignof(::float2) = %lu\n", alignof(::float2));
            printf("alignof(emulated_float2) = %lu\n", alignof(foosycl::emulated_float2));
        });

    queue.wait_and_throw();

    return EXIT_FAILURE;
}
```

I'm using `foosycl::float2` and `foosycl::emulated_float2` here, but these are just the result of reducing about 5000 lines of hipSYCL headers down to their essence. You can switch `float2_t` to `sycl::float2` to see that this error is reproducible with the original type as well.

As suggested in the code, a potential fix could be to set the alignment explicitly (this may need adjustment per backend), and to assert that the alignments (as well as the size) match during device compilation.

**Comment by psalz** [comment]
Ah, I should probably give you the output as well ;-)

```
vec on host: 42.000000,1337.000000
a in buggy kernel: 9.000000
vec in buggy kernel: 1337.000000,0.000000
vec in worky kernel: 42.000000,1337.000000
sizeof(::float2) = 8
sizeof(emulated_float2) = 8
alignof(::float2) = 8
alignof(emulated_float2) = 4
```

**Comment by illuhad** [comment]
Ah, the `vec` class, the most ridiculously complex class in all of the SYCL interface :)

I think is fallout from the recent changes that we had to make to have both CPU and CUDA/HIP backends available simultaneously. Previously, there was only one backend active at any given time, so this sort of issue never occured.

As a hotfix, I think we should just `alignas` the `emulated_vector` here: https://github.com/illuhad/hipSYCL/blob/5216d091cf92a3ef4cc119805f484b5c9720be7f/include/hipSYCL/sycl/libkernel/detail/vec.hpp#L81

In the long term, we should probably refactor the `vec` class somewhat to better account for the multi-backend architecture that we now effectively have. Additionally, that class was written in C++14 and could probably be simplified in a lot of places using C++17 - so it definitely needs some love anyway.
