### ISSUE TITLE
syclcc fatal error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by abboomer** [AdaptiveCpp/AdaptiveCpp#353]
I have (AFAIK) successfully built and installed hipSYCL.

### I run this command to compile by demo program:
`syclcc -O2 -o demo demo.cpp`   (the optimization flag is just to suppress the warning otherwise given).

### And receive this error:
`syclcc fatal error: [Errno 13] Permission denied`

I checked the permissions on syclcc, permissions on the working directly, and compiled the same demo program with g++ without problem. I also tried compiling with sudo. Any ideas where the permissions chain is failing?

I'm running Centos 7 with llvm-toolset-9, cuda, gcc 8.3.1

Here's my demo.cpp:
```
#include <iostream>
int main()
{
    std::cout << "Hello world!" << std::endl;
}
```

Here's the contents of the syclcc.json:
```
{
  "default-clang"     : "/opt/rh/llvm-toolset-9.0/root/usr/bin",
  "default-platform"  : "cuda",
  "default-cuda-path" : "/usr/local/cuda",
  "default-gpu-arch"  : "sm_52",
  "default-cpu-cxx"   : "/opt/rh/devtoolset-8/root/usr/bin/g++",
  "default-rocm-path" : "/opt/rocm",
  "default-use-bootstrap-mode" : "false",
  "default-is-dryrun" : "false",
  "default-clang-include-path" : "/opt/rh/llvm-toolset-9.0/root/lib64/clang/9.0.1/include",
  "default-rocm-link-line" : "-rpath /opt/rocm/lib -rpath /opt/rocm/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64",
  "default-cuda-link-line" : "-rpath $HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart"
}
```

**Comment by keryell** [comment]
Start with an `strace -f` to investigate on which system call it is failing.

**Comment by illuhad** [comment]
>   "default-clang"     : "/opt/rh/llvm-toolset-9.0/root/usr/bin",

That's likely the problem. You need to give it a `clang++` that it can execute, not the directory it is in because otherwise it will try to execute the directory...

Such problems can often be diagnosed by passing `--hipsycl-dryun` to `syclcc` in which case it will print the commands it would execute instead of running them.

**Comment by abboomer** [comment]
@illuhad , yes, that was it. I didn't see that. Thank you!
