### ISSUE TITLE
CTAD support for sycl::range

### ISSUE THREAD

**Issue by jeffhammond** [AdaptiveCpp/AdaptiveCpp#363]
I just fixed a PRK issue where `sycl::range x{a,b}` fails as follows but `sycl::range<2> x{a,b}` succeeds.  I think this is a CTAD feature from SYCL 2020 that should be easy to support.

```
/opt/hipSYCL/bin/syclcc-clang -DPRKVERSION="2020" -std=c++17 -O3 -DHIPSYCL --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx900 transpose-sycl.cc -o transpose-sycl
transpose-sycl.cc:61:15: error: no viable constructor or deduction guide for deduction of template arguments of 'range'
  sycl::range global{padded_order,padded_order};
```

**Comment by jeffhammond** [comment]
Specifically https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf page 214:
```
33 // Deduction guides
34 range(size_t) -> range<1>;
35 range(size_t, size_t) -> range<2>;
36 range(size_t, size_t, size_t) -> range<3>;
```

**Comment by illuhad** [comment]
Yes, we are still missing all of the deduction guides (not only for range). See https://github.com/hipSYCL/featuresupport

We need to grep the spec for "deduction guide" and add that stuff in.

**Comment by jeffhammond** [comment]
I will create a new issue devoted to deduction guides.
