### ISSUE TITLE
Repo host is down

### ISSUE THREAD

**Issue by nicholascioli** [AdaptiveCpp/AdaptiveCpp#367]
Any attempt to query the repo host at [http://repo.urz.uni-heidelberg.de/en](http://repo.urz.uni-heidelberg.de/en) responds with a timed out connection.

(I'm using arch, but I believe the issue is with the hosting provider itself)

![2020-11-07-134732_1359x58_scrot](https://user-images.githubusercontent.com/1240491/98450156-f68b3680-20ff-11eb-8385-fd2c5819e437.png)

![2020-11-07-135859_618x329_scrot](https://user-images.githubusercontent.com/1240491/98450327-96958f80-2101-11eb-878f-0df01ebf4e86.png)

![2020-11-07-135949_601x108_scrot](https://user-images.githubusercontent.com/1240491/98450328-9a291680-2101-11eb-8257-4ac18ce38e51.png)

**Comment by illuhad** [comment]
Thanks, I am already aware of this issue. Since today or yesterday it seems certain connections are currently unstable within our university's network. It seems that not only our repos are affected. I hope that it will be fixed soon.

**Comment by illuhad** [comment]
Since yesterday evening the repositories are available again. I apologize for the inconvenience.
