### ISSUE TITLE
What is the status of the 2020 Sycl standard in hipSycl?

### ISSUE THREAD

**Issue by VictorEijkhout** [AdaptiveCpp/AdaptiveCpp#373]
Is hipSycl incorporating the 2020 standard? Has this already been done?

**Comment by illuhad** [comment]
There is no SYCL implementation that has already implemented all of SYCL 2020 (and in fact, the final version of the SYCL 2020 specification is not even released yet).
But yes, hipSYCL has already started moving to SYCL 2020.

See here for more details:
https://github.com/hipSYCL/featuresupport

**Comment by illuhad** [comment]
Please reopen if you would like to discuss more.
