### ISSUE TITLE
Indexing with sycl::id

### ISSUE THREAD

**Issue by VictorEijkhout** [AdaptiveCpp/AdaptiveCpp#397]
I found this example in an Intel tutorial:

```
#include <CL/sycl.hpp>

constexpr int N=16;

using namespace cl;

int main() {
  sycl::queue q;
  int *data = sycl::malloc_shared<int>(N, q);
  q.parallel_for(sycl::range<1>(N), [=](sycl::id<1> i) {
      // data[i] = i;  // ?? Intel extension ??
      data[i[0]] = i[0];
    }).wait();
  for (int i=0; i<N; i++)
    std::cout << data[i] << "\n";
  free(data, q);
  return 0;
}
```

Note the commented-out line. The `data[i]=i` form works on Intel's devcloud. Is this an intel extension?

**Comment by illuhad** [comment]
Yes, they have added an implicit conversion operator for `sycl::id<1>` to `size_t` so that indexing raw pointers with `sycl::id<1>` works. It's not yet in any released SYCL specification, but might still find its way into other implementations as it makes a lot of sense in the context of USM.
