### ISSUE TITLE
Error when compiling for multiple targets

### ISSUE THREAD

**Issue by mrzv** [AdaptiveCpp/AdaptiveCpp#410]
**Bug summary**
A code that compiles with `--hipsycl-targets="omp"` or `--hipsycl-targets="cuda:sm_72"` gives a compiler error with `--hipsycl-targets="cuda:sm_72;omp"`. 

```
$ hipSYCL/stage/bin/syclcc-clang atomic-counter.cpp -o atomic-counter-0.9.0 -O3 --hipsycl-targets="cuda:sm_72;omp"
clang-11: warning: Unknown CUDA version. cuda.h: CUDA_VERSION=11010. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
In file included from <built-in>:1:
In file included from /usr/lib/clang/11.0.0/include/__clang_cuda_runtime_wrapper.h:406:
/usr/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:74:7: error: no matching function for call to '__nv_isnand'
  if (_ISNANd(__real__(z)) && _ISNANd(__imag__(z))) {
      ^~~~~~~
/usr/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:45:17: note: expanded from macro '_ISNANd'
#define _ISNANd __nv_isnand
                ^~~~~~~~~~~
/usr/lib/clang/11.0.0/include/__clang_cuda_libdevice_declares.h:226:16: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE__ int __nv_isnand(double __a);
               ^
In file included from <built-in>:1:
In file included from /usr/lib/clang/11.0.0/include/__clang_cuda_runtime_wrapper.h:406:
/usr/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:74:31: error: no matching function for call to '__nv_isnand'
  if (_ISNANd(__real__(z)) && _ISNANd(__imag__(z))) {
                              ^~~~~~~
/usr/lib/clang/11.0.0/include/__clang_cuda_complex_builtins.h:45:17: note: expanded from macro '_ISNANd'
#define _ISNANd __nv_isnand
                ^~~~~~~~~~~
/usr/lib/clang/11.0.0/include/__clang_cuda_libdevice_declares.h:226:16: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE__ int __nv_isnand(double __a);
               ^
[...]
```

**Describe your setup**
* I cloned the `develop` branch, which currently aligns with `0.9.0` tag
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang 11, system-wide install on Arch
   * CUDA version 11

**Optional additional diagnostic information**
The following information can potentially help us:
* For compilation/toolchain or setup-related issues: Setting the environment variable `HIPSYCL_DRYRUN=1` during compilation will cause `syclcc` to print the commands it would execute instead of actually executing. This can help verify the sanity of your setup.

```
/usr/bin/clang++ -I/home/dmitriy/Projects/SYCL/hipSYCL/stage/bin/../include/ -D__HIPSYCL__ -std=c++17 -x cuda --cuda-path=/opt/cuda -D__HIPSYCL_ENABLE_CUDA_TARGET__ -D__HIPSYCL_CLANG__ -fplugin=/home/dmitriy/Projects/SYCL/hipSYCL/stage/bin/../lib/libhipSYCL_clang.so -U__FLOAT128__ -U__SIZEOF_FLOAT128__ --cuda-gpu-arch=sm_72 -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -I/include -fopenmp atomic-counter.cpp -o atomic-counter-0.9.0 -O3 -Wl,-rpath=/home/dmitriy/Projects/SYCL/hipSYCL/stage/bin/../lib/ -L/home/dmitriy/Projects/SYCL/hipSYCL/stage/bin/../lib/ -lhipSYCL-rt -Wl,-rpath=/opt/cuda/lib64 -L/opt/cuda/lib64 -lcudart -L/lib -lboost_context -lboost_fiber -Wl,-rpath=/lib -fopenmp
```

**Comment by fodinabor** [comment]
Compiling for CUDA and OpenMP is only supported with the unreleased Clang versions 11.0.1 and 12.

Edit: but as this is just a header file issue, you might fix that yourself locally, this is the required diff: https://github.com/llvm/llvm-project/commit/890fdb8031e3ea2b2ede1e8b90c34a8977e38548

**Comment by illuhad** [comment]
Yup, it's a clang bug that is triggered when `-fopenmp` and `-x cuda` is combined. You can already reproduce it with a simple
```
clang++ -x cuda --cuda-path=... --cuda-gpu-arch=... -fopenmp /dev/null
```

So, not an hipSYCL issue. As @fodinabor points out, this was only resolved in very recent clang versions (or you need to apply the patch yourself).

**Comment by mrzv** [comment]
Ah, brilliant. Thanks for clarifying this so quickly. I think I can force a newer version of clang under spack, and I'm sure Arch will update to the newer version in no time.

**Comment by mrzv** [comment]
I'm back to this issue. The code compiles with LLVM 11.0.1, for both backends. When I list the backends, I get:
```
Devices:
  0: GeForce RTX 2080 Ti
  1: hipSYCL OpenMP host device
```

Running with the device 0 works great, but when I run with OpenMP, I get an error:
```
simple: /home/dmitriy/Projects/SYCL/hipSYCL/stage/bin/../include/hipSYCL/glue/cuda/../generic/hiplike/hiplike_kernel_launcher.hpp:481: virtual hipsycl::glue::hiplike_kernel_launcher<hipsycl::rt::backend_id::cuda, hipsycl::rt::cuda_queue>::~hiplike_kernel_launcher() [Backend_id = hipsycl::rt::backend_id::cuda, Queue_type = hipsycl::rt::cuda_queue]: Assertion `_queue' failed.
```

I can't seem to boil the problem down to a simple example — the actual code is somewhat involved — but is there anything obvious that this could be?

**Comment by mrzv** [comment]
Mea culpa. I was on an outdated version of the code (0.9.0, I think). Pulling the latest `develop` fixed the problem.
