### ISSUE TITLE
[MacOS] clang-11: error: argument to '-Xclang' is missing (expected 1 value) 

### ISSUE THREAD

**Issue by jeffhammond** [AdaptiveCpp/AdaptiveCpp#419]
**Bug summary**

I am trying to use hipSYCL for CPU execution on MacOS.  I followed the recipe in .github/workflows/macos.yml but couldn't get it to work.  If other steps are required, it would nice to document them.
```
dpcpp-tutorial $ make -f Makefile.hipsycl 
./hipSYCL/bin/syclcc-clang -O3 -std=c++17 -ferror-limit=3 --hipsycl-platform=cpu --hipsycl-cpu-cxx=/usr/local/Cellar/llvm/11.0.0/bin/clang++ saxpy.cc -o saxpy.x
Could not open config ./hipSYCL/etc/hipSYCL/syclcc.json
clang-11: error: argument to '-Xclang' is missing (expected 1 value)
make: *** [saxpy.x] Error 1
```

**To Reproduce**

  1. Buy a MacOS computer
  2. Install Homebrew
  3. Brew LLVM 11.0
  4. Run this:
```
git clone https://github.com/jeffhammond/dpcpp-tutorial
cd dpcpp-tutorial
./setup-hipSYCL.sh
make -f Makefile.hipsycl
```

_If possible, provide a minimal reproducer_. The shorter the reproducing code snippet is, the easier will it be for us to debug and understand the issue.

**Expected behavior**

I would like to not need to deal with `-Xclang`, which seems unnecessary anyways, since disabling it in hipSYCL/bin/syclcc-clang allows things to fail elsewhere.

**Describe your setup**

* MacOS 10.14.6 (Mojave)
* Homebrew (latest)

**Comment by illuhad** [comment]
Can you provide the output of this compiler invocation with `--hipsycl-dryrun`? `syclcc` will then tell us the exact clang command it tries to execute.

EDIT: I think the Mac OS github workflow only tests building hipSYCL, not actually compiling something with it. It might be that there's a bug.

EDIT2: This here does not seem correct to me and should be removed: https://github.com/illuhad/hipSYCL/blob/ef204be61993a33340c8891c35b795f1aa862390/bin/syclcc-clang#L650
(same for the second occurence of -Xclang)
I think then you would need to change your `OMP_LINK_LINE` and `OMP_CXX_FLAGS` to `-Xclang -fopenmp` instead of `-fopenmp` (i.e. cmake -DOMP_LINK_LINE=... or edit the resulting `syclcc.json`)

**Comment by jeffhammond** [comment]
Yeah, I'm seeing a bunch of issues, some of which I am in the process of fixing.  Give me a second to post details.

**Comment by jeffhammond** [comment]
You are correct about `flags += ["-Xclang"]` being incorrect.  Removing that mitigates this issue.

**Comment by illuhad** [comment]
I think this issue is fixed by #421, but I've had to develop that blindly without testing possible, so not 100% sure.

**Comment by jeffhammond** [comment]
Dry run:
```
$ ./hipSYCL/bin/syclcc-clang -O3 -std=c++17 -ferror-limit=3 --hipsycl-platform=cpu --hipsycl-cpu-cxx=/usr/local/Cellar/llvm/11.0.0/bin/clang++ -I/usr/local/Cellar/boost/1.74.0/include ./hipSYCL/build/src/runtime/libhipSYCL-rt.dylib /usr/local/lib/libomp.dylib saxpy.cc -o saxpy.x --hipsycl-dryrun
Could not open config ./dpcpp-tutorial/hipSYCL/etc/hipSYCL/syclcc.json
/usr/local/Cellar/llvm/11.0.0/bin/clang++ -I./dpcpp-tutorial/hipSYCL/bin/../include/ -D__HIPSYCL__ -D__HIPSYCL_ENABLE_OMPHOST_TARGET__  -O3 -std=c++17 -ferror-limit=3 -I/usr/local/Cellar/boost/1.74.0/include ./hipSYCL/build/src/runtime/libhipSYCL-rt.dylib /usr/local/lib/libomp.dylib saxpy.cc -o saxpy.x 
```

**Comment by illuhad** [comment]
> Could not open config ./dpcpp-tutorial/hipSYCL/etc/hipSYCL/syclcc.json

If `syclcc` cannot find its config file, it means that it wasn't properly configured/installed. Have you run `make install` and executed the `syclcc` that's in the install directory (not the one from the repository)? I'm missing `-fopenmp` on that command line, and usually it should not be necessary to specify dependencies like boost and internals like the hipSYCL runtime library.

**Comment by jeffhammond** [comment]
Yeah, I didn't install it, because I hate modifying /usr if I don't have to.  I was hoping to just use it in ./build if possible but I guess I can install it somewhere else if necessary.

**Comment by illuhad** [comment]
Running from build is not tested at all and might be very unpleasant ;) During installation cmake generates a configuration file for `syclcc` that tells it how to utilize the dependencies that cmake has found.

You could just install into your home directory. I usually just do `cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install <more args>` inside the build directory.
