### ISSUE TITLE
info :: global_mem_cache_type differs from sycl/1.2.1 spec.

### ISSUE THREAD

**Issue by passingglance** [AdaptiveCpp/AdaptiveCpp#432]
**Bug summary**
The definition of the `enum class cl::sycl::info::global_mem_cache_type` has `write_only`, which is not in the sycl/1.2.1 spec, and is missing `read_write`, which is in the spec.

**To Reproduce**
Look at the source code and the spec? :-)

```c++
#include <CL/sycl.hpp>
int main()
{
  cl::sycl::device device;
  auto foo = device.get_info<cl::sycl::info::device::global_mem_cache_type>() == cl::sycl::info::global_mem_cache_type::read_write ;
  return 0;
}
```

**Expected behavior**
hipSYCL and sycl/1.2.1 match.
No compile time warning error: 'read_write' is not a member of 'hipsycl::sycl::info::global_mem_cache_type'

**Optional additional diagnostic information**
I find write_only in 3 header files, all related to global_mem_cache
```
./include/hipSYCL/runtime/hardware.hpp:45:  global_mem_cache_write_only,
./include/hipSYCL/sycl/device.hpp:456:          rt::device_support_aspect::global_mem_cache_write_only))
./include/hipSYCL/sycl/device.hpp:457:    return info::global_mem_cache_type::write_only;
./include/hipSYCL/sycl/info/device.hpp:165:enum class global_mem_cache_type : int { none, read_only, write_only };
```

**Additional context**
Looking at SYCL specification:  Version 1.2.1  Document Revision: 7  Revision Date: April 27, 2020
Still in my first week of learning / playing with SYCL, so please be kind if I'm clueless. :-)

**Comment by illuhad** [comment]
Thank you, you are absolutely right :) This was changed sometime in the spec and it seems we forgot to change it in hipSYCL.

PS: Better look at the SYCL 2020 specification as hipSYCL has already started moving to SYCL 2020 ;)
