### ISSUE TITLE
Multi-GPU Regression (CUDA Error 400)

### ISSUE THREAD

**Issue by psalz** [AdaptiveCpp/AdaptiveCpp#444]
**Bug summary**
There appears to be a regression in 9cd4aff67 that causes CUDA Error 400 (`cudaErrorInvalidResourceHandle`) when running hipSYCL on a system with multiple GPUs, whenever the last GPU is selected.

**To Reproduce**
Simply run this on any system with more than one NVIDIA GPU, and make sure to select the last one (this is for 4 GPUs, but I would presume it happens for other setups as well):
```c++
int main(int argc, char* argv[]) {
	sycl::queue queue(sycl::platform::get_platforms()[0].get_devices()[3]); // Pick last device
	queue.submit([&](sycl::handler& cgh) { cgh.single_task<class Bug>([=] {}); });
	queue.wait_and_throw();
	return EXIT_SUCCESS;
}
```

Running this with `CUDA_VISIBLE_DEVICES=0` (or any other single device id) fixes the problem.

**Describe your setup**
hipSYCL @ 91258d2
4x NVIDIA RTX 2070 running on CUDA 10.2, driver version 450.80.02.

**Additional context**
I haven't had time to thoroughly investigate the cause for this, but I can say that removing [the check](https://github.com/illuhad/hipSYCL/blob/f2904b3e68f1825feb8bfcda2393b5abd9c86c7e/src/runtime/cuda/cuda_device_manager.cpp#L51) inside `cuda_device_manager::activate_device` whether the given device is already active fixes the issue. (By the way, this also fixes any issues I've had with the unit tests @illuhad). From looking at the debug log of hipSYCL, I think what is happening is that each device is activated once during device discovery, with the last one then remaining the "active" one until any actual device interaction is made. Once the kernel is submitted, the device should be activated again, however since it already is active, the call to `cudaSetDevice` is skipped. I suspect that this check may not be adequate as CUDA tracks streams on a per-thread basis, so tracking a single active device id across all threads wont' suffice in all situations (unless `cuda_device_manager` were to be made `thread_local`).

**Comment by illuhad** [comment]
Thanks!

> I haven't had time to thoroughly investigate the cause for this, but I can say that removing the check inside cuda_device_manager::activate_device whether the given device is already active fixes the issue. (By the way, this also fixes any issues I've had with the unit tests @illuhad). From looking at the debug log of hipSYCL, I think what is happening is that each device is activated once during device discovery, with the last one then remaining the "active" one until any actual device interaction is made. Once the kernel is submitted, the device should be activated again, however since it already is active, the call to cudaSetDevice is skipped. I suspect that this check may not be adequate as CUDA tracks streams on a per-thread basis, so tracking a single active device id across all threads wont' suffice in all situations (unless cuda_device_manager were to be made thread_local).

That check is also the first thing I had planned to experiment with. The assumption behind that design is that the device manager is only used within the runtime's worker thread, in which the check should work as expected. If it is used from somewhere else it is indeed a bug. From a quick glance at the code I couldn't find where it might be activated at device discovery, but will take a closer look later.

**Comment by illuhad** [comment]
Okay, the issue is probably that the `cuda_device_manager` is used in the constructor of `cuda_queue` (same for HIP). This is incorrect, as it breaks the assumption that device activation only happens within the runtime's worker thread.
For increased general robustness, it might still be a good idea to solve this by just making the device manager `thread_local`.
