### ISSUE TITLE
Open access version of hipSYCL publication?

### ISSUE THREAD

**Issue by eschnett** [AdaptiveCpp/AdaptiveCpp#467]
Is there an open access version of the publication you list in your readme?

Aksel Alpay and Vincent Heuveline. 2020. SYCL beyond OpenCL: The architecture, current state and future direction of hipSYCL. In Proceedings of the International Workshop on OpenCL (IWOCL ’20). Association for Computing Machinery, New York, NY, USA, Article 8, 1. DOI:https://doi.org/10.1145/3388333.3388658

**Comment by illuhad** [comment]
It's a talk, the doi just refers to the extended abstract. You can find the talk here: https://www.youtube.com/watch?v=kYrY80J4ZAs

Note that hipSYCL is under rapid development; some of the content of the talk is outdated.

**Comment by eschnett** [comment]
The DOI resolves to a web page that wants $15 to access the extended abstract... and the extended abstract doesn't seem to be available elsewhere. Do you want to add a pointer to the readme stating that this is a talk, and pointing to it?

You could also submit to [JOSS](https://joss.theoj.org). Given the state of your documentation etc. that should not be time-consuming.

**Comment by illuhad** [comment]
Readme updated in PR #470. Thanks for the suggestion.
