### ISSUE TITLE
No unary minus operator for vector types?

### ISSUE THREAD

**Issue by daniel-geon-park** [AdaptiveCpp/AdaptiveCpp#482]
**Describe the motivation for the feature request**
I was shocked to find out that the current SYCL specification seems to be missing the unary minus operator for `sycl::vec` types.

For example, you cannot do this:

```cpp
sycl::float4 vec{};
vec = -vec; // Error
```

**Describe the solution you'd like**
Add a simple unary operator-() for vec types, as an extension.

**If applicable, describe alternatives you've considered**
Of course, you can do `0.f - vec`, but it's less elegant. This must be an oversight by the SYCL spec designers.

**Comment by illuhad** [comment]
hipSYCL already has the operator you are asking for:
https://github.com/illuhad/hipSYCL/blob/c0769a4a3da51caf821bddd723665211b7aa460d/include/hipSYCL/sycl/libkernel/vec.hpp#L786

Your code sample compiles fine with hipSYCL.

IIRC, it was also added to the SYCL 2020 specification. If it is still missing (and for any issues related to the specification), please open an issue at https://github.com/KhronosGroup/SYCL-Docs.

**Comment by daniel-geon-park** [comment]
Upon closer glance, it seems like it should take a const lvalue reference to the vec, instead of a non-const one. My code was something like this:

```
const sycl::float4 v{};
-v; // Error: discards qualifiers
```

[I submitted the issue to the SYCL-Docs repo](https://github.com/KhronosGroup/SYCL-Docs/issues/115), thanks.

**Comment by illuhad** [comment]
Ah, good point about constness. I agree, there is no reason why it should be non-const. This is probably an oversight in the spec. Thanks for submitting!
