### ISSUE TITLE
macOS shared_lib_extension wrong

### ISSUE THREAD

**Issue by Michoumichmich** [AdaptiveCpp/AdaptiveCpp#534]
**Bug summary**
On macOS, the backend tries to load `librt-backend-omp.so` which does not exist. 

**Fix**
Edit line 196 in src/runtime/backend_loader.cpp
```
#ifndef _WIN32
#ifdef __APPLE__
  std::string shared_lib_extension = ".dylib";
  #else
  std::string shared_lib_extension = ".so";
  #endif
#else
  std::string shared_lib_extension = ".dll";
#endif
```
solves it!

**Comment by fodinabor** [comment]
Already on it :)
also adding running (and fixing) tests on MacOS CI ;-)

**Comment by Michoumichmich** [comment]
Oh perfect, and what about https://github.com/illuhad/hipSYCL/issues/437#issue-785192414 ? Then it would work straight out of the box on macOS. The OMP_LINK_LINE is still "broken", I mean, not correct
