### ISSUE TITLE
SYCL extension: Parallel primitives?

### ISSUE THREAD

**Issue by illuhad** [AdaptiveCpp/AdaptiveCpp#54]
I believe that it may be useful to have functions for parallel primitives (sort, reduction, scan etc) available as a SYCL extension. The reason is that at the moment we already target three different devices (CPU, AMD GPUs, NVIDIA GPUs), for each of which there are high performance vendor-optimized libraries available [For us, [hipCUB](https://github.com/ROCmSoftwarePlatform/hipCUB) would probably be a solid choice here].
So, from a performance portability point of view it would be useful to have a SYCL interface that just forwards the operations to these highly optimized libraries.
Personally, I also believe that this interface should be within the scope of SYCL implementations (i.e. as a SYCL extension instead of an independent library), because of the variety of hardware focus of the different implementations. In that way, each SYCL implementation can focus on the hardware of its expertise.

Implementing this would require some effort, so I would first like to ask:
* Is there an interest in this at all?
* Do you think that it makes sense to implement this as a SYCL extension inside hipSYCL, opposed to e.g. modifying libraries like SYCL parallel STL to make use of vendor-optimized libraries?
* Which algorithms/features do you think are most important to get started?

**Comment by jeffhammond** [comment]
Yes, reductions are key.  If you haven't already read it, the Intel proposal is [https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/reduction/reduction.md](here).  There is much less use of scan but it is important for e.g. Kokkos.

**Comment by illuhad** [comment]
Thank you for pointing me to Intel's proposal! Nice to see there's finally something happening in this area.
