### ISSUE TITLE
Problem building with Intel compiler

### ISSUE THREAD

**Issue by VictorEijkhout** [AdaptiveCpp/AdaptiveCpp#557]
Trying to build with OpenMP only
```
             && cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" \
                -D CMAKE_C_COMPILER=${CC} \
                -D CMAKE_CXX_COMPILER=${CXX} \
                    ${SYCL_SRC}/llvm \
```

gives

```
[ 85%] Linking CXX executable ../../bin/llvm-exegesis
/opt/apps/gcc/8.3.0/bin/ld: ../../lib/libLLVMExegesisX86.a(Target.cpp.o): in function `llvm::exegesis::(anonymous namespace)::X86SavedState::~X86SavedState()':
Target.cpp:(.text+0x1967): undefined reference to `__builtin_ia32_fxrstor64'
/opt/apps/gcc/8.3.0/bin/ld: ../../lib/libLLVMExegesisX86.a(Target.cpp.o): in function `llvm::exegesis::(anonymous namespace)::X86SavedState::~X86SavedState()':
Target.cpp:(.text+0x1995): undefined reference to `__builtin_ia32_fxrstor64'
/opt/apps/gcc/8.3.0/bin/ld: ../../lib/libLLVMExegesisX86.a(Target.cpp.o): in function `llvm::exegesis::(anonymous namespace)::ExegesisX86Target::withSavedState() const':
Target.cpp:(.text+0x6b93): undefined reference to `__builtin_ia32_fxsave64'
make[3]: *** [bin/llvm-exegesis] Error 1
make[3]: Leaving directory `/work2/00434/eijkhout/sycl/build'
make[2]: *** [tools/llvm-exegesis/CMakeFiles/llvm-exegesis.dir/all] Error 2
make[2]: Leaving directory `/work2/00434/eijkhout/sycl/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/work2/00434/eijkhout/sycl/build'
```

Let me know what files you want me to send you.

**Comment by fodinabor** [comment]
HI Victor,
it looks like you're building LLVM and experience an issue there.. not exactly sure what the connection with hipSYCL is..?

**Comment by VictorEijkhout** [comment]
On , 2021May21, at 08:53, fodinabor ***@***.******@***.***>> wrote:



HI Victor,
it looks like you're building LLVM and experience an issue there.. not exactly sure what the connection with hipSYCL is..?

Well, it’s apparently one of the backends of hipSYCL.

I’m now trying the OpenMP backend. (Documentation on how to build the backends could be improved. For OpenMP it only mentions that it’s possible. I didn’t find the actual settings.)

Victor.

**Comment by VictorEijkhout** [comment]
Ok, I could really use some help here. 

For the OMP backend, what do I cmake and where? I did cmake in hipsycl/openmp, but that seems to have built OpenMP headers, not anything Sycl related.

Victor.

**Comment by fodinabor** [comment]
Hi Victor,
a typical hipSYCL setup (automatically including the OpenMP backend and if the dependencies are found, CUDA and HIP backend) would look like the following snippet:
```
git clone https://github.com/illuhad/hipSYCL.git
cd hipSYCL
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=<installation prefix>
make install -j
```

this is described in the [docs](https://github.com/illuhad/hipSYCL/blob/develop/doc/installing.md).

For using Intel compilers, you will have to set `CC`, `CXX` or the corresponding `CMAKE_C_COMPILER`, `CMAKE_CXX_COMPILER` to the respective C and C++ compilers.
May I ask which Intel compiler you are trying to use? The classic ICC, the new LLVM based ICX, or directly the llvm fork from github.com/intel/llvm (dpcpp)?

I'm no Intel compiler expert, but I think when using ICC with OpenMP, one would usually have to specify `-openmp` or `-qopenmp` and not `-fopenmp`. This will require adding this to the `cmake` configure command: `-DOMP_CXX_FLAGS=-openmp  -DOMP_LINK_LINE=-lboost_context -lboost_fiber -openmp`, assuming boost is installed in the default locations.

I hope this helps..

**Comment by VictorEijkhout** [comment]
Oh boy. Major error on my side. I had checked out the Intel Sycl repository, rather than hipSycl. That’ll do it.

I apologize for the noise.

Victor.

**Comment by illuhad** [comment]
It's not entirely clear to me what you want to accomplish. Can you please elaborate what exactly you are trying to do, which hardware you want to target with hipSYCL and with which backend, which steps you have taken to do so and where you are stuck?

> Documentation on how to build the backends could be improved. For OpenMP it only mentions that it’s possible. I didn’t find the actual settings.

There is nothing needed to enable the OpenMP backend, hipSYCL always builds the OpenMP backend by default and does not work without it.

> Well, it’s apparently one of the backends of hipSYCL.

I'm not sure what you mean. LLVM as a whole is not a hipSYCL backend. hipSYCL utilizes portions of LLVM for some backends to a greater or lesser extent. But that does not mean that LLVM-specific issues that seem to be independent of the interplay between hipSYCL and LLVM are our field of expertise. hipSYCL is just a user of LLVM.

Are you talking about the Level Zero/SPIR-V backend for Intel GPUs? In this case hipSYCL just invokes an Intel-provided backend compiler - if you have issues building the backend compiler, the backend compiler vendor is in a better position to help you. Similarly to how NVIDIA might be in a better position to help if you have trouble installing CUDA.
How to enable OpenMP support with an Intel LLVM distribution is a question that you might better ask Intel. As @fodinabor points out, it might depend on which Intel compiler you are actually using. This is nothing specific to hipSYCL though, unless you are stuck with how to configure hipSYCL for specific unusual OpenMP compiler flags. In this case you might want to adapt `OMP_CXX_FLAGS` and `OMP_LINK_LINE` as explained by @fodinabor.

Maybe this issue can help if you are interested in Intel GPUs: https://github.com/illuhad/hipSYCL/issues/554

> I did cmake in hipsycl/openmp, but that seems to have built OpenMP headers, not anything Sycl related.

I don't understand - hipSYCL does not have an `openmp` subdirectory.

**Comment by illuhad** [comment]
> Oh boy. Major error on my side. I had checked out the Intel Sycl repository, rather than hipSycl. That’ll do it.

Ah, I see - that explains the confusion on all sides here :-) I will close this issue then.
