### ISSUE TITLE
Round to nearest even floating number feature

### ISSUE THREAD

**Issue by Luigi-Crisci** [AdaptiveCpp/AdaptiveCpp#588]
Hi!

I'm trying to port some cuda code to sycl using HipSYCL but I have a problem. In this code there is a massive use of function like `__fsqrt_rn`,`__fmul_rn`etc. which round a floating point number to nearest floating point even value, and I haven't found anything similar in hipSYCL.
Is there an equivalent way in hipSYCL to enable this rounding feature?

Thank you!

**Comment by illuhad** [comment]
AFAIK in SYCL rte (round to nearest even) is the default rounding mode for floating point values and most math builtins.

Do you have a use case where you think that hipSYCL is not doing the right thing? I'm trying to figure out whether your question is actually a question about the SYCL specification or really a hipSYCL issue.

Of course you can always leverage hipSYCL's backend interoperability mechanisms to call such CUDA intrinsics directly in the CUDA compilation pass.

**Comment by Luigi-Crisci** [comment]
Nono, I did not find a case where it is done incorrectly. I just wanted to know if this feature was implemented, I didn't know that this was the default behaviour.
Thank you a lot!
