### ISSUE TITLE
Nvprof CUDA profiling / OpenACC linkage

### ISSUE THREAD

**Issue by bsobol** [AdaptiveCpp/AdaptiveCpp#598]
I get the following error message running profiling on the hipSYCL program:

`Missing definition of the OpenACC API routine/s in the OpenACC library linked to the application. To work around this issue either force the inclusion of all the OpenACC symbols in the binary or link the OpenACC library dynamically.`

I assume that this originates somewhere in the compilation process of hipSYCL, as I don't directly link my application to any CUDA related libraries.

Do you have any idea where to look for a place to put a workaround?

I didn't have this problem before with hipSYCL profiling, so probably it's because of some change in hipSYCL in recent months, or some nvprof metric that I didn't enable before,

I use CUDA 10.2.

**Comment by illuhad** [comment]
AFAIK it's an nvprof issue. hipSYCL links to CUDA just like any other CUDA application. Since nvprof is deprecated, I recommend you use nsys/nsight compute which does not seem to have this issue.

**Comment by bsobol** [comment]
Yep, I would like to, but unfortunately, at the moment I have access only to the Kepler GPUs, which are not supported by nsight compute.

**Comment by illuhad** [comment]
Closing as it's most likely an nvprof bug that we cannot do anything about.

**Comment by youkaichao** [comment]
The problem was solved by passing a ``--openacc-profiling off`` flag to nvprof. I found it here: https://bytemeta.vip/repo/JuliaGPU/CUDA.jl/issues/1283 . Hope it helps :)
