### ISSUE TITLE
Boost Version 1.74.0

### ISSUE THREAD

**Issue by n-io** [AdaptiveCpp/AdaptiveCpp#608]
Hello,

Building hipSYCL with Boost/1.74.0 succeeds. My setup is to run celerity on top of hipSYCL. When running applications I get `error while loading shared libraries: libboost_context.so.1.68.0: cannot open shared object file: No such file or directory`. Hoping that I am not doing anything obvious wrong - is Boost/1.74.0 currently supported?

Best regards

**Comment by fodinabor** [comment]
Hi n-io,
I got a similar issue then and when after upgrading my boost version.
In that case, I usually just have to re-run CMake `cmake .` for hipSYCL, rebuild `make install` it and probably also rebuild the client application to get everything back up. I'm currently using hipSYCL with 1.76 and have been using it with most versions from 1.70+.
If the issue persists make sure that your `<hipsycl_install>/etc/syclcc.json` file actually mentions `1.74` and not `1.68` for `libboost_context.so` and `libboost_fiber.so`

**Comment by n-io** [comment]
Have done a clean rebuild from scratch and `cyclic.json` looks good, but the issue sadly persists. Relevant lines:
```
"default-omp-link-line" : "-L/.../Boost/1.74.0-gpsmpi-2021/lib -lboost_context -lboost_fiber -Wl,-rpath=/.../Boost/1.74.0-gpsmpi-2021/lib -fopenmp",
"default-omp-cxx-flags" : "-I/.../Boost/1.74.0-gpsmpi-2021/include -fopenmp",
```

**Comment by fodinabor** [comment]
Hmm... it looks to me like the 1.74 version is installed in a non-default location, while 1.68 might be installed in a default location like `/usr/local/lib` or so? not sure how the library selection works if you have two boost versions in a `-L` path.

You could try replacing `-lboost_context` (and the same for fiber) with the full path `/.../Boost/1.74.0-gpsmpi-2021/lib/libboost_context.so.1.74.0`  (note the missing `-l`) in the `syclcc.json` to make sure the linking from hipSYCL happens against that version.

Also, run the build with the environment variable `HIPSYCL_DRYRUN=1` being set, and verify that no other boost libs pop up in the command lines there, which might have been picked up by your downstream projects' build system.

**Comment by danvonk** [comment]
Interestingly, I need to use 1.74.0, as I get the following cmake issue when building with 1.78.0:
```
-- Could NOT find Boost (missing: fiber) (found version "1.78.0")
CMake Error at CMakeLists.txt:38 (message):
  Please provide the path to the root directory of the boost installation
  using the -DBOOST_ROOT option
```

**Comment by fodinabor** [comment]
How did you install Boost? Make sure to install all components (or at least `context` and `fiber` + unittest if building the tests).
On Manjaro the default boost package is at 1.78 with all necessary components and it worked flawless for me so far.

**Comment by danvonk** [comment]
I'm on Fedora 35 I am using the boost 1.78.0 .tgz from the website and have it compiled in a directory. I run cmake like this:
```
cmake -G Ninja -DBOOST_ROOT=/home/dan/dep/new_boost/boost_1_78_0 -DCLANG_INCLUDE_PATH=/lib64/clang/13/include ..
```

but get the error:
```
-- Could NOT find Boost (missing: fiber) (found version "1.78.0")
CMake Error at CMakeLists.txt:38 (message):
  Please provide the path to the root directory of the boost installation
  using the -DBOOST_ROOT option
```


When I use a different boost 1.74.0 directory, it works fine. Maybe it's an issue with the FindBoost script being outdated on my platform.

**Comment by fodinabor** [comment]
How did you configure the boost itself?
Possibly you have to add the `--with-fiber` option or `--build-type=complete` to the `b2` command to include the fiber component in the build? (you can have a look at `/home/dan/dep/new_boost/boost_1_78_0/lib` whether it contains a `libboost_fiber.so.1.78.0` file to verify whether it has been built)

**Comment by danvonk** [comment]
I just build with ```./bootstrap.sh && ./b2```, which builds everything incl. fiber. The library gets built and is found in ```bin.v2/libs/fiber/build/gcc-11/release/link-static/threading-multi/visibility-hidden``` (```libboost_fiber.a```, ```libboost_fiber.so.1.78.0```) but does not get copied to the ```stage``` directory. Whereas, when I build with 1.74.0, it gets copied into the ```stage``` directory and I can build hipSYCL fine.

**Comment by illuhad** [comment]
@danvonk Interesting, I think the same thing happened to me when I built boost from source some time ago (library was built, but not installed). Back then I was in a bit of a hurry and just manually copied the `*.so` to the installation directory, which fixed the issue. Looks like there is a bug in the build system of boost 1.78.

**Comment by BenBrock** [comment]
I also just encountered this issue with Boost 1.78.  It appears to be an issue with Boost's build system, which fails to copy over the library files for fiber.  Solved the issue by copying over the `*.so` file from `boost_1_78_0/bin.v2/libs/fiber/build/gcc-11/release/threading-multi/visibility-hidden` and the `*.a` file from `boost_1_78_0/bin.v2/libs/fiber/build/gcc-11/release/link-static/threading-multi` into the `lib` folder of my install directory for Boost.

Unclear if there are any flags that will make Boost properly install fiber (I tried `--with-fiber` and a collection of other flags, but none of them seemed to work).  Would be nice if you could perhaps recommend an earlier version of Boost for hipSYCL until they fix this issue.

**Comment by illuhad** [comment]
It seems at least some distributions have fixed this in their boost packages. So, unconditionally not recommending 1.78 might be too much. But we can add it to the documentation when building boost from source.
