### ISSUE TITLE
compiling host lambda as device code on linux

### ISSUE THREAD

**Issue by mz24cn** [AdaptiveCpp/AdaptiveCpp#624]
**Bug summary**
compiling host lambda as device code.

**To Reproduce**
```
#include <iostream>
#include <functional>
#include <CL/sycl.hpp>
using namespace cl;
using namespace std;

int play(function<int()> func)
{
	return func();
}
int main()
{
	int r = play([]() -> int {
		return min(rand(), rand());
	});
	cout << r;
}
```
compile commands:

> /opt/hipSYCL/bin/syclcc --hipsycl-targets="omp;cuda:sm_60"  -std=c++20 -m64 -D_SYCL -D_CRT_SECURE_NO_WARNINGS -O3 -c -fmessage-length=0 -o ./build/sycl.o ./src/sycl.cpp
> /opt/hipSYCL/bin/syclcc --hipsycl-targets="omp;cuda:sm_60"  -o ./build/sycl.exe ./build/sycl.o

it complains:

> ./src/sycl.cpp:48:10: error: reference to __device__ function 'min' in __host__ __device__ function
>                 return min(rand(), rand());

**Expected behavior**
print a number.

**Optional additional diagnostic information**
1, The code was compiled and run successfully on Windows.
2, Change the min function to other function, for example, round ("return round(rand());"), it will be compiled and run successfully.
3, Move the code out of the lambda body, it will be compiled and run successfully.

**Comment by fodinabor** [comment]
I guess the main issue is that `min` is not really well defined for the host. CUDA defines it for the device code, though. Using `std::min` from `#include <algorithm>` fixes the issue.
On Windows `min` might be defined as a macro, as long as `-DNOMINMAX` is not defined, thus min is _supported_ there.

The other example you give `round` is well defined for the host as part of C's `math.h` which I think is implicitly included when compiling for CUDA.

Can't tell why it works outside the lambda though...
Edit: ah yeah, the `using namespace std` :)

**Comment by mz24cn** [comment]
> I guess the main issue is that `min` is not really well defined for the host. CUDA defines it for the device code, though. Using `std::min` from `#include <algorithm>` fixes the issue.

No, including algorithm header doesn't work.

> Can't tell why it works outside the lambda though...

I think it is because hipsycl add ``__device__`` to **any lambda**.
./src/sycl.cpp:48:10: error: reference to ``__device__`` function 'min' in ``__host__`` ``__device__`` function
return min(rand(), rand());

**Comment by illuhad** [comment]
> I think it is because hipsycl add 'device' to any lambda.

It doesn't do that. At all.


It's a clang bug, not a hipSYCL bug. Same issue reproduces without hipSYCL:

```c++
#include <iostream>
#include <functional>
//#include <CL/sycl.hpp>
//using namespace cl;
using namespace std;

int play(function<int()> func)
{
        return func();
}
int main()
{
        int r = play([]() -> int {
                return min(rand(), rand());
        });
        cout << r;
}

```
Compile with `$ clang++ -std=c++17 -o test -x cuda --cuda-gpu-arch=sm_61 test.cpp`
Same error, no hipSYCL involved. It seems there is a bug in the clang CUDA wrappers and how they overload `::min`

As a workaround, the issue can be resolved by not `using namespace std`, which is probably better practice anyway for production code.

**Comment by mz24cn** [comment]
Okay, I‘m wrong about hipsycl. LLVM is so fragile. I use std::min and 'using namespace std' simultaneously, it really works around.
I stick on not using 'using namespace std' for many years. But I give it up this year to make code clearer. It really feel good.
