### ISSUE TITLE
vec::load and vec::store do not implement the SYCL 2020 spec

### ISSUE THREAD

**Issue by mabraham** [AdaptiveCpp/AdaptiveCpp#647]
**Bug summary**

`sycl::vec<dataT,numElements>::load` is documented with `Loads the values at the address of ptr offset in elements of type dataT by numElements * offset, into the components of this SYCL vec.` at https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_vec_interface.

The hipsycl implementation at https://github.com/illuhad/hipSYCL/blob/develop/include/hipSYCL/sycl/libkernel/vec.hpp#L528 does not scale `offset` with `numElements` leading to incorrect results.

The matching store operation has the same problem. Perhaps this is related to the change of meaning in sycl 2020 noted in the comment there?

**To Reproduce**
Use an `accessor<float> a` indexed by `i` and a `sycl::float2 f2` and attempt to `f2.load(i, a.get_pointer())`

**Expected behavior**

That it is straightforward to load(store) a `float2` from(to) an accessor of `float` without manually scaling `i` by `numElements`.

**Describe your setup**

hipSYCL develop branch commit 6f4ccc76e41aae running on ROCm 4.3 targeting an MI50

**Additional context**
GROMACS does a 3D-FFT that may or may not be in-place, so we have a 3D grid expressed as a 1-D buffer of `float` that logically contains `complex` values that are convenient to operate on as `sycl::float2`

**Comment by illuhad** [comment]
Thanks, I think this is just an oversight. I think however that the spec requirements might be unnecessarily restrictive, as with this semantics it's not easily possible to pull unaligned data into a vector, which is possible with the current implementation...
But I guess the spec demands what the spec demands ;)

I think the comment regarding changes with the SYCL 2020 API refer to the `multi_ptr` parameter. This class was changed quite substantially for SYCL 2020.

**Comment by mabraham** [comment]
> with this semantics it's not easily possible to pull unaligned data into a vector

Yes, one can pull all the floats from memory into constructor arguments, but that's certainly not "easy."

Thanks for the quick fix!
