### ISSUE TITLE
Possibility to compile SYCL source files that do not have a C++ file extension

### ISSUE THREAD

**Issue by krasznaa** [AdaptiveCpp/AdaptiveCpp#652]
## Describe the motivation for the feature request

In our project we started using the convention of putting SYCL sources into `<foo>.sycl` files, and not `<foo>.cpp`, `<foo>.cxx`, or similar. The motivation for this is to be able to define a "separate language" for CMake for how to compile/link SYCL sources together with any other sources.

Unfortunately it does not seem to be possible to use such files with the `syclcc` executable of this project. :frowning: With Intel's compiler we can force the compiler to consider `.sycl` files as C\+\+/SYCL files with the `-x c++` option. But if I try to do that with `syclcc`, I get the following:

```
[bash][Legolas]:vecmem > /opt/hipSYCL/bin/syclcc --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx803 -c -o main.o -x c++ main.sycl
In file included from main.sycl:1:
In file included from /opt/hipSYCL/bin/../include/CL/sycl.hpp:31:
In file included from /opt/hipSYCL/bin/../include/CL/../hipSYCL/sycl/sycl.hpp:36:
/opt/hipSYCL/bin/../include/CL/../hipSYCL/sycl/backend/backend.hpp:65:12: fatal error: 'hipCPU/hip/hip_runtime.h' file not found
  #include "hipCPU/hip/hip_runtime.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[bash][Legolas]:vecmem >
```

It seems that the definitions used by `syclcc` internally get confused about what platform to compile the code for. So naively it would seem that making `-x c++` compile SYCL source code correctly is "just" a matter of some tweaks to the code...

## Describe the solution you'd like

I would like it if `syclcc` could accept `-x c++`, or possibly any other command line argument, to force it to consider the provided input file as a SYCL source file. Allowing users to use non-standard extensions for their source files.

## If applicable, describe alternatives you've considered

Or course any number of hacky solutions could be done by us, but I would really prefer if it would be possible to use `.sycl` source files with this compiler directly. Since CMake and ROCm semi-officially introduced the `.hip` source extension not that long ago (https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6121), I don't think it's too outrageous to think of a custom extension for SYCL source files as well... :wink:

## Additional context

N/A

**Comment by illuhad** [comment]
> The motivation for this is to be able to define a "separate language" for CMake for how to compile/link SYCL sources together with any other sources.

I would discourage this approach. We have experimented with this before, and ditched it again because it causes issues. See here for the discussions:
https://github.com/illuhad/hipSYCL/pull/309

More philosophically, I disagree with SYCL being a separate language, since it is *just C++*, and some implementations might implement it simply as a regular C++ library. I think creating a new cmake language just raises more questions than it answers.

> But if I try to do that with syclcc, I get the following:

The output shows that you are using a rather old hipSYCL version that is no longer maintained. Please update hipSYCL.

**Comment by krasznaa** [comment]
:confused: I gave some background on why I bumped into this issue. But asking for the ability to use clang's `-x` flag is a bit independent of it all. I could see some other legitimate use cases for wanting this to be possible.

So... would it be possible to compile any source file using `-x c++`? Since it's this flag that is my problem. Not the exact extension of my source file.

```
bash][Legolas]:vecmem > /opt/hipSYCL/bin/syclcc --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx803 -c -o main.o -x c++ main.cxx 
syclcc warning: No optimization flag was given, optimizations are disabled by default. Performance may be degraded. Compile with e.g. -O2/-O3 to enable optimizations.
clang-9: warning: argument unused during compilation: '--cuda-gpu-arch=gfx803' [-Wunused-command-line-argument]
clang-9: warning: argument unused during compilation: '--hip-device-lib-path=/opt/hipSYCL/rocm/lib' [-Wunused-command-line-argument]
In file included from main.cxx:1:
In file included from /opt/hipSYCL/bin/../include/CL/sycl.hpp:31:
In file included from /opt/hipSYCL/bin/../include/CL/../hipSYCL/sycl/sycl.hpp:36:
/opt/hipSYCL/bin/../include/CL/../hipSYCL/sycl/backend/backend.hpp:65:12: fatal error: 'hipCPU/hip/hip_runtime.h' file not found
  #include "hipCPU/hip/hip_runtime.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[bash][Legolas]:vecmem >
```

**Comment by illuhad** [comment]
This definitely *cannot* be done with `-x`, since hipSYCL already uses `-x` to set the language of the source e.g. to hip. Since a source file cannot be handled by two different clang drivers, this cannot work.

It might be possible to add a flag like `--hipsycl-custom-extension=...` to add support for additional file extensions.

**Comment by krasznaa** [comment]
I see. I think I can work with this. I mean the knowledge that I need to use `-x hip` when using the HIP backend for my `.sycl` source files...

**Comment by illuhad** [comment]
I'm not sure if `-x hip` will be sufficient. The core issue in *recent hipSYCL* is that if the filename ending is not of a known source file ending, `syclcc` has to assume that the invocation is a pure linking step. This has implications on which flags can be added to the compiler invocation. So, if you just use `-x hip` I'm concerned that important flags might not be added to the command line.
I don't know what happens with your older hipSYCL version. If it happens to work there, it's not guaranteed to do so.

**Comment by krasznaa** [comment]
The "older hipSYCL version" was because I didn't install `hipsycl-rocm-nightly` initially, but simply `hipsycl-rocm`. But you're right, that package for Ubuntu 20.04 is >1 year old by now.

Initially I was not planning on taking part in the development of this project, that's why I wanted to stay away from the latest and greatest version. In error as it turns out.

I'm afraid that all this just shows the limitations of using a script as the frontent for a compiler. :frowning: Even AMD finally realised that they can't do this anymore with HIP. I fear that hipSYCL will have to too. Compilers like GCC and Clang have a gazillion of options for a reason. Because people had reasons for using each of those in non-trivial software projects. Only being able to use `syclcc` in some very fixed ways is unfortunately not too great. :frowning:

**Comment by illuhad** [comment]
> Compilers like GCC and Clang have a gazillion of options for a reason. Because people had reasons for using each of those in non-trivial software projects. Only being able to use syclcc in some very fixed ways is unfortunately not too great. frowning

You can use the vast majority of those all with hipSYCL as well. hipSYCL supports multiple compiler backends, not only clang or clang-based compilers. In that case there's really no other option.

**Comment by illuhad** [comment]
Recent hipSYCL also treats `.sycl` files as SYCL source code; closing for now as I think the use case should now be covered.
