### ISSUE TITLE
Deadlock when using hipSYCL in multithreaded applications

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#658]
**Bug summary**

Trying to use hipSYCL from a multi-thread (POSIX threads) application occasionally leads to a never-ending `queue::wait()`. The more threads there are, the likelier it is.

The deadlock happens when calling `queue.wait()` from one of the threads. Looking at a stack trace, the thread is stuck on a `_condition_wait.wait` call inside `worker_thread::wait`, despite the `_enqueued_operations` being empty.

Apparently, this thread was not awoken by `_condition_wait.notify_one()` from the executor thread.

The issue is resolved by replacing all `notify_one()` with `notify_all()` in `async_worker.cpp`, but that may be a bit heavy-handed?

**To Reproduce**

Happens pretty regularly in GROMACS runs, with both CUDA and HIP backends. I can come up with a shorted reproducer if needed, but I hope the description would be sufficient to reason through.

**Expected behavior**

`worker_thread::wait()` should return as soon as there are no more tasks in the queue.

**Describe your setup**
* hipSYCL 46d6b3c (latest `develop`)
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang-11 from Ubuntu repos for CUDA build, clang-13 from ROCm for HIP build.
   * CUDA 11.4 (clang-11.0)
   * ROCm 4.3
* Tested with `cuda:sm_75` and `hip:gfx906` backends (separate builds)

**Comment by illuhad** [comment]
Thanks for reporting!

> The issue is resolved by replacing all notify_one() with notify_all() in async_worker.cpp, but that may be a bit heavy-handed?

I think this is the correct approach. If multiple threads are waiting they have to be all woken up. I'm not sure if there's anything more lightweight than this, but I'll check to make sure.
