### ISSUE TITLE
Wrong result for `sub_group::get_group_linear_id()`

### ISSUE THREAD

**Issue by bluebear94** [AdaptiveCpp/AdaptiveCpp#661]
**Bug summary**
`sycl::sub_group::get_group_linear_id()` shifts the `local_tid()` by the wrong value. The tid is shifted by `__ffs(warpSize)`, but for a warp size of 2^n, `__ffs` returns n + 1, not n. Thus, the correct amount to shift by is `__ffs(warpSize) - 1`.

**To Reproduce**

The following is a minimal working example.

```c++
#include <algorithm>
#include <assert.h>

#include <CL/sycl.hpp>

using namespace cl::sycl;

int main() {
  queue myQueue;
  buffer<int> indices{1024};
  myQueue.submit(
      [&](handler &cgh) {
        auto indicesOut = indices.get_access<access_mode::write>(cgh);
        cgh.parallel_for(nd_range<1>{1024, 512}, [=](nd_item<1> item) {
          size_t i = item.get_global_linear_id();
          auto sg = item.get_sub_group();
          size_t lane = sg.get_local_linear_id();
          size_t warp = sg.get_group_linear_id();
          size_t warpSize = sg.get_local_linear_range();
          indicesOut[i] = lane + warp * warpSize;
        });
      });
  myQueue.wait();
  {
    host_accessor indicesIn{indices};
    for (size_t i = 0; i < 1024; ++i) {
      assert(indicesIn[i] == i % 512);
    }
  }
}
```

This code should fill in the indices of each work item relative to the work group into `indices`.

**Expected behavior**

None of the assertions should fail.

**Describe your setup**
* I have hipSYCL built from the git repository, at commit `cdd72c220e0b6c181357725b4e7b7510dd1ebd00`.
* Describe the dependencies that hipSYCL sits on top of in your setup:
   * clang: 12.0.1
   * CUDA version: 11.4
* The preceding example was compiled with `/opt/hipSYCL/bin/syclcc -O3 gtest.cpp -o gtest --hipsycl-gpu-arch=sm_50 --cuda-path=/usr/local/cuda -L/usr/local/cuda/lib64`.

**Comment by illuhad** [comment]
This issue is known, see #627 :) Feel free to submit a PR :)
