### ISSUE TITLE
failed to build the SYCL example code example.cpp on ROCm platform

### ISSUE THREAD

**Issue by ipe-zhangyz** [AdaptiveCpp/AdaptiveCpp#679]
Hello, I'm tring to build the SYCL example source code `example.cpp`, using this command:
`~/software/hipSYCL/bin/syclcc -std=c++17 -O2 -o test --hipsycl-platform=rocm --hipsycl-targets=hip:gfx906 examples.cpp`
It failed at the linking stage, with a lot of errors like:
```
/tmp/examples-295303.o: In function `hipsycl::glue::throw_result(hipsycl::rt::result const&)':
examples.cpp:(.text._ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE[_ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE]+0xdf): undefined reference to `hipsycl::rt::result::what() const'
examples.cpp:(.text._ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE[_ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE]+0x11d): undefined reference to `hipsycl::rt::result::what() const'
examples.cpp:(.text._ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE[_ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE]+0x15b): undefined reference to `hipsycl::rt::result::what() const'
examples.cpp:(.text._ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE[_ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE]+0x199): undefined reference to `hipsycl::rt::result::what() const'
examples.cpp:(.text._ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE[_ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE]+0x2b4): undefined reference to `hipsycl::rt::result::what() const'
/tmp/examples-295303.o:examples.cpp:(.text._ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE[_ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE]+0x2f2): more undefined references to `hipsycl::rt::result::what() const' follow
/tmp/examples-295303.o: In function `std::_MakeUniq<hipsycl::rt::kernel_operation>::__single_object std::make_unique<hipsycl::rt::kernel_operation, char const*, std::vector<std::unique_ptr<hipsycl::rt::backend_kernel_launcher, std::default_delete<hipsycl::rt::backend_kernel_launcher> >, std::allocator<std::unique_ptr<hipsycl::rt::backend_kernel_launcher, std::default_delete<hipsycl::rt::backend_kernel_launcher> > > >, hipsycl::rt::requirements_list>(char const*&&, std::vector<std::unique_ptr<hipsycl::rt::backend_kernel_launcher, std::default_delete<hipsycl::rt::backend_kernel_launcher> >, std::allocator<std::unique_ptr<hipsycl::rt::backend_kernel_launcher, std::default_delete<hipsycl::rt::backend_kernel_launcher> > > >&&, hipsycl::rt::requirements_list&&)':
examples.cpp:(.text._ZSt11make_uniqueIN7hipsycl2rt16kernel_operationEJPKcSt6vectorISt10unique_ptrINS1_23backend_kernel_launcherESt14default_deleteIS7_EESaISA_EENS1_17requirements_listEEENSt9_MakeUniqIT_E15__single_objectEDpOT0_[_ZSt11make_uniqueIN7hipsycl2rt16kernel_operationEJPKcSt6vectorISt10unique_ptrINS1_23backend_kernel_launcherESt14default_deleteIS7_EESaISA_EENS1_17requirements_listEEENSt9_MakeUniqIT_E15__single_objectEDpOT0_]+0x67): undefined reference to `hipsycl::rt::kernel_operation::kernel_operation(std::string const&, std::vector<std::unique_ptr<hipsycl::rt::backend_kernel_launcher, std::default_delete<hipsycl::rt::backend_kernel_launcher> >, std::allocator<std::unique_ptr<hipsycl::rt::backend_kernel_launcher, std::default_delete<hipsycl::rt::backend_kernel_launcher> > > >, hipsycl::rt::requirements_list const&)'
```
However, if I switch the target to `omp`, like this:
`~/software/hipSYCL/bin/syclcc -std=c++17 -O2 -o test --hipsycl-platform=rocm --hipsycl-targets=omp examples.cpp`
the same source code can be compiled and run successfully. Of course it was run on CPU in this case.

I built hipSYCL from source. The cmake command I used is:
`
cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/home/software/hipSYCL -DBOOST_ROOT=/home/software/boost-1.77.0 -DROCM_PATH=/home/software/compiler/rocm/rocm-4.0.1 -DLLVM_DIR=/home/software/llvm-11.1/lib/cmake/llvm -DCLANG_EXECUTABLE_PATH=/home/software/llvm-11.1/bin/clang++ -DCLANG_INCLUDE_PATH=/home/software/llvm-11.1/include
`
The hipSYCL can be built in this way, but it failed to build the simple SYCL example code.

Could anyone help me with this? Thanks!

**Comment by illuhad** [comment]
> ~/software/hipSYCL/bin/syclcc -std=c++17 -O2 -o test --hipsycl-platform=rocm --hipsycl-targets=hip:gfx906 examples.cpp
> ~/software/hipSYCL/bin/syclcc -std=c++17 -O2 -o test --hipsycl-platform=rocm --hipsycl-targets=omp examples.cpp

It's not a good idea to mix the deprecated `--hipsycl-platform` specification and the new `--hipsycl-targets` arguments. You can do everything with `--hipsycl-targets`, e..g `--hipsycl-targets="omp;hip:gfx906" to compile for both OpenMP and ROCm.

Please provide more information on how you have installed hipSYCL. Which OS? Which gcc version?

Most likely the clang that you are using to compile for device does generate a different ABI than the gcc that you have built the hipSYCL runtime library with, so the runtime library is incompatible with the binaries generated by `syclcc` using clang.
Possible explanations could be that one is much newer than the other, especially if they utilize different implementations of the C++ standard library, or that clang is set up to use `libc++` as standard library while gcc uses `libstdc++`

One quick fix could be to compile hipSYCL with the same clang that you are setting as `CLANG_EXECUTABLE_PATH`, or probably to make sure that both are using the same C++ standard library headers.

**Comment by ipe-zhangyz** [comment]
Thanks for you reply! The hipSYCL was built using gcc 9.3.0 on CentOS 7.6。I tried to build hipSYCL using clang，but encountered another error:
```
/home/sourcecode/hipSYCL/src/runtime/backend_loader.cpp:36:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
1 error generated.
```
It seems that before gcc 8 we need to use `experimental::filesystem`. I tried to switch the `filesystem` to `experimental::filesystem`, but the defination of the class `experimental::filesystem` is not the same with `filesystem`.  I've tested it and this problem still exists with clang 13.0. Thus, I have to use gcc 9.3 to build the hipSYCL. 

Do you have any idea about this? Thank you for your help!

**Comment by illuhad** [comment]
It seems that clang uses a libstdc++ installation that is too old and hence does not fully support C++17 features such as `std::filesystem`. Since SYCL relies on C++17, this cannot work.

clang by default tends to just use the system default `libstdc++`, however, you should be able to point it to a newer one (e.g. the one from gcc 9.3.0) e.g. using the clang `--gcc-toolchain=...` argument to point it to gcc 9.3.

I think I now know what is going on and what was causing your issue: You are building hipSYCL with gcc 9.3, which likely uses its own libstdc++ 9. clang on the other hand uses the first C++ standard library that it can find, which probably happens to be the system default standard library. This is going to be older than libstdc++ 9. As a consequence, the hipSYCL runtime library is compiled with a different C++ standard library than the applications compiled by `syclcc`, which relies on clang. Linker errors are the consequence since different versions of C++ standard libraries almost always lead to a different ABI.

Make sure that all compilers involved use the same standard library, e.g. using `--gcc-toolchain=`.

**Comment by illuhad** [comment]
You can use `clang++ --verbose` to check which gcc installation it picks.

**Comment by ipe-zhangyz** [comment]
OK, I'd check it.

**Comment by ipe-zhangyz** [comment]
`clang++ --verbose` shows that there are 3 candidate GCC installations and one of them is selected. Strangely, none of the three candidate GCC installations is the active version (the one that `which gcc` gives) when I built the LLVM.  I add the `GCC_INSTALL_PREFIX ` parameter in my cmake command line when building the LLVM, and then the output of `clang++ --verbose` becomes to this:
```
clang version 11.1.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/software/llvm-11.1/bin
Found HIP installation: /opt/rocm, version 2.8.19361-cbe6b65e
``` 
Yes, I switch to LLVM 11.1, which I have tried before trying LLVM 13.0.
Although I can't find any information of which GCC the clang was built against, it seems that it is GCC 9.3, because after rebuild the hipSYCL against this LLVM, there is no undefined symbol errors as before. However, errors like these occur:
```
/usr/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lgcc
```
I can solve the last three by adding `-L` parameters to the `syclcc` command line, but after I add the crtbegin.o file like this:
```
~/software/hipSYCL/bin/syclcc -std=c++17 -O2 -o test --hipsycl-targets=hip:gfx906 examples.cpp -I/home/software/llvm-11.1/include/c++/v1 -L/home/software/compiler/gcc-9.3.0/lib64 -L/home/software/compiler/gcc-9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0 /home/software/compiler/gcc-9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/crtbegin.o
```
the compiler crashed...
I also want to know if there is any parameter that can show the compiling command that is really used by `syclcc`.
Thank you!

**Comment by illuhad** [comment]
The crash probably happens because hipSYCL underneath compiles using `-x hip` or `-x cuda`. This causes clang to treat all file arguments as CUDA or HIP source files. Naturally, this fails spectacularly when one file is a `.o` binary object and not a source file ;) You would need to compile in two steps: First, compile to `.o` using `-c`, and then link the object files together with a separate `syclcc` invocation.
This is a limitation of how CUDA and HIP compilation with clang works. E.g. `hipcc` in ROCm will likely have the same problem.

You can show the command(s) that `syclcc` executes by either passing `--hipsycl-dryrun` or setting the environment variable `HIPSYCL_DRYRUN=1`.

```
/usr/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lgcc
```
This should not happen. To me it almost looks like clang is now configured without any gcc, and so it does not link any C++ standard library. Are you sure you have set `GCC_INSTALL_PREFIX` correctly?

**Comment by ipe-zhangyz** [comment]
You are right about the compiler crash problem. I have tried the two steps compilation, however, the three gcc libs are still not fount at the link step. I set `GCC_INSTALL_PREFIX` to the path of the libstdc++.so, but in that directory there is not libgcc.so or libgcc_s.so. What kind of directory should be set to the  `GCC_INSTALL_PREFIX` parameter?

**Comment by ipe-zhangyz** [comment]
The `GCC_INSTALL_PREFIX` should be the top level directory of the GCC installation, where there are 
```
bin  include  lib  lib64  libexec  share
```

**Comment by illuhad** [comment]
Correct, it should be the top level directory. Did setting the `GCC_INSTALL_PREFIX` correctly have any impact on your issue?

**Comment by ipe-zhangyz** [comment]
Yes, setting the `GCC_INSTALL_PREFIX` correctly solved all my problem. Now I can build and run the simple `example.cpp` and a more complex molecular dynamics code GROMACS 2022 with hipSYCL.
Thank you for your help!
