### ISSUE TITLE
Example doesn't build / Installation went wrong

### ISSUE THREAD

**Issue by alexschroeter** [AdaptiveCpp/AdaptiveCpp#689]
Hi all,

I cannot run the example in the repository. I am guessing my setup is wrong but I don't know where. I cannot build either for CUDA or ROCm.

**Error Description**
Error for ROCm
```
clang: error: unsupported option '--rocm-device-lib-path=/opt/rocm/amdgcn/bitcode'
clang: error: unsupported option '--rocm-path=/opt/rocm'
clang: error: no such file or directory: 'hip.amdgcn.bc'
clang: error: no such file or directory: 'ocml.amdgcn.bc'
clang: error: no such file or directory: 'ockl.amdgcn.bc'
clang: error: no such file or directory: 'oclc_finite_only_off.amdgcn.bc'
clang: error: no such file or directory: 'oclc_daz_opt_off.amdgcn.bc'
clang: error: no such file or directory: 'oclc_correctly_rounded_sqrt_on.amdgcn.bc'
clang: error: no such file or directory: 'oclc_unsafe_math_off.amdgcn.bc'
clang: error: no such file or directory: 'oclc_isa_version_900.amdgcn.bc'
clang: error: no such file or directory: 'oclc_wavefrontsize64_on.amdgcn.bc'
bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/build.make:83: recipe for target 'bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/bruteforce_nbody.cpp.o' failed
make[2]: *** [bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/bruteforce_nbody.cpp.o] Error 1
CMakeFiles/Makefile2:112: recipe for target 'bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/all' failed
make[1]: *** [bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

same for CUDA
```
clang: error: Unsupported CUDA gpu architecture: sm75
bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/build.make:83: recipe for target 'bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/bruteforce_nbody.cpp.o' failed
make[2]: *** [bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/bruteforce_nbody.cpp.o] Error 1
CMakeFiles/Makefile2:112: recipe for target 'bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/all' failed
make[1]: *** [bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

**To Reproduce**
* installed hipsycl via git commit 67885ff18f73e7758da13cce3c0a0725363439af
```
git clone https://github.com/illuhad/hipSYCL
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/opt/hipSYCL/ -DCMAKE_CXX_COMPILER=g++-10 ..
sudo make install
cd ../../examples
cmake -DHIPSYCL_PLATFORM=rocm -DHIPSYCL_GPU_ARCH=gfx900 ..
```

**Expected behavior**
Build the example

**Describe your setup**
ccmake output
```
AMDDeviceLibs_DIR                /opt/rocm/lib/cmake/AMDDeviceLibs
 AMDGPU_TARGETS                   gfx900;gfx906;gfx908;gfx90a;gfx1030
 CLANG_EXECUTABLE_PATH            /usr/lib/llvm-10/bin/clang++
 CMAKE_BUILD_TYPE
 CMAKE_INSTALL_PREFIX             /opt/hipSYCL
 CUDA_CXX_FLAGS                   -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike
 CUDA_DRIVER_LIBRARY              /usr/local/cuda/lib64/stubs/libcuda.so
 CUDA_HOST_COMPILER               /usr/bin/cc
 CUDA_LINK_LINE                   -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND
 CUDA_TOOLKIT_ROOT_DIR            /usr/local/cuda
 CUDA_USE_STATIC_CUDA_RUNTIME     ON
 CUDA_rt_LIBRARY                  /usr/lib/x86_64-linux-gnu/librt.so
 DEFAULT_GPU_ARCH
 ENABLE_ROCM_UNIFIED_MEMORY_API   ON
 FOUND_CLANG_INCLUDE_PATH         /opt/rocm/include
 GPU_TARGETS                      gfx900;gfx906;gfx908;gfx90a;gfx1030
 HIPSYCL_DEBUG_LEVEL              2
 HIP_CLANG_INCLUDE_PATH           /opt/rocm/llvm/lib/clang/13.0.0/include
 HIP_DIR                          /opt/rocm/lib/cmake/hip
 HSA_HEADER                       /opt/rocm-4.5.0/include
 LLVM_DIR                         /usr/lib/llvm-10/cmake
 NVCXX_COMPILER                   NVCXX_COMPILER-NOTFOUND
 OMP_CXX_FLAGS                    -I/usr/include -fopenmp
 OMP_LINK_LINE                    -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
 ROCM_CXX_FLAGS                   -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike -isystem /usr/lib/llvm-10/lib/clang/10.0.0/include/.. -U__FLOAT128__ -
 ROCM_LIBS                        -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
 ROCM_LINK_LINE                   -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
 SEQUENTIAL_CXX_FLAGS             -I/usr/include
 SEQUENTIAL_LINK_LINE             -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -lomp -Wl,-rpath=/usr/lib/x86_64-linux-gnu
 SYCLCC_CONFIG_FILE_GLOBAL_INST   OFF
 WITH_CUDA_BACKEND                ON
 WITH_CUDA_NVCXX_ONLY             OFF
 WITH_ROCM_BACKEND                ON
 amd_comgr_DIR                    /opt/rocm/lib/cmake/amd_comgr
 hsa-runtime64_DIR                /opt/rocm/lib/cmake/hsa-runtime64
```

hipconfig
```
HIP version  : 4.4.21401-bedc5f61

== hipconfig
HIP_PATH     : /opt/rocm/hip
ROCM_PATH    : /opt/rocm
HIP_COMPILER : clang
HIP_PLATFORM : nvidia
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__= -D__HIP_PLATFORM_NVIDIA__= -I/opt/rocm/hip/include -I/usr/local/cuda/include

== nvcc
CUDA_PATH   : /usr/local/cuda
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

=== Environment Variables
PATH=/home/user/.local/bin:/home/user/bin:/usr/local/go/bin:/home/user/miniconda3/bin:/home/user/miniconda3/condabin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/home/user/go/bin:/opt/hipSYCL/bin
LD_LIBRARY_PATH=/usr/local/cuda/lib64:
HIP_PLATFORM=nvidia
HIP_PATH=/opt/rocm/hip

== Linux Kernel
Hostname     : hostname
Linux hostname 5.4.0-96-generic #109~18.04.1-Ubuntu SMP Thu Jan 13 15:06:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

Thanks for the help

**Comment by illuhad** [comment]
>  HIP_CLANG_INCLUDE_PATH           /opt/rocm/llvm/lib/clang/13.0.0/include
 HIP_DIR                          /opt/rocm/lib/cmake/hip
 HSA_HEADER                       /opt/rocm-4.5.0/include
 LLVM_DIR                         /usr/lib/llvm-10/cmake

You have built hipSYCL against clang 10. This clang version is far too old to support ROCm 4.5, and presumably also too old to support `sm_75` on the CUDA side.
ROCm 4.5 needs at least clang 13. You can try either upgrading your clang installation, or building against the clang 13 that already comes with ROCm 4.5 (it is also able to compile for CUDA). Please set `LLVM_DIR`, `CLANG_EXECUTABLE_PATH` and `CLANG_INCLUDE_PATH` accordingly and rebuild hipSYCL.

EDIT:
* On CUDA, it complains about CUDA architecture `sm75` being unknown. If this is how you've specified it, the spelling is wrong: clang wants `sm_75`.
* `HIPSYCL_PLATFORM` and `HIPSYCL_GPU_ARCH` is deprecated, please use `HIPSYCL_TARGETS` :-) E.g. `HIPSYCL_TARGETS="omp;cuda:sm_75"` to compile for OpenMP and sm_75.

**Comment by alexschroeter** [comment]
Thanks for the help.

I don't exactly understand why the LLVM_DIR wouldn't take. I assume '/opt/rocm/llvm' would be correct. But llvm has a repository for ubuntu so that was fixed very easily. If anybody has the same issue I had to tell cmake to use cuda-10.0 (maybe later versions also work but this was the one I had installed and 11.6 wasn't working). 

Solved.

**Comment by illuhad** [comment]
Great you got it working!

LLVM's cmake infrastructure needs the directory where the LLVM cmake files are, not the top level LLVM directory. From the top of my head this would usually be something like `/opt/rocm/llvm/lib/cmake/llvm` for ROCm LLVM.

I haven't tried CUDA 11.6 yet, but I have used up to 11.5 and they all work. However, clang is a bit picky about how it wants CUDA to be installed and dislikes the way some distributions install it: 
https://www.llvm.org/docs/CompileCudaWithLLVM.html#id3
(the "prerequisites" section)

It also says there that it only supports up to 11.5, but for a long time the official support ended at 10.1 or 10.2, and newer versions still worked fine (it just treats them like the latest supported version), so I wouldn't be too discouraged by that statement..

**Comment by alexschroeter** [comment]
Thank you for the further feedback.

You are correct it also works with CUDA 11.6. I am guessing I was thrown by the warning and maybe an error elsewhere.

```
[ 50%] Building CXX object bruteforce_nbody/CMakeFiles/bruteforce_nbody.dir/bruteforce_nbody.cpp.o
clang: warning: Unknown CUDA version. cuda.h: CUDA_VERSION=11060. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
```

I tried using ROCm's clang but I got multiple linking errors while building the example. I am happy with my solution, so thank you for the fast responses. 

One more question though. Do you have a multi-device example somewhere that I could try? I would like to see my AMD GPUs, Nvidia GPUs, and CPU Cores all working the same problem. I read that Multi-Device-Queue is not optimized yet which I can live with.

Best Regards,
Alex

**Comment by illuhad** [comment]
> One more question though. Do you have a multi-device example somewhere that I could try? I would like to see my AMD GPUs, Nvidia GPUs, and CPU Cores all working the same problem. I read that Multi-Device-Queue is not optimized yet which I can live with.

First of all, to get this working with clang 13 you will need PR #683.

Do you really want multi-device queues, or do you just want to be able to dispatch at runtime to multiple devices?
multi-device queue is a hipSYCL extension where you can submit your kernels to a single queue which will then attempt to *automatically and transparently* perform load balancing by distributing kernels across multiple devices.
You can find some code snippets here: https://github.com/illuhad/hipSYCL/blob/develop/doc/multi-device-queue.md
As you are aware, you probably won't get good performance out of it at the moment.

If you just want to dispatch manually to multiple devices (as intended by the SYCL spec), you can do something like this:
```c++
// Get all devices
auto devs = sycl::device::get_devices();
// Construct one queue for each device
std::vector<sycl::queue> queues;
for(auto dev : devs) {
  queues.push_back(sycl::queue{sycl::context{dev}, dev});
}
// Submit work to all devices
for(auto q : queues) {
  q.parallel_for(....);
}
```

Note that there is currently a limitation in the runtime: What we call "triangle" copies is not yet supported. A triangle copy refers to the case where we cannot directly copy from device A to device B because they are from different backends (e.g.  there is no direct way to copy from an AMD GPU to an NVIDIA GPU) and therefore have to do `A -> host` and then `host -> B`. You can circumvent by manually triggering the necessary copies.

You also need to make sure that your code is compiled for all devices you want to run on, e.g.:
`syclcc --hipsycl-explicit-multipass --hipsycl-targets="omp;cuda:sm_75;hip:gfx900"` or
`syclcc --hipsycl-targets="omp;cuda.explicit-multipass:sm_75;hip:gfx900"` 

The explicit multipass argument is explained here: https://github.com/illuhad/hipSYCL/blob/develop/doc/compilation.md

By the way, this is also exactly why `HIPSYCL_PLATFORM`/`HIPSYCL_GPU_ARCH` where superseded by `HIPSYCL_TARGETS`, since there is no way to specify multiple simultaneous targets with the `HIPSYCL_PLATFORM` approach :-)

**Comment by keryell** [comment]
I am just curious about whether
```c++
queues.push_back({dev});
```
would not be enough? Why do you need to specify the context?

**Comment by illuhad** [comment]
@keryell You're completely right, that is in the spec and is also implemented in hipSYCL. I just kind of tend to forget about this constructor because I took on the habit of specifying the context for these kinds of constructors to avoid constructing unnecessary contexts - but since there's no context sharing in this example anyway, there's really no point to this :-)

**Comment by keryell** [comment]
We need to advertise how simple SYCL can be. :-)
