### ISSUE TITLE
Hinting/limiting the kernel work-group size

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#714]
SYCL offers a standardized way to specify the expected work-group size for a given kernel: `sycl::reqd_work_group_size`, and a weaker version `sycl::work_group_size_hint`. 

I would like to use such attributes to hint the expected kernel size to the optimizer. Specifically, I know in advance the exact kernel dimensions, but even weaker hinting (e.g., upper bound) is interesting.

As far as I understand, neither of those attribute are supported in hipSYCL currently.

I tried adding `clang::amdgpu_flat_work_group_size` attribute (which `__launch_bounds__` expands into) to the kernel lambda, without much success:

```cpp
[[clang::amdgpu_flat_work_group_size(64,64)]]
return [=](sycl::nd_item<3> itemIdx) {
// error: 'amdgpu_flat_work_group_size' attribute cannot be applied to a statement

return [=](sycl::nd_item<3> itemIdx) [[clang::amdgpu_flat_work_group_size(64,64)]] {
// error: 'amdgpu_flat_work_group_size' attribute cannot be applied to types

return [=](sycl::nd_item<3> itemIdx) { [[clang::amdgpu_flat_work_group_size(64,64)]]
// error: 'amdgpu_flat_work_group_size' attribute only applies to kernel functions

#pragma clang attribute push(__attribute__((amdgpu_flat_work_group_size(64, 64))), apply_to=function)
return [=](sycl::nd_item<3> itemIdx) {
#pragma clang attribute pop
// error: 'amdgpu_flat_work_group_size' attribute only applies to kernel functions
```

Could you please suggest if there are any near-term plans of adding `sycl::reqd_work_group_size` or `sycl::work_group_size_hint` to hipSYCL, or is there any possible workaround (any ROCm-specific solution is okay).

**Comment by illuhad** [comment]
We have zero plans to support attributes. This functionality is broken in SYCL and directly contradicts the goal defined in the specification of allowing library-only implementations. hipSYCL supports several compilation flows that are library-only where this cannot be implemented.

There are ideas how attributes could be replaced in future SYCL, such as #543 or constexpr property lists that Intel is working on.

Unfortunately, clang only allows those amdgpu attributes on `__global__` functions. So you would only be able to use them if you define a `__global__` kernel and invoke it from a `hipSYCL_enqueue_custom_operation`.

**Comment by al42and** [comment]
Ok, thank you for your swift response!
