### ISSUE TITLE
syclcc inconsistently (incorrectly?) injects names into namespace std::

### ISSUE THREAD

**Issue by mreineck** [AdaptiveCpp/AdaptiveCpp#730]
**Bug summary**
Compiling a file with no `#include` statements still populates the `std::` namespace with some names, but only for a subset of SYCL backends.

**To Reproduce**
Compile the snippet below with

`syclcc --hipsycl-targets=cuda:sm_80 minmax.cc -c`

and with

`syclcc --hipsycl-targets=omp minmax.cc -c`

The first command finishes without error (which I think it shouldn't), and the second outputs the expected warnings about undefined `min`, `max`, etc.

```
using namespace std;
long f1 (long a, long b) { return max(a,b); }
long f2 (long a, long b) { return min(a,b); }
long f3 (long a) { return abs(a); }
double f4 (double a) { return sin(a); }
```
**Expected behavior**
I would expect the command to return "undeclared identifier" errors in both cases.

**Describe your setup**

`hipSYCL` was installed from the `develop` branch a few days ago, using `clang` version 12.

**Comment by illuhad** [comment]
This seems to be a clang thing, not a hipSYCL thing. clang's CUDA toolchain apparently defines some builtins no matter if standard headers are included or not.
This command reproduces the same behavior without hipSYCL:
```
/usr/bin/clang++ -std=c++17 -x cuda --cuda-path=/opt/cuda --cuda-gpu-arch=sm_61  test.cpp
```
One interesting thing is that the clang CUDA builtins are `__device__` and therefore should not participate in overload resolution when used inside `__host__` functions like `f1` etc. Therefore, I would expect errors that it cannot call a `__device__` function from a `__host__` function. Indeed, this is what happens if we remove `-std=c++17`:
```
test.cpp:3:35: error: no matching function for call to 'min'
long f2 (long a, long b) { return min(a,b); }
                                  ^~~
/usr/lib/clang/13.0.1/include/__clang_cuda_math.h:197:16: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE__ int min(int __a, int __b) { return __nv_min(__a, __b); }
               ^
/opt/cuda/include/crt/math_functions.hpp:868:38: note: candidate function not viable: call to __device__ function from __host__ function
__MATH_FUNCTIONS_DECL__ unsigned int min(const unsigned int a, const unsigned int b)
                                     ^
/opt/cuda/include/crt/math_functions.hpp:873:38: note: candidate function not viable: call to __device__ function from __host__ function
__MATH_FUNCTIONS_DECL__ unsigned int min(const int a, const unsigned int b)
                                     ^
/opt/cuda/include/crt/math_functions.hpp:878:38: note: candidate function not viable: call to __device__ function from __host__ function
__MATH_FUNCTIONS_DECL__ unsigned int min(const unsigned int a, const int b)
                                     ^
/opt/cuda/include/crt/math_functions.hpp:883:34: note: candidate function not viable: call to __device__ function from __host__ function
__MATH_FUNCTIONS_DECL__ long int min(const long int a, const long int b)
                                 ^
/opt/cuda/include/crt/math_functions.hpp:902:43: note: candidate function not viable: call to __device__ function from __host__ function
__MATH_FUNCTIONS_DECL__ unsigned long int min(const unsigned long int a, const unsigned long int b)
....
```

I don't know why `-std=c++17` changes something. My guess is that things like `constexpr` enter the equation then, which can change overload resolution for device builtins.

**Comment by mreineck** [comment]
Fascinating. Thanks for the analysis and sorry for the false alarm!
The real issue that led me to this reduced test case is a bit more complicated. I'll try to find out whether this is also purely `clang`-related; I expect it is.
On the off chance that I can reproduce he original problem only with hipSYCL headers loaded, I'll reopen this and update the reproducer.
