### ISSUE TITLE
build tests failed with version 0.9.2

### ISSUE THREAD

**Issue by pyqhaoku** [AdaptiveCpp/AdaptiveCpp#732]
## question
I want to execte the self test program, but build failed, What's the problem?
## build log
[hipsycl-0.9.2-tests-build-log.txt](https://github.com/illuhad/hipSYCL/files/8560526/hipsycl-0.9.2-tests-build-log.txt)
## build env
[root@simon28li build]# gcc -v
Reading specs from /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/lib/gcc/aarch64-unknown-linux-gnu/10.3.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/libexec/gcc/aarch64-unknown-linux-gnu/10.3.0/lto-wrapper
Target: aarch64-unknown-linux-gnu
Configured with: /home/spack-stage/root/spack-stage-gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/spack-src/configure --prefix=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm --with-pkgversion='Spack GCC' --with-bugurl=https://github.com/spack/spack/issues --disable-multilib --enable-languages=c,c++,fortran --disable-nls --with-system-zlib --with-zstd=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/zstd-1.4.5-llw3smv73bxlxedylprc4dnagnfreyug --with-mpfr-include=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpfr-4.0.2-xw7mvbkg2tn2odcaztn4iulswznxcgbq/include --with-mpfr-lib=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpfr-4.0.2-xw7mvbkg2tn2odcaztn4iulswznxcgbq/lib --with-gmp-include=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gmp-6.1.2-zyhr2mb6lowbsjrenwd3gtgtpznie6rh/include --with-gmp-lib=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gmp-6.1.2-zyhr2mb6lowbsjrenwd3gtgtpznie6rh/lib --with-mpc-include=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpc-1.1.0-ed4mcdbrp76hwfuhkff4kvdrpysseahx/include --with-mpc-lib=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpc-1.1.0-ed4mcdbrp76hwfuhkff4kvdrpysseahx/lib --without-isl --with-stage1-ldflags='-Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/lib64 -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gmp-6.1.2-zyhr2mb6lowbsjrenwd3gtgtpznie6rh/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpfr-4.0.2-xw7mvbkg2tn2odcaztn4iulswznxcgbq/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpc-1.1.0-ed4mcdbrp76hwfuhkff4kvdrpysseahx/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/zlib-1.2.11-wclep75baky5gi4gu5erof55jpbtgbgy/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/zstd-1.4.5-llw3smv73bxlxedylprc4dnagnfreyug/lib' --with-boot-ldflags='-Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gcc-10.3.0-ullvf66dh5tlvn5gezt2a5g3sqw6eudm/lib64 -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/gmp-6.1.2-zyhr2mb6lowbsjrenwd3gtgtpznie6rh/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpfr-4.0.2-xw7mvbkg2tn2odcaztn4iulswznxcgbq/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/mpc-1.1.0-ed4mcdbrp76hwfuhkff4kvdrpysseahx/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/zlib-1.2.11-wclep75baky5gi4gu5erof55jpbtgbgy/lib -Wl,-rpath,/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/zstd-1.4.5-llw3smv73bxlxedylprc4dnagnfreyug/lib -static-libstdc++ -static-libgcc' --enable-host-shared
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Spack GCC)
[root@simon28li build]#
[root@simon28li build]# cmake --version
cmake version 3.19.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

[root@simon28li build]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

**Comment by illuhad** [comment]
libstdc++ is too old and does not contain the symbols for `std::filesystem`. For some earlier gcc/libstdc++ versions, that library was shipped separately and needs to be linked manually. See also #667

**Comment by illuhad** [comment]
Closing because of lack of feedback.

**Comment by simon28li** [comment]
> libstdc++ is too old and does not contain the symbols for `std::filesystem`. For some earlier gcc/libstdc++ versions, that library was shipped separately and needs to be linked manually. See also #667

I have tried the PR submitted in # 667, but it is the same error. It seems that the PR itself has not been integrated. Do I still need to modify it?
