### ISSUE TITLE
Cython in combination with SYCL

### ISSUE THREAD

**Issue by vadkra** [AdaptiveCpp/AdaptiveCpp#733]
Hi everyone!

I'm trying to implement a simple program, which uses Cython in combination with SYCL. My goal is to create a C++ module, which uses SYCL and can then be called and used by a Python function. You can see the program here:

https://github.com/vadkra/Sycl_Cython

I'm encountering the problem of Python throwing out an import error whenever I try to create a queue with SYCL. When I leave the queue out, everything works fine.

Does anyone have a clue what I did wrong? Or is it not possible to combine Cython and SYCL? 

Thank you in advance!

**Comment by illuhad** [comment]
I'm not an expert in cython. If I understand your code correctly, you just wish to expose a C++ function that is callable from python, which then internally uses SYCL. I see no reason why this shouldn't work.

Where do you define the `add()` function? `add.cpp` just defines `main()`, but not `add()`. As far as I can see, `add()` is defined nowhere.

Also, it's probably better to not copy `hipsycl-config*` files to your cmake infrastructure. Those files come with the hipSYCL installation and should be left there, as they might change between hipSYCL versions.

**Comment by illuhad** [comment]
Closing because of lack of feedback.
