### ISSUE TITLE
Information descriptors are enum values, must be structs

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#774]
**Bug summary**

Per [2020r5 spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:information-descriptors), the info descriptors (like `sycl::info::device::device_type`) must be `struct`s:

```cpp
namespace sycl {
namespace info {
namespace platform {
struct profile;
}}}
```

In hipSYCL, they are [enum values](https://github.com/illuhad/hipSYCL/blob/2d937998228826f183a670d927749a4e6cb93a11/include/hipSYCL/sycl/info/platform.hpp#L41):

```cpp
namespace sycl {
namespace info {
enum class platform : unsigned int
{
  profile,
}}}
```

**To Reproduce**

```cpp
// Compile with syclcc test.cpp --hipsycl-targets=omp
#include <sycl/sycl.hpp>
int main() {
  using dt = sycl::info::device::device_type;
  return 0;
}
```

**Expected behavior**

The code above should compile fine. In practice, it produces an error:

`test.cpp:4:14: error: no type named 'device_type' in 'hipsycl::sycl::info::device'; did you mean 'hipsycl::sycl::info::device_type'?`

**Describe your setup**
* Latest `develop` version of hipSYCL, 2d937998228826f183a670d927749a4e6cb93a11
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang-14

**Additional context**

Pretty minor thing and easy to work around. Just wanted to record it.

**Comment by aaronmondal** [comment]
Potentially related is that
> Information query descriptors have been changed to structures under namespaces named accordingly. param_traits has been removed and the return type of an information query is now contained in the descriptor.

at the bottom of [Appendix D](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#cha:what-changed-from).

In hipSYCL:
https://github.com/illuhad/hipSYCL/blob/f31fd92f9cb90852e75025c7b7d9ca748f15c31a/include/hipSYCL/sycl/info/param_traits.hpp#L38-L44

**Comment by illuhad** [comment]
Yes, this is all due to changes from SYCL 1.2.1 to 2020. For most applications, the practical effect of this is fairly limited, so it wasn't a priority to do all the refactoring work to change this to SYCL 2020 until now.
