### ISSUE TITLE
Enforce squash merging by default

### ISSUE THREAD

**Issue by aaronmondal** [AdaptiveCpp/AdaptiveCpp#776]
**Describe the motivation for the feature request**
The git history for this repository is kind of messy and riddled with duplicate commits/merge commits. This makes it hard to track changes, especially small ones. It also produces commits on the main branch that may not necessarily work. If a PR like
```
1. New commit with a bug
2. Fix bug
3. Address review comments
```
is not squash merged, the main branch will not be buildable at the intermediary commit (1.).

**Describe the solution you'd like**
Squash merging by default would create one commit on `main` for each PR. If a contributor revises a PR multiple times, the intermediary commits get "squashed away", resulting in a cleaner git history on `main`.

**If applicable, describe alternatives you've considered**
* It is unrealistic to change the git hoster (to e.g. Gerrit).
* Rebase merging does not solve the issue of adding potentially faulty commits to `main`. It would be inconvenient to expect contributors to squash, and review history would probably be lost.

Other merging strategies certainly have their use cases (for instance for large feature commits), but I think a healthy default would be a "1 PR = 1 Commit" approach.

[Related docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges)

**Comment by illuhad** [comment]
Thank you, we can take this into account for future PRs/currently unmerged PRs. I'm not sure the problem is easily solvable retroactively for the already published git history.

**Comment by aaronmondal** [comment]
@illuhad Cool, Thanks!

Yeah it probably won't be possible to change this retroactively. The only way I can think of is creating a new branch and cherrypicking the `develop` branch manually into it :rofl: Probably not too realistic for ~2000 commits :rofl:

On second thought it may not be *THAT* unrealistic. Ok I'll check whether something like that would preserve the correct contribution attributions. If it does, I'll see what my cherrypicks per hour speed is and how long this would take :rofl:

**Comment by aaronmondal** [comment]
Unfortunately unrealistic after all. I guess we'll just have to live with it for the existing git history.
