### ISSUE TITLE
clang crashes if compile with `-std=c++20` & libstdc++ 12 & ROCm

### ISSUE THREAD

**Issue by fxzjshm** [AdaptiveCpp/AdaptiveCpp#801]
**Bug summary**
The clang compiler crashes when compiling for ROCm/HIP with `-std=c++20` and libstdc++ 12 .

If compile for OpenMP, or with `-std=c++17`, or uninstall `libstdc++-12-dev`, no crash like this happens. 
I have to remove `libstdc++-12-dev` so that it uses `libstdc++-11-dev` and doesn't crash.

Log:

<details>
<pre>$ /opt/hipSYCL/bin/syclcc --hipsycl-targets=&quot;hip:gfx906&quot; -std=c++20 sycl.cpp -o test
syclcc warning: No optimization flag was given, optimizations are disabled by default. Performance may be degraded. Compile with e.g. -O2/-O3 to enable optimizations.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/lib/llvm-14/bin/clang -cc1 -triple amdgcn-amd-amdhsa -aux-triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name sycl.cpp -mrelocation-model pic -pic-level 1 -fhalf-no-semantic-interposition -mframe-pointer=all -fno-rounding-math -mconstructor-aliases -aux-target-cpu x86-64 -fcuda-is-device -mllvm -amdgpu-internalize-symbols -fcuda-allow-variadic-functions -fvisibility hidden -fapply-global-visibility-to-externs -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/hip.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ocml.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ockl.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_daz_opt_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_finite_only_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_wavefrontsize64_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_isa_version_906.bc -target-cpu gfx906 -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -resource-dir /usr/lib/llvm-14/lib/clang/14.0.0 -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include/cuda_wrappers -internal-isystem /opt/rocm/include -include __clang_hip_runtime_wrapper.h -isystem /opt/hipSYCL/bin/../include/hipSYCL/std/hiplike -isystem /usr/lib/llvm-14/lib/clang/14.0.0/include/.. -I /opt/hipSYCL/bin/../include/ -D __HIPSYCL__ -U __FLOAT128__ -U __SIZEOF_FLOAT128__ -I /opt/rocm/include -I /opt/rocm/include -D __HIP_ROCclr__ -D __HIPSYCL_ENABLE_HIP_TARGET__ -D __HIPSYCL_CLANG__ -D __HIPSYCL_ENABLE_OMPHOST_TARGET__ -I /usr/include -D _ENABLE_EXTENDED_ALIGNED_STORAGE -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -fno-autolink -fdebug-compilation-dir=/home/fxzjshm/workspace/sycl-test -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -load /opt/hipSYCL/bin/../lib/libhipSYCL_clang.so -fpass-plugin=/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -cuid=974dc33148a56bb1 -fcuda-allow-variadic-functions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/sycl-ee7fdd/sycl-gfx906.o -x hip sycl.cpp
1.	/opt/hipSYCL/bin/../include/hipSYCL/runtime/dag_node.hpp:152:2: current parser token &apos;;&apos;
2.	/opt/hipSYCL/bin/../include/hipSYCL/runtime/dag_node.hpp:38:1: parsing namespace &apos;hipsycl&apos;
3.	/opt/hipSYCL/bin/../include/hipSYCL/runtime/dag_node.hpp:39:1: parsing namespace &apos;hipsycl::rt&apos;
4.	/opt/hipSYCL/bin/../include/hipSYCL/runtime/dag_node.hpp:48:1: parsing struct/union/class body &apos;hipsycl::rt::dag_node&apos;
 #0 0x00007fea890abd01 llvm::sys::PrintStackTrace(llvm::raw_ostream&amp;, int) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xe3fd01)
 #1 0x00007fea890a9a3e llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xe3da3e)
 #2 0x00007fea890ac236 (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xe40236)
 #3 0x00007fea87d53520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007fea8f792739 clang::FunctionDecl::getNumParams() const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xc54739)
 #5 0x00007fea8f7bb1b9 clang::CXXMethodDecl::isCopyAssignmentOperator() const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xc7d1b9)
 #6 0x00007fea8fc5f767 clang::Sema::checkTypeSupport(clang::QualType, clang::SourceLocation, clang::ValueDecl*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1121767)
 #7 0x00007fea8fee7b33 clang::Sema::DiagnoseUseOfDecl(clang::NamedDecl*, llvm::ArrayRef&lt;clang::SourceLocation&gt;, clang::ObjCInterfaceDecl const*, bool, bool, clang::ObjCInterfaceDecl*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x13a9b33)
 #8 0x00007fea8fef3e8b clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&amp;, clang::DeclarationNameInfo const&amp;, clang::NamedDecl*, clang::NamedDecl*, clang::TemplateArgumentListInfo const*, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x13b5e8b)
 #9 0x00007fea902fe6f2 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x17c06f2)
#10 0x00007fea902f44bc (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x17b64bc)
#11 0x00007fea902f33ef (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x17b53ef)
#12 0x00007fea902e6cea clang::Sema::SubstExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x17a8cea)
#13 0x00007fea8fd8ebbf (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1250bbf)
#14 0x00007fea8fd899f6 clang::Sema::CheckConstraintSatisfaction(clang::NamedDecl const*, llvm::ArrayRef&lt;clang::Expr const*&gt;, llvm::ArrayRef&lt;clang::TemplateArgument&gt;, clang::SourceRange, clang::ConstraintSatisfaction&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x124b9f6)
#15 0x00007fea8fd8a59b clang::Sema::CheckFunctionConstraints(clang::FunctionDecl const*, clang::ConstraintSatisfaction&amp;, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x124c59b)
#16 0x00007fea9018642d clang::Sema::AddMethodCandidate(clang::CXXMethodDecl*, clang::DeclAccessPair, clang::CXXRecordDecl*, clang::QualType, clang::Expr::Classification, llvm::ArrayRef&lt;clang::Expr*&gt;, clang::OverloadCandidateSet&amp;, bool, bool, llvm::MutableArrayRef&lt;clang::ImplicitConversionSequence&gt;, clang::OverloadCandidateParamOrder) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x164842d)
#17 0x00007fea900a45a6 clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x15665a6)
#18 0x00007fea8fd9bbfa clang::Sema::inferCUDATargetForImplicitSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, clang::CXXMethodDecl*, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x125dbfa)
#19 0x00007fea8fe60daa clang::Sema::DeclareImplicitCopyAssignment(clang::CXXRecordDecl*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1322daa)
#20 0x00007fea8fe5f1f9 clang::Sema::AddImplicitlyDeclaredMembersToClass(clang::CXXRecordDecl*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x13211f9)
#21 0x00007fea8fdde5a1 clang::Sema::ActOnFields(clang::Scope*, clang::SourceLocation, clang::Decl*, llvm::ArrayRef&lt;clang::Decl*&gt;, clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesView const&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x12a05a1)
#22 0x00007fea8fe5ebf3 clang::Sema::ActOnFinishCXXMemberSpecification(clang::Scope*, clang::SourceLocation, clang::Decl*, clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesView const&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1320bf3)
#23 0x00007fea8f579504 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesWithRange&amp;, unsigned int, clang::Decl*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa3b504)
#24 0x00007fea8f576cd6 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&amp;, clang::Parser::ParsedTemplateInfo const&amp;, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributesWithRange&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa38cd6)
#25 0x00007fea8f556854 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&amp;, clang::Parser::ParsedTemplateInfo const&amp;, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa18854)
#26 0x00007fea8f6022c8 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&amp;, clang::ParsingDeclSpec&amp;, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xac42c8)
#27 0x00007fea8f602060 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&amp;, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xac4060)
#28 0x00007fea8f6014da clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&amp;, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xac34da)
#29 0x00007fea8f56fcbc clang::Parser::ParseInnerNamespace(llvm::SmallVector&lt;clang::Parser::InnerNamespaceInfo, 4u&gt; const&amp;, unsigned int, clang::SourceLocation&amp;, clang::ParsedAttributes&amp;, clang::BalancedDelimiterTracker&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa31cbc)
#30 0x00007fea8f56f809 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&amp;, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa31809)
#31 0x00007fea8f55588e clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&amp;, clang::ParsedAttributesWithRange&amp;, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa1788e)
#32 0x00007fea8f600c74 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&amp;, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xac2c74)
#33 0x00007fea8f56fcbc clang::Parser::ParseInnerNamespace(llvm::SmallVector&lt;clang::Parser::InnerNamespaceInfo, 4u&gt; const&amp;, unsigned int, clang::SourceLocation&amp;, clang::ParsedAttributes&amp;, clang::BalancedDelimiterTracker&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa31cbc)
#34 0x00007fea8f56f809 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&amp;, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa31809)
#35 0x00007fea8f55588e clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&amp;, clang::ParsedAttributesWithRange&amp;, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa1788e)
#36 0x00007fea8f600c74 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&amp;, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xac2c74)
#37 0x00007fea8f5ffb1d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr&lt;clang::DeclGroupRef&gt;&amp;, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xac1b1d)
#38 0x00007fea8f5428ed clang::ParseAST(clang::Sema&amp;, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa048ed)
#39 0x00007fea906b6b71 clang::CodeGenAction::ExecuteAction() (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1b78b71)
#40 0x00007fea91052b57 clang::FrontendAction::Execute() (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x2514b57)
#41 0x00007fea90faa3a6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&amp;) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x246c3a6)
#42 0x00007fea910cc45b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x258e45b)
#43 0x000000000041328b cc1_main(llvm::ArrayRef&lt;char const*&gt;, char const*, void*) (/usr/lib/llvm-14/bin/clang+0x41328b)
#44 0x00000000004114bc (/usr/lib/llvm-14/bin/clang+0x4114bc)
#45 0x0000000000411307 main (/usr/lib/llvm-14/bin/clang+0x411307)
#46 0x00007fea87d3ad90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#47 0x00007fea87d3ae40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#48 0x000000000040e3b5 _start (/usr/lib/llvm-14/bin/clang+0x40e3b5)
clang: <font color="#C01C28"><b>error: </b></font><b>unable to execute command: Segmentation fault (core dumped)</b>
clang: <font color="#C01C28"><b>error: </b></font><b>clang frontend command failed due to signal (use -v to see invocation)</b>
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-14/bin
clang: <font color="#171421"><b>note: </b></font>diagnostic msg: Error generating preprocessed source(s).</pre>

</details>

<br/>

**To Reproduce**
Code is minimal: (assume file name is test.cpp)
```c++
#include <sycl/sycl.hpp>

int main() {
  return 0;
}
```
Command: `/opt/hipSYCL/bin/syclcc --hipsycl-targets="hip:gfx906" -std=c++20 test.cpp -o test`

**Expected behavior**
Compiler doesn't crash like above.

**Describe your setup**
* Installed hipSYCL develop branch (commit `cc2e355`) to `/opt/hipSYCL`
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang: `Ubuntu clang version 14.0.0-1ubuntu1` shipped with Ubuntu 22.04
   * host compiler: `gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)`, or clang 14
   * CUDA is not enabled
   * ROCm 5.2.0 or 5.2.1 from https://repo.radeon.com/rocm/apt/
* How you have compiled your application and which arguments you have passed to `syclcc`. In particular, which backends and hardware you have compiled for.
   * Command: `/opt/hipSYCL/bin/syclcc --hipsycl-targets="hip:gfx906" -std=c++20 test.cpp -o test`

**Optional additional diagnostic information**
The following information can potentially help us:
* For compilation/toolchain or setup-related issues: Setting the environment variable `HIPSYCL_DRYRUN=1` during compilation will cause `syclcc` to print the commands it would execute instead of actually executing. This can help verify the sanity of your setup.

```
/usr/lib/llvm-14/bin/clang++ -I/opt/hipSYCL/bin/../include/ -D__HIPSYCL__ -isystem /opt/hipSYCL/bin/../include/hipSYCL/std/hiplike -isystem /usr/lib/llvm-14/lib/clang/14.0.0/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I/opt/rocm/include -I/opt/rocm/include --rocm-device-lib-path=/opt/rocm/amdgcn/bitcode --rocm-path=/opt/rocm -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__ -x hip -D__HIPSYCL_ENABLE_HIP_TARGET__ -fplugin=/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_CLANG__ --cuda-gpu-arch=gfx906 -fpass-plugin=/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE -std=c++20 sycl.cpp -o test -L/opt/hipSYCL/bin/../lib/ -lhipSYCL-rt -Wl,-rpath=/opt/hipSYCL/bin/../lib/ -Wl,-rpath=/opt/rocm/lib -Wl,-rpath=/opt/rocm/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64 -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
```

* `syclcc --hipsycl-version` prints information about the hipSYCL configuration that may be interesting for setup-related issues.

<details>

```
syclcc [hipSYCL compilation driver], Copyright (C) 2018-2022 Aksel Alpay and the hipSYCL project
  hipSYCL version: 0.9.2
  Installation root: /opt/hipSYCL
  Plugin LLVM version: 14, can accelerate CPU: True
  Available runtime backends:
     librt-backend-omp.so
     librt-backend-hip.so


Full configuration [can be overriden using environment variables or command line arguments]:
    version-major: 0
    version-minor: 9
    version-patch: 2
    plugin-llvm-version-major: 14
    plugin-with-cpu-acceleration: true
    default-clang: /usr/lib/llvm-14/bin/clang++
    default-nvcxx: (unconfigured)
    default-platform: rocm
    default-cuda-path: (unconfigured)
    default-gpu-arch: (unconfigured)
    default-cpu-cxx: /usr/bin/c++
    default-rocm-path: /opt/rocm
    default-use-bootstrap-mode: false
    default-is-dryrun: false
    default-use-accelerated-cpu: true
    default-clang-include-path: /usr/lib/llvm-14/lib/clang/14.0.0/include/..
    default-sequential-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
    default-sequential-cxx-flags: -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-omp-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
    default-omp-cxx-flags: -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
    default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike -isystem /usr/lib/llvm-14/lib/clang/14.0.0/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
    default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
    default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike
    default-is-explicit-multipass: false
    default-save-temps: false
```

</details>

<br />

* For issues related to the runtime, setting the environment variable `HIPSYCL_DEBUG_LEVEL=3` will cause it to print *a lot* of diagnostic information that might be helpful. Attach the output of your program with `HIPSYCL_DEBUG_LEVEL=3` if you think it might be helpful for your issue.
   * No additional log shown with `HIPSYCL_DEBUG_LEVEL=3` when compiling
* Recent hipSYCL versions include a tool called `hipsycl-info`, which will print information about available backends and devices. This may be interesting for issues related to e.g. device visibility.

<details>

```
=================Backend information===================
Loaded backend 0: OpenMP
  Found device: hipSYCL OpenMP host device

=================Device information===================
***************** Devices for backend OpenMP *****************
Device 0:
 General device information:
  Name: hipSYCL OpenMP host device
  Backend: OpenMP
  Vendor: the hipSYCL project
  Arch: <native-cpu>
  Driver version: 1.2
  Is CPU: 1
  Is GPU: 0
 Default executor information:
  Is in-order queue: 1
  Is out-of-order queue: 0
  Is task graph: 0
  Number of execution lanes for kernels: 1
  Number of execution lanes for data transfers: 1
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 1
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_write_only: 0
  emulated_local_memory: 1
  sub_group_independent_forward_progress: 0
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 1
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 1
  usm_system_allocations: 1
  execution_timestamps: 1
 Device properties:
  max_compute_units: 8
  max_global_size0: 18446744073709551615
  max_global_size1: 18446744073709551615
  max_global_size2: 18446744073709551615
  max_group_size: 1024
  max_num_sub_groups: 18446744073709551615
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 0
  max_malloc_size: 18446744073709551615
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 64
  global_mem_cache_size: 1
  global_mem_size: 18446744073709551615
  max_constant_buffer_size: 18446744073709551615
  max_constant_args: 18446744073709551615
  local_mem_size: 18446744073709551615
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 18446744073709551615
  sub_group_sizes: 1 
```

</details>

<br/>

**Additional context**
I encountered the confilct of `__noinline__` problem when upgrading from libstdc++ 11 to 12 ( ref: https://github.com/ROCm-Developer-Tools/HIP/issues/2678 ), not sure whether this is related.

Additionally, clang-14 with ROCm 5.2.1 and libstdc++ 11 produces another error:
<pre>lld: <font color="#C01C28">error: </font>undefined symbol: __oclc_ABI_version</pre>
Using intel/llvm (or maybe upstream clang-15) avoids this.

**Comment by illuhad** [comment]
It crashes during semantic analysis, which happens even before the hipSYCL clang plugin is invoked, so this does not seem to be a hipSYCL-specific issue.

I remember that, when I tried ROCm 5.2, I had to build hipSYCL against the clang that came bundled with ROCm because apparently ROCm 5.2 requires stuff that is not yet in the clang 14 release.

> Additionally, clang-14 with ROCm 5.2.1 and libstdc++ 11 produces another error:

Can you clarify if you mean by this that you have just tried an earlier libstdc++, or if you have also tried the clang *that comes with ROCm*?

In any case, this seems like a C++20 + libstdc++ 12 + clang HIP problem.

**Comment by fxzjshm** [comment]
I'm not using clang that comes with ROCm, the clang-14 is from Ubuntu 22.04's apt repo, and the missing `__oclc_ABI_version` may be one of the things "that is not yet in the clang 14 release" like you said.

I'm closing this since this is not a hipSYCL-specific issue. Thank you very much for the explanation.
