### ISSUE TITLE
Incorrect use of `__activemask`

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#823]
**Bug summary**

In some group functions for CUDA backend, hipSYCL uses `__activemask` intrinsic to detect currently active threads, e.g. here: https://github.com/illuhad/hipSYCL/blob/develop/include/hipSYCL/sycl/libkernel/cuda/group_functions.hpp#L99

However, per the section "Active Mask Query" in https://developer.nvidia.com/blog/using-cuda-warp-level-primitives/, that is not correct. Listing 5 there is pretty much how hipSYCL does things now. Even if all the threads in a sub-group call the group primitive, it is not guaranteed that `__activemask()` will return all-1s. 

**To Reproduce**

Relies on the de-synchronization within the warp, so NVIDIA Volta or newer is needed.

**Expected behavior**

SYCL specs 2020v5 does not explicitly say what happens if not all threads call `reduce_over_group`, but the wording seems to suggest that it must be called by all threads in a (sub)group:

> Returns: The result of combining all the values of x specified by each work-item in the group using the operator binary_op, where the values are combined according to the generalized sum defined in standard C++.

So, for various warp-level primitives it should be okay to use `const unsigned int activemask = 0xffffffffff;`

- EDIT: not really, we are allowed to launch < 32 work-items overall, so our sub-group will not be a full warp. Pain.

Note: in HIP some inline assembly is used which I'm not willing to dig into, but it seems that something similar is going on there.

**Describe your setup**

* hipSYCL develop, CUDA 11.6, Clang 12

**Comment by al42and** [comment]
Gentle bump. Unless I'm mistaken, this can be a very nasty issue potentially causing sub-group collective operations to produce wrong results.

**Comment by DieGoldeneEnte** [comment]
Sorry, I must have missed this.

I guess we could use ballot_sync as a hotfix for this on Nvidia GPUs.
On AMD-GPUs it wasn't a problem for the GCN architectures, I'll need to check it for CDNA/RDNA.

I'll create a PR with a fix later once I was able to test the hotfix and read up on the AMD architecture.

The group algorithm code will also change in the future and wont need `__activemask()` anymore. So I think a hotfix should be good enough for now.
