### ISSUE TITLE
Overhead of supporting offset in sycl::nd_item

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#829]
**Bug summary**

The presence of `nd_item<Dim>::_offset` field, in some cases, noticeably increases register usage by the kernel.

Usually, the compiler does a good enough job optimizing things, but not always.

For testing, I hacked the `nd_item.hpp` file to remove the `_offset` field and related functionalities. This is not a good solution overall (since in SYCL2020 offsets are only deprecated, not removed), but it works for demo purposes.

**To Reproduce**

(Sorry, not a short reproducer).

Add `-Xcuda-ptxas -v` to `default-cuda-cxx-flags` in `syclcc.json`, compile GROMACS. Compare outputs for hipSYCL versions with `_offset` removed and with it intact.

Some examples of how this helps reduce register usage (after vs. before):

- `__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameI12BondedKernelILb1ELb1EEEE`: 66 vs 68, performance approx. same
- `__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIN3gmx16SettleKernelNameILb1ELb1EEEEE`: 71 vs 72, performance approx. same

But here comes the most interesting part:

- `__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameI15PmeGatherKernelILi4ELb1ELb1ELi1ELb0EL14ThreadsPerAtom0ELi32EEEE`: register usage unchanged, but ~5% faster.

- `__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameI24PmeSplineAndSpreadKernelILi4ELb1ELb1ELb1ELb1ELi1ELb0EL14ThreadsPerAtom0ELi32EEEE`: 32 vs 30, so the register usage increased, but the kernel is ~10% faster

**Expected behavior**

Ideally, the unused offset functionality should not impact the kernel performance.

**Describe your setup**

* hipSYCL 989026577b62409139c856491e9d67707448780a
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang-12 from Ubuntu 20.04 repos
   * CUDA 11.6 for sm_75, NVIDIA GeForce GTX 1660 SUPER

**Comment by illuhad** [comment]
These are interesting findings! It's surprising that LLVM does not manage to realize that it doesn't need the offset (I wonder if this persists with LLVM 13-15).
As you point out, we cannot really remove it because it is still part of SYCL2020, although deprecated.

I wonder if it plays a role that offset is currently stored as a pointer rather than by-value in `nd_item`.

I guess one thing we could do is add a `HIPSYCL_DISABLE_OFFSETS` macro or so that users can set to control whether the headers support offset.

**Comment by al42and** [comment]
> It's surprising that LLVM does not manage to realize that it doesn't need the offset (I wonder if this persists with LLVM 13-15).

I don't think LLVM can do it _in general_. Offsets are used in `get_global_id` and its variations, so they cannot be completely removed.

It might also be a problem when `nd_item` is passed to sub-functions, since copying and call semantics and 0-sized objects and such. Have not analyzed it deeply yet. It depends on inlining aggressiveness, but I suspect that's what we have with our PME kernels. It is the shortcoming of the optimizer, but the current `nd_item` design is not helping. I'll look into the problem later.

> I guess one thing we could do is add a HIPSYCL_DISABLE_OFFSETS macro or so that users can set to control whether the headers support offset.

Can't we somehow differentiate based on which parallel_for` function overload is called? It looks like something like that is done for the `sycl::range`-kernels.

Macro is definitely a solution, although probably not an ideal one. Having tons of knobs for configuring runtime is nice up to a point
where there are too many of them to keep track of :)

For the problem at hand, I'll first try to massage the code in GROMACS to permit the optimizations. But I think that this issue is general enough to be worth filing.

**Comment by illuhad** [comment]
> Can't we somehow differentiate based on which parallel_forfunction overload is called? It looks like something like that is done for thesycl::range`-kernels.

I suspect that this is not possible. For the `range` case, the offset is completely transparent to the user kernel, as the user is only given an `id<>` object. This object does not have to store the offset explicitly. In the `nd_range` case, the user is given direct access to the offset as part of `nd_item`. To remove the offset, we would have to change the `nd_item` data layout, e.g. by specializing it using an additional template parameter when we don't have an offset. This does not work because the specification does not allow this: A user kernel can always expect an `nd_item<Dim>` as argument, and we cannot pass in some modified type.

EDIT: To be more precise, in the `range` case the user is actually given an `item<>` which can then be implicitly converted to `id`. `item` has an additional template parameter which specifies whether it has an offset. So the specification foresees this issue here, but we do not have this additional template parameter for `nd_item` unfortunately.

> Macro is definitely a solution, although probably not an ideal one. Having tons of knobs for configuring runtime is nice up to a point
where there are too many of them to keep track of :)

That's certainly true :)

**Comment by al42and** [comment]
> This does not work because the specification does not allow this: A user kernel can always expect an nd_item<Dim> as argument, and we cannot pass in some modified type.

Ok, I see. Thanks for the explanation.

<hr/>


I decided to play with a toy example to understand the problem better. The following is a bit of a disorganized dump of my observations, but I think it might be useful.

```cpp
#include <SYCL/sycl.hpp>

void run_kernels(const sycl::device &syclDevice) {
  unsigned int numThreads = 512;
  unsigned int wgSize = 64;
  sycl::queue queue = sycl::queue(syclDevice);
  int *ptr = sycl::malloc_device<int>(numThreads, queue);
  queue
      .submit([&](sycl::handler &cgh) {
        cgh.parallel_for<class KernelA>(
            sycl::nd_range<3>{{numThreads, 1, 1}, {wgSize, 1, 1}},
            [=](sycl::nd_item<3> id) {
              int gid = id.get_global_linear_id();
              ptr[gid] = 0;
            });
      })
      .wait_and_throw();
  sycl::free(ptr, queue);
}

int main() {
  for (const auto &dev : sycl::device::get_devices()) {
    run_kernels(dev);
  }
}
```

It produces the following PTX (`syclcc -O3 simple_kernel.cpp --hipsycl-targets=cuda:sm_75 && cuobjdump -ptx a.out`):

```ptx
.reg .b32 %r<17>;
.reg .b64 %rd<23>;

ld.param.u64 %rd1, [__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRKNS_4sycl6deviceEENKUlRNS2_7handlerEE_clES7_E7KernelAEE_param_1+16];
ld.param.u64 %rd2, [__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRKNS_4sycl6deviceEENKUlRNS2_7handlerEE_clES7_E7KernelAEE_param_1+8];
ld.param.u64 %rd3, [__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRKNS_4sycl6deviceEENKUlRNS2_7handlerEE_clES7_E7KernelAEE_param_1];
ld.param.u64 %rd4, [__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRKNS_4sycl6deviceEENKUlRNS2_7handlerEE_clES7_E7KernelAEE_param_0];
cvta.to.global.u64 %rd5, %rd4;
mov.u32 %r1, %ctaid.z;
mov.u32 %r2, %ntid.z;
mov.u32 %r3, %tid.z;
mad.lo.s32 %r4, %r2, %r1, %r3;
cvt.u64.u32 %rd6, %r4;
mov.u32 %r5, %ctaid.y;
mov.u32 %r6, %ntid.y;
mov.u32 %r7, %tid.y;
mad.lo.s32 %r8, %r6, %r5, %r7;
cvt.u64.u32 %rd7, %r8;
mov.u32 %r9, %ctaid.x;
mov.u32 %r10, %ntid.x;
mov.u32 %r11, %tid.x;
mad.lo.s32 %r12, %r10, %r9, %r11;
cvt.u64.u32 %rd8, %r12;
add.s64 %rd9, %rd3, %rd6;
add.s64 %rd10, %rd2, %rd7;
add.s64 %rd11, %rd1, %rd8;
cvt.u64.u32 %rd12, %r10;
mov.u32 %r13, %nctaid.y;
mov.u32 %r14, %nctaid.x;
cvt.u64.u32 %rd13, %r14;
mul.lo.s32 %r15, %r13, %r6;
cvt.u64.u32 %rd14, %r15;
mul.lo.s64 %rd15, %rd13, %rd12;
mul.lo.s64 %rd16, %rd9, %rd14;
add.s64 %rd17, %rd10, %rd16;
mul.lo.s64 %rd18, %rd15, %rd17;
add.s64 %rd19, %rd11, %rd18;
shl.b64 %rd20, %rd19, 32;
shr.s64 %rd21, %rd20, 30;
add.s64 %rd22, %rd5, %rd21;
mov.u32 %r16, 0;
st.global.u32 [%rd22], %r16;
ret;
```

Yiiikes. That's a lot of PTX for such a short kernel.

If we manually compute the index, we avoid the extra loads from constant memory:

```cpp
unsigned int tidX = id.get_local_id(0);
unsigned int tidY = id.get_local_id(1);
unsigned int tidZ = id.get_local_id(2);
unsigned int gidX = id.get_group(0);
unsigned int gidY = id.get_group(1);
unsigned int gidZ = id.get_group(2);
unsigned int gsX = id.get_local_range(0);
unsigned int gsY = id.get_local_range(1);
unsigned int gsZ = id.get_local_range(2);
unsigned int gid = (((gidZ * gsZ + tidZ) * gsY + gidY * gsY + tidY) * gsX + gidX * gsX + tidX);
```

```
.reg .b32 %r<13>;
.reg .b64 %rd<17>;

ld.param.u64 %rd1, [__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRKNS_4sycl6deviceEENKUlRNS2_7handlerEE_clES7_E7KernelAEE_param_0];
cvta.to.global.u64 %rd2, %rd1;
mov.u32 %r1, %tid.z;
cvt.u64.u32 %rd3, %r1;
mov.u32 %r2, %tid.y;
mov.u32 %r3, %tid.x;
mov.u32 %r4, %ctaid.z;
mov.u32 %r5, %ctaid.y;
mov.u32 %r6, %ctaid.x;
mov.u32 %r7, %ntid.z;
cvt.u64.u32 %rd4, %r7;
mov.u32 %r8, %ntid.y;
cvt.u64.u32 %rd5, %r8;
mov.u32 %r9, %ntid.x;
mul.wide.u32 %rd6, %r9, %r6;
add.s32 %r10, %r5, %r3;
cvt.u64.u32 %rd7, %r10;
add.s64 %rd8, %rd6, %rd7;
mul.lo.s64 %rd9, %rd8, %rd5;
add.s32 %r11, %r4, %r2;
cvt.u64.u32 %rd10, %r11;
add.s64 %rd11, %rd9, %rd10;
mul.lo.s64 %rd12, %rd11, %rd4;
add.s64 %rd13, %rd12, %rd3;
and.b64 %rd14, %rd13, 4294967295;
shl.b64 %rd15, %rd14, 2;
add.s64 %rd16, %rd2, %rd15;
mov.u32 %r12, 0;
st.global.u32 [%rd16], %r12;
ret;
```

But we still have nasty conversions between 64-bit and 32-bit integers. Not much we can do, the standard required `sycl::id` and `sycl::range` to be `size_t`. Or can we?

Let's add one small thing: `__builtin_assume(gid >= 0 && gid < 512*64);` right after `gid` calculation:

```
.reg .b32 %r<16>;
.reg .b64 %rd<5>;

ld.param.u64 %rd1, [__hipsycl_kernel__ZTSN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRKNS_4sycl6deviceEENKUlRNS2_7handlerEE_clES7_E7KernelAEE_param_0];
cvta.to.global.u64 %rd2, %rd1;
mov.u32 %r1, %tid.z;
mov.u32 %r2, %tid.y;
mov.u32 %r3, %tid.x;
mov.u32 %r4, %ctaid.z;
mov.u32 %r5, %ctaid.y;
mov.u32 %r6, %ctaid.x;
mov.u32 %r7, %ntid.z;
mov.u32 %r8, %ntid.y;
mov.u32 %r9, %ntid.x;
add.s32 %r10, %r5, %r3;
mad.lo.s32 %r11, %r9, %r6, %r10;
add.s32 %r12, %r4, %r2;
mad.lo.s32 %r13, %r11, %r8, %r12;
mad.lo.s32 %r14, %r13, %r7, %r1;
mul.wide.u32 %rd3, %r14, 4;
add.s64 %rd4, %rd2, %rd3;
mov.u32 %r15, 0;
st.global.u32 [%rd4], %r15;
ret;
```

Which is now more or less identical to what a native CUDA kernel with manual index computation produces. Nice.

Note: `__builtin_assume`ing that the offset is 0 does not prevent loading it :(

Edit: I feel like I messed up the indexing above, but it should not alter the main point.

**Comment by al42and** [comment]
On AMD, the impact (in terms of lines of assembly) is even more drastic. ROCm 5.1.3, bundled clang, hip:gfx908 target:

```
        s_load_dword s0, s[4:5], 0x4
        s_load_dword s11, s[4:5], 0x8
        s_load_dwordx2 s[12:13], s[4:5], 0xc
        s_mov_b32 s15, 0xffff
        s_mov_b32 s17, 0x4f7ffffe
        s_waitcnt lgkmcnt(0)
        s_lshr_b32 s14, s0, 16
        v_cvt_f32_u32_e32 v3, s14
        s_and_b32 s16, s0, s15
        v_cvt_f32_u32_e32 v4, s16
        s_sub_i32 s0, 0, s14
        v_rcp_iflag_f32_e32 v3, v3
        s_mul_i32 s9, s9, s14
        v_rcp_iflag_f32_e32 v4, v4
        s_mul_i32 s8, s8, s16
        v_mul_f32_e32 v3, s17, v3
        v_cvt_u32_f32_e32 v3, v3
        v_mul_f32_e32 v4, s17, v4
        v_cvt_u32_f32_e32 v4, v4
        v_mul_lo_u32 v5, s0, v3
        s_load_dwordx8 s[0:7], s[6:7], 0x0
        s_waitcnt lgkmcnt(0)
        s_and_b32 s3, s11, s15
        s_mul_i32 s10, s10, s3
        v_mul_hi_u32 v5, v3, v5
        s_sub_i32 s3, 0, s16
        s_add_i32 s2, s2, s10
        v_add_u32_e32 v2, s2, v2
        v_add_u32_e32 v3, v3, v5
        v_mul_lo_u32 v5, s3, v4
        v_mul_hi_u32 v3, s13, v3
        v_mul_lo_u32 v2, v2, s14
        s_add_i32 s2, s4, s9
        v_mul_hi_u32 v5, v4, v5
        v_mul_lo_u32 v6, v3, s14
        v_add_u32_e32 v7, 1, v3
        v_add_u32_e32 v4, v4, v5
        v_mul_hi_u32 v4, s12, v4
        v_sub_u32_e32 v6, s13, v6
        v_cmp_le_u32_e32 vcc, s14, v6
        v_cndmask_b32_e32 v3, v3, v7, vcc
        v_mul_lo_u32 v7, v4, s16
        v_subrev_u32_e32 v5, s14, v6
        v_cndmask_b32_e32 v5, v6, v5, vcc
        v_add_u32_e32 v6, 1, v3
        v_cmp_le_u32_e32 vcc, s14, v5
        v_cndmask_b32_e32 v3, v3, v6, vcc
        v_sub_u32_e32 v6, s12, v7
        v_add_u32_e32 v7, 1, v4
        v_cmp_le_u32_e32 vcc, s16, v6
        v_cndmask_b32_e32 v4, v4, v7, vcc
        v_subrev_u32_e32 v7, s16, v6
        v_cndmask_b32_e32 v6, v6, v7, vcc
        v_mul_lo_u32 v5, v3, s14
        v_add_u32_e32 v7, 1, v4
        v_cmp_le_u32_e32 vcc, s16, v6
        v_cndmask_b32_e32 v4, v4, v7, vcc
        v_mul_lo_u32 v6, v4, s16
        v_cmp_gt_u32_e32 vcc, s13, v5
        v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
        v_cmp_gt_u32_e32 vcc, s12, v6
        v_addc_co_u32_e32 v4, vcc, 0, v4, vcc
        v_mul_lo_u32 v2, v2, v3
        v_mul_lo_u32 v3, v4, s16
        v_add3_u32 v1, s2, v1, v2
        v_mul_lo_u32 v2, v3, v1
        s_add_i32 s2, s6, s8
        v_mov_b32_e32 v1, 0
        v_add3_u32 v2, s2, v0, v2
        v_ashrrev_i64 v[2:3], 30, v[1:2]
        v_mov_b32_e32 v0, s1
        v_add_co_u32_e32 v2, vcc, s0, v2
        v_addc_co_u32_e32 v3, vcc, v0, v3, vcc
        global_store_dword v[2:3], v1, off
        s_endpgm
```

With manual calculation:

```
        s_load_dword s0, s[4:5], 0x4
        s_load_dword s1, s[4:5], 0x8
        s_mov_b32 s2, 0xffff
        s_waitcnt lgkmcnt(0)
        s_lshr_b32 s3, s0, 16
        s_and_b32 s0, s0, s2
        s_mul_i32 s0, s0, s8
        s_add_i32 s0, s0, s9
        v_add_u32_e32 v0, s0, v0
        v_mul_lo_u32 v0, v0, s3
        s_and_b32 s0, s1, s2
        v_add3_u32 v0, s10, v1, v0
        v_mul_lo_u32 v0, v0, s0
        s_load_dwordx2 s[0:1], s[6:7], 0x0
        v_mov_b32_e32 v1, 0
        v_add_u32_e32 v0, v0, v2
        v_lshlrev_b64 v[2:3], 2, v[0:1]
        s_waitcnt lgkmcnt(0)
        v_mov_b32_e32 v0, s1
        v_add_co_u32_e32 v2, vcc, s0, v2
        v_addc_co_u32_e32 v3, vcc, v0, v3, vcc
        global_store_dword v[2:3], v1, off
        s_endpgm
```

`__builtin_assume()` does not seem to change things.

**Comment by illuhad** [comment]
Idea sketch that maybe might work:
* have two variants for parallel_for `nd_range` kernel launchers, one with and one without offset
* The one without offset can initialize the `nd_item` with `nullptr` constant as offset pointer
* `nd_item` can have special branching when offset pointer is `nullptr`, such that the offset is not accessed in that case
* LLVM might be able to optimize the extra branching away, by constant-propagating the `nullptr` and hence hardwiring the non-offset case when invoked without offset.

**Comment by illuhad** [comment]
This is what SSCP does with it:

Current develop:
```
        .reg .b32       %r<13>;
        .reg .b64       %rd<24>;

// %bb.0:
        ld.param.u64    %rd1, [_Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsRNS0_4sycl5queueEENK3$_0clERNS4_7handlerEEUlNS4_7nd_itemILi3EEEE_Li3EEEEvRKT__param_0];
        mov.u32         %r1, %ctaid.z;
        mov.u32         %r2, %ctaid.y;
        cvt.u64.u32     %rd2, %r2;
        mov.u32         %r3, %ctaid.x;
        cvt.u64.u32     %rd3, %r3;
        mov.u32         %r4, %tid.z;
        cvt.u64.u32     %rd4, %r4;
        mov.u32         %r5, %tid.y;
        cvt.u64.u32     %rd5, %r5;
        mov.u32         %r6, %tid.x;
        cvt.u64.u32     %rd6, %r6;
        mov.u32         %r7, %ntid.z;
        mov.u32         %r8, %ntid.y;
        cvt.u64.u32     %rd7, %r8;
        mov.u32         %r9, %ntid.x;
        cvt.u64.u32     %rd8, %r9;
        mov.u32         %r10, %nctaid.y;
        cvt.u64.u32     %rd9, %r10;
        mov.u32         %r11, %nctaid.x;
        cvt.u64.u32     %rd10, %r11;
        mul.wide.u32    %rd11, %r7, %r1;
        add.s64         %rd12, %rd11, %rd4;
        mul.lo.s64      %rd13, %rd12, %rd9;
        add.s64         %rd14, %rd13, %rd2;
        mul.lo.s64      %rd15, %rd14, %rd7;
        add.s64         %rd16, %rd15, %rd5;
        mul.lo.s64      %rd17, %rd16, %rd10;
        add.s64         %rd18, %rd17, %rd3;
        mul.lo.s64      %rd19, %rd18, %rd8;
        add.s64         %rd20, %rd19, %rd6;
        shl.b64         %rd21, %rd20, 32;
        shr.s64         %rd22, %rd21, 30;
        add.s64         %rd23, %rd1, %rd22;
        mov.u32         %r12, 0;
        st.global.u32   [%rd23], %r12;
        ret;
```

With #1347:

```
.maxntid 1, 1, 64
{
        .reg .b32       %r<8>;
        .reg .b64       %rd<16>;

// %bb.0:
        ld.param.u64    %rd1, [_Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsRNS0_4sycl5queueEENK3$_0clERNS4_7handlerEEUlNS4_7nd_itemILi3EEEE_Li3EEEEvRKT__param_0];
        mov.u32         %r1, %ctaid.z;
        mov.u32         %r2, %ctaid.y;
        cvt.u64.u32     %rd2, %r2;
        mov.u32         %r3, %ctaid.x;
        cvt.u64.u32     %rd3, %r3;
        mov.u32         %r4, %tid.z;
        cvt.u64.u32     %rd4, %r4;
        mov.u32         %r5, %nctaid.y;
        cvt.u64.u32     %rd5, %r5;
        mov.u32         %r6, %nctaid.x;
        cvt.u64.u32     %rd6, %r6;
        mul.wide.s32    %rd7, %r1, 64;
        or.b64          %rd8, %rd7, %rd4;
        mul.lo.s64      %rd9, %rd8, %rd5;
        add.s64         %rd10, %rd9, %rd2;
        mul.lo.s64      %rd11, %rd10, %rd6;
        add.s64         %rd12, %rd11, %rd3;
        shl.b64         %rd13, %rd12, 32;
        shr.s64         %rd14, %rd13, 30;
        add.s64         %rd15, %rd1, %rd14;
        mov.u32         %r7, 0;
        st.global.u32   [%rd15], %r7;
        ret;
                                        // -- End function
}
```

The conversions are still there (to remove those I think we'd have to take into account the number of groups at JIT time, which we could do in the future I think), but the general problem seems to not be there. Especially with #1347.

**Comment by al42and** [comment]
Nice progress for SSCP! As I understand, no work is planned for the multipass flow?

> The conversions are still there (to remove those I think we'd have to take into account the number of groups at JIT time, which we could do in the future I think), but the general problem seems to not be there.

Can't we quite safely assume (either with `@llvm.assume` or by somehow forcing things to be u32) that all the thread indices fit into 32 (even 31) bits? IIRC, that's what DPC++ does by default, and that seems to be a safe assumption on modern hardware.

**Comment by illuhad** [comment]
> Nice progress for SSCP! As I understand, no work is planned for the multipass flow?

The interoperability-focused multipass flows do not really give us a lot of control to handle these things. And of course if you want to still build against ROCm LLVM, it gets even more difficult to add compiler magic and not break things.

As soon as dedicated compiler optimizations come into play, SSCP really is the much better framework. It already starts at the basics, like SSCP having a unified framework for all devices whereas the SMCP compilation flows need to go through different clang toolchains (CUDA/HIP).

Some optimizations are outright impossible with SMCP. For example, #1347 which is included in the SSCP PTX code that I have shared relies on JIT-compiling work group sizes into the binary at runtime, i.e. hardwiring them as constants (and setting them in `__launch_bounds__`-equivalents). You cannot do these kinds of things without JIT infrastructure.

As a point of comparison, this is what I currently get with `cuda:sm_86`. I don't see a substantial change compared to what you have obtained.

```
	.reg .b32 	%r<16>;
	.reg .b64 	%rd<23>;

	ld.param.u64 	%rd1, [_Z16__hipsycl_kernelIN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRNS0_4sycl5queueEENKUlRNS3_7handlerEE_clES7_E7KernelAEEEvv_param_0];
	cvta.to.global.u64 	%rd2, %rd1;
	mov.u32 	%r1, %ctaid.z;
	mov.u32 	%r2, %ntid.z;
	mov.u32 	%r3, %tid.z;
	mad.lo.s32 	%r4, %r1, %r2, %r3;
	cvt.u64.u32 	%rd3, %r4;
	mov.u32 	%r5, %ctaid.y;
	mov.u32 	%r6, %ntid.y;
	mov.u32 	%r7, %tid.y;
	mad.lo.s32 	%r8, %r5, %r6, %r7;
	cvt.u64.u32 	%rd4, %r8;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r12, %r9, %r10, %r11;
	cvt.u64.u32 	%rd5, %r12;
	ld.param.u64 	%rd6, [_Z16__hipsycl_kernelIN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRNS0_4sycl5queueEENKUlRNS3_7handlerEE_clES7_E7KernelAEEEvv_param_1];
	add.s64 	%rd7, %rd6, %rd3;
	ld.param.u64 	%rd8, [_Z16__hipsycl_kernelIN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRNS0_4sycl5queueEENKUlRNS3_7handlerEE_clES7_E7KernelAEEEvv_param_1+8];
	add.s64 	%rd9, %rd8, %rd4;
	ld.param.u64 	%rd10, [_Z16__hipsycl_kernelIN7hipsycl4glue20complete_kernel_nameIZZ11run_kernelsRNS0_4sycl5queueEENKUlRNS3_7handlerEE_clES7_E7KernelAEEEvv_param_1+16];
	add.s64 	%rd11, %rd10, %rd5;
	cvt.u64.u32 	%rd12, %r10;
	mov.u32 	%r13, %nctaid.y;
	mov.u32 	%r14, %nctaid.x;
	cvt.u64.u32 	%rd13, %r14;
	mul.wide.u32 	%rd14, %r13, %r6;
	mul.lo.s64 	%rd15, %rd13, %rd12;
	mul.lo.s64 	%rd16, %rd14, %rd7;
	add.s64 	%rd17, %rd9, %rd16;
	mul.lo.s64 	%rd18, %rd15, %rd17;
	add.s64 	%rd19, %rd11, %rd18;
	shl.b64 	%rd20, %rd19, 32;
	shr.s64 	%rd21, %rd20, 30;
	add.s64 	%rd22, %rd2, %rd21;
	mov.u32 	%r15, 0;
	st.global.u32 	[%rd22], %r15;
	ret;
```

> Can't we quite safely assume (either with @llvm.assume or by somehow forcing things to be u32) that all the thread indices fit into 32 (even 31) bits? IIRC, that's what DPC++ does by default, and that seems to be a safe assumption on modern hardware.

Yes, I guess we could always add some macro that, if set, potentially adds `llvm.assume` calls, or changes datatypes inside `nd_item`.
I don't have a good understanding yet though when the `u64`->`u32` optimization happens and when it doesn't. I have recently looked at a code which treats `nd_item` very similarly to what you do: Query `get_global_id`, store in an `int`, and then use that `int`, and I don't see the 64-bit use there for the index calculation.
https://gitlab.com/VileLasagna/toyBrot/-/blob/main/raymarched/SYCL/FracGen.cpp?ref_type=heads#L262

**Comment by al42and** [comment]
> Yes, I guess we could always add some macro that, if set, potentially adds llvm.assume calls, or changes datatypes inside nd_item.

The `assume` calls, I think, can be added unconditionally, no? Unlike changing the return type of API, they don't enforce anything, but, per "as-if" rule, the LLVM optimizer should be able to skip most data type conversion even if the operands are `size_t` in C++ code

> Some optimizations are outright impossible with SMCP.

That's why there were function attributes, right? :) But well, that was decided to be a "wontfix".

**Comment by al42and** [comment]
> The assume calls, I think, can be added unconditionally, no? Unlike changing the return type of API, they don't enforce anything, but, per "as-if" rule, the LLVM optimizer should be able to skip most data type conversion even if the operands are size_t in C++ code

Nevermind, you're already adding them in #1347, but apparently that's not enough to fully work :(

**Comment by illuhad** [comment]
> That's why there were function attributes, right? :) But well, that was decided to be a "wontfix".

Function attributes in SYCL are broken and were a mistake, IMO.

> Nevermind, you're already adding them in https://github.com/AdaptiveCpp/AdaptiveCpp/pull/1347, but apparently that's not enough to fully work :(

#1347 adds assumes for group sizes. Perhaps we also need assumes for the number of groups.

**Comment by al42and** [comment]
> Function attributes in SYCL are broken and were a mistake, IMO.

But, for all their limitations, they allow for optimizations possible in CUDA/HIP, but not otherwise possible with SYCL :)

> Perhaps we also need assumes for the number of groups.

**Comment by al42and** [comment]
> Function attributes in SYCL are broken and were a mistake, IMO.

But, for all their limitations, they allow for optimizations possible in CUDA/HIP, but not otherwise possible with SYCL :) JIT solves this problem, but has its own downsides.

> Perhaps we also need assumes for the number of groups.

The question then is, do we use the max. possible value for the device, or the exact value used for the launch. The latter is more precise, but might lead to recompiling the kernel too often.

**Comment by illuhad** [comment]
> But, for all their limitations, they allow for optimizations possible in CUDA/HIP, but not otherwise possible with SYCL :) JIT solves this problem, but has its own downsides.

I think most downsides of JIT can be addressed/mitigated. Well, unless you are in the safety critical business or so where you cannot have JIT no matter what.

> The question then is, do we use the max. possible value for the device, or the exact value used for the launch. The latter is more precise, but might lead to recompiling the kernel too often.

Recompilation should not be a big problem in most cases - AdaptiveCpp SSCP has recently received an on-disk persistent kernel cache. So as long as subsequent application runs do similar things, we can just grab precompiled kernels from storage. The question is whether we expect problem sizes to be all over the place such that they are different for every application run.

**Comment by al42and** [comment]
> The question whether we expect problem sizes to be all over the place such that they are different for every application run.

For GROMACS, definitely :) We have fixed work-group size, but the number of work-groups can change within a single run as domain-decomposition adjusts the number of particles per GPU and the neighbor list gets updated / pruned changing the number of neighbor clusters (not to mention switching between different kernel flavors). And for different runs, the reasonable inputs can be anywhere between 2k and 2M particles per GPU (I'd say, a typical user runs systems of roughly similar size, but not similar enough to rely on the number of work-groups being fixed).

**Comment by illuhad** [comment]
So far, I could not get it to work with 3 dimensional kernels as in your example just by adding assumes on group id and number of groups :( Probably the additional `size_t` calculations when calculating the 3D id are too much for the optimizer to leverage the `assume` information.

We may have to insert the assumes at a higher level :(

If I turn your example code into a 1D problem, I do however get the desired effect with additional assumes on group id and number of groups:

```
.maxntid 64, 1, 1
{
	.reg .b32 	%r<6>;
	.reg .b64 	%rd<4>;

// %bb.0:
	ld.param.u64 	%rd1, [_Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi1EEEE_Li1EEEEvRKT__param_0];
	mov.u32 	%r1, %ctaid.x;
	mov.u32 	%r2, %tid.x;
	shl.b32 	%r3, %r1, 6;
	or.b32  	%r4, %r3, %r2;
	mul.wide.u32 	%rd2, %r4, 4;
	add.s64 	%rd3, %rd1, %rd2;
	mov.u32 	%r5, 0;
	st.global.u32 	[%rd3], %r5;
	ret;
                                        // -- End function
}
```

**Comment by illuhad** [comment]
Ok, I now get this for the 3D case, which I think is pretty perfect:

```
//
// Generated by LLVM NVPTX Back-End
//

.version 6.1
.target sm_61
.address_size 64

	// .globl	_Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi3EEEE_Li3EEEEvRKT_ // -- Begin function _Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi3EEEE_Li3EEEEvRKT_
                                        // @"_Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi3EEEE_Li3EEEEvRKT_"
.visible .entry _Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi3EEEE_Li3EEEEvRKT_(
	.param .u64 _Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi3EEEE_Li3EEEEvRKT__param_0
)
.maxntid 1, 1, 64
{
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<4>;

// %bb.0:
	ld.param.u64 	%rd1, [_Z21__hipsycl_sscp_kernelIN7hipsycl4glue15__sscp_dispatch20ndrange_parallel_forIZZ11run_kernelsvENK3$_0clERNS0_4sycl7handlerEEUlNS5_7nd_itemILi3EEEE_Li3EEEEvRKT__param_0];
	mov.u32 	%r1, %ctaid.z;
	mov.u32 	%r2, %ctaid.y;
	mov.u32 	%r3, %ctaid.x;
	mov.u32 	%r4, %tid.z;
	mov.u32 	%r5, %nctaid.y;
	mov.u32 	%r6, %nctaid.x;
	shl.b32 	%r7, %r1, 6;
	or.b32  	%r8, %r7, %r4;
	mad.lo.s32 	%r9, %r8, %r5, %r2;
	mad.lo.s32 	%r10, %r9, %r6, %r3;
	mul.wide.s32 	%rd2, %r10, 4;
	add.s64 	%rd3, %rd1, %rd2;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd3], %r11;
	ret;
                                        // -- End function
}
```

I could not get this to work with just assume calls. I had to create `int` and `size_t` overloads of the id calculation, with the selection depending on JIT values.
