### ISSUE TITLE
Poor performance in HeCBench/nbody-sycl

### ISSUE THREAD

**Issue by nmnobre** [AdaptiveCpp/AdaptiveCpp#833]
Hi @illuhad,

I've had a play with the nbody benchmark in illuhad/HeCBench and was quite surprised with the (lack of) performance of the sycl variant when compiled with hipSYCL.

I've access to an Nvidia Tesla V100 card, and have tried targeting it with:
- cuda: ~0.55s (nbody-cuda)
`make ARCH=sm_70`
- intel/llvm: ~0.58s (nbody-sycl)
`make CUDA=yes` and removed the gcc toolchain flag
- hipSYCL/nvc++: ~100s (nbody-sycl)
`make CC=syclcc CFLAGS="-O3 -std=c++17 --hipsycl-targets=cuda-nvcxx -Wall -I../include"`
- hipSYCL/llvm: ~116s (nbody-sycl)
`make CC=syclcc CFLAGS="-O3 -std=c++17 --hipsycl-targets=cuda:sm_70 -Wall -I../include"`

I was wondering if the reason for this discrepancy is already known?

Cheers,
-Nuno

**Comment by illuhad** [comment]
Hi,

this is not expected. We have published some numbers for this very benchmark here: https://dl.acm.org/doi/10.1145/3529538.3530005

Here's the relevant plot:

![hecbench](https://user-images.githubusercontent.com/11861762/192100203-fe1f1bc9-5947-46d6-b66e-42e95d7f24bd.png)

It says in the paper, but from the top of my head I'm not entirely sure though if we have used my fork (and if so, which branch) of HeCBench. I'd recommend also trying with the main repo just in case.

Such a massive performance gap could indicate
* That it is falling back to CPU, which can happen if it does not detect a GPU, or there is a setup issue that prevents it from seeing it. Verify that the CUDA device is visible using `hipsycl-info`. Also, when running the application, use the environment variable `HIPSYCL_DEBUG_LEVEL=3` to see to which device it dispatches
* Verify compilation flags passed to clang (target and optimization flags) by setting the environment variable `HIPSYCL_DRYRUN=1`.

**Comment by illuhad** [comment]
Addendum: **IIRC, HeCBench needs you to set the preprocessor macro -DUSE_GPU, otherwise it will use the CPU**. This is probably what is going on here... The HeCBench make infrastructure is a bit error-prone when trying other compilers it was not built for. I think I've also seen cases where it applies things like `-ffast-math` for one version of a benchmark but not another.
If you want to draw solid conclusions here, I'd recommend double checking that all benchmarks for all compilers are built with comparable flags.

**Comment by nmnobre** [comment]
> Addendum: **IIRC, HeCBench needs you to set the preprocessor macro -DUSE_GPU, otherwise it will use the CPU**. This is probably what is going on here...

Indeed it was, apologies, I feel stupid now for overlooking that preprocessor switch...
The performance matches that of intel/llvm. Cheers and have a nice weekend :-)
