### ISSUE TITLE
Using multiple queues within OpenMP threads slows down SYCL

### ISSUE THREAD

**Issue by nordmoen** [AdaptiveCpp/AdaptiveCpp#835]
Hi,

I'm trying to optimize a piece of code by using multiple GPUs. To achieve this I first enumerate the devices on the host, create one queue for each device and then within a `for` loop access the "correct" queue by using `omp_get_thread_num()`. The problem is that using multiple queues slows down the entire computation by almost half. Using the same code with only one GPU (and thus one queue) gives the expected performance.

Since the code is not mine to share I have tried to condense the relevant bits:
```c++
const std::vector<sycl::device> devices = enumerate_devices();
std::vector<sycl::queue> queues;
for (auto device : devices) {
  queues.push_back(sycl::queue{device});
}
omp_set_num_threads(queues.size());
#pragma omp parallel for
for (...) {
  auto Q = queues[omp_get_thread_num()];
  // Each iteration will allocate quite a bit of memory
  // then run quite a few kernels
  // Lastly, free device memory again
}
```

I get the correct results in both instances, but using multiple devices uses the same total amount of time as using a single device, where kernel compute and memory handling takes roughly twice as much time as with a single queue.

I'm wondering if this is a bad approach and if there are any suggestions for using multiple GPUs with hipSYCL (I have looked at the multi device queue, but it seems more difficult than the above with memory handling).

**Comment by illuhad** [comment]
Why is OpenMP involved here? Task submission in SYCL is asynchronous already, so you don't need to submit from separate threads to get concurrent execution. Since it needs to through the same scheduler anyway, the only thing you get is additional synchronization overhead due to the multiple threads entering the runtime :-)

Using multiple queues in principle is the right approach. From this short snippet, I don't see what might be going on apart from multi-threading overhead. And usually I would not expect this to have such a massive performance impact, unless you are already strongly bound by host performance. Of course, as in any multi-threading scenario, you need to watch out for inefficiencies in your data transfer patterns. Also, in this multi-threading scenario, if you are working on a GPU from a NUMA node that is not attached directly to it.

Also, if any of your kernels end up running on CPU, i.e. the CPU device is also part of the device enumeration, this OpenMP pattern might be problematic since the CPU backend also runs through OpenMP.

Be aware that the hipSYCL runtime uses its own worker threads to facilitate asynchronous task processing (this is also why submitting via OpenMP will not improve submission performance). When using OpenMP, it is strongly recommended to enable `OMP_PROC_BIND` (e.g. `OMP_PROC_BIND=true`) to avoid unnecessary thread migration due to the additional worker threads competing for resources.


The multi-device queue is a different beast, it is about automatic distribution of work across the system. Not what you want here.

**Comment by nordmoen** [comment]
Thanks for the quick reply.

There is probably something I don't understand correctly about SYCL or haven't communicated clearly in the example.

In the outer `for` loop (included in the example above), I need to submit multiple kernels, but there are also multiple `Q.wait()` to ensure previous tasks have been completed (i.e. the memory they were touching are ready to read), this is the reason for trying to use OpenMP to utilize multiple devices.

**Comment by illuhad** [comment]
Ok. Is the purpose of `Q.wait()` to ensure that data is ready to be read by other kernels, or by the host after a copy from device to host?

Are your queues a SYCL in-order queue or a (default) out-of-order queue?

**Comment by nordmoen** [comment]
Yeah, the reason for this strange question is that I have multiple nested `for` loops where I didn't want to return the events to wait for. So I made it as async as possible, but the outer loop still required some `Q.wait()` calls to ensure proper ordering (as some of the kernels could be submitted async while others have data dependencies.

I think a re-write is probably better and then I can see.

Just to be clear, your recommendation for using multiple queues is to skip the OpenMP stuff in my original example, keep everything asynchronous inside the "outer" loop and use one device per iteration (something like: `auto Q = queues[i % queues.size()];`)?

**Comment by illuhad** [comment]
> Just to be clear, your recommendation for using multiple queues is to skip the OpenMP stuff in my original example, keep everything asynchronous inside the "outer" loop and use one device per iteration (something like: auto Q = queues[i % queues.size()];)?

Yes, it's probably better to start from a simple setup :-) 

Additionally:
* First of all, try to avoid waiting on the host in the first place, if you can. It's never efficient. If there are dependencies *between kernels*, express them using `handler::depends_on(event)` or use an in-order queue. This will allow dependencies to be expressed on the level of the GPU backend, independently from the host. If you use the buffer-accessor model, dependencies are set up automatically *between kernels*.
* On an out-of-order queue, `event::wait()` is probably going to perform better than `queue::wait()`, especially in cases of multi-threading contention
* On an in-order queue `event::wait()` and `queue::wait()` will perform equally well.
* Use `OMP_PROC_BIND` if OpenMP is involved

**Comment by nordmoen** [comment]
Great, thanks for the quick response and guidance!

**Comment by nordmoen** [comment]
(Sorry for reviving this, but I think this follow up is relevant)

So I was able to rewrite the code and in the process sped it up by a considerable amount. It is still slower than the manually optimized CUDA version, but it is now probably close enough, when using a single GPU. However, I still want to utilize multiple GPUs and I'm not quite sure if my code can use multiple queues as discussed above.

My new pseudo-code:

```c++
const std::vector<sycl::device> devices = enumerate_devices();
std::vector<sycl::queue> queues;
for (auto device : devices) {
  queues.push_back(sycl::queue{device});
}
for (...) {
  auto Q = queues[index % queues.size()];
  // Create buffers to access input on device
  sycl::buffer<float, 1> buf_a{...};
  ...
  // Run the main computation
  Q.submit([&](sycl::handler& h) {
     sycl::accessor acc_a{buf_a, h, sycl::write_only, sycl::no_init};
    ...
  });
  // Copy out result
  Q.submit([&](sycl::handler& h) {
     sycl::accessor acc_a{buf_a, h, sycl::read_only};
     h.copy(acc_a, dest);
  });
```

I managed to convert to only buffers and accessors and with only two submits I think both should order correctly (at least I get the correct output) and internally within the loop everything is asynchronously. However, using multiple GPUs the performance stays identical to a single GPU which leads me to believe that the loop iterations are not run concurrently. If I were to hazard a guess I would think the creation of the buffers within the loop is the culprit (during destruction), but I'm not sure.

I was wondering if my analysis above is correct and whether or not there is anything I can do to utilize the additional GPUs in the current setup? At the moment, moving the buffer creation outside the loop iteration would require quite a bit more GPU memory and would complicate the code a lot which I'm hesitant to do. So I was hoping there is an alternative to using multiple GPUs.

**Comment by illuhad** [comment]
buffer creation is not cheap (so maybe better to do outside the loop), but also not blocking. The issue most likely is the buffer destructor because buffer destructors may wait for all operations working on it to complete when they die. (Avoids memory being released while kernels are still running, and necessary for potential write-backs in case the buffer was constructed with a host pointer as argument).
So yes, better construct buffers outside the loop to avoid serialization.

You don't have to use buffers though, in the pointer-based USM model you can also use multiple GPUs just fine. Just make sure to use an in-order queue or `depends_on` to order kernel execution.

**Comment by nordmoen** [comment]
Thanks Aksel!

One follow up then, when moving the buffer creation outside they would have to comprise much more data, but I see that `sycl::accessors` can be given an offset. The question is then, will the runtime only load the limited data or will the whole buffer be moved to the device and just access limited to the offset + range? To follow up on this again, since each loop iteration then would need to share the buffers, but each iteration only access a unique range, will they be able to run concurrently?

And lastly, depending on the answers to the above, what is guaranteed by the standard and what is specific to hipSYCL? E.g. will the code be portable to other SYCL implementations with the same assumptions on concurrent access to the buffers?

**Comment by nordmoen** [comment]
Quick update.

I updated my code again and moved the buffer creation outside the loop. Even though the accessor pattern has offsets, meaning each loop iteration should be independent, using multiple queues still doesn't speed up the performance.

(I know this is now way outside the bounds of the original question, which was answered, so feel free to close this)

**Comment by fodinabor** [comment]
Hi,
just a quick list of things that might be of interest to you.
By default, using a buffer in a kernel, always assumes the whole buffer may be accessed.
You may however use the hipSYCL-specific buffer page extension:
https://github.com/illuhad/hipSYCL/blob/55bf4e7b5281ff4ec437a094ce6e342f8b36fc7b/doc/extensions.md#hipsycl_ext_buffer_page_size
https://github.com/illuhad/hipSYCL/blob/develop/doc/runtime-spec.md#data-state-tracking-and-pages
It's used like so:
`sycl::buffer<int, 1> buff{size, sycl::property::buffer::hipSYCL_page_size<1>{page_size}};`
The effect is documented in this presentation (slide 9 onwards): https://www.iwocl.org/wp-content/uploads/23-iwocl-syclcon-2021-alpay-slides.pdf

Alternatively, it might make sense to have a list of smaller preallocated buffers, one for each device?

**Comment by nordmoen** [comment]
Thanks for the pointers @fodinabor !

That really helped me better understand how buffers work. The only trouble now is that I tried to add `sycl::property::buffer::hipSYCL_page_size<1>{}` to my one output buffer (which is the only non `sycl::ready_only` buffer access) and I got an error:

```txt
[hipSYCL Error] from /dev/shm/ebbuild/hipSYCL/0.9.3/GCC-11.2.0-CUDA-11.4.1/hipSYCL-0.9.3/src/runtime/dag_direct_scheduler.cpp:148 @ operator()(): dag_direct_sc
heduler: Could not obtain data update sources when trying to materialize implicit requirement                                                                  
============== hipSYCL error report ==============                                                                                                             
hipSYCL has caught the following undhandled asynchronous errors:                                                                                               
                                                                                                                                                               
   0. from /dev/shm/ebbuild/hipSYCL/0.9.3/GCC-11.2.0-CUDA-11.4.1/hipSYCL-0.9.3/src/runtime/dag_direct_scheduler.cpp:148 @ operator()(): dag_direct_scheduler: C
ould not obtain data update sources when trying to materialize implicit requirement                                                                            
```

**Comment by illuhad** [comment]
> One follow up then, when moving the buffer creation outside they would have to comprise much more data

Why? You could just have `std::vector<sycl::buffer<...>>` outside of the loop and then index into that vector using the current device index, similarly to what you do with queue. buffers would stay the same size.

Buffers are built to manage one unit of information on multiple devices (i.e. automatically transferring data in between devices if the buffer is accessed somewhere else9, but they are not necessarily built to decompose that information.
The access offset and range are a hint to the runtime that not the entirety of the buffer has to be copied in case data transfers are required. It (as far as the SYCL specification is concerned) does not lead to concurrent execution of kernels using disjoint regions.

In principle, this can be achieved using subbuffers, but those are only partially supported in hipSYCL because they require a contiguous memory region which severely limits their usefulness beyond 1D allocations.

As @fodinabor points out, in hipSYCL specifically, the runtime *is* able to track memory at a user configurable granularity, which also allows kernels to run concurrently.
But as I've said, I don't understand why you need to deal with this additional complexity and don't maintain a list of smaller buffers, as also suggested by @fodinabor.

**Comment by illuhad** [comment]
> That really helped me better understand how buffers work. The only trouble now is that I tried to add sycl::property::buffer::hipSYCL_page_size<1>{} to my one output buffer (which is the only non sycl::ready_only buffer access) and I got an error:

AFAIR, there are some limitations with regards to gathering buffers again. You might have to manually regather the individual chunks living on different devices, e.g. using multiple invocations (one for each device) of the `handler::update()` extension.

This particular error is emitted when hipSYCL cannot find out from where to get data to update the buffer. This can in particular happen when several data transfers are needed (which is not yet supported). In this case you need to manually regather.

**Comment by nordmoen** [comment]
One last question and then we can close this.

I tried to convert to USM buffers as that was easier when it comes to copying the input buffers per loop iterations, but that resulted in an async error which I don't quite understand. However, I now have a simpler version using buffers where the output buffer is unique per queue while the read only input are shared buffers. I would think that this version would be able to support multiple GPUs, but it seems that even though the shared buffers are accessed read only they end up blocking. My question is simply, is it a correct assumption that shared buffers block even though they are accessed read only?

```c++
const std::vector<sycl::device> devices = enumerate_devices();
std::vector<sycl::queue> queues;
std::vector<sycl::buffer<float, 1>> out_bufs;
for (auto device : devices) {
  queues.push_back(sycl::queue{device});
  out_bufs.push_back(sycl::buffer{const size});
}
// Create shared buffers
sycl::buffer<float, 1> buf_inp{input_ptr, num_elements};
for (...) {
  auto Q = queues[index % queues.size()];
  auto out_buf = out_bufs[index % queues.size()];
  // Run the main computation
  Q.submit([&](sycl::handler& h) {
     sycl::accessor acc_a{out_buf, h, sycl::write_only, sycl::no_init};
     sycl::accessor acc_inp{buf_inp, h, sycl::read_only};
    ...
  });
  // Copy out result
  Q.submit([&](sycl::handler& h) {
     sycl::accessor acc_a{out_buf, h, sycl::read_only};
     h.copy(acc_a, dest);
  });
}
```

---

Edit:
Just to show the failed USM version (which is probably wrong in a C++ sense...)

```c++
struct DeviceMem {
  float* mem_a;
  ...
};
const std::vector<sycl::device> devices = enumerate_devices();
std::vector<sycl::queue> queues;
std::vector<struct DeviceMem> queue_mems;
std::vector<sycl::buffer<float, 1>> out_bufs;
for (auto device : devices) {
  queues.push_back(sycl::queue{device});
  out_bufs.push_back(sycl::buffer{const size});
}
for (auto Q : queues) {
 queue_mems.push_back(
    {
      sycl::malloc_device<float>(a_size / loops),
      ...
    }
   );
}
// No shared buffers, only USM
for (...) {
  auto Q = queues[index % queues.size()];
  auto out_buf = out_bufs[index % queues.size()];
  auto dev_mem = queue_mems[index % queues.size()];
  // Wait for previous iteration with the same queue (this should not slow down concurrent queues)
  // Can be removed when using in order queues
  Q.wait();
  // Update device memory with loop iteration data
  auto mem_a_evt = Q.copy<float>(inp_a + index * (a_size / loops), dev_mem.mem_a, (a_size / loops));
  // Run the main computation
  Q.submit([&](sycl::handler& h) {
     h.depends_on({mem_a_evt, ...});
     sycl::accessor acc_a{out_buf, h, sycl::write_only, sycl::no_init};
     // Direct access to the pointers
    ...
  });
  // Copy out result
  Q.submit([&](sycl::handler& h) {
     sycl::accessor acc_a{out_buf, h, sycl::read_only};
     h.copy(acc_a, dest);
  });
}
```
Since the first `Q.submit` is dependent on the memory copies to device and both `Q.submit`s access the same out buffer I assumed they would be dependent and not need any more synchronization. Second, I also tried with creating the queues with `sycl::queue{device, sycl::property::queue::in_order()}`, but that did not fix the issue either.

With the USM version (and both in order queue and not) I get the following error:
```txt
[hipSYCL Error] from /tmp/ebbuild/hipSYCL/0.9.2/GCC-11.2.0-CUDA-11.4.1/hipSYCL-0.9.2/src/runtime/cuda/cuda_queue.
cpp:284 @ submit_memcpy(): cuda_queue: Couldn't submit memcpy (error code = CUDA:1)                              
```

**Comment by illuhad** [comment]
> My question is simply, is it a correct assumption that shared buffers block even though they are accessed read only?

Yes. Even if you only read from an allocation, you don't want it to be freed while there are still kernels operating on it, do you? :-) So even in this case the destructor will block.
There is an extension in hipSYCL that allows to disable this, namely async buffers: https://github.com/illuhad/hipSYCL/blob/develop/doc/explicit-buffer-policies.md

> With the USM version (and both in order queue and not) I get the following error:

CUDA error code 1 is `CUDA_ERROR_INVALID_VALUE` which happens if you feed something into the API which is an incorrect value. Where does `inp_a` come frome? Is the indexing correct?
You could also just use a USM pointer for the output, and then use `handler::copy()` or `handler::memcpy()` to copy the content to some host pointer to obtain the results. It's possible to mix USM and buffer-accessor model, but not necessary, and mixing them might be ultimately confusing.

**Comment by nordmoen** [comment]
I'm sorry for taking so much of your time, but I'm really interested in understanding why my code isn't working properly with multiple queues. The code works and calculates the correct result, if I use two devices I can see that work is being submitted to both, however, no kernel executes concurrently with another (verified with Nsight Systems). I have now gotten permission to share the core SYCL code:

```c++

#include <SYCL/sycl.hpp>
#include <chrono>
#include <cmath>
#include <iostream>
#include <stdlib.h>
#include <string>
#include <vector>

#include "matched_filter_SYCL.h"

#define STABILITY_THRESHOLD 0.000001f

void println(const std::string &txt) { std::cout << txt << std::endl; }
float elapsed_sec(std::chrono::time_point<std::chrono::steady_clock> t1, std::chrono::time_point<std::chrono::steady_clock> t2) { return std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count() / 1.0e6; }
float elapsed_ms(std::chrono::time_point<std::chrono::steady_clock> t1, std::chrono::time_point<std::chrono::steady_clock> t2) { return std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count() / 1.0e3; }

// Helper struct which holds a collection of device pointers, which makes it
// easier to store a group of pointers in vectors
struct DevicePtrs {
    float* templates;
    float* sum_sq_templates;
    float* data;
    float* weights;
    int* moveouts;
    float* cc_sum;
    sycl::event prev_evt;
};

std::vector<sycl::device> enumerate_devices(const int n_samples_template,
					    const int n_samples_data,
					    const int n_stations,
					    const int n_components,
					    const int n_corr) {
    std::vector<sycl::device> devices;
    // Estimate roughly the amount of device memory we need and filter out
    // devices with too little memory
    const int network_size = n_components * n_stations;
    const int total_memory = sizeof(float) *
	(network_size * n_samples_template + // Storage for 'templates'
	network_size + // Storage for 'sum_square_templates'
	network_size * n_samples_data + // Storage for 'data'
	network_size + // Storage for 'weights'
	network_size + // Storage for 'moveouts'
	n_corr); // Approximate storage for 'cc_sum'
    println("------------------------------");
    println("Performing device discovery");
    for (auto device : sycl::device::get_devices(sycl::info::device_type::gpu)) {
	const auto dev_mem = device.get_info<sycl::info::device::global_mem_size>();
	const auto dev_name = device.get_info<sycl::info::device::name>();
	if (dev_mem >= total_memory) {
	    println("\tUsing device: " + dev_name);
	    devices.push_back(device);
	} else {
	    std::cerr << "\033[0;33mWARN: " << dev_name <<
		" has too little memory, found " << dev_mem <<
		" require " << total_memory << " bytes \033[0m\n";
	}
    }
    return devices;
}

extern "C" { // needed for C-style symbols in shared object compiled by syclcc
void matched_filter(float *templates,
                    float *sum_square_templates,
                    int *moveouts,
                    float *data, 
                    float *weights,
                    int step,
                    int n_samples_template,
                    int n_samples_data,
                    int n_templates,
                    int n_stations,
                    int n_components,
                    int n_corr,
                    float *cc_sum, // output variable
                    int normalize) {
    const auto devices = enumerate_devices(n_samples_template, n_samples_data,
					   n_stations, n_components, n_corr);
    std::vector<sycl::queue> queues;
    if (devices.size() > 0) {
	for (auto device : devices) {
	    queues.push_back(sycl::queue{device});
	}
    } else {
	queues.push_back(sycl::queue{sycl::default_selector{}});
	std::cerr << "\033[0;33mWARN: Did not find any SYCL enabled GPUs, using default device\033[0m\n";
    }
    println("------------------------------");
    println("step               : " + std::to_string(step));
    println("n_samples_template : " + std::to_string(n_samples_template));
    println("n_samples_data     : " + std::to_string(n_samples_data));
    println("n_templates        : " + std::to_string(n_templates));
    println("n_stations         : " + std::to_string(n_stations));
    println("n_components       : " + std::to_string(n_components));
    println("n_corr             : " + std::to_string(n_corr));
    println("------------------------------");

    const auto alloc_start = std::chrono::steady_clock::now();
    // Allocate device memory per queue/device
    const size_t network_size = static_cast<size_t>(n_stations * n_components);
    std::vector<struct DevicePtrs> device_data;
    // Create one output buffer per queue/device so that each loop iteration
    // below can be run independent
    for(auto Q : queues) {
	// Allocate memory per queue/device
	device_data.push_back(
	    {
		sycl::malloc_device<float>(network_size * n_samples_template, Q),
		sycl::malloc_device<float>(network_size, Q),
		sycl::malloc_device<float>(network_size * n_samples_data, Q),
		sycl::malloc_device<float>(network_size, Q),
		sycl::malloc_device<int>(network_size, Q),
		sycl::malloc_device<float>(static_cast<size_t>(n_corr), Q),
	    }
	);
	// 'data' never changes so we upload it right away
	auto queue_mem = device_data[device_data.size() - 1];
	queue_mem.prev_evt = Q.copy<float>(data, queue_mem.data, network_size * n_samples_data);
    }
    auto dt = elapsed_ms(alloc_start, std::chrono::steady_clock::now());
    println("Device allocation : " + std::to_string(dt) + " ms");
    println("------------------------------");

    const auto loop_start = std::chrono::steady_clock::now();
    for (int t = 0; t < n_templates; ++t) {
	const auto queue_index = t % queues.size();
	auto Q = queues[queue_index];
	auto device_mem = device_data[queue_index];

        println("##############################");
	println("Chosen device (" + std::to_string(queue_index) +
	 ")  : " + Q.get_device().get_info<sycl::info::device::name>());
	println("------------------------------");
        const auto t1 = std::chrono::steady_clock::now();
        const int network_offset = t * network_size;
        const int cc_sum_offset = t * n_corr;

        int min_moveout = 0;
        int max_moveout = 0;
        for (int ch = 0; ch < (n_stations * n_components); ++ch) {
            if (moveouts[network_offset + ch] < min_moveout) min_moveout = moveouts[network_offset + ch];
            if (moveouts[network_offset + ch] > max_moveout) max_moveout = moveouts[network_offset + ch];
        }
        const int start_i = static_cast<int>(std::ceil(std::abs(min_moveout)
						       / static_cast<float>(step)) * step);
        const int stop_i = 1 + (n_samples_data - n_samples_template - max_moveout);
	const sycl::range i_range{static_cast<size_t>(stop_i - start_i) / step};
        println("Kernel range : " + std::to_string(i_range.size()));
        println("------------------------------");

	// Copy iteration data to our current queue
	const auto temp_evt = Q.copy<float>(templates + network_offset * n_samples_template,
					    device_mem.templates, network_size * n_samples_template,
					    device_mem.prev_evt);
	const auto sum_sq_evt = Q.copy<float>(sum_square_templates + network_offset,
					      device_mem.sum_sq_templates, network_size,
					      device_mem.prev_evt);
	const auto weight_evt = Q.copy<float>(weights + network_offset,
					      device_mem.weights, network_size,
					      device_mem.prev_evt);
	const auto move_evt = Q.copy<int>(moveouts + network_offset,
					  device_mem.moveouts, network_size,
					  device_mem.prev_evt);
	// First calculate network correlation with all data residing on device
	// this will ensure that all tasks enqueued are run asynchronously
	const auto compute_evt = Q.submit([&](sycl::handler& h) {
	    // Create dependencies on the data movement above
	    h.depends_on({temp_evt, sum_sq_evt, weight_evt, move_evt});

	    h.parallel_for(i_range, [=](auto& idx) {
		const int index = idx[0] * step + start_i;
		float cc_sum = 0.0;
		for (int station = 0; station < n_stations; station++) {
		    for (int comp = 0; comp < n_components; comp++) {
			const int comp_offset = station * n_components + comp;
			const int temp_offset = comp_offset * n_samples_template;
			const int data_offset = comp_offset * n_samples_data + device_mem.moveouts[comp_offset];
			float mean = 0.0;
			float numerator = 0.0;
			float sum_square = 0.0;
			// Check if we need to continue
			if (device_mem.weights[comp_offset] == 0.0) {
			    continue;
			}
			if (normalize) {
			    for (int i = 0; i < n_samples_template; i++) {
				mean += device_mem.data[index + data_offset + i];
			    }
			    mean /= static_cast<float>(n_samples_template);
			}
			for (int i = 0; i < n_samples_template; i++) {
			    const float sample = device_mem.data[index + data_offset + i] - mean;
			    numerator += device_mem.templates[temp_offset + i] * sample;
			    sum_square += sample * sample;
			}
			const float denominator = std::sqrt(
					device_mem.sum_sq_templates[comp_offset] * sum_square);
			if (denominator > STABILITY_THRESHOLD) {
			    cc_sum += (numerator / denominator) * device_mem.weights[comp_offset];
			}
		    }
		}
		device_mem.cc_sum[idx[0]] = cc_sum;
	    });
	});
	// Copy result from device memory to output buffer once the above
	// compute kernel is done
	device_mem.prev_evt = Q.copy(device_mem.cc_sum, cc_sum + cc_sum_offset + start_i,
				     i_range.size(), compute_evt);

	const auto t2 = std::chrono::steady_clock::now();
        dt = elapsed_ms(t1, t2);
        println("Total time : " + std::to_string(dt) + " ms");
        println("------------------------------");
        println("##############################");
    }
    dt = elapsed_ms(loop_start, std::chrono::steady_clock::now());
    println("All loop iterations : " + std::to_string(dt) + " ms");
    println("------------------------------");
    // Free memory per queue
    for (int i = 0; i < queues.size(); i++) {
	auto Q = queues[i];
	// Wait for last submission of this queue
	Q.wait();
	auto dev_mem = device_data[i];
	sycl::free(dev_mem.templates, Q);
	sycl::free(dev_mem.sum_sq_templates, Q);
	sycl::free(dev_mem.data, Q);
	sycl::free(dev_mem.weights, Q);
	sycl::free(dev_mem.moveouts, Q);
    }
} // matched_filter
} // extern C
```

This version uses only USM pointers, as you can see, and uses multiple queues to submit. Naively it seems that this should work, the queues should be able to run in parallel as there are no dependencies between queues nor loop iterations (the `for (int t = 0; t < n_templates; ++t)`)

**Comment by illuhad** [comment]
I don't see anything immediately; does it execute concurrently if you increase problem size? For short-running kernels, I can imagine that the execution of one iteration of the loop and processing all the submits might take longer than the actual operations on device. In this case, they would appear to run sequentially.
What happens if you turn the queue into an in-order queue?

**Comment by nordmoen** [comment]
Maybe that could be the problem, but I don't have a larger problem size at the moment.

From the `println` debugging I can see that `All loop iterations : 0.310000 ms`, so job submission seem to end quite quickly, but then it takes another 5 seconds before the jobs are done. Based on the Nsight trace I see that each kernel runs for around 300+ms:

![Screenshot from 2022-10-03 14-59-05](https://user-images.githubusercontent.com/190117/193583078-8179e9fb-6d2c-48a9-a2f6-47966b2bdf8b.png)

Changing to in-order queue changes nothing (I tested by changing  the `queues.push_back(sycl::queue{device})` to `queues.push_back(sycl::queue{device, sycl::property::queue::in_order()})`

**Comment by illuhad** [comment]
> From the println debugging I can see that All loop iterations : 0.310000 ms, so job submission seem to end quite quickly

It offloads submission to a worker thread to process things in the background, so you cannot really draw this conclusion unfortunately. A `submit()` will return pretty much immediately to the main thread.

Are you sure that we actually see kernels running here? Are the blue bars kernels or memory transfers? The CUDA API trace looks suggestively like it spends most of its time actually doing data transfers, not kernels (but I don't know from the top of my head how nsight visualizes things, and I don't have it here right now to verify).
You do data copies in every iteration, which might have a substantial impact. Is it really necessary to copy back every iteration?

I know that with a single device, NVIDIA typically can only do data transfers concurrently if any involved host pointers are from page-locked ("pinned") host memory. Such memory can be obtained in SYCL from `sycl::malloc_host()`. I don't know if this also applies to multi-device concurrency, but it might be worth a try - of course, even better would be to just eliminate unnecessary data transfers.

**Comment by nordmoen** [comment]
Thank you so much @illuhad, the point about CUDA not being able to concurrently copy data to host pointers turned out to be the culprit in this scenario. I changed it to store everything in device memory until the end and now it is working (running kernels in parallel on two GPUs)!

Thank you both so much for the help, I have learned a lot!
