### ISSUE TITLE
Behavior of accessor access created with offset

### ISSUE THREAD

**Issue by nordmoen** [AdaptiveCpp/AdaptiveCpp#837]
Hi,

I have some code where I create `sycl::accessors` with an offset intended to index with an offset to the underlying buffer.

```c++
sycl::buffer buf{data_ptr, sycl::range{N * M}};
for(int i = 0; i < M; i++) {
  Q.submit([&](sycl::handler& h) {
    sycl::accessor acc{buf, h, sycl::range{N}, sycl::id{i * N}};
    ...
  });
}
```

I would have assumed that when I index `acc[idx]` it would be offset with `i * N`, however, when trying this it is not offset and I have to index with `acc[acc.get_offset() + idx]`, to get the correct offset. Is this expected?

**Comment by illuhad** [comment]
This is a remnant from SYCL 1.2.1. In SYCL 1.2.1, indexing would always start from the base of the allocation. In SYCL 2020, indexing was changed to start from the offset. We have not yet made that change.

**Comment by nordmoen** [comment]
That makes sense, thanks!
