### ISSUE TITLE
Problem when building

### ISSUE THREAD

**Issue by ManuelCostanzo** [AdaptiveCpp/AdaptiveCpp#841]
Hi all! 

When I build the project I get this:

`#0 28.22 /tmp/hipSYCL-installer/src/compiler/cbs/IRUtils.cpp: In function 'bool hipsycl::compiler::utils::checkedInlineFunction(llvm::CallBase*, llvm::StringRef)':
#0 28.22 /tmp/hipSYCL-installer/src/compiler/cbs/IRUtils.cpp:138:59: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
#0 28.22   138 |   llvm::InlineResult ILR = llvm::InlineFunction(*CI, IFI, nullptr);
#0 28.22       |                                                           ^~~~~~~
#0 28.22 In file included from /tmp/hipSYCL-installer/src/compiler/cbs/IRUtils.cpp:41:
#0 28.22 /opt/hipSYCL/llvm/include/llvm/Transforms/Utils/Cloning.h:267:34: note:   initializing argument 3 of 'llvm::InlineResult llvm::InlineFunction(llvm::CallBase&, llvm::InlineFunctionInfo&, bool, llvm::AAResults*, bool, llvm::Function*)'
#0 28.22   267 |                             bool MergeAttributes = false,
`

Does someone know how to solve it? Thank you very much!

**Comment by illuhad** [comment]
Hi!

please provide more information:
* operating system
* commands used to install hipSYCL
* which hipSYCL version
* which LLVM version

**Comment by ManuelCostanzo** [comment]
Hi @illuhad yes, sorry:

Operating system: Ubuntu 20.04
LLVM version: 16
hipSYCL version: I cloned de develop branch
commands used to install hipSYCL: I'm doing: 
```
cmake \
-DWITH_CPU_BACKEND=ON \
-DWITH_CUDA_BACKEND=ON \
-DLLVM_DIR=$HIPSYCL_LLVM_DIR \
-DCMAKE_INSTALL_PREFIX=$HIPSYCL_INSTALL_PREFIX \
..
```

Thanks

**Comment by illuhad** [comment]
@fodinabor Do you happen to know what the status of our LLVM 16 support is?

**Comment by ManuelCostanzo** [comment]
Hey, yes, I tried with LLVM 15, and it worked! So it's a problem with LLVM 16. Thanks!
