### ISSUE TITLE
Performance cuda kernel vs hipSYCL kernel

### ISSUE THREAD

**Issue by Rhynden** [AdaptiveCpp/AdaptiveCpp#851]
Hi,

for some runtime analysis for porting a hip/cuda application to hipSYCL I wanted to "benchmark" some very simplistic kernels.

In a [previous issue (#850)](https://github.com/illuhad/hipSYCL/issues/850) I was a bit surprised about the runtime differences within hipSYCL itself, so maybe I'm just not utilizing hipSYCL correctly.

Now, I tested the following small snippets, computing a simple scalar multiplication.
hipSYCL:
```
#include <sycl/sycl.hpp>
#include <vector>
#include <iostream>
using namespace sycl;

int main()
{
    queue myQueue;
    size_t size = 3375;
    auto dims = sycl::range<1>{size * 64 * 64 * 64};
    std::vector<sycl::float2> vecWithData(size * 64 * 64 * 64, sycl::float2{1.0f, 0.0f});
    std::cout << "vector size " << vecWithData.size() << std::endl;
    {
        sycl::buffer<sycl::float2, 1> complexIn = sycl::make_async_writeback_view(vecWithData.data(), dims, myQueue);

        myQueue.submit([&](sycl::handler &cgh)
                       {

                           cgh.parallel_for(dims, [=](sycl::id<1> index)
                                            { vec_acc[index] = vec_acc[index] * 3.0f; }); });
    }

    myQueue.wait();
}
```

vs cuda:
```
#include <stdio.h>

__global__ void mul(int n, float *x)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        x[i] = x[i] * 3.0f;
}

int main(void)
{
    int N = 2*960*960*960;
    float *x, *d_x;
    x = (float *)malloc(N * sizeof(float));

    cudaMalloc(&d_x, N * sizeof(float));

    for (int i = 0; i < N; i++)
    {
        x[i] = 1.0f;
    }

    cudaMemcpy(d_x, x, N * sizeof(float), cudaMemcpyHostToDevice);

    // Perform mul 
    mul<<<(N + 255) / 256, 256>>>(N, d_x);

    cudaMemcpy(x, d_x, N * sizeof(float), cudaMemcpyDeviceToHost);
    double sum = 0;
    for(int i=0; i<N; i++)
        sum += x[i];
    printf("final result: %f\n", sum/N);

    cudaFree(d_x);
    free(x);
}
```

Both run on a RTX 2080 Ti and analysed with Nsight Systems produced (Top is CUDA, bottom is hipSYCL):
![cuda_native_mul](https://user-images.githubusercontent.com/17203805/196030489-3cc050e0-3a9e-4ac4-a4fd-c67da682a18d.JPG)
![hipSYCL_cuda_mul](https://user-images.githubusercontent.com/17203805/196030494-2883d58a-5a13-4d0f-8194-4debef04280e.JPG)

As you can see, the memory allocation/deallocation requires similar times, but the execution of the kernels varies with 1900 miliseconds vs 26 miliseconds. This is a big difference for such a small computation. 

Shouldn't the runtimes be about similar, with hipSYCL being only slightly less performant?
If not, why is hipSYCL so much slower and what would be some options to improve it?

Any help appreciated

Kind regards

**Comment by illuhad** [comment]
> Shouldn't the runtimes be about similar, with hipSYCL being only slightly less performant?

Yes, on average performance should be roughly on par (there are also cases where hipSYCL can outperform native APIs).

Please provide more information:
* Software used (CUDA, hipSYCL, clang/LLVM, OS)
* How you have built hipSYCL and your example application.
* Output of `hipsycl-info`

It might also be worth a try using linear `float` instead of float2 (maybe two arrays for the two components to avoid strided access, or your own data structure) . SYCL vector types are insanely complex, and it's not always clear what the compiler makes of it.

**Comment by Rhynden** [comment]
Hi,
currently using hipsycl 0.9.1, therefore I can't provide hipsycl-info output.
Running on Ubuntu 18.04.1, cuda 11.8.89, llvm 13.
hipSYCL was built with clang13 and I compiled the provided examples with an adapted version of [your CMakeLists.txt example](https://github.com/illuhad/hipSYCL/blob/develop/examples/CMakeLists.txt)
`cmake .. -DhipSYCL_DIR=/opt/hipSYCL-llvm13/lib/cmake/hipSYCL/ -DHIPSYCL_TARGETS="omp;cuda:sm_75"`
You need further information?

PS: Using `float` instead of `sycl::float2` still has a runtime of about 600ms, so around 1/3 of using `sycl::float2` but still way slower than the cuda program.

**Comment by illuhad** [comment]
Thanks, please set the environment variable `HIPSYCL_DRYRUN=1` when building your code and post the output.

**Comment by Rhynden** [comment]
Hi,
with `HIPSYCL_DRYRUN=1` I get the following output:
```
[ 96%] Building CXX object CMakeFiles/CppRandomTests.dir/doctest/CppRandomTests.cpp.o
syclcc warning: No optimization flag was given, optimizations are disabled by default. Performance may be degraded. Compile with e.g. -O2/-O3 to enable optimizations.
/usr/lib/llvm-13/bin/clang++ -I/opt/hipSYCL-llvm13/bin/../include/ -D__HIPSYCL__ -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -fplugin=/opt/hipSYCL-llvm13/bin/../lib/libhipSYCL_clang.so -fpass-plugin=/opt/hipSYCL-llvm13/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_USE_ACCELERATED_CPU__ -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE -x cuda --cuda-path=/usr/local/cuda -D__HIPSYCL_ENABLE_CUDA_TARGET__ -D__HIPSYCL_CLANG__ -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem /opt/hipSYCL-llvm13/bin/../include/hipSYCL/std/hiplike --cuda-gpu-arch=sm_75 -I/usr/include/mpich -isystem /usr/local/cuda/include -isystem /opt/hipSYCL-llvm13/include -std=gnu++20 -MD -MT CMakeFiles/CppRandomTests.dir/doctest/CppRandomTests.cpp.o -MF CMakeFiles/CppRandomTests.dir/doctest/CppRandomTests.cpp.o.d -o CMakeFiles/CppRandomTests.dir/doctest/CppRandomTests.cpp.o -c /home/ArtiatomiHPC/doctest/CppRandomTests.cpp
[100%] Linking CXX executable CppRandomTests
/usr/lib/llvm-13/bin/clang++ CMakeFiles/CppRandomTests.dir/doctest/CppRandomTests.cpp.o -o CppRandomTests -L/opt/rocm/lib -L/usr/local/cuda/lib64 -Wl,-rpath,/opt/rocm/lib:/usr/local/cuda/lib64:/opt/hipSYCL-llvm13/lib -lmpich /usr/local/cuda/lib64/libcudart.so /usr/local/cuda/lib64/libcufft.so -lhipfft /opt/hipSYCL-llvm13/lib/libhipSYCL-rt.so -L/opt/hipSYCL-llvm13/bin/../lib/ -lhipSYCL-rt -Wl,-rpath=/opt/hipSYCL-llvm13/bin/../lib/ -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp -Wl,-rpath=/usr/local/cuda/lib64 -L/usr/local/cuda/lib64 -lcudart
```

Kind regards

**Comment by illuhad** [comment]
> syclcc warning: No optimization flag was given, optimizations are disabled by default. Performance may be degraded. Compile with e.g. -O2/-O3 to enable optimizations.

Well that explains it :D It's not compiling with any optimization flags.
Are you sure you're using `CMAKE_BUILD_TYPE=Release`?

**Comment by zjin-lcf** [comment]
@Rhynden 

I am not familiar with the gui interface, but the block sizes are different in the figure. In addition, could you try the other compiler  https://github.com/intel/llvm ?

**Comment by illuhad** [comment]
@zjin-lcf The block sizes  are different because the SYCL code uses range-based parallel for where the implementation selects a work group size automatically. hipSYCL chooses 128 here, while the CUDA code uses 256.
Based on the output it is clear that this is unrelated to the performance behavior, and the performance gap comes from the fact the program was not compiled with `-O3`.
Please do not point to other SYCL implementations which may require substantial effort to set up,  when the issue can be resolved easily on the user side by compiling with appropriate flags. Thanks :)

@Rhynden I assume the issue is resolved. Please reopen if there are still open questions.
