### ISSUE TITLE
sycl::vec swizzle is not working properly

### ISSUE THREAD

**Issue by misos1** [AdaptiveCpp/AdaptiveCpp#865]
**Bug summary**
Seems `swizzle` just returns a sliced copy of original `vec`.

Also could not that constructor with variable template arguments deduce type of data and number of components from passed data? So it would be possible to just write something like `sycl::vec(1, 2, 3, 4)` or `sycl::vec v(1, 2, 3, 4)`.

**To Reproduce**
``` c++
auto v = sycl::vec<int, 4>(1, 2, 3, 4);
printf("%i %i\n", v.hi().x(), v.hi().y());
```

**Expected behavior**
Function `hi` should return (3, 4) instead of (1, 2).

**Describe your setup**
Commit 53937c6e908446bfd639a5e8ab7548e5f698b102.

**Comment by illuhad** [comment]
Thank you, both the vector constructor and the swizzle issue should be resolved by #866.
