### ISSUE TITLE
[hipSYCL Error] Did not find kernel mangling suggestion for encountered kernel, this should never happen

### ISSUE THREAD

**Issue by misos1** [AdaptiveCpp/AdaptiveCpp#871]
**Bug summary**
Not sure whether to send this to llvm or here.

 #0 0x00005623f0c9f574 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005623f0c9cdd4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007feab7bce420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007feab7540d36 hipsycl::compiler::FrontendASTVisitor::nameKernelUsingKernelManglingStub(clang::FunctionDecl*) (/usr/local/bin/../lib/libhipSYCL_clang.so+0x5ed36)
 #4 0x00007feab755fe55 hipsycl::compiler::FrontendASTVisitor::applyAttributes() (/usr/local/bin/../lib/libhipSYCL_clang.so+0x7de55)
 #5 0x00007feab7560713 hipsycl::compiler::FrontendASTConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/../lib/libhipSYCL_clang.so+0x7e713)
 #6 0x00005623f1821850 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/rocm-5.3.0/llvm/bin/clang-15+0x3342850)
 #7 0x00005623f2c93469 clang::ParseAST(clang::Sema&, bool, bool) (/opt/rocm-5.3.0/llvm/bin/clang-15+0x47b4469)
 #8 0x00005623f1ee3445 clang::CodeGenAction::ExecuteAction() (/opt/rocm-5.3.0/llvm/bin/clang-15+0x3a04445)
 #9 0x00005623f17e74a1 clang::FrontendAction::Execute() (/opt/rocm-5.3.0/llvm/bin/clang-15+0x33084a1)
#10 0x00005623f176f24b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/rocm-5.3.0/llvm/bin/clang-15+0x329024b)
#11 0x00005623f18c519b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/rocm-5.3.0/llvm/bin/clang-15+0x33e619b)
#12 0x00005623ef318674 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/rocm-5.3.0/llvm/bin/clang-15+0xe39674)
#13 0x00005623ef311efb ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#14 0x00005623ef314451 clang_main(int, char**) (/opt/rocm-5.3.0/llvm/bin/clang-15+0xe35451)
#15 0x00007feab764c083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#16 0x00005623ef3114ee _start (/opt/rocm-5.3.0/llvm/bin/clang-15+0xe324ee)
clang-15: error: unable to execute command: Segmentation fault (core dumped)
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)

**To Reproduce**
I just tried to not use lambda:

``` c++
void func()
{
}

int main()
{
	sycl::queue().single_task(func);
}
```

**Comment by illuhad** [comment]
Invalid code. Kernels in SYCL need to be lambda functions or function objects.

If you pass in a regular function, it will decay to a function pointer which is not allowed in device code. That said, maybe we should give a clearer error message instead of just crashing.

**Comment by misos1** [comment]
Yes, that would be good because it prints error message which starts with "PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.".
