### ISSUE TITLE
Additional latency added by hipSYCL

### ISSUE THREAD

**Issue by misos1** [AdaptiveCpp/AdaptiveCpp#879]
I wanted to roughly measure the approximate latency of kernel execution on my system. I expected the default queue to have higher latency because of synchronization when dispatching work into the queue pool. So with `sycl::property::queue::in_order` it should be really close to what I can get with `hip` but unfortunately these values are about 4x higher. Should not `in_order` cause `hipSYCL` to use a dedicated queue? As mentioned in #142 this should have lower latency: "In that way, a SYCL library that knows that its kernels are best processed in-order for lower latency could submit its kernels with in-order scheduling..."

```
hipSYCL		hip
11382		2811
10614		2215
10568		2262
11135		2221
10654		2202
10455		2200
10734		2205
11215		2247
10713		2238
10549		2199
```

<details>
<summary>source</summary>

``` c++
#include <sycl/sycl.hpp>

__global__ void hip(int *buf, int i)
{
	buf[i] = i;
}

int main()
{
	const int iters = 10;
	const int num = 10000;

	sycl::queue q = sycl::queue({sycl::property::queue::in_order()});
	int *buf = (int*)sycl::malloc_host(num * sizeof(int), q);
	int times_sycl[iters];
	int times_hip[iters];

	for(int i = 0; i < iters; i++)
	{
		for(int i = 0; i < num; i++)buf[i] = -1;
		auto sta = std::chrono::high_resolution_clock().now();
		for(int i = 0; i < num; i++)q.single_task([=]()
		{
			buf[i] = i;
		});
		q.wait();
		auto end = std::chrono::high_resolution_clock().now();
		for(int i = 0; i < num; i++)assert(buf[i] == i);
		times_sycl[i] = (end - sta).count() / num;
	}

	for(int i = 0; i < iters; i++)
	{
		for(int i = 0; i < num; i++)buf[i] = -1;
		auto sta = std::chrono::high_resolution_clock().now();
		for(int i = 0; i < num; i++)hipLaunchKernelGGL(hip, 1, 1, 0, 0, buf, i);
		assert(!hipDeviceSynchronize());
		auto end = std::chrono::high_resolution_clock().now();
		for(int i = 0; i < num; i++)assert(buf[i] == i);
		times_hip[i] = (end - sta).count() / num;
	}

	printf("hipSYCL\t\thip\n");
	for(int i = 0; i < iters; i++)printf("%i\t\t%i\n", times_sycl[i], times_hip[i]);
}
```

</details>

Also `hipSYCL` allows for running `hip` kernels on its queues. Is it possible to do it in reverse, to get the `hip` kernel, let's say `hipFunction_t` from `sycl` kernel lambda? Possibly without dispatching it first on `hipSYCL` queue. It would be really convenient when working with features not yet implemented in `hipSYCL` like subdevices (which is possible in `hip` using `hipExtStreamCreateWithCUMask`) while avoiding marking all things as `__host__` and/or `__device__`. Or is it possible to somehow extract `amd_kernel_code_t` of `hipSYCL` kernel (low level struct actually describing kernel and "containing" its binary on rocm platform)?

Another little thing I noticed is that compilation using `syclcc` takes a really long time, about 10 seconds while `hipcc` runs much faster. And also there is a relatively huge delay when creating the first sycl queue.

Also I noticed that queue profiling (btw enabled profiling have huge impact on latency) timestamps like `sycl::info::event_profiling::command_start` have different resolution than these of `hip` events and I noticed some hints in `hipSYCL` sources. Are they all coming from `std::chrono` rather than `hip` also for GPUs? On rocm there are also "native" timestamps which can be obtained directly for kernel dispatch recorded directly by hardware with only minimal impact (no `hip` events are needed for this).

**Comment by illuhad** [comment]
> Should not in_order cause hipSYCL to use a dedicated queue? 

It does use a dedicated queue for SYCL `in_order` queues.

> but unfortunately these values are about 4x higher.

You are not measuring kernel submission latency. You are measuring kernel submission, kernel execution and kernel synchronization, and you are comparing a framework that does automatic DAG construction and kernel dependency tracking, as well as support for automatic data movements using the buffer abstraction :-)
Also SYCL and HIP make different synchronization guarantees. If you run the kernels using the `hipSYCL_coarse_grained_events` command group property, which tells the runtime that you are not interested in having synchronization mechanisms for each individual kernel launch, just like in HIP, it gets much closer:
```
hipSYCL         hip
3656            2531
4248            1809
4147            1465
3986            1644
4624            1441
4079            1635
3790            1463
3889            1631
3561            1457
4014            1628
```
The rest is probably due to these additional abstractions. Also keep in mind that some of these overheads might not impact actual kernel throughput.

> Also hipSYCL allows for running hip kernels on its queues. Is it possible to do it in reverse, to get the hip kernel, let's say hipFunction_t from sycl kernel lambda?

Not yet. hipSYCL might multi-version kernels, so you may have multiple HIP kernels for one kernel lambda.

> Another little thing I noticed is that compilation using syclcc takes a really long time, about 10 seconds while hipcc runs much faster. And also there is a relatively huge delay when creating the first sycl queue.

Both are basically just clang. What you are seeing is the time it takes to parse a large header written in modern C++, as defined by the specification: `sycl.hpp`. Add similar abstractions and compile them with `hipcc` and you will see the same compilation times.
As a sidenote, hipSYCL substantially outperforms `hipcc` compile times when using the new (work-in-progress) single-pass compiler framework, especially when targeting multiple devices in #862.

> Also I noticed that queue profiling (btw enabled profiling have huge impact on latency) timestamps like sycl::info::event_profiling::command_start have different resolution than these of hip events and I noticed some hints in hipSYCL sources. Are they all coming from std::chrono rather than hip also for GPUs? On rocm there are also "native" timestamps which can be obtained directly for kernel dispatch recorded directly by hardware with only minimal impact (no hip events are needed for this).

There is no `std::chrono` involved. Currently hipSYCL uses events for this because it allows sharing some code between HIP and CUDA. I am aware of the more advanced HIP kernel launch mechanisms. These can however not be used with all compilation flows that hipSYCL supports.
Resolution differences are probably because SYCL thinks in terms of absolute start+stop times while HIP/CUDA think in terms of differences (and only return those differences as single-precision float). This means we need to have a reference event to compare to in order to get absolute timings.

**Comment by illuhad** [comment]
> And also there is a relatively huge delay when creating the first sycl queue.

The first time you are doing SYCL stuff, the hipSYCL runtime is initialized, which loads all backends, does device discovery, maybe constructs the stream pool etc. This is expected.

**Comment by misos1** [comment]
> ```
> hipSYCL         hip
> 3656            2531
> 4248            1809
> 4147            1465
> 3986            1644
> 4624            1441
> 4079            1635
> 3790            1463
> 3889            1631
> 3561            1457
> 4014            1628
> ```

If you do not mind on what gpu you run it?

> The rest is probably due to these additional abstractions. Also keep in mind that some of these overheads might not impact actual kernel throughput.

Yes, of course. But sometimes this latency matters. I suppose it cannot be brought even closer to `hip` for now? I am actually surprised that it is so low with `hip` as it is also doing seemingly a lot of things. I cannot get it lower than by about 30% by even using HSA queue directly even with AQL queue and all things allocated in gpu memory and dispatching kernels from gpu and I suppose it is really close to hardware limit.

> Not yet. hipSYCL might multi-version kernels, so you may have multiple HIP kernels for one kernel lambda.

It would be nice to have the possibility to get them all.

> Both are basically just clang. What you are seeing is the time it takes to parse a large header written in modern C++, as defined by the specification: `sycl.hpp`. Add similar abstractions and compile them with `hipcc` and you will see the same compilation times.

Yes I should have realized this. Especially that there are actually two passes. I also just tried `clang` with a minimal amount of flags just `-std` and it got to about half of that (as it was just one pass). I tried it with a precompiled header and it feels a little faster. Maybe now I will try to figure out how to use precompiled headers with `syclcc` as it seems it must be generated separately for each pass. Unfortunately it seems I cannot directly control these two passes. I would need to have different command line arguments for each pass. Is this possible?

> As a sidenote, hipSYCL substantially outperforms `hipcc` compile times when using the new (work-in-progress) single-pass compiler framework, especially when targeting multiple devices in #862.

That looks interesting.

**Comment by illuhad** [comment]
> If you do not mind on what gpu you run it?

Ryzen 4750U APU in my development notebook. So, no PCIe involved which might explain why it is even lower than for you with HIP.

> Yes, of course. But sometimes this latency matters. I suppose it cannot be brought even closer to hip for now?

Optimization is an ongoing effort, but I would say that probably most of the obvious low-hanging fruits are gone now. So probably no easy improvements.

> Unfortunately it seems I cannot directly control these two passes. I would need to have different command line arguments for each pass. Is this possible?

It depends on the compilation flow. With `hip.integrated-multipass` compilation flow, clang controls these multiple passes. I don't think we can individually control them. With `hip.explicit-multipass`, hipSYCL controls the passes. If you configure `syclcc`'s rocm cxx flags, those will only be applied in the device pass.
In both cases, you can also always ask the compilers what commands they want to execute, and execute the commands manually... For integrated multipass/clang this can be done using `-###`, and for explicit multipass using `--hipsycl-dryrun`.
