### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by Alex2671** [AdaptiveCpp/AdaptiveCpp#917]
Greetings! I have failures within build setup, which i could't resolve. i have the following configuration: i7 10700 without discrete video, debian system. So i need to run al least on cpu, further on integrated gpu.

I do intallation in this manner:
cmake -DWITH_ROCM_BACKEND=OFF -DLLVM_DIR=../llvmBuild/llvm/lib -DWITH_CUDA_BACKEND=OFF -DWITH_ACCELERATED_CPU=ON -DCMAKE_INSTALL_PREFIX=../install -S ../hipSYCL-0.9.3
make install

and have some troubles after:
 /home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:56:14: error: 'RegisterStandardPasses' in namespace 'llvm' does not name a type
   56 | static llvm::RegisterStandardPasses
      |              ^~~~~~~~~~~~~~~~~~~~~~
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:60:14: error: 'RegisterStandardPasses' in namespace 'llvm' does not name a type
   60 | static llvm::RegisterStandardPasses
      |              ^~~~~~~~~~~~~~~~~~~~~~
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:74:14: error: 'RegisterStandardPasses' in namespace 'llvm' does not name a type
   74 | static llvm::RegisterStandardPasses
      |              ^~~~~~~~~~~~~~~~~~~~~~
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:84:14: error: 'RegisterStandardPasses' in namespace 'llvm' does not name a type
   84 | static llvm::RegisterStandardPasses
      |              ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/compiler/CMakeFiles/hipSYCL_clang.dir/build.make:76: src/compiler/CMakeFiles/hipSYCL_clang.dir/HipsyclClangPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: src/compiler/CMakeFiles/hipSYCL_clang.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

____________________________________________________________________________________________________________________________

Second approach i did with -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang and get little another message,but also connected with llvm namespace:
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:56:14: error: no type named 'RegisterStandardPasses' in namespace 'llvm'
static llvm::RegisterStandardPasses
       ~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:57:67: error: no member named 'EP_EnabledOnOptLevel0' in 'llvm::PassManagerBuilder'
    RegisterGlobalsPruningPassOptLevel0(llvm::PassManagerBuilder::EP_EnabledOnOptLevel0,
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:60:14: error: no type named 'RegisterStandardPasses' in namespace 'llvm'
static llvm::RegisterStandardPasses
       ~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:61:71: error: no member named 'EP_OptimizerLast' in 'llvm::PassManagerBuilder'
    RegisterGlobalsPruningPassOptimizerLast(llvm::PassManagerBuilder::EP_OptimizerLast,
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:74:14: error: no type named 'RegisterStandardPasses' in namespace 'llvm'
static llvm::RegisterStandardPasses
       ~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:75:76: error: no member named 'EP_EarlyAsPossible' in 'llvm::PassManagerBuilder'
    RegisterLoopSplitAtBarrierPassOptimizerFirst(llvm::PassManagerBuilder::EP_EarlyAsPossible,
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:84:14: error: no type named 'RegisterStandardPasses' in namespace 'llvm'
static llvm::RegisterStandardPasses
       ~~~~~~^
/home/alexey/code/hipSYCL/hipSYCL-0.9.3/src/compiler/HipsyclClangPlugin.cpp:85:68: error: no member named 'EP_VectorizerStart' in 'llvm::PassManagerBuilder'
    RegisterMarkParallelBeforeVectorizer(llvm::PassManagerBuilder::EP_VectorizerStart,
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
8 errors generated.
make[2]: *** [src/compiler/CMakeFiles/hipSYCL_clang.dir/build.make:76: src/compiler/CMakeFiles/hipSYCL_clang.dir/HipsyclClangPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: src/compiler/CMakeFiles/hipSYCL_clang.dir/all] Error 2


i see that problem in llvm, but i can't understand it deeply. By far, i tried to install llvm from your script at install directory.

**Comment by fodinabor** [comment]
Hi, you seem to be using a pretty new LLVM that has some legacy infrastructure removed. We adapted hipSYCL to deal with that in a commit post 0.9.3, so could you try if the develop branch works for you?

**Comment by Alex2671** [comment]
> Hi, you seem to be using a pretty new LLVM that has some legacy infrastructure removed. We adapted hipSYCL to deal with that in a commit post 0.9.3, so could you try if the develop branch works for you?

do you mean to download develop version? Yes , i did. It has changed prompt a little:
In file included from /home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/cbs/LoopSplitterInlining.cpp:31:
/home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/../../include/hipSYCL/compiler/cbs/SplitterAnnotationAnalysis.hpp:71:9: error: 'Optional' in namespace 'llvm' does not name a template type
   71 |   llvm::Optional<SplitterAnnotationInfo> SplitterAnnotation_;
      |         ^~~~~~~~
/home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/../../include/hipSYCL/compiler/cbs/SplitterAnnotationAnalysis.hpp: In member function 'const hipsycl::compiler::SplitterAnnotationInfo& hipsycl::compiler::SplitterAnnotationAnalysisLegacy::getAnnotationInfo() const':
/home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/../../include/hipSYCL/compiler/cbs/SplitterAnnotationAnalysis.hpp:84:69: error: 'SplitterAnnotation_' was not declared in this scope; did you mean 'SplitterAnnotationInfo'?
   84 |   const SplitterAnnotationInfo &getAnnotationInfo() const { return *SplitterAnnotation_; }
      |                                                                     ^~~~~~~~~~~~~~~~~~~
      |                                                                     SplitterAnnotationInfo
/home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/../../include/hipSYCL/compiler/cbs/SplitterAnnotationAnalysis.hpp: In member function 'hipsycl::compiler::SplitterAnnotationInfo& hipsycl::compiler::SplitterAnnotationAnalysisLegacy::getAnnotationInfo()':
/home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/../../include/hipSYCL/compiler/cbs/SplitterAnnotationAnalysis.hpp:85:57: error: 'SplitterAnnotation_' was not declared in this scope; did you mean 'SplitterAnnotationInfo'?
   85 |   SplitterAnnotationInfo &getAnnotationInfo() { return *SplitterAnnotation_; }
      |                                                         ^~~~~~~~~~~~~~~~~~~
      |                                                         SplitterAnnotationInfo
make[2]: *** [src/compiler/CMakeFiles/hipSYCL_clang.dir/build.make:104: src/compiler/CMakeFiles/hipSYCL_clang.dir/cbs/LoopSplitterInlining.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:410: src/compiler/CMakeFiles/hipSYCL_clang.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

__________________________________________________________________________________________________-
and with -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++:
In file included from /home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/cbs/LoopSplitterInlining.cpp:31:
/home/alexey/code/hipSYCL/hipSYCL-develop/src/compiler/../../include/hipSYCL/compiler/cbs/SplitterAnnotationAnalysis.hpp:71:3: error: no template named 'Optional' in namespace 'llvm'; did you mean 'std::optional'?
  llvm::Optional<SplitterAnnotationInfo> SplitterAnnotation_;
  ^~~~~~
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/optional:659:11: note: 'std::optional' declared here
    class optional
          ^
1 error generated.
make[2]: *** [src/compiler/CMakeFiles/hipSYCL_clang.dir/build.make:104: src/compiler/CMakeFiles/hipSYCL_clang.dir/cbs/LoopSplitterInlining.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:410: src/compiler/CMakeFiles/hipSYCL_clang.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by fodinabor** [comment]
Alright, seems the current LLVM development again butchered our upstream LLVM compatibility.
Will submit a PR remedying those issues in a bit.

(note, you'll need to have LLVM built with `-DLLVM_BUILD_LLVM_DYLIB=ON` for the new SSCP infrastructure... rebuilding with that is what currently keeps me from submitting the PR ;-))

**Comment by illuhad** [comment]
@Alex2671 Overall, be advised we only test with unreleased LLVM versions occasionally, as these are moving targets and can change APIs frequently as you see here. You will have a more stable experience if you use an officially released LLVM version such as 14 or 15.
