### ISSUE TITLE
How to compile code statically with syclcc?

### ISSUE THREAD

**Issue by ghost** [AdaptiveCpp/AdaptiveCpp#923]
I'm trying to compile a simple hello world program using syclcc,
I installed hipSYCL to a custom prefix (/home/iyad/hipSYCL_install)

without `--static` compilation works great
`syclcc hello_sycl.cpp --hipsycl-targets=generic -O3`
but I'm worried because the compiled program tries to load libraries from my install prefix

once I add static compiler flag it does not work anymore
`syclcc hello_sycl.cpp --hipsycl-targets=generic -O3 --static`
output
```
/usr/bin/ld: cannot find -lhipSYCL-rt: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried adding /home/iyad/hipSYCL_install/lib to LIBRARY_PATH and using `-L` flag with no success

program:
```
#include <iostream>
#include <CL/sycl.hpp>

class vector_addition;

int main(int, char**) {
   cl::sycl::float4 a = { 1.0, 2.0, 3.0, 4.0 };
   cl::sycl::float4 b = { 4.0, 3.0, 2.0, 1.0 };
   cl::sycl::float4 c = { 0.0, 0.0, 0.0, 0.0 };

   cl::sycl::default_selector device_selector;

   cl::sycl::queue queue(device_selector);
   std::cout << "Running on "
             << queue.get_device().get_info<cl::sycl::info::device::name>()
             << "\n";
   {
      cl::sycl::buffer<cl::sycl::float4, 1> a_sycl(&a, cl::sycl::range<1>(1));
      cl::sycl::buffer<cl::sycl::float4, 1> b_sycl(&b, cl::sycl::range<1>(1));
      cl::sycl::buffer<cl::sycl::float4, 1> c_sycl(&c, cl::sycl::range<1>(1));
  
      queue.submit([&] (cl::sycl::handler& cgh) {
         auto a_acc = a_sycl.get_access<cl::sycl::access::mode::read>(cgh);
         auto b_acc = b_sycl.get_access<cl::sycl::access::mode::read>(cgh);
         auto c_acc = c_sycl.get_access<cl::sycl::access::mode::discard_write>(cgh);

         cgh.single_task<class vector_addition>([=] () {
         c_acc[0] = a_acc[0] + b_acc[0];
         });
      });
   }
   std::cout << "  A { " << a.x() << ", " << a.y() << ", " << a.z() << ", " << a.w() << " }\n"
        << "+ B { " << b.x() << ", " << b.y() << ", " << b.z() << ", " << b.w() << " }\n"
        << "------------------\n"
        << "= C { " << c.x() << ", " << c.y() << ", " << c.z() << ", " << c.w() << " }"
        << std::endl;
		
   return 0;
}
```

**Comment by illuhad** [comment]
Hi!

-static prevents linking with all shared libraries (`.so`). Because the hipSYCL runtime library is a shared library, it cannot be linked anymore then. I think other SYCL implementations like DPC++ don't provide static versions of their runtime libraries either.
What is your use case that makes you not want a shared library?

**Comment by ghost** [comment]
I want to distribute the program on its own to users, they would need to have the shared libs in the expected location I suppose,
But I think now I understand I should ship the shared libraries alongside the program, I will try to figure it out then, thanks a ton for letting me know that it is not possible to statically link it 🙏

**Comment by illuhad** [comment]
Ok, I see. Yes you should redistribute the runtime library. The bigger problem is going to be the runtime's backends (`librt-backend-*`). They might expect CUDA/ROCm/Level Zero in the location where they were when building, or they might expect particular CUDA/ROCm/L0 versions etc. It's on the todo list to work on this, but not done yet (you could try getting it to linking statically with libcudart or libamdhip64 though)

**Comment by ghost** [comment]
Thanks again this helps 🙏
