### ISSUE TITLE
Project renaming to Open SYCL

### ISSUE THREAD

**Issue by illuhad** [AdaptiveCpp/AdaptiveCpp#942]
For a long time this project had issues with people misinterpreting what it is about based on the name hipSYCL. For example, it has been assumed that the project was somehow focused on AMD GPUs in particular, or even that it is an AMD project. While there are historic reasons for the name hipSYCL, the project has now outgrown the original name, and the name no longer fits.

The best example for this is the[ generic single-pass compiler](https://opensycl.github.io/hipsycl/sscp/compiler/generic-sscp/) that we have now, making it the only SYCL implementation with a unified code representation across backends and GPUs from AMD, NVIDIA and Intel -- able to generate binaries that run "everywhere" with just a single compiler pass.

Therefore, we have decided to rename the project to Open SYCL. This is to underline its importance in the ecosystem as not just a niche implementation with one particular focus, but a full-fledged open-source SYCL implementation project. It also underlines our commitment to growing its community in terms of both contributors and users. We believe that the community plays a vital role for the future of this project.

From the the perspective of our team at Heidelberg University as currently the main supporter of the project, nothing changes about the people involved in the project or the project's goals. The name change is there to align better with the existing strategy and commitment.

This issue is also here to discuss the migration process with users. Renaming a project is never an easy feat, but we want to avoid breaking things as much as possible.

We are currently planning the following migration process to the new name:

1. No user impact. This will be done immediately.
    * Rename the repository. GitHub automatically sets up redirects, therefore all existing links should remain valid.
    * Update logos and documentation
    * Add note to documentation that this project is in a renaming phase, and some parts have not migrated yet to avoid confusion.
    * Changes in source files that do not have observable impact, such as comments or include guards
2. Only expert user impact. Those will be done iteratively over the next weeks and months.
    * Rename internal APIs that in most cases should not be accessed by users. If you have some requirements here, please let us know.
3. Direct user impact. All users are expected to be affected. For these, we will continue to support the old naming during a deprecation period over multiple releases to avoid breaking user code. The renamed variants will be added ASAP to allow migration.
    * compiler flags, environment variables, cmake infrastructure, documented extensions

**Comment by FCLC** [comment]
Great to see! 

I'm a little worried about possible confusion with OpenCL/OpenGL etc. since SYCL as a spec is run by the Khronos Group.

**Comment by illuhad** [comment]
Thanks for the feedback :) Yes, this is a concern, and also the reason why we decided to write it with a space: Open SYCL, to distinguish in particular from OpenCL.

That said, Open is a common prefix for open source projects, so I hope that most people will see it in that context, and not immediately in the context of Khronos. We picked that name from a longer list of even less ideal names ;)

**Comment by FCLC** [comment]
> to write it with a space: Open SYCL, to distinguish in particular from OpenCL.

It may just be me, but the immediate reflex was to assume the space was a typo of sorts. ( Since in a directory you wouldn't have the space, and the URL doesn't have the space ofc.)

Definitely better than HipSYCL!

**Comment by illuhad** [comment]
I suppose if the space does not stick, it's a fairly easy fix to go back to not using a space (that would only affect documentation and not code). Open MPI also is using a space, and it seemed to have worked there - so let's see :-)

**Comment by illuhad** [comment]
Unfortunately, due to external legal pressure, we are forced to abandon the Open SYCL name.
Please discuss potential new names here: https://github.com/OpenSYCL/OpenSYCL/issues/999
