### ISSUE TITLE
SVG version of the logo is not rendered consistently

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#945]
**Bug summary**

Firefox 109 on Ubuntu 22.04 renders the SVG logo differently from the PNG:

- Cropped on the right
- Different font

Above: PNG from README; below: SVG opened separately in the same browser.

![image](https://user-images.githubusercontent.com/933873/217912580-0a842a00-01bb-41df-a628-01e60ad0763e.png)

On Chrome Mobile, the fonts are correct, but the "L" is still cropped.

**To Reproduce**

Open SVG and PNG side-by-side on different systems.

**Expected behavior**

No perceptible differences between SVG and PNG versions.

**Additional context**

I suspect converting the text to paths or embedding the font would help.

**Comment by illuhad** [comment]
Does it work if you open it with inkscape? It was created in inkscape, which I think uses some svg extensions.

**Comment by al42and** [comment]
Here's how it looks with Inkscape. Still has a different font (but at least sans-serif) and overruns the bounding box on the right:

![image](https://user-images.githubusercontent.com/933873/217915405-dfe5d89e-110a-486f-8b2d-2258bc82baa8.png)
