### ISSUE TITLE
Ambiguous type conversion in sycl::half

### ISSUE THREAD

**Issue by normallytangent** [AdaptiveCpp/AdaptiveCpp#956]
**Bug summary**
When running the tests in SYCL-CTS, as well as [while building OneMKL](https://github.com/normallytangent/oneMKL/actions/runs/4282543086/jobs/7456952634) with Open SYCL with CPU backend, I get an error of the following type.

```
Users/vsanc/opensycl/build/install/include/sycl/../hipSYCL/sycl/libkernel/half.hpp:50:11: error: call to 'create' is ambiguous
  : _data{fp16::create(f)} {}
```
If I understand correctly, at least inside SYCL-CTS, it breaks because of the [implicit cast of `int`](https://github.com/KhronosGroup/SYCL-CTS/blob/be5b4853fee384555979ffb179654bb34390ea5f/tests/common/common.h#L249), also I do not see a matching constructor in `half.hpp` as of #885.

**Comment by illuhad** [comment]
Presumably we get this issue exactly because there's no constructor from int. The SYCL specification is very vague with respect to what the `half` class needs to support. So, I'm not sure this is technically a bug - but we could just add an int constructor for the sake of convenience.

**Comment by normallytangent** [comment]
I can have a go at it, if that's okay with you :)

**Comment by illuhad** [comment]
Alright :)
