### ISSUE TITLE
Help with Stage 2: llvm-to-backend

### ISSUE THREAD

**Issue by juhigupta0** [AdaptiveCpp/AdaptiveCpp#961]
Greetings everyone,

As a newcomer to this project, I've been experimenting with the provided examples to familiarize myself with the tool. Currently, I'm researching ways to integrate hipSYCL into my project and leverage its capabilities. Specifically, I'm exploring the Generic SSCP compilation flow, and I have a question regarding _**Stage 2: llvm-to-backend**_.

I noticed that the implementation provides a tool (such as llvm-to-ptx-tool or llvm-to-spirv-tool) that can be used to perform the stage 2 compilation step manually. However, I'm not entirely sure how to use the tool. Could someone please provide me with instructions or guidance on how to use it effectively?

**Comment by illuhad** [comment]
First you need to obtain the HCF file, e.g. using `syclcc --opensycl-targets="generic" -mllvm -hipsycl-sscp-emit-hcf` (The `-hipsycl-sscp-emit-hcf` argument will be renamed in the future to `-opensycl-sscp-emit-hcf`).

You can inspect the content of the HCF file using `opensycl-hcf-tool`. This will list all the content in the HCF:
```
opensycl-hcf-tool file.hcf -p root
```
There will be an `images` node. The subnodes of that node correspond to names of device code images embedded in the HCF. Currently, this is very simple as we only generate a single global LLVM IR image per HCF for now. This image is called `llvm-ir.global`.

You can then use the llvm-to-backend tools to translate this image, e.g for the `llvm-ir.global` image:
```
lvm-to-spirv-tool file.hcf output.spirv llvm-ir.global
```

Note however that the tools currently do not expose all the functionalities that can be required to successfully translate an HCF that has been generated from SYCL. For example, the `SYCL_EXTERNAL` feature requires linking of device images which is not exposed in the tools.

Also, note that some backends have to be configured appropriately using the `--build-opt` or `--build-flag` arguments. This is a bit of a moving target, and might change in the future. At the moment SPIR-V wants to have the size of local memory configured. In the future, it is also planned to configure the work group size at stage 2 compilation time.
