### ISSUE TITLE
Linker error with HIP backend: undefined symbol: __oclc_ABI_version

### ISSUE THREAD

**Issue by reguly** [AdaptiveCpp/AdaptiveCpp#963]
**Bug summary**
Trying to compile the simplest example results in the above linker error

**To Reproduce**
A singularity/apptainer image built on docker://rocm/rocm-terminal (Rocm 5.4.2)
LLVM/Clang 14 installed using steps in docs
configured with
cmake .. -DROCM_PATH=/opt/rocm-5.4.2 -DWITH_ROCM_BACKEND=ON -DCMAKE_INSTALL_PREFIX=/opt/opensycl-install
Compilation with
syclcc --opensycl-targets=hip:gfx90a vec.cpp -O3
lld: error: undefined symbol: __oclc_ABI_version
>>> referenced by /tmp/vec-d649e7/vec-gfx90a.o:(void __hipsycl_kernel<hipsycl::glue::complete_kernel_name<main::'lambda'(hipsycl::sycl::handler&)::operator()(hipsycl::sycl::handler&) const::FillBuffer> >())
>>> referenced by /tmp/vec-d649e7/vec-gfx90a.o:(void __hipsycl_kernel<hipsycl::glue::complete_kernel_name<main::'lambda'(hipsycl::sycl::handler&)::operator()(hipsycl::sycl::handler&) const::FillBuffer> >())
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)

Linker command with -v:
 "/usr/lib/llvm-14/bin/lld" -flavor gnu --no-undefined -shared -plugin-opt=-amdgpu-internalize-symbols -plugin-opt=mcpu=gfx90a -plugin-opt=O3 -plugin-opt=-amdgpu-early-inline-all=true -plugin-opt=-amdgpu-function-calls=false -o /tmp/vec-85e55a/vec-gfx90a.out /tmp/vec-4405d8/vec-gfx90a.o

**Expected behavior**
Should link OK

**Describe your setup**
OpenSYCL commit b2e3f332e589743c3a3bf66b50b62689e64f5c9f
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang version 14 installed using llvm.sh and apt
   * Other SW stack and ROCm (5.4.2) as it comes from docker image
* How you have compiled your application and which arguments you have passed to `syclcc`. In particular, which backends and hardware you have compiled for.
syclcc --opensycl-targets=hip:gfx90a vec.cpp -O3

**Optional additional diagnostic information**
The following information can potentially help us:
* For compilation/toolchain or setup-related issues: Setting the environment variable `HIPSYCL_DRYRUN=1` during compilation will cause `syclcc` to print the commands it would execute instead of actually executing. This can help verify the sanity of your setup.
goes all the way to linking OK
* `syclcc --hipsycl-version` prints information about the hipSYCL configuration that may be interesting for setup-related issues.
Apptainer> syclcc --hipsycl-version
syclcc [Open SYCL compilation driver], Copyright (C) 2018-2023 Aksel Alpay and the Open SYCL project
  Open SYCL version: 0.9.4
  Installation root: /opt/opensycl-install
  Plugin LLVM version: 14, can accelerate CPU: True
  Available runtime backends:
     librt-backend-hip.so
     librt-backend-omp.so

Full configuration [can be overriden using environment variables or command line arguments]:
    version-major: 0
    version-minor: 9
    version-patch: 4
    plugin-llvm-version-major: 14
    plugin-with-cpu-acceleration: true
    default-clang: /usr/lib/llvm-14/bin/clang++
    default-nvcxx: (unconfigured)
    default-platform: rocm
    default-cuda-path: (unconfigured)
    default-gpu-arch: (unconfigured)
    default-cpu-cxx: /usr/bin/c++
    default-rocm-path: /opt/rocm-5.4.2
    default-use-bootstrap-mode: false
    default-is-dryrun: false
    default-use-accelerated-cpu: true
    default-clang-include-path: /usr/lib/llvm-14/lib/clang/14.0.6/include/..
    default-sequential-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
    default-sequential-cxx-flags: -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-omp-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
    default-omp-cxx-flags: -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm-5.4.2/lib -L/opt/rocm-5.4.2/hip/lib -lamdhip64
    default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike -isystem /usr/lib/llvm-14/lib/clang/14.0.6/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
    default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
    default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike
    default-is-explicit-multipass: false
    default-save-temps: false
* Recent hipSYCL versions include a tool called `opensycl-info`, which will print information about available backends and devices. This may be interesting for issues related to e.g. device visibility.
Can see the device fine

**Comment by illuhad** [comment]
This is a bug in specific versions of clang and/or ROCm, which do not seem to link the required ROCm bitcode files automatically. You can fix this by linking manually using `-Xclang -mlink-bitcode-file -Xclang /rocm/install/path/amdgcn/bitcode/oclc_abi_version_400.bc` when compiling.

**Comment by reguly** [comment]
Thank you, that does resolve the issue! I am using the official clang-14 release - what version of the RoCM stack is recommended?
