### ISSUE TITLE
atomic_ref fails with generic flow

### ISSUE THREAD

**Issue by RaulPPelaez** [AdaptiveCpp/AdaptiveCpp#974]
**Bug summary**
The following MRE sets an atomic in a parallel_for by using atomic_ref. This test passes with the omp flow in a CPU and with cuda:sm_75 in an RTX2080Ti, but fails with generic.

**To Reproduce**
```c++
#include<CL/sycl.hpp>
using namespace cl;
int main(){
  sycl::queue q;
  constexpr int N = 100;
  int v = 0;
  sycl::buffer<int> buf(&v, 1);
  q.submit([&](sycl::handler& h) {
     sycl::accessor acc{buf, h, sycl::read_write};
     h.parallel_for<class AtomicExample>(sycl::range<1>{N}, [=](sycl::id<1> i) {
       auto atom = sycl::atomic_ref<int, sycl::memory_order::relaxed,
                        sycl::memory_scope::device>(acc[0]);
       atom.fetch_add(1);
     });
   }).wait_and_throw();
  sycl::host_accessor acc{buf, sycl::read_only};
  assert(acc[0] == N);
return 0;
}
```
Fails if compiled with ```HIPSYCL_TARGETS="generic"```. Does not show any error or crashes, simply yields ```acc[0] == 0```

**Expected behavior**
Both cuda:sm_75 and generic should result in the same behavior.

**Describe your setup**
* how you have installed hipSYCL, and which version/branch/git commit
Last commit on develop (d461988fe36)
Compiled with:
```shell
HIPSYCL_TARGETS="cuda:sm_75,sm_80;generic" CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA_BACKEND=ON -DCUDA_DRIVER_LIBRARY=$CONDA_PREFIX/lib/stubs/libcuda.so .. && make -j15 install
```
* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang version and how clang was installed
   I am using the following conda environment:
```conf
channels:
  - conda-forge
  - conda-forge/label/llvm_rc
  - nvidia
dependencies:
  - clang = 16
  - clangdev
  - boost
  - llvm
  - llvmdev
  - cuda
  - gxx = 11
  - gcc
  - cmake
  ```
   
   * CUDA version (if applicable)
   12
* How you have compiled your application and which arguments you have passed to `syclcc`. In particular, which backends and hardware you have compiled for.
I am using cmake, but the relevant line is:

```
/home/raul/mambaforge/envs/test/lib/cmake/hipSYCL/syclcc-launcher --launcher-cxx-compiler=/home/raul/mambaforge/envs/test/bin/clang++ --launcher-syclcc=/home/raul/mambaforge/envs/test/bin/syclcc-clang  --hipsycl-targets="generic" /home/raul/mambaforge/envs/test/bin/clang++  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/raul/mambaforge/envs/test/include -O3 -O3 -DNDEBUG -pthread -std=gnu++20 -o CMakeFiles/example_example.dir/example.cpp.o -c /home/raul/test/examples/example.cpp

```

**Comment by nilsfriess** [comment]
Thanks for reporting, this is (currently) expected. The atomic builtins for the generic backend are defined in [this file](https://github.com/OpenSYCL/OpenSYCL/blob/d461988fe36b0a1db22dedce6916e77d268d1cfb/include/hipSYCL/sycl/libkernel/sscp/atomic_builtins.hpp#L82) and are not implemented yet.

**Comment by RaulPPelaez** [comment]
Great to know, I was going crazy!
Maybe some kind of compiler or runtime warning would be possible here?

**Comment by illuhad** [comment]
Given that this is already WIP in PR #941, it is probably a better investment of time to just finalize atomic support there instead of creating a warning that will be outdated soon.

In general, emitting warnings for undefined functions in the generic SSCP compiler can be difficult because there can be cases where functions can remain undefined (e.g. a specific code path is only relevant for a particular device or backend, or a function will be defined later using backend bitcode libraries etc.)

**Comment by RaulPPelaez** [comment]
Sounds good, thanks for the work guys!
