### ISSUE TITLE
syclcc not taking into account environment variables for flags

### ISSUE THREAD

**Issue by illuhad** [AdaptiveCpp/AdaptiveCpp#978]
**Bug summary**

`syclcc` does not take into account environment variables for flags anymore. e.g. `OPENSYCL_DRYRUN=1 syclcc` does not work. For non-flags it works, e.g. `OPENSYCL_TARGETS=generic syclcc`.

This is probably a regression from #948.

**To Reproduce**

Run  `OPENSYCL_DRYRUN=1 syclcc --help` and observe that `is-dryrun` is not enabled according to the output.

**Comment by normallytangent** [comment]
I can have a look at it

**Comment by illuhad** [comment]
Thanks! :)
