### ISSUE TITLE
Tests can't find package Open SYCL

### ISSUE THREAD

**Issue by normallytangent** [AdaptiveCpp/AdaptiveCpp#983]
**Bug summary**
Cmake error when building Open SYCL tests. 
```
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindOpenSYCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenSYCL",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenSYCL" with any
  of the following names:

    OpenSYCLConfig.cmake
    opensycl-config.cmake

  Add the installation prefix of "OpenSYCL" to CMAKE_PREFIX_PATH or set
  "OpenSYCL_DIR" to a directory containing one of the above files.  If
  "OpenSYCL" provides a separate development package or SDK, be sure it has
  been installed.
```
 
**To Reproduce**
Build the tests with the cmake variable `-DhipSYCL_DIR=/install/prefix/lib/cmake/OpenSYCL`
Changing the variable to `-DOpenSYCL_DIR ...` causes compile time errors: 
```
syclcc fatal error: Neither a --opensycl-targets specification nor the legacy combination of --opensycl-platform and --opensycl-gpu-arch was provided
make[2]: *** [CMakeFiles/sycl_tests.dir/build.make:318: CMakeFiles/sycl_tests.dir/sycl/kernel_invocation.cpp.o] Error 255
```

**Comment by illuhad** [comment]
I think this is expected: The old `hipSYCL` integration is in `lib/cmake/hipSYCL`, while the new `OpenSYCL` integration is in `lib/cmake/OpenSYCL`. So you have to match your `-Dhip/OpenSYCL_DIR` with the path that you give it.

The compile time error that you see is probably because `-DOpenSYCL_TARGETS` is not set.

**Comment by normallytangent** [comment]
Thank you, matching  `-DOpenSYCL_DIR` with the path I give works.  

Just FYI when the pair is with `-DhipSYCL_DIR` and `-DhipSYCL_DIR=/install/prefix/lib/cmake/hipSYCL`, I still get the above error. 
Setting `-DHIPSYCL_TARGETS` no more works. It necessarily requires `-DOPENSYCL_TARGETS`. If I understand correctly we have functionality, for switching the deprecated string, and so this should have worked?

**Comment by illuhad** [comment]
Yes, it should have worked, and I just tried it: `HIPSYCL_TARGETS` still works for me when using the old hipSYCL integration as it should.

**Comment by normallytangent** [comment]
I don't see the mistake I make [here](https://github.com/normallytangent/oneMKL/actions/runs/4554802061/workflow#L81) because for me it didn't work.

**Comment by nilsfriess** [comment]
[In the `tests/CMakeLists.txt`](https://github.com/OpenSYCL/OpenSYCL/blob/2b0067b58780663a8ea651bcc7ef24a7ae248ff7/tests/CMakeLists.txt#L10) we only have `find_package(OpenSYCL)` but not `find_package(hipSYCL)`, so I guess changing it to `OpenSYCL_DIR` and `OPENSYCL_TARGETS` should fix it.

**Comment by normallytangent** [comment]
Yes, that does work. :) I just wanted to make sure that the hipSYCL integration still worked since other projects, for example OneMKL haven't changed to the new name yet. But interestingly, I don't have issues there but only when I build the Open SYCL tests

**Comment by nilsfriess** [comment]
`find_package(hipSYCL)` still works, but our tests are already updated to the new name (i.e., they use `find_package(OpenSYCL)` instead of `find_package(hipSYCL)`), that's why it doesn't work when compiling the tests but it does work when compiling oneMKL :)

**Comment by normallytangent** [comment]
Thank you, that makes sense!
